### ISSUE TITLE
Unexpected mypy type error

### ISSUE THREAD

**Issue by luciotudisco** [python/mypy#10119]
**Bug Report**

Unexpected mypy type error.

**To Reproduce**

```
from typing import List, Type, Union, Callable


def is_excluded(exception: Exception, exclusions: List[Union[Type[Exception], Callable]]):
    exception_type = type(exception)
    for exclusion in exclusions:
        if type(exclusion) is type:
            if issubclass(exception_type, exclusion):
                return True
            elif callable(exclusion):
                if exclusion(exception):
                    return False


e: Exception = ValueError('Oops!')
assert is_excluded(e, [ValueError])
```

**Expected Behavior**

mypy returns no error.

**Actual Behavior**

```
$ mypy test.py

test.py:8: error: Argument 2 to "issubclass" has incompatible type "Union[Type[Exception], Callable[..., Any]]"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
```

**Comment by beetle-in-a-box** [comment]
I wouldn't be inclined to call this issue a bug. Its actually caused do to the indirect type check you have in your code. This prevents mypy from concluding that the second argument to `issubclass` is actually an object. Hence the warning.

The simple solution would be to use the idiomatic approach `isinstance` instead of your `type(exclusion) is type` statement. For a minimally viable example which highlights this difference:

```python
import typing

exclusion: typing.Union[type, int] = ValueError

if type(exclusion) is type:
    print(issubclass(ValueError, exclusion))

if isinstance(exclusion, type):
    print(issubclass(ValueError, exclusion))
```

On a slightly unrelated note: your `callable` check seems to have no effect. The type comparison above excludes anything but classes and object types. Thus, `callable` always returns `True`.

**Comment by luciotudisco** [comment]
Thanks!

```
if isinstance(exclusion, type):
    if issubclass(exception_type, exclusion):
        return True
```

fixes indeed.

Regarding the callable, that was a bad indentation on my side while reporting the issue. Good catch!

**Comment by beetle-in-a-box** [comment]
Great to hear :)! Always happy to help. Do be sure to close the issue ;)

**Comment by luciotudisco** [comment]
Thanks again!
