### ISSUE TITLE
Adjusting the signature of a function on the basis of caller types in plugin

### ISSUE THREAD

**Issue by Paul-Ilyin** [python/mypy#10216]
What is the proper way to adjust the signature of a function basing on actual caller types?
I have two ideas:
1. using get_function_signature_hook, manually inferring all types from FunctionSigContext.args list
2. using get_function_hook, calling `FunctionContext.api.fail` every time when arguments are invalid

Are there any better ways?

**Comment by ikonst** [comment]
I've stumbled into the same issue and can't see any better way.

- `get_function_signature_hook` is called too early so it doesn't get arg types.
- `get_function_hook` is called late enough for expressions to be mapped to their types, but cannot change the signature anymore, so it would have to do its own validation (which is ironic since it's called from within `ExpressionChecker.check_call`)

Also, I found `FunctionSigContext.args` to be incomplete, w.r.t. kwargs. At the point where it's called we also know `arg_names` (and `arg_kinds`, though arguably you should know the function you're hooking), so why not pass that in?

**Comment by ikonst** [comment]
If we address this, we should update the docs here w.r.t "Note that argument types aren't available yet":
https://github.com/python/mypy/blob/a9bc366ae501ccced78a2746b6eac07b93d7b15e/mypy/plugin.py#L423-L426
("use a method hook instead" should've said "use a function hook instead" in this case -- copy-pasta)

Notably this comment is in @sobolevn's #9102 which added this hook, so this looks at least somewhat intentional, but I can't tell if there's a really good reason.

**Comment by ikonst** [comment]
@ilevkivskyi let's have #15369 resolve this one too?
