### ISSUE TITLE
overload hides 'is not a function' error in stubtest

### ISSUE THREAD

**Issue by hatal175** [python/mypy#10254]
**Bug Report**

I've noticed that overloading a function can hide a mismatch between the runtime type and the stub type. I noticed this as I was going over typeshed stubtest exceptions, specifically for itertools.accumulate.
Tests for python 3.6 and 3.7 failed because the stubs declared accumulate as a function while it was actually a class. However for 3.8 it is defined as two functions with overload and the tests passed successfully.

**To Reproduce**

(Write your steps here:)

1. Run stubtest for typeshed in python 3.8.
2. Test passes.
3. Remove one of the overloads in itertools.pyi
4. run again and see it fails.

**Expected Behavior**

I t should fail on a type mismatch like it does for no overloads.

**Actual Behavior**

passed.

**Your Environment**

Ran from latest python 3.8 and latest mypy from github.

**Comment by hauntsaninja** [comment]
Thanks for reporting! This is easy to fix (just ensure `verify_overloadedfuncdef` makes the same check as `verify_funcitem`). That said, none of the dozen or so new errors on stdlib you get after fixing this are useful... arguably if you've gotten to the point of writing overloads, you're probably conscious of the fact that you're pretending the object is a function, so maybe this bug is a feature?

**Comment by JelleZijlstra** [comment]
Even if the issues this currently finds are not too useful, it feels better for stubtest to consistently check everything it could check instead of just giving up. I can imagine some useful checks it could do with overloads, like checking that all overloads are at least a subset of possible useful calls.

**Comment by hauntsaninja** [comment]
Just to clarify, stubtest does check overloads (in fact, that's probably the most complicated part of stubtest). However, I will change the "is not a function" error to not early return if the object is still callable, so that if you have a signature you still get those errors in addition. Anyway, #10254 for you
