### ISSUE TITLE
Support call expression in function argument

### ISSUE THREAD

**Issue by pasunx** [python/mypy#10277]
```python
from typing import TypedDict

def register(user: TypedDict("User", { # I know that I can define User as variable
            "name": str,               # but I think it might ok to support this
            "age": int
        }, total = False)) -> None: ...
```

**Comment by erictraut** [comment]
Mypy and other type checkers do not allow call expressions within type annotations, so this construct is considered an error. The correct formulation is to assign the TypedDict to a type alias like this:

```python
from typing import TypedDict

User = TypedDict("User", {"name": str, "age": int}, total=False)

def register(user: User) -> None:
    ...
```

PEP 484 does not explicitly disallow call expressions in type annotations, but it does say:
>Annotations should be kept simple or static analysis tools may not be able to interpret the values. For example, dynamically computed types are unlikely to be understood. (This is an intentionally somewhat vague requirement, specific inclusions and exclusions may be added to future versions of this PEP as warranted by the discussion.)

The authors of PEP 484 were wise to say that annotations should be kept simple. It's important for evaluation of type annotations to be fast — and for them to be unambiguous in their meaning, even across type checkers. Call expressions require complex logic to evaluate, and the type evaluation results can vary between type checkers because of subtle differences in type inference and overload evaluation behaviors. For those reasons, it makes sense to disallow call expressions within type annotations. Type aliases provide a convenient mechanism to handle most of the use cases that call expressions otherwise would.

**Comment by 97littleleaf11** [comment]
Eric has already gave a detailed explanation. Just close this issue.
