### ISSUE TITLE
List is compatible with Sequence, but incompatible with MutableSequence

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#10327]
**Bug Report**

`typing.List` appears to be compatible with `typing.Sequence`, but not `typing.MutableSequence`, making it impossible to annotate a function that would accept a list, and then mutate it (see repro below).

**To Reproduce**

```py
from typing import Union, List, Sequence, MutableSequence

class X: pass
class Y: pass

def func1(it: List[Union[X, Y]]):
    pass

def func2(it: Sequence[Union[X, Y]]):
    it.insert(X())  # "Sequence[Union[X, Y]]" has no attribute "insert"

def func3(it: MutableSequence[Union[X, Y]]):
    it.insert(X())  # OK

my_list: List[X] = []

# Argument 1 to "func1" has incompatible type "List[X]"; expected "List[Union[X, Y]]"
# "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
# Consider using "Sequence" instead, which is covariant
func1(my_list)

func2(my_list)  # OK
func3(my_list)  # Argument 1 to "func3" has incompatible type "List[X]"; expected "MutableSequence[Union[X, Y]]"
```

**Expected Behavior**

The `func3(my_list)` call in the repro above, to type check correctly (no error).

**Actual Behavior**

An error - see repro above.

**Your Environment**

- Mypy version used: mypy-0.820+dev.2ac722ac7d844f4c5ae2f3c36f3470543cf01b11 (latest master)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8.8
- Operating system and version: Win7x64

**Comment by brandtbucher** [comment]
I think you want `MutableSequence[X]` in the `foo3` annotation.

Note that `MutableSequence[Union[X, Y]]` is *not* the same thing as `Union[MutableSequence[X], MutableSequence[Y]]`. Similarly, `List[Union[X, Y]]` (a list that may contain both `X`s and `Y`s) is not the same as `Union[List[X], List[Y]]` (either a list containing only `X`s, or a list containing only `Y`s).

The reason for this is that it is not safe to pass a `List[X]` where a `MutableSequence[Union[X, Y]]` is expected, since a `Y` may be inserted into it:

```py
def func4(it: MutableSequence[Union[X, Y]]):
    it.insert(Y())  # OK

my_list: List[X] = []

func4(my_list)  # Whoops, now my_list has a Y in it!
```

**Comment by JelleZijlstra** [comment]
@brandtbucher is right; this is expected behavior due to variance.
