### ISSUE TITLE
mypy - unable to specify pattern in config file

### ISSUE THREAD

**Issue by kurtgn** [python/mypy#10379]
I have a `migrations` folder in my app:

```
$ ls src/migrations/
README          __pycache__     alembic.ini     env.py          script.py.mako  versions

```

And a `mypy` config file:

```
$ cat setup.cfg 
[mypy]
ignore_missing_imports = True
disallow_untyped_calls = True
disallow_incomplete_defs = True

[mypy-*.migrations.*]
ignore_errors = True

```

But when I run 

```
mypy src
```

I still see errors from the migrations folder:

```
src/migrations/env.py:95: error: Call to untyped function "run_migrations_offline" in typed context
src/migrations/env.py:97: error: Call to untyped function "run_migrations_online" in typed context

```

why is that and how to fix this?

My version is:

```
$ mypy --version
mypy 0.812
```

**Comment by nickgashkov** [comment]
Same here, config with separate sections for patterns works fine for `mypy==0.782` but does not work anymore in `mypy==0.800`.

**Comment by hauntsaninja** [comment]
The issue is likely that `ignore_errors` uses a module name, but you're missing an `__init__.py` / the right set of flags to make mypy associate `src/migrations/env.py` with `migrations.env` instead of say `env`. `mypy -v` can confirm this for you. https://mypy.readthedocs.io/en/latest/running_mypy.html#mapping-file-paths-to-modules

Consider using `--exclude`.
