### ISSUE TITLE
int and float types are treated as the same

### ISSUE THREAD

**Issue by vagarkav** [python/mypy#10471]
**Bug Report**

I try to use `typing.Protocol` to implement abstract interfaces where any kind of inheritance is not an option. I've noted that `mypy` makes no difference between `int` and `float` values when they are the method's arguments. At the same time it claims error while, for instance, `str` type is declared in actual class instead of `int` that's required according to protocol.

**To Reproduce**

Create the next source file and check it with `mypy`.
```
from typing import Protocol

class P(Protocol):
    def foo(self, n: int) -> None: ...

class F:
    def foo(self, n: float) -> None: ...

class S:
    def foo(self, n: str) -> None: ...

def bar(x: P): ...

bar(F())
bar(S())
```

**Expected Behavior**

```
... error: Argument 1 to "bar" has incompatible type "F"; expected "P"
... note: Following member(s) of "F" have conflicts:
... note:     Expected:
... note:         def foo(self, n: int) -> None
... note:     Got:
... note:         def foo(self, n: float) -> None
... error: Argument 1 to "bar" has incompatible type "S"; expected "P"
... note: Following member(s) of "S" have conflicts:
... note:     Expected:
... note:         def foo(self, n: int) -> None
... note:     Got:
... note:         def foo(self, n: str) -> None
Found 2 error in 1 file (checked 1 source file)
```
**Actual Behavior**
```
... error: Argument 1 to "bar" has incompatible type "S"; expected "P"
... note: Following member(s) of "S" have conflicts:
... note:     Expected:
... note:         def foo(self, n: int) -> None
... note:     Got:
... note:         def foo(self, n: str) -> None
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: not specified
- Mypy configuration options from `mypy.ini` (and other config files): not used
- Python version used: 3.9.0
- Operating system and version: Windows 10

**Comment by srittau** [comment]
Per [PEP 484](https://www.python.org/dev/peps/pep-0484/), `int` is a subtype of `float`, meaning that every function that takes `float` arguments also takes `int` arguments. As `F.foo()` also accepts `int`s, `F.foo()` is a subtype of `P.foo()` and therefore `F` fulfills protocol `P`.

**Comment by vagarkav** [comment]
@srittau, oh, it appears to be my bad. Thank you! ;)

**Comment by JakubTesarek** [comment]
@srittau [PEP 484](https://www.python.org/dev/peps/pep-0484/) doesn't say that because it's not true. Int is not subtype of int and float has some methods that int doesn't have: `(2.0).is_integer()`.

**Comment by erwinkinn** [comment]
Saints! You are right ;)
This case is not so simple as seen from the first sight. This is the place where mypy becomes useless...

**Comment by thomaseding** [comment]
Pretty sad this is the current state of affairs, considering the following typechecks:
```
def foo(x: float) -> float:
    assert isinstance(x, float)
    return x

foo(1)  # AssertionError
```

**Comment by dave-doty** [comment]
This issue, and the related #11054, were both closed. Is there a fix that was not documented here, or a link I missed to mypy documentation for how to properly handle the problems the issues raised?

Although neither OP specifically said it this way, I interpret both issues to point towards a feature request: put a type in the `typing` module that can represent either an `int` or a `float`, which will work generically in as many circumstances as possible, specifically in the circumstances documented in each of these issues. I suppose that type is supposed to be `float` itself, given the pointers to [the numeric tower](https://peps.python.org/pep-0484/#the-numeric-tower) (meaning, the tower ignored by `isinstance`), but I fairly frequently encounter problems like the ones encountered in these issues.

For that matter, I'm fairly confused what is the purpose of the abstract classes in the `numbers` module referenced by the numeric tower. I hoped for a time those could solve the "are ints also floats?" problem, but the following is about as counterintuitive as it gets:

```python
from numbers import Integral

def func(n: Integral) -> None:
    print(n)
unequivocally_an_integer = sum([1,2,3])
func(unequivocally_an_integer) # mypy error:
# Argument of type "int" cannot be assigned to parameter "n" of type "Integral" in function "func"
#   "int" is not assignable to "Integral"

# Above error indicates mypy apparently believes ints are not instances of Integrals, 
# so the next statement will definitely fail, right?
assert isinstance(unequivocally_an_integer, Integral)  # passes just fine; 
# mypy must be ignoring whatever `isinstance` checks when it comes to Integral, except...
func(unequivocally_an_integer) # now there's no mypy error. ?????
```

But I digress. I'll add my own case where I got bit by the lack of a generic number type:

Even if `int` *were* a subtype of `float`, there is still a need for a type variable that can represent either due to [invariance of generic collections](https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance): `Mapping[int, str]` would not be a subtype of `Mapping[float, str]`. So this code has a mypy error, but would also have a mypy error if `int` were a subtype of `float`:

```python
from typing import Mapping

def val(dct: Mapping[float, str], key: float) -> str:
    return dct[key]
d = {1: 'abc'}
s = val(d, 1) # mypy error: 
# Argument of type "dict[int, str]" cannot be assigned to parameter "dct" of type "Mapping[float, str]" in function "f"
#   "dict[int, str]" is not assignable to "Mapping[float, str]"; 
#   Type parameter "_KT@Mapping" is invariant, but "int" is not the same as "float"
```

Currently I handle this with `TypeVar`:

```python
from typing import Mapping, TypeVar

Number = TypeVar("Number", float, int)

def val(dct: Mapping[Number, str], key: Number) -> str:
    return dct[key]

d = {1: 'abc'}
s = val(d, 1))  # no mypy error
```

(For that matter, I'm a bit baffled why Mapping is an exception to the claim that [Most immutable container types, such as `Sequence` and `frozenset` are covariant](https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types). `Mapping` is an immutable container type, and I don't see what class of runtime errors is prevented by making it invariant in its key type, but that are not *also* problems caused by allowing `Sequence` to be covariant in its element type.)

But this sort of situation, wanting to use ints wherever floats are expected, is so common that I'm surprised mypy does not supply such a type to cover both cases, or at the very least recommend an approach such as the one I use with `TypeVar`.

The comments bring up very good points concerning how the lack of such a type causes other problems when Python programmers try to roll their own solutions (e.g., with union types like `int | float`):

1. "*Per [PEP 484](https://www.python.org/dev/peps/pep-0484/), int is a subtype of float*". As @JakubTesarek points out, PEP 484 does not say this, and it is not true. It also should not be true; interpreting a type as a *set of values* that objects of that type can represent, "subtype" is a synonym for "subset". The set of integers ℤ (which is actually the set of values Python `int`'s can represent) is a subset of the set of real numbers ℝ, but ℤ is not a subset of the finite set of dyadic rational numbers representable by 64-bit floating-point values. (Though the integers in the range $[-2^{53},\dots,2^{53}]$ [are](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#Precision_limitations_on_integer_values), so one could imagine doing this in other languages with an `int32` type.)
2. mypy is supposed to catch potential runtime errors statically. A correct static type checker should be *sound*: if it declares a line of code won't raise an exception (e.g., it declares that a parameter `s` of type `str | None` is `str` within a certain block, then it is guaranteed I can safely call `len(s)`). But it seems like a glaring unsound property that mypy happily declares the example of @thomaseding as good: the [documentation for `isinstance(variable, MyType)`](https://docs.python.org/3/library/functions.html#isinstance) says "*Return True if [`variable`] is an instance of [`MyType`], or of a (direct, indirect, or [virtual](https://docs.python.org/3/glossary.html#term-abstract-base-class)) subclass thereof.*" The whole point of mypy is to catch errors of the form "*I, the programmer, thought `variable` was an instance of `MyType`, but I was wrong, thank you mypy!*" But it faceplants on this example. I realize that it is consistent with what [mypy officially says about duck typing](https://mypy.readthedocs.io/en/stable/duck_type_compatibility.html). Nevertheless, since these examples show that duck typing and actual subtype relationships are two different things, one should expect generations of Python programmers to remain confused about this, expecting mypy to be checking subtypes as it does in most circumstances, getting bit when it silently switches from checking subtype relationships to duck typing. But this particular int/float duck typing check appears to be a special case: through duck typing I can pass two lists to this function: 
    ```python
    def add(x: int, y: int) -> int:
        return x+y
    add(['a','b'], ['c'])
    ```
    and get back their concatenation. But mypy correctly complains about this. I'm not claiming mypy should stop doing the duck typing thing when someone uses an `int` where a `float` is expected; one of my annoyances with Rust is the fact that [`1 + 2.0` is not valid Rust code](https://doc.rust-lang.org/rust-by-example/types/cast.html). But it would be great if mypy provided a way around problems caused by this special case.
3. Although not as big a deal as being unsound, ideally a good static type checker should not be overly conservative and declare problems that will not actually manifest at runtime. In issue #11054, the example shows how mypy mistakenly concludes a statement is unreachable, because it disagrees with `isinstance`, believing `int` to be a subtype of `float`. Luckily this one is not unsound, mypy is simply being overly conservative. Yet I would argue that when the mypy team's [official recommendation](https://github.com/python/mypy/issues/11054#issuecomment-927369461) is to add `# type: ignore`, there's a deficiency worth addressing.

I'm not faulting the mypy team for not addressing this *yet*; the issue is obviously subtle and complex. They need to spend a lot more time thinking about it than I have, since they need to support as many use cases as possible across millions of Python programmers. No one wants a repeat of the Python 2-to-3 upgrade, now from 3 to 4, because a feature was carelessly bolted onto Python 3, and then we discover the hard way it was problematic. I don't know whether my hack with `TypeVar` is a good solution. I'm honestly not even entirely sure why it works despite invariance of generic collection types.

But it does feel like a real problem is being pointed out by these issues.

**Comment by dave-doty** [comment]
@erictraut Thank you! You can interpret my whole comment as longhand for "*please tell us where we should go to read about these thorny issues and find out more*", and you've done exactly that, much appreciated. I'll check it out.

I'm also now curious about pyright, never heard of it before, but I certainly like how it treats your first example better than mypy.
