### ISSUE TITLE
Security concerns from `mypy --install-types` and malicious third-party stubs

### ISSUE THREAD

**Issue by Zac-HD** [python/mypy#10538]
Reading [the recent blog post announcing `--install-types`](https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html), I was concerned that malicious third parties might create a `types-$popular_package` package and have it recommended or even installed by `mypy`.

[The docs for this feature](https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-install-types) don't outline any security considerations.  Has the risk of malicious packages been considered?  If so, what mitigations are in place?  It would be great to document this.

**Comment by srittau** [comment]
See also pypa/warehouse#4967. This is a serious concern.

**Comment by JukkaL** [comment]
Mypy ships with information about a [various known stub packages](https://github.com/python/mypy/blob/master/mypy/stubinfo.py) and these are the only ones that it will suggest installing, or install using `--install-types`. All of these originate from typeshed. The typeshed uploader script for packages lives in [another repository](https://github.com/typeshed-internal/stub_uploader) with restricted write access, and we make sure to only include stub files (not executable code) in the packages that are uploaded. 

It makes sense to mention this in the documentation as otherwise users may be hesitant to install these packages without first manually validating them.

Having a dedicated namespace for stub packages would be nice, but it's unclear when this might be supported.

I have plans to claim `types-foo` for a large number of projects on PyPI for typeshed, by auto-generating stubs and uploading them (assuming typeshed maintainers are okay with this). I think that this would make things less risky.

**Comment by srittau** [comment]
@JukkaL Sounds like a good plan! Both restricting `--install-types` to known stub packages as well as auto-generating stubs. I hope we will get namespaces on PyPI at some point, though.

**Comment by JukkaL** [comment]
Note that `--install-types` is already restricted to known stub packages, but auto-generating additional stubs won't happen before the 0.900 release (I don't have a concrete timeline yet for it).
