### ISSUE TITLE
typeshed is old

### ISSUE THREAD

**Issue by Akuli** [python/mypy#10621]
**Feature**

It would be nice if the typeshed would be updated before the next release (next week? #10600).

**Pitch**

Recently I improved some commonly used classes in tkinter stubs: https://github.com/python/typeshed/pull/5586, https://github.com/python/typeshed/pull/5584, https://github.com/python/typeshed/pull/5583. These are not actually usable to most people, and in my project, a custom typeshed as submodule causes trouble to other people working on the project.

To show the difference, I created  #10620.

**Comment by JukkaL** [comment]
Releasing a new version of typeshed is a pretty heavy process, since we want to validate it with internal Dropbox repos. I don't want to go through a full release process now, so this means that we can't really update typeshed until later. However, cherry-picking specific typeshed commits that are known to cause trouble is fine. Would that work for you?

**Comment by Akuli** [comment]
It would work, but perhaps we should ask other typeshed people if there's anything they want to include. My cherry-picked typeshed branch, based on the latest "Sync typeshed" commit in mypy history, is https://github.com/Akuli/typeshed/tree/mypy-typeshed.

**Comment by JukkaL** [comment]
Cherry-picking typeshed fixes is not something we have normally done, but we can use just the tkinter stub fixes as a test run. If things work out well, we can publicize this more widely.
