### ISSUE TITLE
`import itsdangerous.exc` errors asking to `--install-types` even if it is already installed

### ISSUE THREAD

**Issue by asottile** [python/mypy#10645]
**Bug Report**

```python
import itsdangerous.exc
```

**To Reproduce**

```
virtualenv venv
venv/bin/pip install mypy types-itsdangerous
venv/bin/mypy
```

**Expected Behavior**

no error

(Write what you thought would happen.)

**Actual Behavior**

```console
$ venv/bin/mypy t.py 
t.py:1: error: Library stubs not installed for "itsdangerous.exc" (or incompatible with Python 3.8)
t.py:1: note: Hint: "python3 -m pip install types-itsdangerous"
t.py:1: note: (or run "mypy --install-types" to install all missing stub packages)
t.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.902
- Mypy command-line flags: none, also tried `--ignore-missing-imports`
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8.5
- Operating system and version: ubuntu 20.04

**Comment by srittau** [comment]
I assume that's due to the fact that in typeshed, there is no `itsdangerous.exc` module. (In fact, there's only an `itsdangerous.pyi` file, not package at all.) So it's both a typeshed problem, but also something that mypy should probably not complain about.

**Comment by srittau** [comment]
Also: itsdangerous 2.0.0+ ships a `py.typed` file, so the recommendation to install its stubs makes no sense in that case.

**Comment by Zac-HD** [comment]
Similarly, 

```python
from pytz.tzinfo import StaticTzInfo
```

complains that I should install `types-pytz`, even with that stubs package already installed, presumably because the stubs don't include any pytz submodules.  I don't mind if `typeshed` has decided that this submodule is not public API, but `mypy` shouldn't tell me to install a package which is already installed!

**Comment by JukkaL** [comment]
There seem to be at least three issues.

First, `--ignore-missing-imports` not working for missing submodules when stubs are installed is a bug.

Second, since `itsdangerous` ships with `py.typed`, we should probably recommend installing the implementation package instead of stubs.

Third, typeshed is missing some submodules of `pytz`. This should be easy to fix, at least by providing placeholders with module-level `__getattr__`.

**Comment by asottile** [comment]
seems fixed in 910 -- thanks for this!
