### ISSUE TITLE
Documentation of `type` type might need updating for Python 3.9

### ISSUE THREAD

**Issue by stephen-h-d** [python/mypy#10985]
**Documentation**

The following code passes for me when using Python 3.9.5 but fails when using Python 3.8.10:

```
from typing import TypeVar, Type


class User:
    # Defines fields like name, email
    ...

class BasicUser(User):
    def upgrade(self):
        """Upgrade to Pro"""

class ProUser(User):
    def pay(self):
        """Pay bill"""

U = TypeVar('U', bound=User)

def new_user(user_class: type[U]) -> U:
    user = user_class()
    # (Here we could write the user object to a database)
    return user

beginner = new_user(BasicUser)  # Inferred type is BasicUser
beginner.upgrade()  # OK
```

I believe that this is expected behavior, though I can not find mention of it in the documentation.  I got this example from [this section](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#the-type-of-class-objects), entitled "The type of class objects."  It implies that `type` is not subscriptable, which is true for Python 3.8 but is not true for Python 3.9.

Based on experimenting with the above code, I have not observed a difference between `type` and `Type` in Python 3.9.  Is there one, and if so, what is it?  I believe that this should be noted in the documentation, perhaps in [this section](https://mypy.readthedocs.io/en/stable/builtin_types.html) about built-in types.

Thanks ever so much!

**Comment by mixed-source** [comment]
This is the expected behavior. 
According to the [docs](https://docs.python.org/3.9/library/typing.html#typing.Type) and [PEP 585](https://peps.python.org/pep-0585/#implementation), `type` and `Type` produce the same results but `type` only works in Python 3.9 and later while `Type` works in Python 3.8 and earlier.

The difference between `type` and `Type` is that `type` is a generic type invoked from the builtins module in Python 3.9 and later while `Type` is a legacy type in typing module.

I think it is recommended to use `type` if we are using Python 3.9 and later since `Type` is deprecated from 3.9 and will be removed in the future.

Hope this helps! 
Thanks!
