### ISSUE TITLE
implicit optional doesn't work with new union syntax

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#10987]
```py
from typing import Union


def foo(value: int | str = None) -> None: # error: Incompatible default for argument "value" (default has type "None", argument has type "Union[int, str]")
    ...


def bar(value: Union[int, str] = None) -> None: # no error
    ...
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=13ab271a59d6301d98dac48ccb87e9c8

**Comment by Zymergen-jvandezande** [comment]
I asked the [same question on stackoverflow](https://stackoverflow.com/questions/67589804/different-behavior-between-union-and-in-mypy-when-dealing-with-optionals?noredirect=1#comment119468458_67589804) a little while back (and neglected to issue a bug report until today). PEP 484 indicates that the second example is the correct way to write it, as `Optional` should be explicit.

**Comment by erictraut** [comment]
Implicit optional is supported for backward compatibility, but its use is deprecated as per PEP 484, which states:

> This is no longer the recommended behavior. Type checkers should move towards requiring the optional type to be made explicit.

Since the `|` union syntax is new, there is no backward-compatibility issue with enforcing the explicit use of `None`. I suspect that it was therefore intentional not to support the old implicit optional behavior with the new syntax.

You can avoid the error by explicitly including `None` in the union:

```python
def foo(value: int | str | None = None) -> None:
    ...
```

**Comment by JelleZijlstra** [comment]
I'm not sure this is really intentional, but I agree with @erictraut that we should keep the behavior as is. Implicit optional is a deprecated behavior that we're phasing out; we shouldn't introduce it with new syntax.
