### ISSUE TITLE
support using assignment expressions for generics

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11101]
**Feature**
```py
def foo(value: (T:=TypeVar("T"))) -> T:
    ...
```

**Pitch**
i find it very gross to have to declare a variable outside of my function/class for every generic i use. using an assignment expression makes it much cleaner looking

**Comment by erictraut** [comment]
I think this would be problematic. What if the same name were used in multiple declarations within the same scope?

```python
def foo(value: (T:=TypeVar("T"))) -> T:
    ...

def bar(value: (T:=TypeVar("T", bound=int))) -> T:
    ...
```

It's ambiguous which TypeVar declaration that `-> T` refers to in both `foo` and `bar`. Is it in code flow order? What if it's a stub or `from __future__ import annotations` is in effect, in which case code flow order no longer applies? Would it be an error to use the same name twice within a scope?

There have been some discussions in the typing-sig about ways to improve the syntax for generics. I'd personally rather see us put our efforts behind those explorations rather than modifying PEP 484 to accommodate assignment expressions in this manner.

**Comment by erictraut** [comment]
I think it's OK to close this now that PEP 695 addresses this issue.
