### ISSUE TITLE
Make Mapping covariant in key

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1114]
Mapping should be covariant. See discussion at #1113.

Note that the key type is used as an argument type to `__getitem__` and `get`, so mypy may complain about a covariant key type variable, but we can just ignore that error in the stub, as covariance is safe in this case. `Mapping` doesn't support mutation operations and `__getitem__` can fail even in fully type safe code.

**Comment by gvanrossum** [comment]
See also #738.

**Comment by JukkaL** [comment]
Actually this would not really be safe for key types, as a custom subclass could allow mutation via the `Mapping` interface, or it could do mutation operations internally as part of caching or similar. One option would be to only treat values covariantly and have keys be invariant -- I think that it would be safe. Another option would be to not worry about the potential unsafety, as this would only affect pretty marginal use cases. As most mapping keys tend to have simple types (not union types, for example) the decision would likely only affect a small fraction of code.

**Comment by pkch** [comment]
Maybe define a supertype of `Mapping` that's covariant in its key type (which, of course, doesn't have `__getitem__` or `__get__` methods)?

`typing.Mapping` derives from `collections.abc.Mapping`; we can't easily change the inheritance hierarchy in `collections.abc`, but if we only need this for typing purposes, I think it's not too hard to leave the runtime-related libraries untouched.

**Comment by richvdh** [comment]
see also: https://github.com/python/typing/issues/445

**Comment by erictraut** [comment]
Is there anything remaining for this issue? I think it may be OK to close at this point.

**Comment by JelleZijlstra** [comment]
Agree, Mapping has to remain invariant in the key type.

**Comment by tgrue-openai** [comment]
I've run into a case where I believe it'd be nice to have a covariant key.

I have a super class with:
`get_values() -> Mapping[str | uuid, str]:`

and a subclass with:
`get_values() -> Mapping[uuid, str]`

IIUC, the later is valid under LSP.

It's nice for people directly using the subclass to know they're always going to have UUIDs so they don't have to handle both types.

While perhaps there are reasons we don't want to make Mapping's key covariant, is the conclusion of this bug that we shouldn't be able to express my pattern above?  (I see pkch had one suggestion above).

Thank you. (Also apologies if it's bad form to comment on a closed issue, but it felt worse opening a new one.)

**Comment by iutlu** [comment]
Apologies likewise for piling on, but I'm also having trouble figuring out how to convince Mypy that the following "should be" OK:

```
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypeAlias

ValidKey: TypeAlias = Literal["foo", "bar"]

sample_dict: dict[ValidKey, Any] = {"foo": None}
some_mapping: Mapping[str, Any] = sample_dict

sample_list: list[ValidKey] = ["foo", "foo"]
some_sequence: Sequence[ValidKey] = sample_list
```

Here's a scenario where something like this might come about: When writing your `sample_dict`, you realize you have more information as to what the keys could be, and decide to restrict the keys like above, and hope to recruit the static type checker in helping you catch any coding mistakes like assigning a new foreign key, etc. Great!

But since Mapping is not covariant in the key, `sample_dict` defined like this becomes unusable: you cannot assign it to something like `some_mapping`. The result is that you throw up your hands, and go back to annotating `sample_dict: dict[str, Any]` 😔 

The `list` / `Sequence` example doesn't suffer from the same problem.
