### ISSUE TITLE
compat issue with other tools

### ISSUE THREAD

**Issue by bluebrown** [python/mypy#11191]
# THIS IS NOT ABOUT TRYING TO EXCLUDE A PARTICULAR FILE WITH COMMAND LIKE FLAG

Mypy doesn't integrate well with VS Code and Pre Commit. Would be nice if you could make this happen, thanks.

Other tools seem to have issue to propagate the exclude-pattern targeting a 

# FOLDER

```
[mypy]
exclude = alembic
```

note this is a 

# FOLDER

Pre commit is checking the 

# Whole Workspace

Not a single file.

It's invoking mypy like this.

```

-   id: mypy
    name: mypy
    entry: mypy
    language: python
    'types': [python]
    args: ["--ignore-missing-imports", "--scripts-are-modules"]
    require_serial: true
    additional_dependencies: []
```

VS Code on the other hand may check a 

# single file. 

Namely, the one that was just saved. I have not enough knowledge of the codebase to confirm this but observing the behaviour of it, it is likely. Because it only changes the errors and warnings for the file that was just saved.

Maybe mypy should not lint the file when it's part of the ignore pattern, even when It's directly targeted.

**Comment by ethanhs** [comment]
Both pre-commit, and last I checked VSCode, work by invoking mypy on individual files. So this is actually the same as https://github.com/python/mypy/issues/11094.

Please do not open an issue because you disagree with another issue being closed. Furthermore, please do not post in anger, use all caps, and larger font. There's really no need to yell. If you cannot participate in a civil manner I will report you to the Python org admins to be blocked.

**Comment by bluebrown** [comment]
If you feel like it, then please go ahead. Would have been nice to just say this flat out on the other issue. Instead of acting like you are not even reading and closing in conjunction with phrases like *it seems*, and *I think*. That doesn't come off very certain, and it doesn't provide enough insights to understand why you think issues are related.

**Comment by bluebrown** [comment]
I apologize for my behaviour, though. I shouldn't act like this regardless.
