### ISSUE TITLE
Function returning dataclass.Field misinterpreted by mypy

### ISSUE THREAD

**Issue by intgr** [python/mypy#11265]
**Bug Report**

When using wrapper functions that help with construction of `dataclass.field()`, mypy gets confused and thinks that it's a default value instead.

```python
import dataclasses

def field_description(description: str) -> dataclasses.Field:
    return dataclasses.field(metadata={"serializer_kwargs": {"help_text": description}})

@dataclasses.dataclass
class Gnarly:
    brouhaha: str = field_description("Bodacious")
    # ^^^ E: Incompatible types in assignment (expression has type "Field[Any]", variable has type "str")
    badger: int
    # ^^^ E: Attributes without a default cannot follow attributes with one
```

However, the code above is equivalent to the following, which is currently allowed by mypy:
```python
@dataclasses.dataclass
class Gnarly2:
    brouhaha: str = dataclasses.field(metadata={"serializer_kwargs": {"help_text": "Bodacious"}})
    badger: int
```

**Expected Behavior**

I understand that mypy can't know whether the returned `dataclass.Field` has `default=` set or not, so the "Attributes without a default" check should be disabled in the presence of such functions. But this valid code should not be highlighted as error.

**Your Environment**

- Mypy version used: 0.902
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files): defaults
- Python version used: 3.9.7
- Operating system and version: macOS

**Comment by intgr** [comment]
Similar issue in PyCharm: https://youtrack.jetbrains.com/issue/PY-43590

**Comment by erictraut** [comment]
I wouldn't expect this to work with any static type checker. The behavior is the same in pyright as well. 

The problem is that `Field` is not a generic type, so it carries no information with it other than the fact that it's a `Field`. Its type doesn't inform the values that were used to initialize it (e.g. the `init` or `default` parameters). This information is required by a static type checker to provide correct type checking. As such, static type checkers require that you use the `dataclasses.field` call within the dataclass class declaration directly. A function like `field_description` won't work.
