### ISSUE TITLE
Improving inference of generic types of decorators.

### ISSUE THREAD

**Issue by letalvoj** [python/mypy#11458]
**Feature**

It would be nice if we could infer types of a generic variables of a decorator.
Consider the following scenario.

**Pitch**
Let's say that I have the following straightforward contract which makes non `Optional` methods `Optional`.

```py
UT = TypeVar('UT')
VT = TypeVar('VT')

class none_if_none(Generic[UT, VT]):
    def __call__(self, func: Callable[[UT], VT]) -> Callable[[Optional[UT]], Optional[VT]]:
        @wraps(func)
        def wrapped(legacy: Optional[UT]) -> Optional[VT]:
            if legacy is None:
                return None
            else:
                return func(legacy)

        return wrapped
```

I would hope that to apply this I could simply pass it as

```py
@none_if_none()
def parse(value: str) -> int:

# Argument 1 to "__call__" of "none_if_none" has incompatible type "Callable[[str], int]"; expected "Callable[[<nothing>], <nothing>]"
```
Specifying the types manually fails as well

```py
@none_if_none[str, int]()
def parse(value: str) -> int:

# Python version 3.8 does not support arbitrary expressions as a decorator
```

the only option seems to be

```py
none_if_none_int = none_if_none[str, int]()
@none_if_none_int
def parse(s: str) -> int:
    ...
```

which is pretty verbose and hard to maintain.

**Comment by erictraut** [comment]
The problem is that the type variables `UT` and `VT` are scoped to the class `none_if_none` rather than to the method `__call__`. When you instantiate `none_if_none`, the values of the type variables can't be established because there's no `__init__` method. That means `none_if_none` cannot be specialized appropriately when it is constructed.

I think you have two options:

1. Remove the `UT` and `VT` from the `none_if_none` class. In other words, make the class non-generic.
2. Keep the class generic but add an `__init__` method that accepts the function and captures its types, like this:

```python
class none_if_none(Generic[UT, VT]):
    def __init__(self, func: Callable[[UT], VT]) -> None:
        self.func = func

    def __call__(
        self, arg: Optional[UT]
    ) -> Optional[VT]:
        if arg is None:
            return None
        else:
            return self.func(arg)


@none_if_none
def parse(value: str) -> int:
    ...
```

**Comment by letalvoj** [comment]
@erictraut thx for the thorough reply, makes sense. I did not realize I can pass the wrapped function to `__init__` :)
