### ISSUE TITLE
"Cannot redefine an existing name as final" error when defining final variable in if statement

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11454]
```py
from typing import Final
def foo() -> bool:
    ...
if foo():
    bar: Final = 1
else:
    bar: Final = 2 # Cannot redefine an existing name as final  [misc]
```
https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-codes&gist=c47613f9034ab9f0562a710b1d7925de

i think this should be allowed as it only defines the variable once

**Comment by erictraut** [comment]
Mypy is correct to flag this as an error. A `Final` symbol cannot be assigned more than once. PEP 591 is very clear on this point.

> There must be exactly one assignment to a final name.

To understand why this is required... `Final` allows you to omit the explicit type annotation. In that case, the type checker infers the type. Since it the symbol is Final, a literal value should be inferred. If we modify the above sample to include the explicit annotations, it becomes:

```python
if foo():
    bar: Final[Literal[1]] = 1
else:
    bar: Final[Literal[2]] = 2
```

Clearly `bar` cannot be both `Literal[1]` and `Literal[2]`.

**Comment by DetachHead** [comment]
```py
from typing import Final, Literal
def foo() -> bool:
    ...
if foo():
    bar: Final[Literal[1, 2]] = 1
else:
    bar: Final[Literal[1, 2]] = 2
```
in that case, i'd expect it to work when i do this?

**Comment by erictraut** [comment]
That's still illegal according to PEP 591.

> There must be exactly one assignment to a final name.

Your example includes two assignments.

**Comment by pranavrajpal** [comment]
I think the reason PEP 591 disallows your second example is because uses of `Final` variables are supposed to be equivalent to using a literal value:
> Type checkers should treat uses of a final name that was initialized with a literal as if it was replaced by the literal.

Allowing multiple different values to be assigned to the same final variable would make that impossible, as you could no longer just replace uses of `Final` variables with the corresponding value and type check a program as if that value was used directly if there are multiple possible values for that variable.

**Comment by hauntsaninja** [comment]
In addition to what others have said, the easy workarounds are a) use ternary expression, b) use a temporary variable, then assign to your final
