### ISSUE TITLE
getattr() type inference fails with empty container as third argument

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#11572]
This code requires a type annotation, which is a regression from mypy 0.910:
```
x = getattr(object(), 'a', [])  # Need type annotation for "x"
```
The signature of `getattr` was changed relatively recently, and it causes the issue. The new signature is better than old one, but this case got worse.

I'm not sure what would be the best way to deal with this, but there are at least these plausible options:
1. Implement a plugin hook that deals with `getattr`.
2. Somehow improve type inference in this case.
3. Modify the signature of `getattr` to make the problem go away by providing e.g. `Iterable[Any]` as the context in an overload variant. This would be pretty ad hoc though.

This is not blocking the 0.920 release, since the workaround is straightforward and this doesn't seem to come up very often.

**Comment by hauntsaninja** [comment]
Relatedly, mypy had other difficulties with the getattr signature changes. In typeshed we ended up adding extra explicit but technically unnecessary overloads for None and bool specifically to help mypy, since those are the most common type of third argument.

https://github.com/python/typeshed/blob/0d7064c357c21572bca5010710f90bc1c86d60e1/stdlib/builtins.pyi#L1060

https://github.com/python/typeshed/pull/5516#issuecomment-846275361

**Comment by JukkaL** [comment]
python/typeshed#6355 works around the issue in the (vast) majority of use cases.
