### ISSUE TITLE
Type annotation + type casting is not understood by mypy

### ISSUE THREAD

**Issue by pjoziak** [python/mypy#11676]
MWE:
```
import typing

class A:
	def __init__(self):
		print('Instantantiated as A')

class B(A):
	def __init__(self):
		super().__init__()
		print('Instantantiated as B')

instance: A = B()
instance: B = typing.cast(B, instance)
```
and then `mypy tmp.py` produces:
```
tmp.py:13: error: Name 'instance' already defined on line 12
Found 1 error in 1 file (checked 1 source file)
```
but if one removes the second type annotation, then `mypy` run is green. 

Is it the really desired outcome? Some other typing plugins for IDE do not understand the fix needed for `mypy`, i.e. removing type annotation, and understand `instance` as an `A`-class after usage of `typing.cast` without it.

**Comment by sobolevn** [comment]
> Is it the really desired outcome?

In my opinion, yes. I would expect this error. Why?

- Because when we use assignment with a type it is something like "variable declaration" in other languages. Say, `let` or `const` in TypeScript. Or `var` in Java. At least for me it is a similar semantic. The same happens without `cast`:
```python
instance: str = 'a'
instance: int = ord(instance) # E: error: Name "instance" already defined on line 1
```

- When we use reassignment (with a different value, but without a type annotation), this is more like a regular reassignment. Like in this example:
```ts
let a = 1
a = 2  # here!
```

So, producing `Name 'instance' already defined on line X` is something I would expect to happen, when I have two type annotations for a single variable assignment with the same name in the same scope.

**Comment by pranavrajpal** [comment]
The original example seems to pass mypy if you use [--allow-redefinition](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-allow-redefinition): https://mypy-play.net/?mypy=latest&python=3.10&flags=allow-redefinition&gist=2a3e23485a3bd4069ff624f4ea97ce62

**Comment by AlexWaygood** [comment]
I agree with the other two commenters in this thread. This doesn't seem like a bug, and there's a config option to switch off mypy complaining if you really want to do this.
