### ISSUE TITLE
Types aliased to class variables are not recognized

### ISSUE THREAD

**Issue by howardzlee** [python/mypy#1180]
```
class A:
    IntType = int

    @classmethod
    def m(cls, i):
        # type: (A.IntType) -> None
        pass
```

```
$ mypy --py2 testclass.py
testclass.py: note: In function "m":
testclass.py:5: error: Invalid type "IntType"
```

**Comment by JukkaL** [comment]
Type aliases can't currently be defined in class bodies, even though they should be okay. The current workaround is to move them to the module top level.

**Comment by ilevkivskyi** [comment]
This is because by current rules unsubscripted classes create variables (instance attributes with types like ``Type[...]``),  _not_ aliases. On the contrary, this works:
```python
class A:
    IntListType = List[int]

    def m(cls, i):
        # type: (A.IntListType) -> None
        reveal_type(i) # Revealed type is 'builtins.list[builtins.int]'
```
It was discussed before if we should change this (i.e. require an explicit annotation to declare a variable instead of an alias) and it was decided not to do this, since local variables are much moe abundant than local unsubscripted aliases.

There is an issue to document this, I am working on it.
