### ISSUE TITLE
Multiple assignment targets not recognised as type aliases

### ISSUE THREAD

**Issue by 0scarB** [python/mypy#11858]
**Bug Report**

Python's [assignment statement](https://docs.python.org/3/reference/simple_stmts.html#assignment-statements) supports multiple targets `target1 = target2 = value`. Types that are assigned to multiple targets are not recognised as aliases by mypy.

**To Reproduce**

```python
from typing import Any

SuccinctlyNamedType = _ExplicitlyNamedType = dict[str, Any]

d1: _ExplicitlyNamedType = {"a": "b"}  # fails
d2: SuccinctlyNamedType = {"a": "b"}  # fails
```

Playground: https://mypy-play.net/?mypy=latest&python=3.10&gist=2d48b69ed185b4eb922b262a37341efb

**Expected Behavior**

No error.

**Actual Behavior**

```
main.py:5: error: Variable "__main__._ExplicitlyNamedType" is not valid as a type
...
main.py:6: error: Variable "__main__.SuccinctlyNamedType" is not valid as a type
...
```

**Your Environment**

- Mypy version used: v0.930 and all less recent versions, I tried
- Python version used: v3.10.1

**Very simple workaround**

Use new assignment statements for each target.

```python
_ExplicitlyNamedType = dict[str, Any]
SuccinctlyNamedType = _ExplicitlyNamedType
```

Playground: https://mypy-play.net/?mypy=latest&python=3.10&gist=6c8d4f13020daa74c5cea1744e320620

---

This a very easy to work around and a niche use case - I don't expect a fix any time soon. Just thought it would be a good idea to document it here

**Comment by erictraut** [comment]
This behavior is intentional. Prior to PEP 613, there was no way in the Python type system to unambiguously define a type alias. A series of rules and heuristics were needed to distinguish a type alias from a regular variable assignment. One such rule is that multiple assignments are not considered a type alias. If your intent is to define two type aliases, the proper way to do so is what you've done in your workaround above. Even better yet, you could use an explicit `TypeAlias` annotation from PEP 613.

```python
_ExplicitlyNamedType: TypeAlias = dict[str, Any]
SuccinctlyNamedType: TypeAlias = _ExplicitlyNamedType
```

**Comment by 0scarB** [comment]
That makes sense. Wasn't aware that this was intentional. Thanks for the clarification and thanks for the tip :)
