### ISSUE TITLE
`stubgen` should also include docstrings

### ISSUE THREAD

**Issue by robertaistleitner** [python/mypy#11965]
**Feature**

When generating `*.pyi` files, docstrings describing the contained classes, methods and members are not included in the file.

**Pitch**

In my opinion it would be helpful to have them and other tools for `pyi` generation do exactly this.

**Comment by tttapa** [comment]
For what it's worth, [sizmailov/pybind11-stubgen](https://github.com/sizmailov/pybind11-stubgen) already supports extracting docstrings from C modules and including them in the stub files.

I think this would be most useful for external C or C++ modules, because some IDEs don't look for signatures or docstrings in compiled modules.  
Using `stubgen` at least fixes autocomplete for compiled modules, but if the stub files don't include docstrings, IDEs might not show any documentation when hovering over the function/class/variable in the editor (unlike with plain Python modules).

For example, Pylance in VSCode doesn't show documentation for functions in compiled modules, even with stub files generated by `stubgen`.

**Comment by nschloe** [comment]
Subscribing and +1 on `--include-docstrings`.  (My use case: [Nuitka](https://github.com/Nuitka/Nuitka/)-compiled modules.)

**Comment by moi90** [comment]
Starting point would be: https://github.com/python/mypy/blob/master/mypy/stubgen.py

**Comment by robertaistleitner** [comment]
Thanks for making this happen @chylek and @ilevkivskyi! 🎉
