### ISSUE TITLE
`@final` and `ParamSpec`

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#12033]
This code produces a strange error:

```python
from typing import ParamSpec, Generic, final

_P = ParamSpec("_P")

@final  # E: Argument 1 to "final" has incompatible type "Type[_lru_cache_wrapper[Any]]"; expected "Type[_lru_cache_wrapper[Any]]"
class _lru_cache_wrapper(Generic[_P]):  
    pass
```

I will take a look, hopefully can fix it today.

Originally seen in https://github.com/python/typeshed/pull/6986

**Comment by AlexWaygood** [comment]
The original error for this issue is no longer reproducible following @A5rocks's PR #11847. However, I'm not sure this issue should be closed yet, since @Akuli's PR #12096 may still be worth merging, as discussed in that PR thread and https://github.com/python/mypy/pull/11847#issuecomment-1091582726
