### ISSUE TITLE
MyPy fails to install with pyenv/poetry due to typed-ast dependency

### ISSUE THREAD

**Issue by sam-hoffman** [python/mypy#12057]
**Bug Report**

**To Reproduce**
On Mac OS 11.3.1:
1. `brew update && brew install pyenv`
2. `pyenv install 3.9.9`
3. `pyenv global 3.9.9`
4. `brew install poetry`
5. Create a `pyproject.toml` as follows:
```
[tool.poetry]
name = "mypy-test"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "3.9"
lxml = "^4.7.1"
lxml-stubs = "^0.2.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pytest-cov = "^2.8.1"
mypy = "^0.740"
pytest = "^6.2.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
6. `poetry update`
7. `poetry install`

I assume this is a `typed-ast` issue but is it possible to work around it for now?

**Expected Behavior**

I thought everything would install!

**Actual Behavior**

Poetry errors out with pages of problems related to `typed-ast`

**Comment by hauntsaninja** [comment]
0.740! Use a version of mypy released less than three years ago ;-) In particular, at some point we changed things so that typed-ast is an optional dependency on Python 3.8 and later (so if you have Python 3.8, you'd only need typed-ast if you want to type check Python 2 code).

If you need to check Python 2 code, I'd be willing to bet typed-ast installs fine, and it's just that mypy 0.740 wants an equally ancient version of typed-ast.

**Comment by sam-hoffman** [comment]
omg, thanks, highly embarrassing
