### ISSUE TITLE
mypy's type narrowing does not work consistently for type(..) or identity checks

### ISSUE THREAD

**Issue by jab** [python/mypy#12106]
**Bug Report**

The https://mypy.readthedocs.io/en/latest/type_narrowing.html docs advertise mypy's ability to narrow types using expressions like `isinstance(obj, float)` and `type(obj) is int`. However, the `type(obj) is int` form is not working as advertised in the reproducer below.

This example also shows off mypy's ability to perform type narrowing for expressions like `obj is None`, i.e. using an identity check[1], but shows that mypy does not apply identity check type narrowing consistently. Apparently this only works for the special case of `NoneType` (as in `obj is None`). Note that this example demonstrates a prominent use case that would be enabled if mypy could consistently apply identity check type narrowing for types besides just NoneType:

```python
d = {1: 'one', 2: 'two'}
v = d.get(3)
reveal_type(v)  # Type of "v" is "str | None"
if v is not None:
    reveal_type(v)  # Type of "v" is "str"

########

d: dict[int, str | None] = {1: 'one', 2: None}

class _NoneType:
    """Private sentinel representing 'missing'.
    For cases where None could be present as a valid value.
    """

_None = _NoneType()

v = d.get(3, _None)
reveal_type(v)  # Type of "v" is "str | _NoneType | None"
# This should work the same as in the `v is not None` on the 4th line above:
if v is not _None:
    # But here mypy thinks type(v) could still be _NoneType, even though it can't:
    reveal_type(v)  # Type of "v" is "str | _NoneType | None"

# Same thing happens if we check the type directly:
if type(v) is not _NoneType:
    # According to https://mypy.readthedocs.io/en/latest/type_narrowing.html
    # mypy should be able to rule out _NoneType here, but it does not:
    reveal_type(v)  # Type of "v" is "str | _NoneType | None"

# At least the isinstance form of type narrowing works here as advertised:
if not isinstance(v, _NoneType):
    reveal_type(v)  # Type of "v" is "str | None"

# However, using isinstance is not a clear or Pythonic way of doing a sentinel check.
#
# It's also 2-3x slower. Being able to write clear, consistent, and idiomatic
# code that mypy understands consistently is the primary concern, but fwiw:
# 
# In [1]: %timeit v is not _None
# 25.7 ns ± 0.476 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
#
# In [2]: %timeit not isinstance(v, _NoneType)
# 62.5 ns ± 1.27 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
#
# In [3]: %timeit type(v) is not _NoneType
# 56 ns ± 0.999 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

I hit this while working on my [bidict](https://github.com/jab/bidict) library, which is type hinted and checked with mypy, and which needs to use non-None sentinels as in the reproducer above. See also [PEP 661 -- Sentinel Values](https://www.python.org/dev/peps/pep-0661/) and its references for additional evidence of interest in better support for sentinels in general.

[1] While putting this issue together, I noticed that identity check type narrowing is not currently documented at https://mypy.readthedocs.io/en/latest/type_narrowing.html -- should that be added there too, at least for the currently-supported special case of `obj is None`?

**Your Environment**

- Mypy version used: 0.931 (currently the latest stable release)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.1 (currently the latest stable release)

**Comment by hauntsaninja** [comment]
The issue is that mypy doesn't know that your custom class is a singleton. That is, it's totally legitimate for `v` to be some other instance of `_NoneType`. This is why you need something like PEP 661, as you linked.

If you want to use sentinels today using identity checks, I recommend using the enum trick: https://www.python.org/dev/peps/pep-0661/#use-a-single-valued-enum.
Otherwise just use isinstance, mypy itself does this here and it's pretty readable: https://github.com/python/mypy/blob/3b331b30049bb085485b8aa7c1fe34064cab927e/mypy/stubtest.py#L196

**Comment by hauntsaninja** [comment]
Ah, sorry, I did miss that.
It's not a bug, it's intentional. `type(obj) is X` narrows `obj` to `X`, but `type(obj) is not X` does not narrow, since `obj` could be a subclass of `X`. I'd welcome improvements to documentation for this.

I don't have thoughts / feel strongly about documenting narrowing `x is None`. It's so idiomatic that people just expect it to work and it does. It's also special cased, so there's no real pattern to learn.

**Comment by erictraut** [comment]
Mypy already handles this case if the class is marked as `final`.
```python
@final
class _NoneType: ...

_None = _NoneType()

v = d.get(3, _None)
if type(v) is not _NoneType:
    reveal_type(v)  # Type of "v" is "str | None"
```
