### ISSUE TITLE
Module attribute assignment gives Module has no attribute error

### ISSUE THREAD

**Issue by pavoljuhas** [python/mypy#12116]
**Bug Report**

When setting new attribute to some other module mypy takes left-hand-side `module.name = value` as attribute access and gives "Module has no attribute" error.  I'd like to use such construct from a top-level `__init__.py` to set a submodule attribute which is not yet defined at the time of submodule import.

**To Reproduce**

Here is an illustrative t.py file (I would not use system module IRL):

```python
import configparser
# this works
setattr(configparser, 'bananas', 7)
# this fails with Module has no attribute "bananas"
configparser.bananas = 7
```

**Expected Behavior**

mypy check is successful.

**Actual Behavior**

mypy check fails with
```
t.py:5: error: Module has no attribute "bananas"
```

**Your Environment**

- Mypy version used: 0.931 
- Mypy command-line flags: mypy t.py
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.9
- Operating system and version: GNU/Linux, Debian 5.14

**Comment by JelleZijlstra** [comment]
This is intentional. Static type checkers need to know what attributes exist on a module based on the module itself, not on assignments in unrelated parts of the code.

That said, you may be able to work around this by adding a type declaration in the affected module, such as adding `bananas: int` in `configparser.py`.

**Comment by pavoljuhas** [comment]
Got it, thank you for explanation.
