### ISSUE TITLE
Use __slots__ as a shorthand for NamedTuple?

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1211]
We found an internal use case where we want to combine NamedTuple with another base class. The idea is that the other base class implements some functionality on top of NamedTuple. But since NamedTuple is a type-factory function you can't subclass it, and mypy doesn't support other functions that wrap it either (let alone a metaclass to do so). Maybe it would be possible to arrange things so that this:

```
class C(B):
    __slots__ = {'a': int, 'b': str}
    ...
```

is more or less equivalent to this?

```
C1 = NamedTuple('C1', [('a': int, 'b': str)])
class C(B, C1):
    ...
```

I realize this doesn't quite work because the dict doesn't have ordering, but maybe there's still something we could do here.

**Comment by JukkaL** [comment]
It would not be quite equivalent to `NamedTuple` because the class wouldn't be tuple-like. However, it wouldn't be hard to teach mypy to infer attributes from `__slots__`. If mypy had a type system plugin system this could be a good candidate for writing an internal plugin, as the dictionary in `__slots__` idiom is non-standard.

(Note also that mypy supports having `NamedTuple(...)` as an immediate base class.)

**Comment by gvanrossum** [comment]
Also see #1240.

**Comment by hauntsaninja** [comment]
This never seemed to go anywhere / mypy has plugins now
