### ISSUE TITLE
(🐞) `TypeGuard` is not captured or retained when passed through a higher order function

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12166]
```py
from typing import TypeGuard, _T, Callable

class Sus:
    def fake_tasks(sus, where: str) -> None: ...

def is_sus(it: object) -> TypeGuard[Sus]: ...

def run(fn: Callable[[], _T]) -> _T: ...

crewmate: int

if run(lambda: is_sus(crewmate)):
    crewmate.fake_tasks("medbay")  # int" has no attribute "fake_tasks"
```

It would make sense if the return result of `run` in this case would retain the `TypeGuard` effects and narrow `crewmate` to a sus imposter.

**Comment by erictraut** [comment]
No, TypeGuard isn't meant to be retained when passing through to a higher order function. It becomes a `bool` at that point. If your intent is to use the function as a type guard, you should call it directly.

**Comment by KotlinIsland** [comment]
For what purpose is it intentionally removed from the type? I want to use a handler but also want the typeguard benefits.

**Comment by neta-elad** [comment]
Is there a technical reason for "widening" `TypeGuard`to `bool` in higher-order functions? This is also broken in lambda functions that aren't passed to higher-order functions:

```python
f = lambda y: isinstance(y, int)
reveal_type(f)  # get Callable[[Any], bool], should be Callable[[Any], TypeGuard[int]]

x: Any

if f(x):
    reveal_type(x)  # get Any, should be int
```

**Comment by erictraut** [comment]
@neta-elad, `isinstance` isn't a user-defined `TypeGuard`. You'll see in `builtins.pyi` that its return type is `bool`, not `TypeGuard`. The type narrowing logic for `isinstance` is too complex for `TypeGuard`, so type checkers need to handle `isinstance` with built-in logic. If you want to use `TypeGuard`, you need to define your own function (not a lambda) and give it an explicit return type of `TypeGuard[int]`.

**Comment by neta-elad** [comment]
I see. However, this does not work for user defined `TypeGuard` just the same:

```python
from typing import TypeGuard, Any

def is_int(x: Any) -> TypeGuard[int]:
    return isinstance(x, int)
    
f = lambda x: is_int(x)
reveal_type(f)  # Any -> bool

y: Any
if f(y):
    reveal_type(y)  # Any
```

This might not seem that important, since for this example we could just use `f = is_int` (which would work in local scope, but, as mentioned above, not when passed to a higher-order function),
but I would argue that this should still work inside lambdas, specifically because it's useful when we want to combine guards:

```python
def is_int(x: Any) -> TypeGuard[int]: ...
def is_str(x: Any) -> TypeGuard[str]: ...

f = lambda x: is_int(x) or is_str(x)
reveal_type(f)  # should be Any -> TypeGuard[int | str]
```

**Comment by erictraut** [comment]
Even if `TypeGuard` were preserved in the lambda, I wouldn't expect `TypeGuard[int] | TypeGuard[str]` to get combined into a `TypeGuard[int | str]`, just like I wouldn't expect `Sequence[int] | Sequence[str]` to get combined into `Sequence[int | str]`. If you want to create a composite type guard function, you should use a `def` statement.

```python
def is_int_or_str(x: Any) -> TypeGuard[int | str]:
    return is_int(x) or is_str(x)
```

**Comment by erictraut** [comment]
`TypeGuard` is not a type, so subtype relationships don't apply here, nor does it make sense to capture `TypeGuard` in a type variable as suggested by the title of this issue. 

`TypeGuard` is a special form that provides metadata about a function's full signature, not just its return type. If you divorce the return type from the rest of the signature (as occurs when capturing the return type into a type variable), it necessarily turns into `bool`, which is the actual return type of a user-defined type guard.

The special form specified in [PEP 647](https://peps.python.org/pep-0647/) was chosen because the Python steering council has made it clear that they're generally unwilling to accept grammar changes for static typing features. Other languages that support user-defined type guards provide dedicated syntax. For example, in TypeScript you would define a user-defined type guard as follows:

```typescript
function isBar(x: Foo): x is Bar {
    return x instanceof Bar;
}
```

When you look at this through the lens of a dedicated syntax, it becomes clear that `TypeGuard` is not a type.

If you capture the return type into a type var (such as in the sample at the top of this issue), the captured type should be `bool` because the return type is now divorced from the full function signature.

If you capture the entire function signature into type variable (e.g. a TypeVar with an upper bound of `Callable[..., Any]`), then it makes sense to retain the metadata implied by the `TypeGuard` special form. And indeed, mypy does this.

```python
from typing import Any, Callable, TypeGuard, TypeVar

S = TypeVar("S", bound=Callable[..., Any])

def is_str(x: Any) -> TypeGuard[str]:
    return isinstance(x, str)

def decorator(f: S) -> S:
    return f

is_str_1 = decorator(is_str)

def test1(x: object):
    if is_str_1(x):
        reveal_type(x)  # str (narrowing is applied)

R = TypeVar("R")

def high_order(f: Callable[[object], R], o: object) -> R:
    return f(o)

def test2(x: object):
    if high_order(is_str, x):
        reveal_type(x)  # object (narrowing is not applied)
```

As I said above, I think mypy is working correctly here. I can state that with some degree of authority because I'm the author of PEP 647. I also wrote the reference implementation of the PEP in pyright, and mypy works consistently with pyright in this case.

I recommend closing this issue.

**Comment by neta-elad** [comment]
Hey Eric, thanks for taking the time to write such a detailed response. I really appreciate it (and I appreciate your contributions to Python in general). I think I understand better how to think of `TypeGuard` now.
