### ISSUE TITLE
problem finding data_dir on Windows when run using "python -m mypy"

### ISSUE THREAD

**Issue by allthedata** [python/mypy#1225]
I ran into issues with mypy on a simple example. Running Windows 8.1, Python 3.5 using Anaconda. Installed mypy using `pip install git+https://github.com/python/mypy.git`
Saved the following as `a.py`:
```python
import typing

def f():
    1 + 'x'  # No static type error (dynamically typed)

def g() -> None:
    1 + 'x'  # Type check error (statically typed)
```

Ran the following in the command prompt: `python -m mypy a.py` and got the following:
```
a.py:1: error: Could not find builtins
a.py:1: error: No library stub file for standard library module 'typing'
a.py:1: note: (Stub files are from https://github.com/python/typeshed)
```

I found that the files were installed in the following locations:
- The `.py` files are in `C:/Users/MyUserName/Anaconda3/Lib/site-packages/mypy`
- The `typeshed` and `xml` directories are in `C:/Users/MyUserName/Anaconda3/Lib/mypy`
- The mypy script is `C:/Users/MyUserName/Anaconda3/Scripts/mypy` (Running mypy in the command prompt doesn't work in Windows, which is why I had to run it as a module.)

I ran pdb and found that when I call mypy as a module:
1. ` __init__.py` calls mypy.main.main(None)
2. `build.build` is called with `bin_dir=None`
3. `build.default_data_dir` is called with `bin_dir=None`
4. `build.default_data_dir` returns `C:/Users/MyUserName/Anaconda3/Lib/site-packages` when it should return `C:/Users/MyUserName/Anaconda3/Lib/mypy`

In `build.default_data_dir`, for the case of `not bin_dir` I changed the line `lib = os.path.dirname(os.path.dirname(parent))` to `lib = os.path.dirname(parent)` and now I can run mypy as a module. Not sure if it's the best solution but it works.

Possibly related issue: https://github.com/python/mypy/issues/653. Later realized that I can run the mypy script within git bash if I change `#!/usr/bin/env python3` to `#!/usr/bin/env python`, and then I don't have to worry about the module stuff. But Windows users installing from pip may not have a bash shell.

**Comment by brettcannon** [comment]
On Windows using CPython 3.5.1 in a venv I'm also running into the `ni\__init__.py:1: error: Could not find builtins` message. The package I want checked is in the same directory I'm running from using the command, .e.g. `.\venv\Scripts\python.exe -m mypy ni`.

**Comment by gvanrossum** [comment]
Maybe a fix similar to #1253 is needed, or a generalization thereof. I can't test on Windows but I'm happy to take PRs from people who are in a position to test them.

**Comment by brettcannon** [comment]
Starting to dig into this for CPython 3.5.1 on Windows 10 in a venv, it looks like https://github.com/python/mypy/blob/d4a555bfa7016432940f38e2029d03e6bae81f18/mypy/build.py#L767 is where the error message is being specified, so that suggests the `builtins` module can't be typed. OK, so that's a stdlib module, so I guess typeshed should be handling this? Anyway, when I print out https://github.com/python/mypy/blob/d4a555bfa7016432940f38e2029d03e6bae81f18/mypy/build.py#L1028 for `builtins` I get `('builtins', ('C:\\Users\\brcan\\Documents\\Repositories\\knights-who-say-ni', '.', '.', '.', '.', '.
', '.', '.', '.', '.', '.', '.'))` which obviously contains no path to typeshed as installed in the venv.

Now looking at my venv, the location of `typeshed` in the venv is `.\venv\Lib\mypy` where there is a `typeshed` and `xml` directory (this is also where some `tcl8.6` in `.\venv\Lib` so this seems to be where `pip` and `setuptools` puts your data files). When I looked at `setup.py I see you specified the `typeshed` files as `data_files` in `setup()`, but then I also noticed you don't use `pkg_resources` or `setuptools` in your code to calculate the path to `typeshed`. So my suspicion is you're making some assumptions somewhere about where `typeshed` files are being installed that are not followed on Windows because you're hand-calculating the paths to data files instead of using `pkg_resources` and/or `setuptools` to do it for you.

**Comment by gvanrossum** [comment]
Correct! The PR that I linked to actually shows the code where this determination is made. Sorry, I should have been more explicit. Here's the logic: https://github.com/python/mypy/blob/d4a555bfa7016432940f38e2029d03e6bae81f18/mypy/build.py#L215

**Comment by allthedata** [comment]
Here's my proposed fix: https://github.com/python/mypy/compare/master...allthedata:master. I tested it on Windows and Ubuntu and it seems to work. Side note: despite the comment in the function that says `__file__ is __init__.py`, on both platforms when I ran mypy as a module I found that `__file__` was actually `build.py`. I didn't test it in a virtualenv so please let me know whether it works in that case.

**Comment by gvanrossum** [comment]
Can you submit that as a PR? Also, you can fix that comment about `__file__` -- it's outdated (I guess the code lived somewhere else long ago).

**Comment by brettcannon** [comment]
Are you willing to take a dependency on `pkg_resources` and/or `setuptools`? I believe the former has a function you can simply use to do the calculation instead of having to reverse-engineer the logic of where `setuptools` installs data files.

**Comment by gvanrossum** [comment]
Honestly I'd prefer not to have those dependencies. And not everyone
uses setuptools.
