### ISSUE TITLE
(😕) `--allow-incomplete-defs` can be misleading and confusing

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12256]
```py
def f(i) -> None: ...
def f2(i): ...
```
```
>mypy --strict --allow-incomplete-defs test.py
test.py:1: error: Function is missing a type annotation for one or more arguments
test.py:2: error: Function is missing a type annotation
Found 2 errors in 1 file (checked 1 source file)
```
I read this as "be strict, but allow partially typed defs" and not show an error on the first line, but it actually only means "be strict".

As far as I can tell there is no such functionality as "allow partially typed defs" due to  `--disallow-untyped-defs` applying to incomplete as well as completely untyped defs.

**Comment by hauntsaninja** [comment]
Closing this feature request since it hasn't attracted much attention. I'm not sure I really see the use case for this feature either. Since mypy doesn't attempt cross-function inference, it's mostly a liability if mypy shuts up if just one argument is annotated, and there isn't a strong gradual typing case to be made for it.
