### ISSUE TITLE
mypy website talks about mypy as if it were it's own language

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1228]
The mypy website refers to "mypy programs" in a number of places, which I think is potentially confusing for new users.  For example, the Examples page calls half the example programs "Mypy with dynamic typing", which made sense historically, but now is a bit strange -- they're all standard Python 3.

I think it could be worthwhile to come up with some standard language for a Python program that mypy can typecheck and then using that consistently on the website.

**Comment by tony** [comment]
"mypy" as a brand inherits a lot of connotations. I'm still confused where mypy sits in the ecosystem, before and now.

I'm of the understanding mypy was a language. Then the type hinting in python 3.5 was inspired by mypy.

The voice inside my head: _So why is there mypy, isn't it redundant? Well maybe mypy exists to give <3.5 type hinting._

The pypi package is "mypy-lang". In addition to how @ddfisher mentions it brands itself as its own language. This could give the uninitiated the impression they're reinventing the wheel with a new language, or its a non-standard, incompatible overlay.

If its the desire to get people collaborating now, prior exposure (on mailing lists, tech news) to mypy being branded as a tool that existed outside of the PEP, it being branded as a language, etc.

As an outsider who has (and still is) experiencing confusion over mypy, I would even consider rebranding it: pytyped. typedpy, typ "type", typyd "typed", something else new.

Gradually, mypy for what it is, is going to become muscle memory to me, and I won't care to press the issue or anything as drastic as above. Its not often we're lucky enough to get issues that the message being conveyed is confusing.

**Comment by JukkaL** [comment]
This confusion is because of the rather complicated history of mypy. Here's a short primer; perhaps something like this should be added to the documentation. I'll also update the website to be less confusing.

**Phase 1: Mypy as a Python variant**

Initially (in 2012) mypy was a Python variant that had a shared subset with Python and a bunch of incompatible extensions, in some ways a bit like Cython used to be, and also similar to how TypeScript works by translating from TypeScript to regular JavaScript. There was a translator from mypy to Python and I started working on a mypy-to-C compiler, though I never got very far and the specifics of mypy weren't well documented back then. This is why the mypy package is called `mypy-lang` and mypy is still called the "mypy language" in some places, and there is talk of "mypy programs".

**Phase 2: Mypy with Python-compatible but non-standardized syntax**

At the suggestion of Guido mypy switched to a new, Python 3 compatible syntax. Guido gave valuable input to the syntax, but there was no PEP 484 yet so it was all mypy-specific. Around this time (or maybe a little later) I mostly forgot about the mypy-to-C compiler, and mypy stopped being a proper language that is distinct from Python. Instead, mypy became a type checker for a Python subset.

**Phase 3: PEP 484**

The idea of PEP 484 was conceived in 2014 with the goal of making the type annotation syntax standard across different tools. The rationale is well documented, but consolidation of effort was obviously an important consideration -- various tools had invented their own type annotation variants that weren't compatible, and this risked fragmenting the domain and making the type checking landscape a mess, a bit like Python packaging has/had been for a long time (at least in my opinion).

The first drafts of PEP 484 were very close to what mypy was doing back then, but later we improved the PEP and at times mypy was playing catch-up and didn't conform to the PEP, as it's much easier to change a spec than to change an implementation. The type system didn't change much during the process (though new features were added), but syntactic details and the specifics of stub files changed a great deal, among other things.

The end result was that Python got a standard type annotation syntax, but there was (and still is) no standard type checker. Mypy is still as relevant as it was before PEP 484 -- actually it's more useful, as other tools such as PyCharm started adopting the standard, and there is starting to be interoperability between tools.

**Present time**

Now mypy mostly conforms to PEP 484 and mypy is simply a type checker targeting standard Python. In particular, mypy type checks Python programs conforming to PEP 484.

**Comment by gvanrossum** [comment]
I think the main action item here is probably to edit the website to
consistently refer to the present situation (except it may be interesting
to have a page explaining the history as Jukka just posted here). But most
of the text should refer to mypy as a tool for type-checking Python code
annotated with PEP 484. (There are also still some vestiges of the loftier
earlier plans in the code, esp. in main.py and build.py, that as some point
I'd like to remove.)

**Comment by JukkaL** [comment]
I updated the website though I didn't verify every single thing. Anybody spot any out-of-date language still, or can we close this issue?

**Comment by JukkaL** [comment]
I'm moving this to 0.3.3 since the worst offenders are probably already fixed and going through the website doesn't seem productive right now.

**Comment by JukkaL** [comment]
I'm closing this since nobody has spotted any remaining issues. We can can reopen this if we still found something or create a new issue.
