### ISSUE TITLE
Regression - Module "_typeshed" has no attribute "SupportsLessThan"

### ISSUE THREAD

**Issue by Zeckie** [python/mypy#12355]
**Bug Report**

The example of using `SupportsLessThan` in [the documentation](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-types-defined-in-stubs-but-not-at-runtime) does not work in mypy 0.941 or 0.940.

**To Reproduce**

https://mypy-play.net/?mypy=0.931&python=3.10&gist=6ad43abe09b33cd9dceea02d40c0224d

Works correctly on 0.931, but not 0.941 or 0.940.

**Comment by AlexWaygood** [comment]
We got rid of `SupportsLessThan` from `_typeshed` in https://github.com/python/typeshed/pull/6583, because it wasn't doing a great job at describing the various types at runtime it was trying to describe. We replaced it with a new `SupportsRichComparison` type, which is a little more complicated, but does a much better job at describing the types at runtime.
