### ISSUE TITLE
Type narrowing with type() comparisons fails

### ISSUE THREAD

**Issue by Klim314** [python/mypy#12371]
**Bug Report**

Type narrowing fails when explicit type comparisons are used, but succeeds when isinstance is used instead. Notably, this differs from existing [documentation ](https://mypy.readthedocs.io/en/stable/type_narrowing.html#type-narrowing)

**To Reproduce**

```
def foo(a: str):
    pass

def bar(s: int):
    pass

a: str|int = 1

# This fails
if type(a) is str:
# This works
# if isinstance(a, str):
    print(reveal_type(a))
    foo(a)
else:
    print(reveal_type(a))
    bar(a)
```

**Expected Behavior**

both `isinstance` and `type` can be used to narrow the type to `int` when bar is called

**Actual Behavior**

Only `isinstance` successfully narrowed the type for bar. `type` instead raised an incompatible type error.

**Your Environment**

- Mypy version used: 0.941
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.8, 3.10
- Operating system and version: WSL2, ubuntu

**Comment by pranavrajpal** [comment]
This is expected behavior. `type(a) is str` will be False if `a`'s type is a subclass of `str`, so `a` in the else case could be a subclass of `str`.

The solution to this is to either mark the class as [`final`](https://docs.python.org/3/library/typing.html#typing.final) (if possible) to tell mypy that it can't be subclassed, or to just use `isinstance`.
