### ISSUE TITLE
mypy fails for a simple `Any` type alias`

### ISSUE THREAD

**Issue by srittau** [python/mypy#12421]
I can't reproduce this locally, but please have a look at the CI failures of python/typeshed#7535. The change is a simple type alias `Incomplete = Any`. The `TypeAlias` is optional, mypy fails with or without it. CI runs mypy 0.941 with all Python versions.

**Comment by AlexWaygood** [comment]
#12134 (by @sobolevn) contains a fix for this bug. I think it might be good to excise that fix into a standalone PR.

**Comment by JukkaL** [comment]
I'll extract the `Any` fix from #12134 to a standalone PR. (cc @sobolevn)

**Comment by JukkaL** [comment]
Extracted the fix to #12429. The issue seems specific to typeshed (and possibly typeshed tests, in particular), and only reproduces for me if the files are passed to mypy in a specific order in the typeshed mypy test. I was able to reproduce it on macOS occasionally by randomizing the order of files passed to mypy.
