### ISSUE TITLE
Use enums instead of manually assigning small integers

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1243]
We use manually rolled enum equivalents in a number of places instead of just using the 3.4 enum module.  Using real enums would make debugging a lot nicer in some cases.

The main downside to this change is that it'll add an additional dependency when running on 3.3 and below.

**Comment by JukkaL** [comment]
This would be a reasonable thing to refactor, though not high priority.

**Comment by elazarg** [comment]
I have a working branch, with 4 new Enums.

By order of impact:
 1.  Literal(YES|NO|TYPE): relatively minor and local change
 2. Variance: The result is longer and not match clearer, except here and there in type annotations
 3. Argument kinds
 4. Node kinds

**Comment by gvanrossum** [comment]
Maybe do one at a time? Do you use enum34 from PyPI or would this imply dropping Python 3.3?

**Comment by elazarg** [comment]
I did it only as an experiment. the Literal part is pretty trivial (and not very helpful). I'm not familiar with enum34; I can try it.

**Comment by elazarg** [comment]
As for Variance, I think that `NewType` will be more suitable than `Enum`, because the names are already very descriptive, and it's unlikely to be confused wit something else. Node kinds and Argument kinds are more likely to be mixed accidentally,

(I used `IntEnum` to avoid dealing with Json serialization. I guess it's not big deal anyway)

**Comment by elazarg** [comment]
I don't know if that's common knowledge, but I've found out that enum access is very very slow. I guess it won't be noticeable in this project, but that's another thing to take into account.

**Comment by JukkaL** [comment]
I've heard bad things about enum performance. Improving mypy performance is going to be a main focus of the core team, and switching to enum carries some risk. It's not worth it, even if the risk is small. 

I'm not closing this issue since this may make sense in the long term, after we are happy with mypy performance.

**Comment by elazarg** [comment]
How about using NewType?

**Comment by JukkaL** [comment]
NewType creates a subtype so it's less safe than an enum. I'd prefer to (eventually) switch to enums.

**Comment by ilevkivskyi** [comment]
There is a discussion on python-dev about improving Python start-up time and enums being slow is one of the issues discussed. There is a chance performance will be improved in Python 3.7.
