### ISSUE TITLE
Windows CI builds broken

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#12460]
Currently all Windows CI builds seem to be broken. 

Example failure: https://github.com/python/mypy/actions/runs/2044190861

This might be caused by the switch to a new CI image with Windows Server 2022: https://github.com/actions/virtual-environments/issues/4856

We could try falling back to Windows-2019 temporarily while we investigate what is going on.

Any help with investigating the failures would be appreciated, since I don't do much development in Windows.

**Comment by JelleZijlstra** [comment]
The only suspicious thing I saw in the output is `cl : Command line warning D9002 : ignoring unknown option '/O0'`. https://docs.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=msvc-170 doesn't mention O0. Maybe it's a setuptools issue?

**Comment by ethanhs** [comment]
I can take a look at the issue a little later.

**Comment by KotlinIsland** [comment]
last pass was https://github.com/python/mypy/runs/5694572863?check_suite_focus=true
first fail was https://github.com/python/mypy/runs/5700430887?check_suite_focus=true

The last pass was on windows server 2022, so I don't think that is the root cause.

This is the `MYPYC_OPT_LEVEL` being set here:

https://github.com/python/mypy/blob/1480344cfc99ed0396c2b9b9f36c14b253f440b4/mypyc/test/test_run.py#L246

**Comment by JelleZijlstra** [comment]
In #12462 I tried to fix the `/O0` issue; unfortunately it didn't fix the build.

**Comment by pranavrajpal** [comment]
setuptools had some releases around the time CI started failing, and since the bug seems to be related to the names of the generated extension modules and I think we use setuptools to handle the compilation, a setuptools change could cause a failure there.

The last pass in https://github.com/python/mypy/issues/12460#issuecomment-1079848551 seems to be using setuptools 61.0.0, and the first fail seems to be using 61.1.0.

I haven't looked too much into what the cause of the failures is, but it seems worth trying to pin setuptools to 61.0.0 for now to see if that fixes the CI.

**Comment by ethanhs** [comment]
I started looking into it last night, but it seems that the test suite hangs and I cannot Ctrl+C when it fails for me, which is unfortunate. I will try to run things with failfast and see if using an older setuptools fixes things. (Hopefully it fixes the test hanging as well, but that may be another issue).

**Comment by jhance** [comment]
https://github.com/python/mypy/runs/5714129295?check_suite_focus=true

Doesn't seem like its setuptools?

**Comment by KotlinIsland** [comment]
virtualenv==20.13.4 went to virtualenv==20.14.0?

**Comment by KotlinIsland** [comment]
#12471 that didn't help either

**Comment by JukkaL** [comment]
I'm doing some experiments in #12476. The first result is that a running single test case still fails (`-k testRunDataclass`), which makes it faster to iterate using a PR. I also disabled all the other builds in this PR to avoid using lots of CI capacity.

**Comment by JukkaL** [comment]
Seems to be fixed now. Thanks for the help! 

It would be great if somebody could install the latest Windows wheel from https://github.com/mypyc/mypy_mypyc-wheels (once it's ready) and check that it works and is compiled.

**Comment by pranavrajpal** [comment]
It looks like this is an instance of pypa/setuptools#3219, and setuptools upgrading was what broke the CI. I think #12471 didn't help because the CI run still appears to be using setuptools version 61.2.0 because there are 2 `pip install` commands that try to install setuptools ([here](https://github.com/python/mypy/blob/a66cb498ed6bd8b582ccc9e88c89cef332ef8245/.github/workflows/test.yml#L111) and [here](https://github.com/python/mypy/blob/a66cb498ed6bd8b582ccc9e88c89cef332ef8245/.github/workflows/test.yml#L115)) and for some reason pip doesn't appear to be reinstalling setuptools for the second one.

**Comment by ethanhs** [comment]
> It would be great if somebody could install the latest Windows wheel from https://github.com/mypyc/mypy_mypyc-wheels (once it's ready) and check that it works and is compiled.

I will test this once I am back in front of my computer in about an hour.

**Comment by ethanhs** [comment]
Things seem to be working as expected!
