### ISSUE TITLE
Timely releases on conda-forge

### ISSUE THREAD

**Issue by twoertwein** [python/mypy#12742]
This is not a mypy issue.

Conda-forge has not yet updated mypy to 0.950 even though an [automated PR](https://github.com/conda-forge/mypy-feedstock/pull/67) has been created 10 days ago and the last active maintainer has been pinged.

For mypy's new monthly release cycle, it might be beneficial if some mypy maintainers become maintainers of https://github.com/conda-forge/mypy-feedstock to provide timely releases through conda-forge.

**Comment by JelleZijlstra** [comment]
I'm not sure any of the maintainers are familiar with Anaconda. What would being a maintainer of mypy-feedstock entail?

**Comment by twoertwein** [comment]
I don't know, it is probably a bit more than just merging automated PRs.

**Comment by nehaljwani** [comment]
Hi, I am one of the maintainers at https://github.com/conda-forge/mypy-feedstock. Apologies for the delay. I was on vacation.

**Comment by twoertwein** [comment]
Thank you @nehaljwani! Hope you had a nice vacation!

Feel free to close this issue @JelleZijlstra, unless @nehaljwani wants to recruit you/others to help at conda-forge ;)

**Comment by nehaljwani** [comment]
A helping hand is always welcome!

**Comment by hauntsaninja** [comment]
Thanks Nehal for helping make mypy more accessible! Closing this issue out, since it seems like mypy-feedstock is up to date.

I don't know much about Anaconda so can't really offer to help, but let us know if there are things we can do to help or if you want a mypy maintainer with commit access on there in case you get hit by a bus.
