### ISSUE TITLE
NamedTuple with no fields causes `"object" not callable` error

### ISSUE THREAD

**Issue by averagehat** [python/mypy#1276]
```python
Blue = NamedTuple("Blue", [])
```
Fails with:
```python
example.py:5: error: "object" not callable
```

But this code runs fine in python2/python3.

__Edit__:  
Seems like it's falling out to [here](https://github.com/python/mypy/blob/e308f2f786d432577286e0d84abaca505d02ec81/mypy/checkmember.py#L160)
a bit odd to me because NamedTuple does indeed have a `__call__` attribute

Interesting. The following fails:
```python
alist = [('afield', str)]
Green = NamedTuple("Green", alist)

example.py:3: error: List literal expected as the second argument to namedtuple()
example.py:3: error: "object" not callable
```
But this works:
```python
Green = NamedTuple("Green", [('afields', str)])
```
I think the `type_map` is storing `NameExpr(NamedTuple [typing.NamedTuple])` as an `object`, and it looks like the in the latter case it's skipping a check . . . I remember reading in an issue that NamedTuple wasn't fully supported, so I assume that's what's going on.

**Comment by gvanrossum** [comment]
I think I know what this is. Because there are no items, the code [here](https://github.com/python/mypy/blob/e308f2f786d432577286e0d84abaca505d02ec81/mypy/semanal.py#L1355) thinks there's an error. It then skips the assignment to `call.analyzed` a few lines later. Maybe it can be fixed by changing "return" to "info =" in the error branch.

**Comment by gvanrossum** [comment]
FWIW the thing you noted with using a variable for the list of fields is unrelated -- it's a general thing that mypy doesn't understand dynamically constructed types.
