### ISSUE TITLE
dmypy: run multiple independent daemons

### ISSUE THREAD

**Issue by Jasha10** [python/mypy#12771]
While editing python files, I use two tools that both rely on `dmypy` as a backend.
Sometimes one tool causes the other tool to malfunction via `dmypy` interaction.

For example, tool 1 works well on its own, but once I start tool 2, tool 1's call to `dmypy` results in a "configuration changed" message and a "No data received" error with exit code 2:
```
Restarting: configuration changed
Daemon stopped
Daemon started
No data received
```

**Feature**

I would like each tool to use it's own instance of `dmypy`. Tool 2 should not interfere with tool 1.
Perhaps this could be configured via a command-line flag for the `dmypy` executable.

**Comment by pranavrajpal** [comment]
I believe this should already be supported by the [`--status-file`](https://mypy.readthedocs.io/en/stable/mypy_daemon.html#cmdoption-dmypy-status-file) flag. Both tools would have to create their own names for the status file in a way that wouldn't result in conflicts so that both don't end up trying to use .dmypy.json as the status file.

**Comment by Jasha10** [comment]
Awesome... Thanks very much!!
