### ISSUE TITLE
TypeVar[x, y] cannot be Union[x, y] error

### ISSUE THREAD

**Issue by headtr1ck** [python/mypy#12789]
**Bug Report**

A `TypeVar` with multiple possible Values seems incompatible with a `Union` of the exact same Values.
If a function expects a Typevar but is given such a Union, mypy should infer that this is acceptable.
Instead mypy raises an error.

Unless my understanding of TypeVars is completely wrong :(

**To Reproduce**

```python
from typing import TypeVar

T = TypeVar("T", int, str)

def x(i: T) -> T:
    return i
    
def y(i: int | str | None) -> int | str:
    if i is None:
        return -1
    return x(i)
```
(The None is actually not needed to reproduce this code it is just a placeholder to show that more things are going on in y. Also, in the real code the return value of x is used for further processing, so using `T | None` as type for `i` is not useful.)

**Expected Behavior**

In function `y`:
The input to `x` is either `int` or `str`, so it should be conform to the typevar `T`.
Since we cannot know the type, mypy should infer that `x` in this instance returns `int | str`. 

**Actual Behavior**

Mypy complains: `error: Value of type variable "T" of "x" cannot be "Union[int, str]"  [type-var]`

**Your Environment**

- Mypy version used: 0.950
- Mypy command-line flags: /
- Mypy configuration options from `mypy.ini` (and other config files): /
- Python version used: 3.9.12
- Operating system and version: win10

**Comment by AlexWaygood** [comment]
This is expected behavior. When using a `TypeVar` constrained to `int` or `str`, the `TypeVar` can only be "solved" as being _exactly_ `int` or `str` (it cannot be a subclass of `int`, a subclass of `str`, or the union `str | int`. You probably want to use a `TypeVar` bound to a union instead:

```python
# You can use PEP 604 syntax if you're on Python 3.10+
from typing import TypeVar, Union
T = TypeVar("T", bound=Union[str, int])
```

https://docs.python.org/3/library/typing.html#typing.TypeVar

**Comment by AlexWaygood** [comment]
> While indeed `T` cannot be `int | str`, the value passed to `x()` will be either an integer or a string, not some kind of superposition of both.

This is true in _this_ case, but I don't see how mypy could be expected to be able to understand that while simultaneously holding to the spec laid out in PEP 484. PEP 484 states:

> TypeVar supports constraining parametric types to a fixed set of possible types (note: those types cannot be parameterized by type variables). For example, we can define a type variable that ranges over just `str` and `bytes`. By default, a type variable ranges over all possible types. Example of constraining a type variable:
> 
> ```python
> from typing import TypeVar, Text
> 
> AnyStr = TypeVar('AnyStr', Text, bytes)
> 
> def concat(x: AnyStr, y: AnyStr) -> AnyStr:
>     return x + y
> ```
>
> The function `concat` can be called with either two `str` arguments or two `bytes` arguments, but not with a mix of `str` and `bytes` arguments.

In this kind of example, it is _crucial_ for type safety that we disallow solving `AnyStr` as being `str | bytes`. And this is the whole reason why we have constrained `TypeVar`s as well as `bound` `TypeVar`s. Otherwise, we would only have `bound` `TypeVar`s, which -- in my opinion -- are usually easier to reason about, and have more intuitive behaviour.

Using a `bound` `TypeVar` works fine here (or, should do, if it weren't for some lingering mypy bugs). So I don't personally see a particularly compelling argument for this feature request.

**Comment by mthuurne** [comment]
I think the solution here isn't reducing `T` to `int | str`, but splitting up the call to `f()` into one path that uses `int` exclusively and another path that uses `str` exclusively. That is also what happens in the modified test cases that use `@overload` or the conditional expression. The union only appears when merging the return values from both branches, not in the call to `f()` itself.

**Comment by AlexWaygood** [comment]
> I think the solution here isn't reducing `T` to `int | str`, but splitting up the call to `f()` into one path that uses `int` exclusively and another path that uses `str` exclusively. That is also what happens in the modified test cases that use `@overload` or the conditional expression. The union only appears when merging the return values from both branches, not in the call to `f()` itself.
> 
> What I'm trying to say is that it is correct that `f()` refuses an argument of type `int | str`. But given that refusal, mypy could try to split up the union at the call site and try `int` and `str` individually and if calls succeed for each element of the split, merge the resulting types into a new union, that just happens to be `int | str` as well.

But this sounds complicated, and I'm still not sure I see the advantages over the existing mechanisms (bound `TypeVar`s, overloads).

**Comment by AlexWaygood** [comment]
- This issue was filed as a bug report, and (at present) this is definitely intended behaviour. So I'm not going to reopen it.
- I'm still not 100% convinced that this feature can be implemented without a PEP change, so I'm still not convinced the mypy issue tracker is the best place for this discussion.
- I think it's pretty unlikely that the feature will be implemented unless you file a PR yourself.
- I'm also not an expert on mypy's internals, but I think making this change could be tricky, and could open up the possibility of more bugs in the future.
- I'm still not particularly sold on the feature itself. Yes, constrained `TypeVar`s can be pretty counter-intuitive, but I think this change could make explaining them even harder. And as I've said, I think the existing solutions (bound `TypeVar`s, overloads) work fine.

**Comment by mthuurne** [comment]
Fair enough.

I think the requested behavior does not contradict the PEP, since the PEP effectively requires a constrained `TypeVar` to be handled the same as a series of `@overload` declarations.

This feature itself is not urgent for me; I happened to find it when I was investigating what looked like a related issue, but that turned out to be something entirely different when I minimized the test case.

So I'm fine with this issue staying closed for now, although I do hope that some day it will be implemented. Thanks for your time and explanations.

**Comment by erictraut** [comment]
I agree with Alex that mypy is doing the right thing here. I also think it's unlikely that this will change in the future.

Consider the following small change to your example:
```python
from typing import TypeVar
T = TypeVar("T", int, str)

def x(i: T, j: T) -> T:
    ...

def y(i: int | str, j: int | str) -> int | str:
    return x(i, j)
```

I think it's clear in this case that the expression `x(i, j)` should result in a type violation error. What if we changed `x(i, j)` to `x(i, i)`? The arguments have the same type in both cases, so they should arguably have the same behavior.

Or consider this variant:
```python
def x(i: Sequence[T]) -> T:
    ...

def y(i: Sequence[int | str]) -> int | str:
    return x(i)
```

Here again, I think it's clear that this should generate a type violation error.
