### ISSUE TITLE
mypy gets confused by double coding cookie

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1281]
When a file has two different coding cookies (one in line 1, one in line 2) mypy gets confused and uses the cookie from the second line. It should use the first.

Low priority; I found this by accident and the new parser will presumably make this go away.

**Comment by andersschuller** [comment]
I remember reading through [the PEP](https://www.python.org/dev/peps/pep-0263/) and [the docs](https://docs.python.org/3/howto/unicode.html#unicode-literals-in-python-source-code) about this when I was considering picking up #522. I was slightly surprised that neither of them seem to document the expected behaviour when both the first and second lines contain a valid encoding comment. However it's entirely possible that I missed something, and in any case it's probably best to match the behaviour of CPython as you suggest.

**Comment by gvanrossum** [comment]
FWIW I clarified this in the PEP.

**Comment by serhiy-storchaka** [comment]
The regular expression that matches the current behavior of CPython is `br'(\xef\xbb\xbf)?([ \t\f]*(?:#.*)?(?:\r\n?|\n))??[ \t\f]*#.*?coding[:=][ \t]*([-\w.]+)'`.

You should check the BOM, the first line can be blank, and `\s` in current regexp matches too wide range of whitespace characters (in particular `'\n'` and `'\r'`).

**Comment by gvanrossum** [comment]
Thanks! We do the bom checking elsewhere and I've already updated the
regex according to your earlier advice
(8f3381c3b2a3a2f3330b247b07cba7b5ab4977c5).
