### ISSUE TITLE
`@classmethod` typing for `cls` argument when use `cls.method()` inside it

### ISSUE THREAD

**Issue by diego-garro** [python/mypy#12847]
Hi everyone! I have a little trouble with this:

How can I get typing the `cls` argument in a class method when I have to use `cls.method()` inside it?

I saw the hint of use

```Python
from typing import TypeVar, Type

T = TypeVar("T", bound="Foo")

class Foo:

    @classmethod
    def bar(cls: Type[T], arg: Any) -> T:
       # snip behavior
       return cls(*args)

    def some_method(self, arg: str) -> str:
        # snip behavior
        return "some string"
```
But, when I have to use a method from the class `Foo` inside `bar` like:

```Python
class Foo:

    @classmethod
    def bar(cls: Type[T], arg: Any) -> T:
       # snip behavior
       cls.some_method()
       # snip behavior
       return cls(*args)

    # snip method
```
I get the error: Argument 1 to "some_method" of "Foo" has incompatible type "Type[T]"; expected "Foo", because of the `self` argument in `some_method`.

So, what it is the correct typing for this case and make error disappear? I have tried several hints found on the web but not help me.
Thanks for your time! :)

**Comment by AlexWaygood** [comment]
It would be easier to understand your problem if you could provide a fully self-contained snippet of code that illustrates the problem, instead of splitting it between two snippets.

But it looks to me like mypy is correct to emit an error in this case, since you're trying to access an instance method from the class, instead of from an instance.

**Comment by diego-garro** [comment]
@AlexWaygood that's correct, the method must be static... How can I erase this? haha
