### ISSUE TITLE
Don't run PEP561 tests in runtests.py by default

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#12879]
Now that PEP561 tests run sequentially (#12857), they can take a big fraction of the
entire runtests.py runtime. I think that we should make the tests opt-in, similar to some 
of the slow mypyc tests. They will run in CI always in any case.

Anybody want to help with this?

**Comment by erikkemperman** [comment]
> Anybody want to help with this?

Since I am responsible for making the PEP561 so much slower, I think it's only fair that I be the one to make them optional :-)

By the way, these tests aren't completely sequential, just the `pip install` steps were made to not overlap. It's a lot slower than before, to be sure, but `pytest -n0` is even worse (at least on my machine).
