### ISSUE TITLE
Inconsistency in use `builtin.type` and `typing.Type` in error messages

### ISSUE THREAD

**Issue by denballakh** [python/mypy#13027]
Consider this example:
```py
x: type[type]
reveal_type(x) # Revealed type is "Type[builtins.type]"

reveal_type(type[type]) # Value of type "Type[type]" is not indexable
                        # Revealed type is "Any"
```
Here im using only `builtins.type`, but in error messages and notes i can see:
- `type` (i think it is the same as `builtins.type`)
- `builtins.type`
- `Type` (i think it is the same as `typing.Type`)

**Expected Behavior**
Choose one alias for `builtins.type` and use it everywhere.
OR
Use the alias that was used in the code.

**My Environment**
- `mypy 0.961 (compiled: no)`
- no command-line flags, no config file
- `CPython 3.10.4`
- Windows 10

**Comment by rohitsanj** [comment]
There are [two places](https://github.com/search?q=repo%3Apython%2Fmypy%20f%5C%22Type%5B&type=code) where we construct uppercase `Type` in an error/note. 

- [`mypy.types.TypeStrVisitor.visit_type_type`](https://github.com/python/mypy/blob/16b936c15b074db858729ed218248ef623070e03/mypy/types.py#L3189) - used for notes
- [`mypy.messages.format_type_inner`](https://github.com/python/mypy/blob/16b936c15b074db858729ed218248ef623070e03/mypy/messages.py#L2520) - used for errors -- fixed in #15139
