### ISSUE TITLE
Stubtest: option to ignore "runtime does not have argument" when implementation accepts *args/**kwargs

### ISSUE THREAD

**Issue by twoertwein** [python/mypy#13305]
**Feature**

Pandas uses many decorators. Some of them change the function signature, e.g., `@deprecate_nonkeyword_arguments(...)` exposes a function that accepts `*args, **kwargs` instead of the original function. It would be nice to have an option to suppress "runtime does not have argument"-warnings when the implementation accepts *args/**kwargs.

**Pitch**

Add an option to deal with decorators or args/kwargs.

@hauntsaninja

**Comment by hauntsaninja** [comment]
I assume you're referring to errors like the following?
```
pandas.DataFrame.ffill is inconsistent, runtime argument "inplace" is not keyword-only
pandas.DataFrame.ffill is inconsistent, runtime argument "limit" is not keyword-only
pandas.DataFrame.ffill is inconsistent, runtime argument "downcast" is not keyword-only
pandas.DataFrame.ffill is inconsistent, runtime does not have argument "downcast"
pandas.DataFrame.ffill is inconsistent, runtime does not have argument "inplace"
pandas.DataFrame.ffill is inconsistent, runtime does not have argument "limit"
```

stubtest does actually handle decorators and args / kwargs mostly well. The issue is that `pandas.DataFrame.ffill` does not look like it takes `*args, **kwargs`. Because `deprecate_nonkeyword_arguments` uses `functools.wraps`, `inspect.signature` sees a more complete signature:
```
In [4]: inspect.signature(pandas.DataFrame.ffill)
Out[4]: <Signature (self: 'DataFrame', axis: 'None | Axis' = None, inplace: 'bool' = False, limit: 'None | int' = None, downcast=None) -> 'DataFrame | None'>
```

stubtest's output^ is confusing, but it basically is reporting errors twice, once when checking whether positional args match and once when checking whether keyword-only args match:
```
pandas.DataFrame.ffill is inconsistent, runtime argument "downcast" is not keyword-only
pandas.DataFrame.ffill is inconsistent, runtime does not have [keyword-only] argument "downcast"
```
If I were to fix the duplication, you'd still get the following (because `inspect.signature` sees the full signature because of `functools.wraps`):
```
pandas.DataFrame.ffill is inconsistent, runtime argument "inplace" is not keyword-only
pandas.DataFrame.ffill is inconsistent, runtime argument "limit" is not keyword-only
pandas.DataFrame.ffill is inconsistent, runtime argument "downcast" is not keyword-only
```

**Comment by twoertwein** [comment]
Thank you, that makes sense that it errors because of the arguments not being keyword-only! I focused only on the many "runtime does not have argument" warnings which did not seem very intuitive.

**Comment by hauntsaninja** [comment]
#13307 will fix the duplicate error, so will just say:
```
pandas.DataFrame.fillna is inconsistent, stub argument "limit" differs from runtime argument "inplace"
pandas.DataFrame.fillna is inconsistent, stub argument "downcast" differs from runtime argument "limit"
pandas.DataFrame.fillna is inconsistent, stub argument "inplace" differs from runtime argument "downcast"
```
