### ISSUE TITLE
Convert type `[A | B]` to type `[A] | [B]` when the list has a single element

### ISSUE THREAD

**Issue by ajhynes7** [python/mypy#13388]
**Pitch**

I have two functions that look like this:

```py
from uuid import UUID


def get_objects(object_ids: list[int] | list[UUID]):
    pass


def get_object(object_id: int | UUID):

    return get_objects([object_id])
```

The `get_object` function takes an ID which is either an `int` or a `UUID`. It puts this ID into a list and passes this to `get_objects`, which accepts either a list of `int`s or a list of `UUID`s.

`mypy` raises an error on this code.

```
Argument 1 to "get_objects" has incompatible type "List[Union[int, UUID]]"; expected "Union[List[int], List[UUID]]"
```

I understand that this isn't a bug, because a list of either `int`s or `UUID`s isn't equivalent to a list of all `int`s or a list of all `UUID`s. But when the list has only one element, it actually does satisfy the typing requirement of being either a list of all `int`s or a list of all `UUID`s, because it's either a list with one `int` or a list with one `UUID`.

So I'm wondering if mypy could recognize that this list has only element, and hence convert the type of `[A | B]` to `[A] | [B]`.

**Comment by JelleZijlstra** [comment]
I can see the use case, but this feels like an awfully special special case. The suggested change could generate new problems because list is invariant. Pyright also rejects the code in your sample.

**Comment by ajhynes7** [comment]
Ok, that's understandable. In this case, I guess the simplest solution would be to just change the type annotation of `get_objects` to `list`.

```python
from uuid import UUID


def get_objects(object_ids: list):
    pass


def get_object(object_id: int | UUID):

    return get_objects([object_id])

**Comment by terencehonles** [comment]
Just driving by, but if you're able to handle either in `get_objects`, does it actually need to be a homogeneous list? Your alternative typing suggests it doesn't, and at that point you might as well declare `def get_objects(object_ids: list[int | UUID]) -> None` since that would also pass the type checking.

It's an interesting corner case and why I looked at what the description was. Generalized any array of one or less can be deconstructed to union of homogeneous arrays of any type in the union (zero is a special case where it still can be any type).

If you indeed need a homogeneous list, I would think implementing a type guard which checks the item types would allow you to safely inform mypy that the type is not a heterogeneous list of the type union instead of using a cast which you _can_ use in your code:

```python
def get_object(object_id: int | UUID):
  return get_objects(cast(list[int] | list[UUID], [object_id]))
```

**Comment by ajhynes7** [comment]
Thanks for the tips @terencehonles.
