### ISSUE TITLE
[regression] Callable field first argument is not recognized as self

### ISSUE THREAD

**Issue by opk12** [python/mypy#14053]
**Bug Report**

A field of type `Callable[['C', Any], Any]` is called as `object.field(args)`. Older mypy versions accepted this; newer mypy wants me to call `object.field(object, args)` which fails at runtime.

**To Reproduce**

The requested playground link is https://mypy-play.net/?mypy=latest&python=3.10&gist=99746aed7661ae1228ace92ba4b74ffb

**Expected Behavior**

mypy should accept `C().f(3)`.

**Actual Behavior**

```
$  mypy a.py --pretty
a.py:11: error: Too few arguments  [call-arg]
    print(C().f(3))        # mypy error, runtime works: (<class '__main__.C'>, <class 'int'>)
          ^~~~~~~~
a.py:11: note: "f" is considered instance variable, to make it class variable use ClassVar[...]
a.py:11: error: Argument 1 has incompatible type "int"; expected "C"  [arg-type]
    print(C().f(3))        # mypy error, runtime works: (<class '__main__.C'>, <class 'int'>)
                ^
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.990
- Python version used: 3.9.2 from debian 11

**Comment by ilevkivskyi** [comment]
You should annotate that field as `ClassVar[Callable[['C', Any], Any]]` since you are setting it on class. Then it should work as expected. See examples at the bottom of this section https://mypy.readthedocs.io/en/stable/class_basics.html#class-attribute-annotations

Actually looking at the error message mypy is already told you to do this:
```
a.py:11: note: "f" is considered instance variable, to make it class variable use ClassVar[...]
```
