### ISSUE TITLE
Incorrect inferred type

### ISSUE THREAD

**Issue by epenet** [python/mypy#14210]
**Bug Report**

Whilst working on HomeAssistant PR, found this weird behavior where the type inferred from a dict is completely wrong.
https://github.com/home-assistant/core/pull/82853

**To Reproduce**

```python
ZHA_HW_DISCOVERY_DATA = {
    "name": "Yellow",
    "port": {
        "path": "/dev/ttyAMA1",
        "baudrate": 115200,
        "flow_control": "hardware",
    },
    "radio_type": "efr32",
}
reveal_type(ZHA_HW_DISCOVERY_DATA)
```

**Expected Behavior**

I would have expected the value type to be `dict[str, str | dict]`, or maybe `dict[str, Any]`

**Actual Behavior**

Revealed type is `builtins.dict[builtins.str, typing.Collection[builtins.str]]`

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.15

**Comment by AlexWaygood** [comment]
This is another one of the many "join-vs-union" behavioural peculiarities that mypy has: in many situations, mypy prefers to infer a type as being a common supertype rather than a union. Here, it sees that some values in the dictionary are `str`, and others are `dict[str, object]`, so infers `Collection[str]`, since this is indeed a common supertype of `str` and `dict[str, object]` according to the definitions in typeshed.

We already have _many_ join-vs-union issues open, and I don't really think we need another, so I'm going to close this out. Follow #12056 for discussion on possibly changing mypy's behaviour here :)
