### ISSUE TITLE
List with Union do not really typecheck

### ISSUE THREAD

**Issue by tharvik** [python/mypy#1428]
```python
from typing import Union

def a(w: List[Union[int, str]]): pass

b = [1]
a(b)
```
gives
```python
union.py:6: error: Argument 1 to "a" has incompatible type List[int]; expected List[Union[int, str]]
```
but it should type check

strangly, having
```python
from typing import Union

def a(w: List[Union[int, str]]): pass

b = 1
a([b])
```
does typecheck

**Comment by gvanrossum** [comment]
The first failure is because of variance. Suppose we have a base class B from which we derive a class C. Then even though C is a subtype of B, List[C] is not a subtype of List[B]. The same applies in your first example: even though int is a subtype of Union[int, str], List[int] is not a subtype of List[Union[int, str]].

The second example works because the type of a list literal (like [b]) is determined in part by its context, and in this case the context is the type of a's argument. It turns out that in that context, [1] can be coerced to List[Union[int, str]]. This effect only works within one expression or assignment, so it doesn't help in your first example.

IOW both examples work as expected.
