### ISSUE TITLE
Dict update error

### ISSUE THREAD

**Issue by ahaven** [python/mypy#1430]
In the following example:
```
d = {}  # type: Dict[str, Optional[int]]
d.update({str(i): None for i in range(4)})
```
The second line yields the following error: `Argument 1 to "update" of "dict" has incompatible type Dict[str, None]; expected union type (2 items)`

The function is stubbed as
```
def update(self, m: Union[Mapping[_KT, _VT], Iterable[Tuple[_KT, _VT]]]) -> None: ...
```
but the dict comprehension has inferred type `Dict[str, None]`.

**Comment by gvanrossum** [comment]
Hmm... This feels like one of the effects of `None` not being a real value in mypy. E.g. just this gives an error:
```
d = {'': None} # E: Need type annotation for variable
```

**Comment by ahaven** [comment]
it may also have to do with covariance because the following also errors:
```
e = {}  # type: Dict[str, Union[int, str]]
e.update({str(i): i for i in range(4)})  # error: Argument 1 to "update" of "dict" has incompatible type Dict[str, int]; expected "Union[Mapping[...], Iterable[...]]"
```

**Comment by JukkaL** [comment]
I suspect that this is related to type inference + union types. https://github.com/python/mypy/pull/1408 might fix this as well.

**Comment by rwbarton** [comment]
This is related to but distinct from #1408. Here we need to infer the key and value types of the dictionary comprehension `{str(i): None for i in range(4)}` that will make its type a subtype of the expected argument type `Union[Mapping[str, Optional[int]], Iterable[Tuple[str, Optional[int]]]]`. (This is `t <: Union[...]`, rather than `Union[...] :> t`; the organization of constraint generation is such that these are different problems, though I'm not sure that they need to be.)

This particular case is complicated by the fact that a `Dict[K, V]` is both a `Mapping[K, V]` and an `Iterable[K]`, which makes the declaration
```
def update(self, m: Union[Mapping[_KT, _VT], Iterable[Tuple[_KT, _VT]]]) -> None: ...
```
a bit of a lie. Suppose you have a `d: Dict[K, V]` and `m: Dict[Tuple[K, V], W]` and you call `d.update(m)`. Then mypy will allow the call, but python will really add the key-value pairs of `m` to those of `d`, creating a dictionary with some keys of type `K` and some keys of type `Tuple[K, V]`. I assume that `update` internally does something like an `isinstance(..., dict)` check, and if the argument is not a `dict`, falls back to the iterator protocol. And so in reality if you pass a `Dict[K, V]` to `update`, then `update` will always have the type corresponding to the `Mapping[_KT, _VT]` option, and never the `Iterable[Tuple[_KT, _VT]]]` option, even if `K` happens to be of the form `Tuple[_KT, _VT]`.

This also means that (even if mypy could infer constraints from `t <: Union[...]`) in the actual call
```
d.update({str(i): None for i in range(4)})
```
we can't infer the key type of the dictionary comprehension from the context alone; it could be either `str` or `Tuple[str, Optional[int]]`. In the latter case, the value type could be anything. So in order to handle this case, we'd have to first work out the key type from the body of the comprehension `str(i): None`, then eliminate the possibility of the comprehension having type `Iterable[Tuple[str, int]]`, then conclude it has type `Mapping[str, Optional[int]]` and use that to infer the value type `Optional[int]` and type check the body of the comprehension. This is probably workable, but unappealing since it's only needed because the stub type for `update` is not entirely accurate.

In practice I found it seems to work well to change the stub for `update` to an overloaded function, like
```
    @overload
    def update(self, m: Mapping[_KT, _VT]) -> None: ...
    @overload
    def update(self, m: Iterable[Tuple[_KT, _VT]]) -> None: ...
```
Now if the argument is a `Dict[K, V]` for yet-unknown types `K` and `V`, the first overload will be selected, even though both could match, simply because it is the first one. Then the rest of inference goes through successfully.

**Comment by gvanrossum** [comment]
Can you start with making update() an overloaded function? That seems a
no-brainer regardless of the rest of the issue. (I think it may have
started out as overloaded, and when we added Union support we may have been
a little too enthusiastic about replacing all overloads with unions.)

On Thu, Apr 28, 2016 at 11:52 AM, rwbarton <notifications@github.com> wrote:

> This is related to but distinct from #1408
> <https://github.com/python/mypy/pull/1408>. Here we need to infer the key
> and value types of the dictionary comprehension {str(i): None for i in
> range(4)} that will make its type a subtype of the expected argument type Union[Mapping[str,
> Optional[int]], Iterable[Tuple[str, Optional[int]]]]. (This is t <:
> Union[...], rather than Union[...] :> t; the organization of constraint
> generation is such that these are different problems, though I'm not sure
> that they need to be.)
>
> This particular case is complicated by the fact that a Dict[K, V] is both
> a Mapping[K, V] and an Iterable[K], which makes the declaration
>
> def update(self, m: Union[Mapping[_KT, _VT], Iterable[Tuple[_KT, _VT]]]) -> None: ...
>
> a bit of a lie. Suppose you have a d: Dict[K, V] and m: Dict[Tuple[K, V],
> W] and you call d.update(m). Then mypy will allow the call, but python
> will really add the key-value pairs of m to those of d, creating a
> dictionary with some keys of type K and some keys of type Tuple[K, V]. I
> assume that update internally does something like an isinstance(..., dict)
> check, and if the argument is not a dict, falls back to the iterator
> protocol. And so in reality if you pass a Dict[K, V] to update, then
> update will always have the type corresponding to the Mapping[_KT, _VT]
> option, and never the Iterable[Tuple[_KT, _VT]]] option, even if K
> happens to be of the form Tuple[_KT, _VT].
>
> This also means that (even if mypy could infer constraints from t <:
> Union[...]) in the actual call
>
> d.update({str(i): None for i in range(4)})
>
> we can't infer the key type of the dictionary comprehension from the
> context alone; it could be either str or Tuple[str, Optional[int]]. In
> the latter case, the value type could be anything. So in order to handle
> this case, we'd have to first work out the key type from the body of the
> comprehension str(i): None, then eliminate the possibility of the
> comprehension having type Iterable[Tuple[str, int]], then conclude it has
> type Mapping[str, Optional[int]] and use that to infer the value type
> Optional[int] and type check the body of the comprehension. This is
> probably workable, but unappealing since it's only needed because the stub
> type for update is not entirely accurate.
>
> In practice I found it seems to work well to change the stub for update
> to an overloaded function, like
>
>     @overload
>     def update(self, m: Mapping[_KT, _VT]) -> None: ...
>     @overload
>     def update(self, m: Iterable[Tuple[_KT, _VT]]) -> None: ...
>
> Now if the argument is a Dict[K, V] for yet-unknown types K and V, the
> first overload will be selected, even though both could match, simply
> because it is the first one. Then the rest of inference goes through
> successfully.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/python/mypy/issues/1430#issuecomment-215526825>
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by rwbarton** [comment]
Yes, making `update` an overloaded function will fix this case, and I don't propose to do anything further here at the moment.

**Comment by gvanrossum** [comment]
Thanks -- shall we close this issue? Or do we need to keep it open as a reminder of the remaining problem?

**Comment by rwbarton** [comment]
Yes, this can be closed now.
