### ISSUE TITLE
Base type Resource becomes 'Any' due to an unfollowed import

### ISSUE THREAD

**Issue by Luiz-Cruz** [python/mypy#14387]
Hello guys, how can i fix the error message: "Base type Resource becomes 'Any' due to an unfollowed import" by the following code?

```
from flask_restx import Resource
@router.route("/", endpoint="main")
class Seasonality(Resource):
        def post(self)-> str:
               return "Works"
```

According to the Mypy doc I would have to type the "Resource" but it is a class, and what I get in this class is an object of a class, I tried with Type[Resource] but when I did it this way I get the error invalid base class "Type" [misc]...

**Comment by hauntsaninja** [comment]
You'll have to ask https://github.com/python-restx/flask-restx to publish PEP 561 type hints. In the meantime, you can use `# type: ignore`, but note that mypy may miss errors down the line, e.g. if you do `seasonality.method_that_does_not_exist()` mypy will not complain because it doesn't have types for the base class.

**Comment by Luiz-Cruz** [comment]
hmmm okay i get it, thanks!! ill post a question in the link that u gave me!
