### ISSUE TITLE
Mypyc constructs generator in full

### ISSUE THREAD

**Issue by nickdrozd** [python/mypy#14418]
I think I've come across a Mypyc bug. Basically, a generator is getting constructed in full, when really it should never get that far.

Without any context, here is the problem function:

```python
def run_variations(
        prog: str,
        sim_lim: int,
        depth: int,
        max_block: int = 1,
        back_wrap: int = 0,
        lin_rec: int = 50,
) -> Iterator[bool]:
    yield LinRecMachine(prog).run(
        step_lim = lin_rec,
        check_rec = 0,
        skip = True,
    ).xlimit is None

    yield from (
        Machine(macro).run(
            sim_lim = sim_lim,
            prover = depth,
        ).xlimit is None
        for macro in macro_variations(
                prog, max_block, back_wrap)
    )
```

It yields a bool, then constructs a bool generator and yields from that. The consumer of this function is running it until it gets a `True` back.

When running this interpreted on a specific workload, that generator usuall doesn't get very far; `True` is normally found early on. This is the expected behavior.

But when I compile it with Mypyc, it seems to be running through the entire generator every time, regardless of what is found. This behavior is unexpected and undesirable.

I can recover the correct behavior by writing the loop in a slightly different way:

```python
def run_variations(
        prog: str,
        sim_lim: int,
        depth: int,
        max_block: int = 1,
        back_wrap: int = 0,
        lin_rec: int = 50,
) -> Iterator[bool]:
    yield LinRecMachine(prog).run(
        step_lim = lin_rec,
        check_rec = 0,
        skip = True,
    ).xlimit is None

    # manually yield from loop
    for macro in macro_variations(prog, max_block, back_wrap):
        yield Machine(macro).run(
            sim_lim = sim_lim,
            prover = depth,
        ).xlimit is None
```

That version works both interpreted and compiled. AFAIK the two versions should be equivalent, which would make this a Mypyc bug.

Let me know if any further information would be helpful (compiled code, link to repo, etc, etc). I couldn't come up with a minimal reproducing example.

```
mypy 0.991 (compiled: yes)
Python 3.11.0
```

**Comment by ichard26** [comment]
Mypyc does not properly support generator comprehensions yet. It compiles them into an "equivalent" list comprehension with the obvious problem that the list eagerly consumes the whole generator.

See also:
- https://github.com/mypyc/mypyc/issues/681
- https://github.com/mypyc/mypyc/issues/873

As noted in the closed issue above, mypyc should emiting a warning about this, but it does not right now due to a bug (where it only emits diagnostics if there's an error). I have an open PR for that (https://github.com/python/mypy/pull/10940) , but it's extremely stale and broken. I can look into getting it merged when I have more time.

**Comment by nickdrozd** [comment]
This is a well-known issue, so I'll close this.

To add my opinion, I would prefer for an error to be emitted indicating that generators simply aren't supported.
