### ISSUE TITLE
Better documentation for dir/ and --package command line arguments

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1449]
The `--help` text is confusing, and mypy docs probably don't explain these either.

**Comment by JukkaL** [comment]
Also, `mypy --silent-imports dir/` behavior is surprising, since only the top-level files will be processed unless the directory has an `__init__.py` file. Without `--silent-imports` mypy will follow imports and will likely process packages under the directory as well. 

@gvanrossum Would it make sense to have `dir/` always descend into subdirectories? The current behaviour could be had by using `mypy dir/*.{py,pyi}`.

**Comment by gvanrossum** [comment]
Maybe we should completely revamp the entire command line arguments processing.

The current -- very confusing -- situation is as follows (for simplicity I am writing `x.py` to mean either `x.py` or `x.pyi`).

- `mypy -c code` is the simplest; it checks code (like `python -c code`) except it incorrectly accept the option multiple times (and then only the last one is used)

- `mypy -m mod` is also pretty simple; it interprets mod as a module name (possibly with dots if it's a submodule of a package), looks that up in the default path (`MYPYPATH` + platform/installation-specific defaults). It can be repeated, e.g. `mypy -m mod1 -m mod2`. (The usage message isn't clear on that, it says `-m MODULES` which suggests `-m mod1 mod2` but that's wrong.) If `mod` is actually a package, it loads the `__init__.py` file.

- `mypy -p pkg` looks like it would be similar to `mypy -m pkg` (except it can't be repeated and has the same problem as `-c`) but actually it's subtly different: while `mypy -m pkg` only loads `pkg/__init__.py` and whatever it imports, `mypy -p pkg` recursively loads all submodules of `pkg`.

- `mypy pkg` treats `pkg` as a pathname pointing to a package. If there is no `pkg/__init__.py` this prints an error.

- `mypy pkg/` (trailing slash!) behaves like `mypy pkg` if `pkg/__init__.py` exists; but if it doesn't exist, it looks for `pkg/*.py` (but does not look for .py files in subdirectories).

- `mypy file.py` loads that file. The only special thing is that it's aware of the package containing `file.py`, and if you pass it e.g. `pkg/a.py`when `pkg/__init__.py` also exists, it will do the right thing for relative imports, essentially adding `pkg/..` to `MYPYPATH`. Also, if you ask for `mypy pkg/__init__.py` it will understand that the module name is `pkg`, not `pkg.__init__`.

In my next comment I'll try to propose how to change this.

**Comment by gvanrossum** [comment]
Here's a proposal for how to simplify the treatment of packages and directories.

- No changes for `mypy file.py`

- The only change for `mypy -c code` I propose would be to reject multiple `-c` flags.

- For `mypy -m mod` I propose that if `mod` is a package, we process *all* submodules and subpackages rather than just loading `mod/__init__.py`.

- For `mypy pkg` or `mypy pkg/` I propose to always recursively process all `.py` files in the directory, regardless of the presence of a trailing '/' or a `__init__.py` file.

- Kill the `-p` flag (use `-m` instead).

- If you really want to process just `mod/__init__.py` (plus whatever it imports) you have to figure out the exact pathname and pass that as a filename -- you can't use `-m`.

There are some related concerns:

- Python 3 has the concept of [implicit namespace packages](https://www.python.org/dev/peps/pep-0420/) -- this is a directory without a `__init__.py` file. (And there could be multiple such directories, which are merged at by the module search, unlike regular packages, where module search stops once it finds a directory containing `__init__.py`.)

- The command line arguments that take files/directories also implicitly add the directory where each source is found to MYPYPATH, after crawling up until no sibling `__init__.py` is found. We should keep this behavior but de-duple the resulting path (this is one source of redundant `os.stat()` calls).

- See also #1380 which is about scripts, i.e. files whose extension isn't `.py` or `.pyi`. There can currently be only one of these, since it is given the module name `__main__`. A proposed hack to avoid errors about duplicate modules here is to use `__main2__`, `__main3__` if there are multiple scripts.

**Comment by gnprice** [comment]
+1 to that proposal -- that sounds like very straightforwardly understandable and easy-to-use behavior.

I'm actually surprised that `mypy pkg/` doesn't already descend into subdirectories!

**Comment by gvanrossum** [comment]
> I'm actually surprised that `mypy pkg/` doesn't already descend into subdirectories!

Yeah, that surprised me too -- especially since `mypy pkg` does! Like several other aspects of the current situation it seems that the behavior is an accident of how various helper functions interacted rather than carefully planned.

Another set of concerns is that the unit tests probably depend on some of these command line behaviors; and so do the typeshed tests (https://github.com/python/typeshed/blob/master/runtests.py).

**Comment by JukkaL** [comment]
Another +1

Here's how I'd prioritized these for 0.4 if we don't have time to implement everything (roughly in order of preference):

1. New `mypy pkg` or `mypy pkg/` behavior (+ documentation)
2. New `-m` behavior (+ documentation)
3. Drop `-p`

**Comment by gvanrossum** [comment]
There's a wrinkle for `mypy pkg[/]`. Suppose pkg has no `__init__.py`. And suppose it has a subdir subpkg with .py files in it, but no `__init__.py` either. What should the module name for pkg/subpkg/a.py be? `pkg.subpkg.a`, `subpkg.a`, or plain `a`?

**Comment by gvanrossum** [comment]
I think for that edge case (`pkg` has no `__init__.py`) the path of the files relative to `pkg` should be used. Here's how I derive that. Suppose the entire contents of `pkg` is `pkg/a.py` and `pkg/b.py`. Then I would like `mypy pkg` to be equivalent to `mypy pkg/a.py pkg/b.py` and for the latter the module names will be `a` and `b`. For subpackages (e.g. `pkg/subpkg` if `pkg/subpkg/__init__.py` exists) this also gives the right answer. For subdirectories (e.g. `pkg/subdir` where `pkg/subdir/__init__.py` does not exist) it would be inconvenient to flatten the structure (even though explicitly listing those files would indeed flatten it) so there I propose to deviate from the equivalence.

**Comment by gvanrossum** [comment]
However there's another edge case to consider. Suppose (for historical reasons :-) your directory structure is as follows:
```
- toplevel  # not a package
  - package1  # a package
  - package2  # a package
  - subdir1  # not a package
    - package3  # a package
    - package4  # a package
```
and suppose at runtime we have `PYTHONPATH=subdir1:toplevel` so that in fact packages 1, 2, 3 and 4 are all sibling toplevel packages. How would we present this to mypy? We can't say `mypy toplevel` because it would infer `subdir1.package3` for the name of `package3`; we can't say `mypy subdir1 toplevel` either because that would find everything under `subdir1` twice. The best I can come up with is `mypy package1 package2 subdir`. Is that acceptable?

**Comment by gvanrossum** [comment]
And on the third hand maybe `mypy foo/bar` should consider `bar` the toplevel package even if it has no `__init__.py`.

**Comment by gvanrossum** [comment]
So now that I've implemented the plan a few comments above, I've found more edge cases. My current algorithm finds the same set of files regardless of whether the top directory contains `__init__.py` or not (it just assigns module names differently depending on the latter). However, now `mypy mypy` is broken (crashing with an internal error!) because it finds test fixtures and a few other things.

Some possible ways out:

- Fix the crash and live with it. If you want to check mypy, use `mypy -p mypy`.
- If the toplevel dir is a package, treat it roughly as `-p`.
- Same, and if the toplevel dir isn't a package, but some of its subdirs are, treat *those* as packages, but still recurse into non-package directories and assign fake package names.
- Similar, but flatten namespaces so that e.g. `dir/subdir/a.py` has module name `a` and too bad if there's another `a.py` in dir/subdir2/a.py`.

I probably need to track down @JukkaL and discuss this with him.

**Comment by gvanrossum** [comment]
We discussed this offline and decided on the following: ignore subdirectories that don't have a `__init__.py` file. The only exception is the presence or absence of `__init__.py` in the argument directory itself; this should affect only the module names assigned to files, not the selection of files.

**Comment by gvanrossum** [comment]
I've written some docs in 55e13ffbff2debe6e339c0a3f3d79f6aa0160520.

The code change is under review at #1473.

Should I also change the help text emitted by the program? (It never mentioned the difference between dir and dir/).

**Comment by gvanrossum** [comment]
Some parts of the original proposal aren't implemented, and in fact I've reversed my opinion on these.

- The difference between `-m` and `-p` is intentional and should remain.

- There's no support for namespace packages (for now, you can probably just add an empty `__init__.pyi`).

- Non-packages are not traversed when a directory is given on the command line.

Significant changes:

- The argument to `-p` cannot have a slash in it.

- `mypy dir` and `mypy dir/` are treated the same, regardless of whether `dir` is a package (has an `__init__.py`) or not.

- The only difference between `mypy pkg` and `mypy dir` is the module names assigned to the files found.
