### ISSUE TITLE
Recursive type aliases don't match compatible explicitly typed values

### ISSUE THREAD

**Issue by JordonPhillips** [python/mypy#14540]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=cb7d33a323807f054f95c4c4804ea697

```python
from typing import TypeAlias

JSON: TypeAlias = (
    dict[str, "JSON"] | list["JSON"] | str | int | float | bool | None
)

json_list: JSON = ["foo", "bar"]

string_list: list[str] = ["foo", "bar"]

json_list = string_list
```

**Expected Behavior**

mypy should recognize that `list[str]` is compatible with the `JSON` type alias.

**Actual Behavior**

`Incompatible types in assignment (expression has type "List[str]", variable has type "JSON")  [assignment]`

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags: n/a
- Mypy configuration options from `mypy.ini` (and other config files): n/a
- Python version used: 3.11

**Comment by erictraut** [comment]
Mypy's behavior is correct here. The type parameter for `list` is invariant, so you cannot assign a `list[str]` to a `list[JSON]`. 

You can fix the typing violation in your code a number of ways:
1. Annotate `string_list` as `JSON` so the assigned list "starts life as" a `JSON` type rather than a `list[str]`.
2. Define an ImmutableJSON recursive type that uses `Mapping` and `Sequence` rather than `dict` and `list`.
3. Write a function that converts a `list[str]` to to `JSON`. 

```python
def to_json(x: list[str]) -> JSON:
    return list(x)

json_list = to_json(string_list)
```

**Comment by AlexWaygood** [comment]
What @erictraut said. This is due to `list` invariance rather than a special property of recursive types.
