### ISSUE TITLE
(🐞) no error when type alias to type doesn't specify the type arg

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#14582]
```py
from typing import TypeAlias
t: TypeAlias = type

a: t[int]  # main.py:4: error: "type" expects no type arguments, but 1 given  [type-arg]

l: TypeAlias = list

b: l[int]  # no error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=strict&gist=9a7636d1484e8fb7a10cf57e6ca70af4)

**Comment by ilevkivskyi** [comment]
FWIW this is intentional behavior (there is actually a whole machinery to support this). Special forms (including `Type` and `Tuple`) eagerly substitute missing type parameters with `Any`, but plain classes behave essentially the same way they do at runtime.

You can check `reveal_type(b)` to see that it works correctly.

**Comment by KotlinIsland** [comment]
@ilevkivskyi Hmm, I think the title was a little confusing, I've added more detail, can you take another look at this please?
