### ISSUE TITLE
Cannot pass a dict[str, str] as dict[str| int, str]

### ISSUE THREAD

**Issue by philippgl** [python/mypy#14610]
I cannot add much to the title. A more restricted dict should be allowed to be passed in to a function, that takes a less restricted parameter.

There are similar bugs reported, but I could not find one, that matches well enough and also has a simple repro.

**To Reproduce**

```python
def print_foo(foo: dict[str | int, str]):
    print(foo)

def print_dict(foo: dict[str, str]):
    print_foo(foo)

print_dict({"foo": "bar"})
```

**Expected Behavior**

I think, passing a dict[str, str] as a dict[str|int, str] should be fine.

**Actual Behavior**
I get the following error:
```
minimal.py:6: error: Argument 1 to "print_foo" has incompatible type "Dict[str, str]"; expected "Dict[Union[str, int], str]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 0.991 (compiled: no)
- Mypy command-line flags: just the filename was used as argument
- Mypy configuration options from `mypy.ini` (and other config files): No config file was used 
- Python version used: Python 3.10.9

The file with the content above was copied to an empty directory and mypy and python from the arch repo was used, but I have also seen this in my venv, but that had way more variables.

**Comment by TeamSpen210** [comment]
This isn't actually typesafe. The key and value typevars are both "invariant", meaning that they must exactly match, neither a superclass or subclass relationship is acceptable. The reason `dict[str, str]` can't be passed to a function expecting `dict[int | str, str]` is that the function could then do something like `mydict[45] = "text"`. Then the original function would have a dict containing non-string keys, but believe it's a string-only dict, so the type is wrong. The solution is to annotate the function as taking a `Mapping` - since that doesn't allow modification, it can be "covariant" and allow expansion to broader keys like this.

**Comment by JelleZijlstra** [comment]
@TeamSpen210 is correct here, except that Mapping doesn't help in this particular case; it's still invariant in its key type. See https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance for more.

**Comment by samueljsb** [comment]
If `Mapping` does not help in this case, what is the appropriate solution?

If I want to say that my function accepts a mapping, which it will not mutate, where the keys can be either `str` or `int`, how do I express that?

(In my particular case, I want the key type to be a protocol. I care that all of the keys have a 'is_match' method, but nothing else about them.)
