### ISSUE TITLE
have some special function that makes mypy statically print the type of its argument

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1466]
It would be very useful when debugging (and potentially when writing code) to have some cast-like function that tells mypy to print out the type of its argument (but is otherwise the identity function).  This could also make a lot of the unit tests look slightly nicer going forward (because they won't have to artificially induce a type error to get the type of something, as is the current practice).  This should be pretty straightforward to implement.

I'm not entirely sure what the function should be called.  I believe @rwbarton suggested `reveal_type`, which seems reasonable.  Thoughts?

**Comment by ddfisher** [comment]
Along similar lines, it could be nice to support ["typed holes", like GHC](https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/typed-holes.html).  What that boils down to for mypy is just some function that makes mypy error out with the type needed by the surrounding context.  This is probably less useful than in Haskell, because our types are a bit less complex, but e.g. could be a very convenient way to figure out an argument type to a function without having to grep through the code.  I think this should also be pretty straightforward to implement.

**Comment by gvanrossum** [comment]
I am very much in favor of the first idea. To be concrete, it would look like this:
```python
from ??? import reveal_type
x = 1  # type: float
print(reveal_type(x+1))
```
When executed this would print `1`; when checked with mypy it would issue a note like this:
```
main.py:3: note: type of "x+1" is 'float'
```
Can you present me with an example for the hole syntax? I don't read Haskell error messages.

**Comment by gvanrossum** [comment]
There's a question in my example about where `reveal_type()` should be imported from. Adding it to `typing.py` would require a PEP 484 change. Maybe we could abuse some special form of `cast()`, perhaps `cast("reveal", x+1)`? Or we could make it a built-in function only known to mypy, and just let it error out at runtime. (Most use cases I can think of never make it to being executed using CPython.)

**Comment by ddfisher** [comment]
Sure!  Haskell error messages are a huge pain to read when unfamiliar.

Concretely, the usage would look like this:
```python
from ??? import typed_hole()

# this function would likely be in some far away file
def foo(x: List[Dict[str, int]]) -> None: ...

# let's say you're trying to call foo(), and you remember foo() is a list of dicts 
# from strings to something, but you're not sure what
foo([{"bar": typed_hole()}])
```

Mypy would print:
```
main.py:8: error: found typed hole with type `int`
```

**Comment by ddfisher** [comment]
Of those options, my inclination would be to make it a built-in function known only to mypy.  The one downside there is that we'd probably need to make them errors instead of warnings, because they would in fact be runtime errors.

**Comment by gvanrossum** [comment]
Then again, the typed hole can be approximated by guessing -- you put in 0 and if you don't get an error you know the expected type is an integer, otherwise the error message will tell you what was expected.

I note that `reveal_type()` supports use cases that have actually been requested (on our internal Slack channel, by people either trying to repro some issue or trying to figure out how to spell something, by experimenting with a small test program).

I haven't seen a request for `typed_hole()` yet. (I often want to know what the argument of some function defined elsewhere is, but invariably the function hasn't been annotated, so the `typed_hole()` would just tell me that it expects `Any`.)

> Of those options, my inclination would be to make it a built-in function known only to mypy. The one downside there is that we'd probably need to make them errors instead of warnings, because they would in fact be runtime errors.

That sounds good to me.

**Comment by ddfisher** [comment]
Yeah, let's hold off on `typed_hole()` until there's a more compelling case for it.  I think `reveal_type()` should be pretty fast, so let me see if I can just bang it out.

**Comment by JukkaL** [comment]
Sounds good! `reveal_type` would be nice. A current workaround is to do `x()` instead of `reveal_type(x)`, resulting in an error like `"int" is not callable`. This is hacky and unintuitive, and it doesn't work for callables. 

Perhaps we should have an underscore (or even double underscore) prefix to mark that this is a special function. Also, this would make it a little less likely to conflict with a user-defined function with name `reveal_type`.

A related thing is displaying all of the internal structure of callable types, such as argument names. The `Callable[...]` syntax doesn't support them. Would `reveal_type` always display valid PEP 484 types, or could it include extra information as well? Or perhaps there would be a verbose option for displaying all the internal mypy type attributes as well. For example, `_reveal_type(x, verbose=True)`.

**Comment by gvanrossum** [comment]
I say _reveal_type() should show as much info as possible, without options.

On Tue, May 3, 2016 at 4:05 AM, Jukka Lehtosalo <notifications@github.com>
wrote:

> Sounds good! reveal_type would be nice. A current workaround is to do x()
> instead of reveal_type(x), resulting in an error like "int" is not
> callable. This is hacky and unintuitive, and it doesn't work for
> callables.
>
> Perhaps we should have an underscore (or even double underscore) prefix to
> mark that this is a special function. Also, this would make it a little
> less likely to conflict with a user-defined function with name reveal_type
> .
>
> A related thing is displaying all of the internal structure of callable
> types, such as argument names. The Callable[...] syntax doesn't support
> them. Would reveal_type always display valid PEP 484 types, or could it
> include extra information as well? Or perhaps there would be a verbose
> option for displaying all the internal mypy type attributes as well. For
> example, _reveal_type(x, verbose=True).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/python/mypy/issues/1466#issuecomment-216496667>
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by rwbarton** [comment]
It's a little unfortunate that the syntax we have for types that includes all the internal information is also sometimes completely different from the corresponding PEP 484 syntax (e.g., ``def [T] (x: T`-1) -> builtins.list[T`-1]`` vs. `Callable[[T], List[T]]`), so the user of `_reveal_type` will need to learn both syntaxes. In the long term we should probably do something about this, but for now always displaying the internal syntax makes the most sense to me.

**Comment by ddfisher** [comment]
I think we should consider leaving the name as `reveal_type`, because it looks much nicer IMO, and I don't think it's a particularly common name for a function (and in the case that a user defined function is in scope, that function wins).  If we do think that `reveal_type` is common enough to worry about, I think we should use the double underscore'd `__reveal_type`, because the single underscore prefix is commonly used for private methods (so only double underscores really look special).

**Comment by gvanrossum** [comment]
+1

**Comment by gvanrossum** [comment]
If you still want the hole, open a new issue please.

**Comment by gvanrossum** [comment]
Can we please document this?

**Comment by JukkaL** [comment]
Added some documentation: https://github.com/python/mypy/commit/12dd05632e7fdefa218f8ce90f84ceb87818c42b
