### ISSUE TITLE
stubtest: enum completeness check

### ISSUE THREAD

**Issue by srittau** [python/mypy#14692]
**Feature**

stubtest could do a completeness check for enums. 

**Pitch**

This would be quite useful for cases like python/typeshed#9727, i.e. if enum values are added in later versions of a library.

**Comment by JelleZijlstra** [comment]
Note that in the case you linked, the class is not an enum (at least not in the stub). But it would be useful for stubtest to flag missing class attributes whether or not the class is an enum.

**Comment by hauntsaninja** [comment]
stubtest does already do this. The issue is just that the typeshed third party stub tests default to passing `--ignore-missing-stub`
https://github.com/python/typeshed/blob/70f0f5488aed9952a5bea1d76eef9f97ce60dc40/tests/parse_metadata.py#L70

I've advocated against typeshed doing this in the past, current issue for this is https://github.com/python/typeshed/issues/9538
