### ISSUE TITLE
Allow union-attr for None within try-except blocks that catch AttributeError

### ISSUE THREAD

**Issue by berzi** [python/mypy#14743]
**Feature**

Attempting access to an attribute that doesn't exist understandably causes a `union-attr` error like:
>  error: Item "None" of "Optional[MyClass]" has no attribute "bogus"  [union-attr]

I propose to avoid raising this error if the attribute access occurs within a `try`/`except` block which catches `AttributeError`, which would always catch such errors and access to a possibly nonexistent attribute is thus likely intended. Besides, if the error will always be caught, what advantage does Mypy offer by reporting it? I argue: none at all, it's just noise.

**Pitch**

In general, asking for forgiveness rather than permission is often considered pythonic. In this instance, Mypy only gives the option of asking for permission (unless you silence it, making something routine look like a special case).

**Comment by lmazuel** [comment]
Found this issue while I was having the same problem, did a mypy playground link to showcase the problem:
https://mypy-play.net/?mypy=latest&python=3.11&gist=4770881b31fe65ce75dc10c1ed1831d3

```python
from typing import Optional

class Foo:
    
    def __init__(self, something: Optional[str] = None):
        self.something = something

    def __str__(self) -> str:
        try:
            return self.something.lower()
        except AttributeError:
            return "There was nothing"

```

**Comment by JelleZijlstra** [comment]
I think there have been a few previous feature requests like this, but I am going to reject it. Suppressing some checks within a try-except block would be very unusual behavior for a type checker, and it is generally more robust anyway to do a check like `if self.something is not None:` (what if `.lower()` itself raises an AttributeError? what if `self.something` doesn't exist?).

**Comment by ambarjobs** [comment]
In practice this means that it is useless to use exception handling as [EAFP](https://docs.python.org/3/glossary.html#term-EAFP) with mypy.

It's really a pity, it makes mypy much less useful.

**Comment by SwampFalc** [comment]
I would like to add my vote in asking for some solution.

I have code that loads data from a database. The database has clearly typed columns, some nullable, some not, so I went and created a TypedDict that corresponds to that:

```python
from typing_extensions import TypedDict

Datum = TypedDict(
    "Datum",
    {
        "PERS_INFO.VAR1": str | None,  # max. 250 characters, nationality
        "PERS_INFO.VAR2": str | None,  # max. 250 characters, OV/SP number
        "PERS_INFO.VAR3": str | None,  # max. 250 characters, room
    },
)
```

And so my database queries return TypedDicts.

In order to work with this information, though, I want to transform it into another class. A crucial element of this step is that data that is incomplete gets noticed, logged as an error and is NOT transformed into this other class. The other class is a Pydantic model, where you will note the corresponding fields are typed as str only, not allowing None:

```python
from pydantic import BaseModel

class Resident(BaseModel):
    resident_nationality: str
    pubsec_number: str
    center_room: str
```

And thus, when I transform from Datum to Resident, I can just do it and catch the Pydantic ValidationErrors. As a bonus, it means that multiple Nones just creates one single ValidationError:

```python
from pydantic import ValidationError

def make_resident(resident_dict: Datum) -> Resident | ResidentError:
    try:
        return Resident(
            resident_nationality=resident_dict["PERS_INFO.VAR1"],
            pubsec_number=resident_dict["PERS_INFO.VAR2"],
            center_room=resident_dict["PERS_INFO.VAR3"],
        )
    except ValidationError as ve:
        return ResidentError(error=ve, source=resident_dict)
```

(The ResidentError class is just to wrap the ValidationError with some extra data, and it gets returned instead of raised because I need to go over all the data in the database and not halt at the first error.)

But of course, mypy does not like this:

```
src/fedpass/libraries/uni_database.py:212: error: Argument "resident_nationality" to "Resident" has incompatible type "str | None"; expected "str"  [arg-type]
src/fedpass/libraries/uni_database.py:213: error: Argument "pubsec_number" to "Resident" has incompatible type "str | None"; expected "str"  [arg-type]
src/fedpass/libraries/uni_database.py:214: error: Argument "center_room" to "Resident" has incompatible type "str | None"; expected "str"  [arg-type]
```

Even though the type error is expected, even desired.

The solutions I can see are all... far from ideal.

Suppressing the arg-type error for these lines does not feel like a clean approach. It will also suppress possible errors in the future, in case a field were to ever change type.

Writing code to handle the case where values are None, feels like reinventing the wheel from Pydantic.

So yeah, if anyone has a good idea on how to handle this, I'm all ears.

**Comment by berzi** [comment]
@SwampFalc You should be using Pydantic's `model_validate()` method to parse unvalidated data (which it is, if it can be None where it's not allowed to be), or better yet not assert what kind of `dict` your `dict` is. Otherwise you would have to validate in your own code that something is not None to restrict its type, but that doesn't make sense in a scenario where you use Pydantic.

As far as the code you've shown is concerned, the typed dict layer is superfluous if not to make sure that you're not passing `make_resident()` a parameter that has to do with something else; but in that case you could just use a NewType to make sure that what goes into `make_resident()` is what comes out of the one specific database query.

`Any` is not evil: it means you can't state with certainty which type the data has; in your case, that's Pydantic's job, so it's fine if what goes into the model is a `dict[str, Any]` because Pydantic will make sure that what comes out is a very specific type you can trust.
