### ISSUE TITLE
typing.Self return type doesn't recognize explicit return is same thing

### ISSUE THREAD

**Issue by Garrett-R** [python/mypy#14794]
**Bug Report**

When a function returns a type explicitly, the result can't be used as a return with type `Self`

**To Reproduce**

Observe [this Mypy Playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=b348225859b20cb54bdce66da584053c), repeated here for convenience:

```python
import random
from typing import Self

class Dog:
    def make_dog(self) -> Self:
        return _make_a_dog()
        

def _make_a_dog() -> Dog:
    return Dog()
```

**Expected Behavior**

No errors.

**Actual Behavior**

I get this error:
```
main.py:6: error: Incompatible return value type (got "Dog", expected "Self")  [return-value]
```

**Your Environment**

- Mypy version used: 1.0.0
- Python version used: 3.11

**Comment by TeamSpen210** [comment]
Mypy is correct here. The issue occurs if you subclass `Dog`. If you did the following:
```py
class ShortDog(Dog):
    pass
short = ShortDog().make_dog()
```
`short` here should be a `ShortDog` because of the `Self` annotation, but at runtime this code produces a plain `Dog` still. If you decorate `Dog` with `@typing.final` to indicate that it cannot be subclassed further, Mypy will then accept your original code.

**Comment by Garrett-R** [comment]
Ah right, very cool, thanks!  

Closing.
