### ISSUE TITLE
Introduce `assert_transformer` to annotate functions with assertion behaviour

### ISSUE THREAD

**Issue by mahmoudajawad** [python/mypy#14846]
**Feature**

Using `assert` allows `mypy` to understand subsequent lines confirms value of `Optional` variable is non-`None`. This is great behaviour:

```python
def foo(bar: Optional[str]) -> None:
  # to mypy bar is Optional[str] here
  assert bar
  # bar is now assumed to be str
```

However in daily coding further checks are required in some functions, such as combination of two variables checks and so on. Offloading such checks to other functions mean `mypy` will become ignorant of assertion happening in other function and making it complain about possible `None` values of variables that can be silenced using `cast`, but the the code become a pile of checking function call followed by a `cast`, or alternatively the assertion function has to return the same value if assertion successful, and the assertion function can no longer be used such as  explained and only as:

```python
def check_bar(bar: Optional[str]) -> str:
  assert bar
  # Some more checks...
  return bar

def foo(bar: Optional[str]) -> None:
  check_bar(bar)
  # bar is still Optional[str]
  bar = check_bar(bar)
  # Now it is str
```

**Pitch**

Typing decorator `dataclass_transformer` is a great approach to extend mypy functionalities with meta aspects. If similar is taken into consideration for `assert_transformer` such as:

```python
@assert_transformer
def check_bar(bar: Optional[str]) -> None:
  # check 1
  # check 2
  # check 3
  pass

def foo(bar: Optional[str]) -> None:
  check_bar(bar)
  # Here mypy will understand that check_bar acts similar to assert resulting in any variables passed as arguments to it must be cast the non-`None`.
```

**Comment by erictraut** [comment]
This would require an extension to the type system, so it would be better to discuss this in the [python/typing discussion forum](https://github.com/python/typing/discussions) rather than a mypy issue. 

There is precedent in other languages for what you're describing here. For example, TypeScript offers [this capability](https://learntypescript.dev/07/l7-assertion-signature).

I don't think that a "transform" is the right way to model this, however. Nothing is being "transformed", after all. Instead, it's more like a user-defined type guard (the `TypeGuard` special form) described in PEP 647.

I proposed adding a `TypeAssert` equivalent to `TypeGuard` in [this typing-sig discussion](https://mail.python.org/archives/list/typing-sig@python.org/thread/JTO3WKRKQFW5YFP3ZSMNTRIEA5NPJEM6/). So far, there hasn't been sufficient interest to justify pursuing a PEP.

**Comment by mahmoudajawad** [comment]
@erictraut, couldn't agree anymore! I see why use of `transform` is wrong now after your comment. I shall post the same to the forum as you suggested and then close this here.

**Comment by AlexWaygood** [comment]
> This would require an extension to the type system, so it would be better to discuss this in the [python/typing discussion forum](https://github.com/python/typing/discussions) rather than a mypy issue.

As per Eric's comments above, I'm closing this until it's been discussed in a wider forum
