### ISSUE TITLE
"No overload variant of sub" Issue with re.compile after upgrading to mypy 0.4

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1492]
On upgrading to mypy 0.4 I get this new error:
```
/home/tabbott/foo.py:4: error: No overload variant of "sub" matches argument types [typing.Pattern[builtins.str*], builtins.str, builtins.str]
```
when using a compiled regular expression:
```
content = "test"
import re
quote_re = re.compile(r'{quote}(.*?){quote}', re.DOTALL)
content = re.sub(quote_re, r'~~~ quote\n\1\n~~~', content)
```
Haven't had a chance to investigate whether this is caused be a change in typeshed or mypy itself.

**Comment by gvanrossum** [comment]
That's strange. Assuming you're using `--py2` mode (there's no overload in the Python 3 stub for `re.pyi`). The `stdlib/2.7/re.pyi` hasn't changed since your change 21c90d52b919f60c69a39784b019ab70e931ea79 in January. It looks like the spec for `sub()` is wrong, it doesn't allow `Pattern[AnyStr]` for the pattern arg. I'm guessing that some bug in overload checking was fixed that surfaced this. The stub needs to be fixed.

**Comment by rwbarton** [comment]
Oh, I think one of my changes made it so that type variables with value restriction in overloads would only match types that are a subtype of the union of the possible values of the type variable. So `Pattern[str]` no longer matches `Union[str, unicode]`. Not sure why the statement type checked in the first place, maybe #1322?

**Comment by timabbott** [comment]
OK, I think this turned out to be just a stub issue, so we can close it, right?

**Comment by gvanrossum** [comment]
Yup.
