### ISSUE TITLE
Spurious "Cannot inherit non-frozen dataclass from a frozen one"

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#14952]
I'll produce a MWE when I have more time, but this is error is happening on all my projects that use `dataclass_transform` with `frozen=True`.  For example,  https://github.com/NeilGirdhar/tjax/

Simply clone, and run MyPy _twice_.  Thus, it appears there's something missing from or wrongly added to the MyPy cache.

```
tjax/_src/fixed_point/simple_scan.py: note: In class "SimpleScan":
tjax/_src/fixed_point/simple_scan.py:15: error: Cannot inherit non-frozen dataclass from a frozen one  [misc]
    class SimpleScan(IteratedFunctionBase[Parameters, State, Trajectory, State],
...
```
CC @wesleywright

**Comment by wesleywright** [comment]
It looks like this is specific to decorator-based usage, and seems to be because `FuncItem` does not deserialize the `arguments` field: https://github.com/python/mypy/blob/01a088b954ec9a0f351f4e9e9749896df8193830/mypy/nodes.py#L657 The code currently inspects this field to read the dataclass_transform parameters out of the applied decorator. I'll probably have to save the fields somewhere in the AST during semanal rather than re-reading them each time.
