### ISSUE TITLE
A tool for generating stubs from test runs

### ISSUE THREAD

**Issue by lopuhin** [python/mypy#1508]
It should be possible to generate stubs for libraries with good test coverage by running their tests and observing types at least on the function/method call level. There is a problem that in some cases the types could be too granular (if the type is `Any` but it is tested with some concrete type), and perhaps some other problems. But there are a lot of pretty big libraries with decent test coverage, so perhaps it can get the correct results in most cases.
Do you think such tool could be useful? Do you see any other obvious problems?

**Comment by JukkaL** [comment]
We already have something like this (see the `pinfer` subdirectory of the repo). What you are suggesting is possible, but it's less obvious how useful this is in practice. The main issue is that the inferred types are concrete. For example, we can infer a type `List[int]` but inferring type `Iterable[int]` is harder.  Also, if a function is generic, the inferred type would likely have large unions. However, the inferred types could still be a reasonable starting point, and they could useful together with manual cleanup.

I have ideas for inferring abstract types, but we haven't implemented any yet. For example, we could wrap an argument and record all operations that are used on it. If a function only calls `__iter__` on a list argument, we could infer an `Iterable` type instead of `List[...]`.

If you are interested in this, go ahead and play around with the `pinfer` tool. I'd like to warn that the code likely isn't close to production quality yet, and you may first have to fix a bunch of issues :-)

**Comment by lopuhin** [comment]
@JukkaL thanks, ``pinfer`` is indeed what I was thinking about (although I have a slightly different implementation in mind, using a trace function), and it manages to produce interesting results! I'll try to tweak it to get full stubs for some third-party modules.

**Comment by ethanhs** [comment]
Dropbox released [pyannotate](https://github.com/dropbox/pyannotate) and Instagram released [MonkeyType](https://github.com/Instagram/MonkeyType), which both use tracing.
