### ISSUE TITLE
“Duplicate base class” blocks checking

### ISSUE THREAD

**Issue by xiaxinmeng** [python/mypy#15349]
The duplicate base class causes the checking blocked. 

example.py
```
class N(type):
    pass

class B(N, metaclass=N):
    pass

class D(B, B):
    pass
```

### The expected behavior：
The error can be ignored and the checking will not be blocked.

### The actual behavior：
```
>> mypy example.py
Desktop/example.py:7: error: Duplicate base class "B"
Found 1 error in 1 file (errors prevented further checking)
```

### Environment
Mypy version: 1.3.0
Python version: 3.11.3
Operating System: Ubuntu 18.04
How to install MyPy: "python3.11 -m pip install mypy"

**Comment by gregorysantosa** [comment]
@xiaxinmeng I believe mypy is correct in this case because when class D is constructed, since it inherits two instances of class B, when an attribute or method of class N is invoked from an instance of class D, Python does not know which instance of class N should be called. I believe this issue can be worked around by removing the "metaclass=N" argument from class B

**Comment by sobolevn** [comment]
I think that this is a correct thing to do:
1. It is a `TypeError` in runtime:

```python
>>> class A: ...
... 
>>> class B(A, A): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: duplicate base class A
```

So, you app won't work and mypy catches that.

2. It is not clear how to construct `D` type info for us, so we can continue type checking

**Comment by JelleZijlstra** [comment]
Can't we make it inherit from Any or ignore the second base? I feel we should strongly avoid blocking errors if possible.

**Comment by sobolevn** [comment]
We can still inherit from one of them, I guess. I will take a look and send a PR.
