### ISSUE TITLE
Document how (not) to use basestring

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1537]
Users have started using `basestring` in stubs and elsewhere. Using `basestring` as a function argument type in a stub seems relatively benign (though inconsistent), but using as a return type is problematic for a few reasons:
- `basestring` currently has no operations and can't be passed to functions expecting `unicode` or even `Union[bytes, unicode]`.
- Using `isinstance()` doesn't work well, since it's not a union. It's often necessary to use something like `if isinstance(x, bytes): ... elif isinstance(x, unicode)` instead of `if isinstance(x, bytes): ... else: ...`.

Not sure what we should tell users. Perhaps say that using `basestring` as an argument type is not recommended (at least for now), and `Union[bytes, unicode]` is the recommended, hopefully future-proof alternative in Python 2 -- even though it's currently equivalent to just `unicode`. 

Also say the `basestring` should not be used as a return value or attribute type, but `Union[bytes, unicode]` should also be avoided there. In these contexts `str`, `bytes`, `unicode` and `AnyStr` are better, whenever possible.

See also https://github.com/python/typeshed/issues/202.

**Comment by gvanrossum** [comment]
See also https://github.com/python/typeshed/pull/138

**Comment by lucaswiman** [comment]
This comes up in attempting to make python-3 compatible code with `six`, since `six.string_types` is aliased to `basestring` (both in `six` and in the stub). Here's a simplified example from a codebase I'm attempting use mypy on:
```python
import six
from typing import Any

def c(a, b):  # type: (Any, Any) -> int
    if isinstance(a, six.string_types):
        return getattr(b, a)
    else:
        return b[a]
```

@JukkaL [commented](https://github.com/python/typeshed/pull/138#issuecomment-219526689):
> Having basestring aliased to Union[bytes, unicode] might work better (I think somebody suggested it), though the resulting error messages could be confusing, as they wouldn't refer to basestring.

I think updating the type signature in the stub type of `six.text_type` to `(Union[bytes, unicode], )` wouldn't be more confusing, since `six.text_type` already doesn't mention `basestring`.

**Comment by hauntsaninja** [comment]
What is Python 2?
