### ISSUE TITLE
Mypy v.990 crash checking function redefinition FuncDef

### ISSUE THREAD

**Issue by paula75** [python/mypy#15436]
**Crash Report**

Today, when i installed mypy v0.990 on an already working repository i get a crash: Internal Error

**Traceback**

```
{project_directory}/venv/lib/python3.8/site-packages/cattrs/gen/_shared.py:43: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.990
Traceback (most recent call last):
  File "mypy/checker.py", line 573, in accept
  File "mypy/nodes.py", line 822, in accept
  File "mypy/checker.py", line 938, in visit_func_def
  File "mypy/checker.py", line 963, in _visit_func_def
AssertionError: Error checking function redefinition FuncDef:43(
  handler
  Args(
    Var(v)
    Var(_)
    default(
      Var(_h)
      NameExpr(handler [l])))
  Block:43(
    ReturnStmt:44(
      CallExpr:44(
        NameExpr(_h [l])
        Args(
          NameExpr(v [l])
          NameExpr(type [l]))))))
{project_directory}/venv/lib/python3.8/site-packages/cattrs/gen/_shared.py:43: : note: use --pdb to drop into pdb

```

**To Reproduce**

Working fine in an environment that i had installed since 2 months, but when i clone again the project and set up the working environment, with mypy==0.990 i get and error making mypy . in my project

**Your Environment**

- Mypy version used: 0.990
- Mypy command-line flags: mypy . --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files): 
check_untyped_defs = true
disallow_any_unimported = true
disallow_untyped_defs = true
explicit_package_bases = true

- Python version used: 3.8.10
- Operating system and version: ubuntu 20.04.6 LTS

**Comment by AlexWaygood** [comment]
Thanks for the report, but I'm afraid it's impossible for us to help you unless you give us a way to reproduce the problem. You haven't showed us any of your code, so there's no way for us to investigate what's going wrong here.

Additionally, mypy v0.990 is quite an old version of mypy. We fix bugs in every release of mypy, so it's very possible that this has already been fixed in the latest version (mypy 1.3).

If you find that mypy still crashes on your code with the latest version of mypy, _and_ you're able to give us a way to reproduce the problem, I'll reopen the issue, but for now I'm going to close it.
