### ISSUE TITLE
Transliterate mypy into rust? Using ChatGPT??

### ISSUE THREAD

**Issue by edreamleo** [python/mypy#15560]
**Pitch**

[ruff](https://github.com/astral-sh/ruff) is (mostly) pylint written in rust. ruff is 100x faster than pylint! I now mostly use ruff and only occasionally use pylint.

Inspired by ruff, I thought I would ask if there were any plans to transliterate mypy to rust.

Googling "mypy in rust" yields only [this page](https://news.ycombinator.com/item?id=35621032). I have not found any more evidence of this project.

Transliterating mypy into rust might be a good way for me to learn rust :-)

But I wonder, could ChatGPT do the job? Probably not yet, but I can't be the first to ask such a question.

Any thoughts?

**Comment by AlexWaygood** [comment]
Thanks for the suggestion, but I think it's safe to say that we won't be doing this any time soon :)

It's certainly possible that we could speedup mypy by using Rust rather than Python, but you're essentially talking about a complete rewrite of the codebase rather than something that could be easily done. Ensuring that all edge cases of behaviour are handled correctly would be a monumental undertaking. Unfortunately, I don't think tools such as ChatGPT are sophisticated enough to make this significantly less arduous right now.

Note that mypy is also already quite a bit faster than garden-variety Python, due to its use of [mypyc](https://github.com/mypyc/mypyc).

**Comment by edreamleo** [comment]
@AlexWaygood Thanks for your comments. They seem perfectly reasonable :-)
