### ISSUE TITLE
mypy confused about `Self`

### ISSUE THREAD

**Issue by alexei** [python/mypy#15609]
**Bug Report**

The docs at https://docs.python.org/3/library/typing.html#typing.Self say that:

> In general if something currently follows the pattern of:
> 
> ```python
> class Foo:
>     def return_self(self) -> "Foo":
>         ...
>         return self
> ```
> You should use Self etc.

My understanding of it is I'd be able to use `Self` whenever a function is receiving or returning an instance of the class they belong to. Yet that doesn't seem to be the case, or maybe there's some subtlety I'm missing?

**To Reproduce**

Example 1 with enum:

Gist URL: https://gist.github.com/mypy-play/c4154f1c7d6f066601f4c9012e26e06f
Playground URL: https://mypy-play.net/?mypy=latest&python=3.11&gist=c4154f1c7d6f066601f4c9012e26e06f

Example 2 with class:

Gist URL: https://gist.github.com/mypy-play/84f545a05b09852df62368de7cb5bc36
Playground URL: https://mypy-play.net/?mypy=latest&python=3.11&gist=84f545a05b09852df62368de7cb5bc36

Briefly, the following lines fail:

```python
class Color(Enum):
    ...

    @classmethod
    def gimme_green(cls) -> Self:
        return cls.GREEN
```
and:
```python
@dataclass
class Everyman:
    ...

    @classmethod
    def create_d(cls) -> Self:
        return Everyman(name="Emmanuel")
```

**Expected Behavior**

I'd expect both examples to pass mypy checking.

**Actual Behavior**

They don't.

**Your Environment**

```shell
$ python --version
Python 3.11.3
$ mypy --version
mypy 1.4.1 (compiled: yes)
```

**Comment by AlexWaygood** [comment]
> ```python
> @dataclass
> class Everyman:
>     ...
> 
>     @classmethod
>     def create_d(cls) -> Self:
>         return Everyman(name="Emmanuel")
> ```

Mypy's behaviour is correct here. For the `Everyman` class specifically, `create_d` returns the type of `self`, but if you have a subclass of `Everyman`, it will not return the type of `self`, as it is hardcoded to return `Everyman`. If you annotate a method as returning `Self`, it means that it always returns whatever the type of `self` is, _even in subclasses_. It's possible that this could be documented better over at CPython; I'd happily merge a CPython PR improving the docs to that end.

> ```python
> class Color(Enum):
>     ...
> 
>     @classmethod
>     def gimme_green(cls) -> Self:
>         return cls.GREEN
> ```

This is strictly-speaking a false positive, as `Color` cannot be subclassed (enums with members are implicitly `@final`). As such, it can be guaranteed that `gimme_green` will always return the type of `self`. However, adding special handling for `enum` classes would arguably be a feature request rather than a bug report.

**Comment by alexei** [comment]
@AlexWaygood thanks for the explanation, it makes more sense now. I followed your suggestion at improving the docs and gave it a try at https://github.com/python/cpython/pull/107511 though I admit it didn't feel that necessary after reading your comment.
