### ISSUE TITLE
Function parameter annotated as List of A does not accept List of subclass of A

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#1566]
```py
from typing import List, MutableSequence, Sequence

class A: pass
class B(A): pass

def func1(mmaps: Sequence[B]) -> None: pass
def func2(mmaps: Sequence[A]) -> None: pass
def func3(mmaps: MutableSequence[B]) -> None: pass
def func4(mmaps: MutableSequence[A]) -> None: pass
def func5(mmaps: List[B]) -> None: pass
def func6(mmaps: List[A]) -> None: pass

li = [B(), B()]
func1(li)
func2(li)
func3(li)
func4(li)
func5(li)
func6(li)
```

gives the output

```
myfile.py:17: error: Argument 1 to "func4" has incompatible type List[B]; expected MutableSequence[A]
myfile.py:19: error: Argument 1 to "func6" has incompatible type List[B]; expected List[A]
```

In this example, I think `List[B]` is a subtype of `List[A]` and `MutableSequence[A]`, but mypy doesn't think so. Is this a bug?

**Comment by rwbarton** [comment]
Nope! `List[B]` isn't a subtype of `List[A]` because you can append an `A` to a `List[A]` but you can't append an `A` to a `List[B]` (it would no longer be a `List[B]`). This doesn't come up for `Sequence` because it is immutable, so `Sequence[B]` can be a subtype of `Sequence[A]`. In type theory terminology, we say that `Sequence` is covariant but `List` is invariant. Unfortunately this is not really documented in the mypy documentation yet.

If your function accepts a list of `A`s but doesn't modify it, then it's usually better to declare it as taking a `Sequence[A]`, for this reason.

**Comment by sharmaeklavya2** [comment]
Thanks for explaining!
