### ISSUE TITLE
Inconsistent Type Narrowing Depending on Variable Name

### ISSUE THREAD

**Issue by randolf-scholz** [python/mypy#15694]
**Bug Report**

Type narrowing produces inconsistent results in dict-comprehension if the same variable name is reused.

**To Reproduce**

```python
def foo(**id_subsets: int | list[int]):
    id_subsets = {  # reusing same name
        key: [value] if isinstance(value, int) else value
        for key, value in id_subsets.items()
    }
    reveal_type(id_subsets)  # ✘  dict[str, int | list[int]]

    
def bar(**id_subsets: int | list[int]):
    ids = {  # using different name
        key: [value] if isinstance(value, int) else value
        for key, value in id_subsets.items()
    }
    reveal_type(ids)         # ✔  dict[str, list[int]]
```

https://mypy-play.net/?mypy=latest&python=3.11&flags=new-type-inference&gist=c2ecbe6a4d637fc50edf5d946eecb494

**Expected Behavior**

The revealed types should be identical.

**Your Environment**

- Mypy version used: tested with mypy-play 1.4.1 and master branch.

**Comment by erictraut** [comment]
I think mypy is correct here. For comparison, pyright evaluates the same types.

The type of `id_subsets` is declared as `dict[str, int | list[int]]`. (The `dict[str, x]` is implicit because it is an annotation on a `**kwargs` parameters.) That means it cannot be narrowed on assignment to `dict[str, list[int]]` because this isn't a valid subtype of `dict[str, int | list[int]]`. Using bidirectional type inference (aka "context"), mypy evaluates the type of the dictionary comprehension to be `dict[str, int | list[int]]`, which is compatible with the declared type.

In your second example, `ids` has no type declaration, so its type is inferred. There is no type narrowing involved here.

**Comment by randolf-scholz** [comment]
Invariance strikes again.
