### ISSUE TITLE
Type error unpacking Union of Lists 

### ISSUE THREAD

**Issue by thiago-silva** [python/mypy#1575]
Version: master branch, 001ae51778baf3e2351d3efc63dc4eb4a191acef

Code:

``` python
from typing import Union

def f(x: bool) -> Union[List[int], List[str]]:
    if x:
        return [1, 1]
    else:
        return ['1', '1']

def g(x:bool):
    a,b = f(True)
```

Error:

```
z/test.py: note: In function "g":
z/test.py:10: error: 'Union[builtins.list[builtins.int], builtins.list[builtins.str]]' object is not iterable
```

**Comment by gvanrossum** [comment]
Interesting. Yes, this should be supported IMO.

**Comment by thiago-silva** [comment]
This seems be an issue particular to destructuring assignment as mypy accepts indexing the result of the `f()` call.

**Comment by kirbyfan64** [comment]
Looking around, this seems to be because `type_is_iterable` checks if the given type is...well, iterable, but `Union[A, B]` where `A` and `B` are themselves iterable types isn't considered a subclass of `typing.Iterable`. I tried the obvious fix (adding a clause that checks if a union type and, if it is, then checks its children), but it caused an internal failure somewhere else...
