### ISSUE TITLE
False negative: Incorrect return type overlooked when it is an alias to Union[T, …]

### ISSUE THREAD

**Issue by lukasjuhrich** [python/mypy#15803]
**Bug Report**

_This may be related to #12211_.
When extracting a type annotation like `-> t.AnyStr | int` to a `t.Union` alias, mypy fail to detect incorrect return types.

The actual problem for me was that annotating flask view functions with `ResponseValueType` did not find obvious return type violations, but (as I found out during writing of this issue) a workaround [seems to have been added](https://github.com/pallets/flask/commit/190dd4df86874495f56bb088fbd0cb1d9f0e77a0#diff-eb15c7c70f2ace4b5da85dfb0bdfba12a226181c672271d150eb0d2462c4fec7).

I'm unsure what to expect of mypy here but silently allowing everything seems like a big hazard to me.

**To Reproduce**
See the functions `foo2` and `bar2` in the following gist:
https://mypy-play.net/?mypy=latest&python=3.11&gist=04f598b90124f58021cf19209a7df967.

**Expected Behavior**

the return statements of `foo2` and `bar2` should cause an error, either the same error as `foo` and `bar` or the same as `foo3` and `bar3`.

**Actual Behavior**

`foo2` and `bar2` don't cause an error

**Your Environment**

- Mypy version used: 1.4.1
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.11

**Comment by erictraut** [comment]
I think mypy is doing the right thing here. You're using type variables incorrectly. `AnyStr` is a type variable. It is not equivalent to `str | bytes`.

The signature `def foo() -> AnyStr | int` is using the type variable `AnyStr` incorrectly because it appears only once in the signature. You probably mean `def foo() -> str | bytes | int` in this case.

The statement `R = t.Union[t.AnyStr, int]` defines a type alias `R` that is generic and accepts a single type argument. A proper use of `R` would be `R[bytes]` or `R[str]`. If you don't specify the type argument, a type checker will fill in `Any`, so the union effectively becomes `Any | int`.

The same logic applies to your other examples that use type variable `T`.

In general, if a type variable appears only once within a function signature, you are using the type variable incorrectly.
