### ISSUE TITLE
Cannot unify universally-quantified type with a more specific but compatible type

### ISSUE THREAD

**Issue by vthemelis** [python/mypy#15800]
**Bug Report**

I'm trying to type-check a lambda-based encoding of Lisp's cons, car, and cdr.

For cons I have:
```Python3
from typing import Callable, TypeVar

T = TypeVar('T')
U = TypeVar('U')
V = TypeVar('V')

def cons(a: T, b: U) -> Callable[[Callable[[T, U], V]], V]:
    return lambda f : f(a, b)
```
This uses a universally-quantified Callable (for every 'V'). This first bit seems to confuse Pyre (see https://github.com/facebook/pyre-check/issues/771) but mypy (maybe accidentally) accepts this just fine.

The issue starts when I'm trying to type-check car and cdr:
```Python3
def car(cons: Callable[[Callable[[T, U], V]], V]) -> T:
    return cons(lambda x, _: x)
```
This fails with:
```
error: Incompatible return value type (got "V", expected "T")  [return-value]
error: Argument 1 has incompatible type "Callable[[T, U], T]"; expected "Callable[[T, U], V]"  [arg-type]
```

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=30773cfcb7f4bf19fb6a1602d10a4549

**Expected Behavior**

mypy should unify `V` with `T` in car.

**Actual Behavior**

It complains that `V` and `T` are not the same

**Comment by ilevkivskyi** [comment]
Mypy is correct in allowing the first, and it is correct in prohibiting the second. It cannot "unify" `V` in `car` body, because it is not a variable there anymore. Python doesn't have a syntax to explicitly declare type variables during function definition (but there is a PEP to add this in Python 3.12 IIRC), so mypy uses a simple rule: all type variables that appear in function _argument types_ and not already bound by enclosing functions/classes are this functions type variables. So what you wrote is actually:
```python
def car[T, U, V](cons: Callable[[Callable[[T, U], V]], V]) -> T:
    return cons(lambda x, _: x)
```
but what you want is
```python
def car[T, U](cons: Callable[[Callable[[T, U], V]], V]) -> T:
    return cons(lambda x, _: x)
```
To define the latter you need to use (a bit verbose, but very flexible) callback protocols:
```python
T_co = TypeVar('T_co', covariant=True)
S_co = TypeVar('S_co', covariant=True)

class Cons(Protocol[T_co, S_co]):
    def __call__(self, __f: Callable[[T_co, S_co], V]) -> V: ...

def car(cons: Cons[T, U]) -> T:
    return cons(lambda x, _: x)
```
and now mypy is happy.
