### ISSUE TITLE
`reveal_type` doesn't produce any output for `<nothing>`-types

### ISSUE THREAD

**Issue by randolf-scholz** [python/mypy#15820]
**To Reproduce**

The easiest way to produce a `"<nothing>"` (or: `Never`) is to exhaust a `Union` type:

```python
def foo(x: int | tuple[int, ...]) -> str:
    if isinstance(x, int):
        return "an integer"
    if isinstance(x, tuple):
        return "a tuple"

    reveal_type(x)  # doesn't show anything...
    y: int = hash(x)
```

https://mypy-play.net/?mypy=master&python=3.11&gist=3caf40c6fe0a9e4652449ec5340667e1

**Expected Behavior**

A message like `note: Revealed type is "<nothing>"` (or: `Never`)

**Actual Behavior**

No output at all.

**Comment by randolf-scholz** [comment]
I think this goes back to python not implementing empty `Union`-types. (see https://github.com/python/typing/issues/1362).

In principle, `Union`-should just work like a `set` and a type-checker should be able to `set.remove` a type when it is exhausted. The empty set `Union`/`Union[]`/`Union[()]` should be identified with the bottom type `Never`.

**Comment by erictraut** [comment]
This is because mypy doesn't analyze code that it considers unreachable. So this is intended (or at least expected) behavior.

Also, `<nothing>` is the same as `Never`. The former is a mypy internal concept used in cases where the constraint solver is unable to solve a type variable. The latter is a part of the official Python type system (and is an alias for `NoReturn`.)

Python type checkers do implement empty union types. If you want to use this concept in a type annotation, you can spell it as `Never` or `NoReturn`. As discussed in the python/typing thread, there's no good justification for creating yet another redundant way to spell the same thing, especially using the `Union` special form, which is something that is on its way to being deprecated now that `|` has gained wide adoption.

**Comment by AlexWaygood** [comment]
Your diagnosis is incorrect: this doesn't have anything to do with `reveal_type` in particular. It happens because of the fact that mypy doesn't do any type-checking at all for code blocks it determines to be unreachable, and this includes `reveal_type` calls. If you run mypy with `--warn-unreachable` you'll see that it has determined that block of code to be unreachable.

(FWIW, I agree that it's counter-intuitive and surprising behaviour that mypy just ignores everything in a code block it has determined to be unreachable, but we already have several other issues open discussing that problem.)

**Comment by ikonst** [comment]
FWIW it's on my radar to fix
