### ISSUE TITLE
commit e9379d8 (fix for #1513) broke our setup

### ISSUE THREAD

**Issue by Herst** [python/mypy#1592]
We are setting `MYPYPATH` to a relative location where we have our stubs for various 3rd party libs stored before running `mypy`. Apparently some of these stubs are being ignored in the newest post-0.4.1 revisions (`"module" has no attribute [...]`).

`git bisect` points me to commit e9379d8 (fix for #1513) as the culprit.

Any other information you need? (Have fun @ PyCon BTW.)

**Comment by gvanrossum** [comment]
I'd love more info -- what files are being tried before that commit and
what files are being tried after it?

The commit is quite important IMO, since previously mypy would be
inconsistent with Python when both foo.py and foo/__init__.py exist.

**Comment by Herst** [comment]
Not sure what you mean with "tried" here.

**Comment by Herst** [comment]
Ah you mean with `git bisect`, what commits are tried? I simply but the HEAD as the first bad commit and the one where the version got bumped to `0.4.1` as the last good one but I can see whether simply reverting that commit (if it works) will indeed fix this issue.

**Comment by Herst** [comment]
OK, so I reverted the commit and the problem is gone, then I reset back to before the revertion and the problem is back, so clearly it is that one commit.

**Comment by gvanrossum** [comment]
No, that's not what I meant.

Mypy tries whether various files exist, e.g. when it is looking for "foo",
it is looking for foo.py, foo.pyi, foo/__init__.py, foo/__init__.pyi, in
all lib_path entries, until it finds one. The commit changed the order in
which files are tried, because the old behavior was different than the way
Python searches (but Python of course doesn't search for the .pyi files,
and its search path is different).

The commit you found shows you where the changed code is. Try putting some
prints in there and compare the output before and after that commit.

I presume that this will reveal that you have some place in your repo where
there's both a foo.py and a directory named foo containing an __init__.py
(or perhaps a .pyi for either or both). Then you will have to ask yourself,
what does Python do there, and why do you have both of those.

**Comment by Herst** [comment]
You're right, that was the problem! I have to ask my colleague why he created this folder and put some of the stubs there and some not but it seems to me like it very likely had no good reason which is why I consider this to be a non-issue from mypy's side and therefore will be closing this.
Thanks for your help! Great stuff you do!

**Comment by gvanrossum** [comment]
Glad you figured it out!
