### ISSUE TITLE
No overload variant of "astype" of "Series" matches argument types "Type[int]", "str"

### ISSUE THREAD

**Issue by nbro10** [python/mypy#15922]
I'm getting the following error

```
No overload variant of "astype" of "Series" matches argument types "Type[int]", "str"
````

When I try to convert the type of a single column using `astype`, something like this

```
for column in integer_columns:
    df[column] = df[column].astype(np.int64, errors="ignore")

for column in float_columns:
    df[column] = df[column].astype(np.float64, errors="ignore")
```

Even if I use `"int64"` or `int` instead of `np.int64`, I still get the same error. I can't yet update `mypy` to the latest version because this library that I'm working on still supports Python 3.7. Currently, I'm using `mypy 0.950`

I suppose this is a mypy issue because pandas actually expects `Type[int]`.

- Pandas 1.4.4
- Python 3.8.13

So, if this is a bug with mypy 0.95, is there a newer version of mypy where this has been fixed and it's compatible with Python >=3.7.2?

**Comment by erictraut** [comment]
Could you provide a minimal self-contained code sample that demonstrates the problem? The code above references symbols that are not defined, such as `df` and `integer_columns`.

**Comment by erictraut** [comment]
When I run the latest version of mypy on your sample, I don't see any errors. I also have the latest version of pandas and numpy installed. Perhaps you're using older versions of these libraries?

**Comment by erictraut** [comment]
> It would be great to know what the minimum versions of mypy, pandas and numpy are where this issue was solved

The maintainers of pandas are probably in a better position to answer this question than the mypy maintainers. The maintainers of pandas have made great progress in improving the type information over the last year. Older versions of the library (like the one you're currently using) had many type-related bugs (e.g. incomplete overloads) that have since been fixed. You might need to bisect versions to find the minimum one that works with the particular classes and methods you're using in your code.

**Comment by JelleZijlstra** [comment]
As in most open source projects we don't attempt to support old versions. If something is fixed in a newer version, that's good enough. If you need to figure out exactly what version something was fixed in, you can do that yourself.
