### ISSUE TITLE
Regression: missing output from reveal_type

### ISSUE THREAD

**Issue by eltoder** [python/mypy#15954]
Apologies if this was already reported. `reveal_type` is a hard thing to search for.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=2a1d6a831177eb02b175a25fc07a374e
```python
class A:
    x: int

class B:
    x: float

class C(A, B):
    x: int

c: A = C()
assert isinstance(c, B)
reveal_type(c)
reveal_type(c.x)
```

**Expected Behavior**

I expect to see 2 lines of output from `reveal_type`. This works in 1.4.x but stopped working in 1.5.x.

**Actual Behavior**

No output.

**Your Environment**

- Mypy version used: 1.5.1
- Python version used: 3.11

**Comment by AlexWaygood** [comment]
This doesn't actually have anything to do with reveal_type: the reason why mypy doesn't output anything for those reveal_type calls is just because mypy doesn't analyse any blocks of code it has determined are unreachable, and it has (erroneously) determined here that all code below the `assert isinstance(c, B)` line is unreachable. If you add the `--warn-unreachable` flag to the mypy config, you can see this clearly: https://mypy-play.net/?mypy=latest&python=3.11&gist=617de6102ded35d1eaa9aa0c22142b43&flags=warn-unreachable

**Comment by eltoder** [comment]
@AlexWaygood thank you for the explanation. In that case, the question is whether isinstance() should be considered always false. If there's already an issue about this, feel free to close this as a duplicate.

**Comment by AlexWaygood** [comment]
Yeah, it's a ~known issue that mypy struggles a little bit with multiple inheritance. See e.g. https://github.com/python/mypy/issues/3603 and https://github.com/python/mypy/issues/5529

**Comment by eltoder** [comment]
@AlexWaygood both of these issues are pretty old. The change here happened between 1.4 and 1.5, so this is something new.

**Comment by AlexWaygood** [comment]
@ikonst recently improved the consistency of whether or not mypy will actually ignore all blocks of code that are deemed unreachable or not. So the recent change in behaviour is likely due to that. But that's a strict improvement over the previous behaviour since, as I say, by design, mypy is currently _meant_ to ignore everything in a block of code it considers unreachable.

The reachability analysis hasn't changed (mypy considered the block of code at the bottom unreachable in v1.4.x as well); the only difference is that mypy is now more consistent about how it treats unreachable code, which is a good thing.
