### ISSUE TITLE
Type not narrowed with inheritance except when narrowed explicitly

### ISSUE THREAD

**Issue by bersbersbers** [python/mypy#15963]
**Bug Report**

It seems that with inheritance, type narrowing does not work implicitly and has to be made explicit. Is this intended or a bug? Pylance behaves the same way, so maybe this is simply intended.

**To Reproduce**

```python
from pathlib import Path

class Base:
    path: Path | None = None

class Class(Base):
    def __init__(self) -> None:
        self.path = Path()   # fails
        # self.path: Path = Path()  # works

    def fun(self) -> None:
        self.path.touch()
```
https://mypy-play.net/?mypy=latest&python=3.11&gist=c2b7e527a71c2a9d79dce97ae9939658

**Expected Behavior**

No error

**Actual Behavior**

> bug.py:12: error: Item "None" of "Path | None" has no attribute "touch"  [union-attr]

**Your Environment**

- Mypy version used: 1.5.1
- Python version used: 3.11.5

**Comment by erictraut** [comment]
I think mypy is working correctly here. Type narrowing works only within a local scope, so method `fun` will not see a type that has been narrowed by assignment in method `__init__`. If you add the explicit `Path` type declaration in the `__init__` method, you are explicitly declaring that `path` has the type `Path` rather than `Path | None`. This redeclaration in a subclass is allowed because `Path` is a subtype of `Path | None`. 

Mypy and pyright are in agreement here. If you omit the explicit type declaration for `path` in the `__init__` method (as you've done in the unmodified sample), a type violation is reported within the `fun` method. If you add the explicit type declaration (comment out the "fails" line and uncomment the "works" line), no type violation is reported.
