### ISSUE TITLE
`ParamSpec` doesn't handle out-of-order kwargs for callable protocol

### ISSUE THREAD

**Issue by koogoro** [python/mypy#15984]
**Bug Report**

If you use a `ParamSpec` to accept a callable and its arguments, and supply keyword args in a different order than they appear in the arguments, mypy reports an error:
https://mypy-play.net/?mypy=master&python=3.11&gist=56911342c8a4d3326da4cc1265f1a156

This didn't happen on the last release, and in fact didn't happen as recently as 5d909f1cdd7dde5e58259dc153959a38d084b988. It does seem to happen only for callable protocols and not for functions.

**Actual Behavior**
```
main.py:12: error: Argument 1 to "g" has incompatible type "A"; expected "Callable[[int, str], None]"  [arg-type]
main.py:12: note: "A.__call__" has type "Callable[[Arg(str, 'x'), Arg(int, 'y')], None]"
```

**Comment by ilevkivskyi** [comment]
Yeah, this is caused by my PR. I will take a look later today (It is sad we don't have something like `get_proper_type()` and plugin for `CallableType`, maybe we should write one, but I guess it may be a pain to use, since we don't have `checkmember` infra available in many places, so it comes back again to https://github.com/python/mypy/issues/7724)
