### ISSUE TITLE
Improve error message when type variable used in Union in type alias definition

### ISSUE THREAD

**Issue by pyrocat101** [python/mypy#1613]
Python 2.7 Code:

``` python
from typing import AnyStr, Union
StrOrInt = Union[AnyStr, int]
```

The error:

``` python
test.py:error: Invalid type "typing.AnyStr"
```

**Comment by gvanrossum** [comment]
That's because AnyStr is really a type variable. You would have to write this as `Union[bytes, unicode, int]`.

**Comment by pyrocat101** [comment]
@gvanrossum Thanks for the clarification. I assume that this issue is a won-fix?

**Comment by gvanrossum** [comment]
Well, what was the rest of your program going to be? Was it going to use that type variable somehow?

**Comment by JukkaL** [comment]
At least the error message isn't very informative.

**Comment by pyrocat101** [comment]
@gvanrossum Previously I wrongly assumed `AnyStr` to be an union type, and was gonna use that `StrOrInt` as argument type / return type in my program.

**Comment by gvanrossum** [comment]
See also this blog post (disclaimer: it's mine :-)
http://neopythonic.blogspot.com/2016/05/the-anystr-type-variable.html

**Comment by ilevkivskyi** [comment]
The original example actually passes now and creates a generic alias. Not sure what to do here, it is documented that variance etc. of type variables is ignored when defining generic aliases, so that ``StrOrInt[int]`` is accepted (it is rejected however later if this is used in a function/class defined with ``AnyStr``).

I was thinking some time ago _maybe_ we should require "normal" (i.e. unconstrained invariant) type variables to define generic aliases. This will require a bit of verbosity in some cases (one would need to define a dedicated variable), but will avoid possible confusions (most users read the docs after they have problems, not before). Or we can just close this issue.

**Comment by ilevkivskyi** [comment]
This is supported for quite some time and is relatively well documented now.
