### ISSUE TITLE
(🐞) `TypeGuard` is applied to the `self` argument when passed explicitly

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#16146]
```py
from typing import TypeGuard
class A:
    def f(self, a: object) -> TypeGuard[int]:
       return True
       
a = A()

b: object
assert a.f(b)
reveal_type(a)  # A
reveal_type(b)  # int
    
c: object
assert A.f(a, c)
reveal_type(a)  # int
reveal_type(c)  # object
```

PEP doesn't cover this case, but it is obviously incorrect.

**Comment by bucknathanael** [comment]
Two issues here:

1. In the method f of class A, you have annotated the parameter a as an object, but you are returning True from the method, which is a boolean value, not an int. This is incorrect because the annotation suggests that the method should return an int. You should fix the return type annotation to match the expected return type.

2. In the second part of the code, you are using the reveal_type function from the typing module to check the types of variables a, b, and c. However, the way you're using it is not consistent with the actual types of these variables.

Here's the corrected code:

from typing import TypeGuard

class A:
    def f(self, a: int) -> TypeGuard[int]:
        return True

a = A()

b: int
assert a.f(b)
reveal_type(a)  # A
reveal_type(b)  # int

c: int
assert a.f(c)
reveal_type(a)  # A
reveal_type(c)  # int


Hope this helps!

**Comment by KotlinIsland** [comment]
@AlexWaygood 

Can you delete / report this AI spam comment.

https://github.com/python/mypy/issues/16146#issuecomment-1730198641

**Comment by AlexWaygood** [comment]
> @AlexWaygood
> 
> Can you delete / report this AI spam comment.
> 
> [#16146 (comment)](https://github.com/python/mypy/issues/16146#issuecomment-1730198641)

Sadly not; I'm not a maintainer, and that requires more than my triage privileges. Otherwise I would.

**Comment by JelleZijlstra** [comment]
Reported and deleted the comment, will hide your comments and mine as off-topic.

**Comment by eli-schwartz** [comment]
> PEP doesn't cover this case, but it is obviously incorrect.

Isn't it? The PEP says that narrowing will be performed on the first explicit argument passed to the TypeGuard function, and that is the explicitly passed self on an instance method accessed via its class.

It's not a very good TypeGuard since it can just be a freestanding function, but it does seem to be PEP compliant...

**Comment by erictraut** [comment]
This code sample uses a user-defined type guard function in a manner for which it wasn't designed and I wouldn't recommend. That said, I think that mypy is behaving correctly here and is in compliance with PEP 647, so I don't consider this a bug. Note: I'm the author of PEP 647.

The PEP says that the expression passed as _the first positional argument_ to the call should be narrowed. In your example, the first positional argument in the call expression `A.f(a, c)` is `a`. Mypy behaving in accordance with the text of the PEP. It's also working consistently with pyright, which is the reference implementation for PEP 647.

**Comment by KotlinIsland** [comment]
BTW this was resolved (among other typeguard issues) in basedmypy 2.2.0

[playground](https://mypy-play.net/?mypy=basedmypy-2.2.1&python=3.11&gist=0519ab58f76854ec7d10501e245d1a06)
