### ISSUE TITLE
Consider naming Optional something else

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1654]
I just wanted to post some feedback that I've had a few people try to annotate optional arguments as Optional, when the argument cannot be None, and when asked it turned out that they were confused about what Optional means.

Not sure there's anything that can be done about the name now, but since I got this in annotations from at least 2 people that I can remember today, I thought it worth flagging.

**Comment by gvanrossum** [comment]
Interesting!

It is not too late, since PEP 484 is still provisional. But I'm not really keen on Nullable (since Python calls that thing None, not Null) and I can't think of another name.

Can you remember exactly what they had typed? Would they type
```python
def foo(a):
    # type: (Optional[int]) -> None
```
or did they type
```python
def foo(a=0):
    # type: (Optional[int]) -> None
```
If the former, it suggests they believed that adding Optional[] would make the argument optional (rather than mandatory but nullable). If the latter, I'm not sure what they were thinking.

A theory to explain the confusion is that the text about Optional[t] in http://mypy.readthedocs.io/en/latest/kinds_of_types.html?highlight=Optional#the-type-of-none-and-optional-types is a bit confusing, since it uses an argument as an example. (If it were to use a return type there would be less opportunity for confusion.)

Finally, the cheat sheet has exactly one example using Optional[], and it uses an optional argument -- perhaps that's another source of the confusion?

-----

Probably unrelated, there's a feature that's pretty much the opposite, where you can _leave out_ the Optional but add a None default:
```python
def foo(a: int = None): ...
```
Here a's type is Optional[int].

**Comment by timabbott** [comment]
They typed something more like the second one (often with something falsey.  Two examples I remember are:

```
def foo(a=""):
    # type: (Optional[str]) -> None
def foo(a=[]):
    # type: (Optional[List[str]]) -> None
```

**Comment by gvanrossum** [comment]
Hm, that could come from the cheat sheet.

On Saturday, June 4, 2016, Tim Abbott <notifications@github.com> wrote:

> They typed something more like the second one (often with something
> falsey. Two examples I remember are:
>
> def foo(a=""):
>     # type: (Optional[str]) -> None
> def foo(a=[]):
>     # type: (Optional[List[str]]) -> None
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/mypy/issues/1654#issuecomment-223795375>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACwrMsg9cLreTOpYMO87tpfWTgMrPSDuks5qImjqgaJpZM4IuSE9>
> .
>


-- 
--Guido (mobile)

**Comment by ddfisher** [comment]
One thing to consider: when strict Optional is the default, these annotations are likely to cause errors (because the Optional-annotated arguments won't have been checked for None in the function body).  Maybe if we think carefully about how those errors are phrased we could educate people about their mistake.  (We could even consider having a special explanatory message if all optional arguments are Optional annotated and not properly checked in the function.)

**Comment by jhance** [comment]
I think `Optional` is a somewhat undescriptive name because it sounds too much like it behaves similarly to Haskell's `Maybe`. `Optional` has different semantics than a true optional type.

**Comment by gvanrossum** [comment]
But Haskell users are not the target audience here. What does the word
Optional mean intuitively to Python users?

**Comment by jhance** [comment]
I think intuitively it means

```
def foo(a=0):
    # type: (Optional[int]) -> None
```

Regardless of whether that makes any sense from a type inference perspective

**Comment by gvanrossum** [comment]
I've thought about this some more and I'm going to close this as a won't fix. It would be tough to change: PEP 484 changes require a bunch of pleading with other Python developers and projects (pytype, PyCharm), it's not just up to mypy, and getting a new version of typing.py into the stdlib is a lot of work (I've just finished doing this for 3.5.2 which is about to be released this weekend).

We have enough other things on our plate.
