### ISSUE TITLE
(🐞) 1.7 regression, `(x: int)` considered a valid subtype of `(*args: Any)`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#16569]
Given:
```py
# mypy: disable-error-code=empty-body

from typing import Any, Protocol

class Base:
    def f(self, *args: Any) -> None: ...

class Derived(Base):
    def f(self, x: int) -> None: ...  # no error
```
See:
https://github.com/python/mypy/blob/1200d1d956e589a0a33c86ef8a7cb3f5a9b64f1f/mypy/subtypes.py#L1597-L1607

@ilevkivskyi 

- Related #16567

**Comment by JelleZijlstra** [comment]
That error seems correct. The protocol demands that the function take *any number* of arguments. A callable that takes exactly one argument is not compatible.

**Comment by KotlinIsland** [comment]
@JelleZijlstra Intuitively, I thought the same thing, but I think this is intentional, when it is not the subject of protocol compatability, mypy likes this subtype:
```py
# mypy: disable-error-code=empty-body
from __future__ import annotations

from typing import Any, Protocol

class A(Protocol):
    def __call__(self, *args: Any) -> None: ...

class B(A): 
    def __call__(self, x: int) -> None: ...  # no error

a: A = B()  # no error
```

Although, it could be that __this__ is the defective behavior...

**Comment by erictraut** [comment]
Jelle's analysis above is correct. Mypy is correct in emitting an error in the first code sample because protocol `A` requires that the method accept an arbitrary number of positional arguments, but `B` does not.

> it could be that this is the defective behavior...

Yes, I think this is a false negative. This should be flagged as an incompatible method override. For comparison, [pyright emits an error here](https://pyright-play.net/?strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFAArgxgDGYANgFDM30CGAzh4QBSVjU69AJQAuRlElQAJgFNgUAPqKabevWU8Os%2BsDIAqNiDQdRhYsKgBaAHxQAcmBSzxUt1AB0X5o1aduAEI8BGISUnIKyqrqmtq6ZAAeZqgwlrYOTi5h7p7ezGxmBFAAvFBBwoxAA).

The justification provided in the comment seems weak. This introduces a hole in the type system. Likewise, I don't think it's correct to consider `(*Any, **Any)` a supertype of all callables. However, `...` (when used in a `Callable` or as as a type argument to a `ParamSpec`) _is_ both a _supertype_ and a _subtype_ of all callables. (It's the moral equivalent of `Any` when used with a callable signature.)

These would be good points to discuss and clarify in the context of the typing spec shepherded by the newly-formed typing council (TC).

**Comment by KotlinIsland** [comment]
Ah yes, after some investigation, it appears that this is an unintended regression in 1.7

**Comment by KotlinIsland** [comment]
@ilevkivskyi Was this closed as it is working as intended? if so, could you comment on the second example in the OP.
