### ISSUE TITLE
Add a Python 3 version of cheat sheet

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1661]
This should use the PEP 3107 annotation syntax, and the discussion of strings will differ.

**Comment by JukkaL** [comment]
This should mention string literal forward references, which are less relevant for Python 2.

**Comment by ultimatecoder** [comment]
I am working on this. Many thanks!

**Comment by ultimatecoder** [comment]
I will push work in next two days. I am still working on this.

**Comment by ddfisher** [comment]
Any update? :)

**Comment by ethanhs** [comment]
Some thought should be put into this due to the Python 3.6 variable annotation syntax. Maintaining 3 docs doesn't really make sense to me. Perhaps explaining only what is different might be good? Explain the function annotations, forward references, and then a section in the end about the new 3.6 syntax?

I'd be happy to work on this... don't know where @ultimatecoder is on it...

**Comment by gvanrossum** [comment]
Let's assume @ultimatecoder got sidetracked. I'd be happy to have someone else do this.

Agreed that it should be enough to have a single Python 3 sheet that calls out the PEP 526 syntax at the end. (We also have http://mypy.readthedocs.io/en/latest/python36.html for that, but the cheat sheets' purpose is different.) But I think it should be possible to read the Python 3 cheat sheet without ever referring to the Python 2 one (or vice versa).

**Comment by ethanhs** [comment]
Okay. I'll get started on that now. I expect I'll have something tomorrow.
