### ISSUE TITLE
Incompatible types in assignment (marshmallow) error

### ISSUE THREAD

**Issue by tester-sn** [python/mypy#16955]
Mypy falsely reports error if user-defined schema field name is the same as in marshmallow's own Schema class.
Marshmallow itself has no problem with such field definitions, works fine.

https://github.com/marshmallow-code/marshmallow/issues/1697

Maybe you could redefine this error as warning, so user could disable it?
Or offer other solution?
Our code is required to pass linters, and we may need such namesake fields to be defined.

**Comment by erictraut** [comment]
Could you provide a self-contained, minimal code sample that exhibits the problem in mypy?

**Comment by tester-sn** [comment]
```
from marshmallow import Schema, fields

class MySchema(Schema):
    context = fields.String(required=False)
```
![image](https://github.com/python/mypy/assets/138874829/8e60273c-3f4d-4d3f-ad16-e9c2965c437f)

**Comment by erictraut** [comment]
This looks like a legitimate type violation. The base class `Schema` already has an instance variable named `context`. Mypy infers that its type is `dict | None` based on the assignment in `Schema.__init__`. In the child class `MySchema`, you're attempting to overwrite the instance variable with a value that is the wrong type. If the base class is assuming this value will always be a `dict` or `None`, the program will not function correctly.

**Comment by tester-sn** [comment]
yes, i understand the mechanics of the error. but hear me out, i am defining a field in my schema class, that can be _any_ name. marshmallow understands that too, and works around any such coincidence internally. so from the point of view of the actual library processing this code, it is fine, and it works as intended. however mypy is not able to see it.

**Comment by sirosen** [comment]
Marshmallow has a metaclass which does some work on these attributes, which is why it's totally fine at runtime but expected that any reasonable type checker will complain.

---

This might actually be a use case for the `no_type_check` decorator. I didn't pay close attention to the recent discussion about it, but if applying it to `Schema.__init__` in marshmallow works for suppressing the error in library consumers, that would sort of make sense.

**Comment by sirosen** [comment]
Just for the record, I looked again and realized that it wouldn't really be appropriate to `@no_type_check` in marshmallow because these are instance attributes that are well-typed and are usable in subclasses.
`marshmallow` draws a division between instance attributes and class attributes via its metaclass for schemas.

Short of a mypy plugin though, I think this is a nothing-to-do item. It's exactly the kind of "arbitrary metaclass magic" that has long been known to be unsupported for type checkers.
