### ISSUE TITLE
remove mypy's stub cleanliness checking and deprecate `-f`/`--dirty-stubs`

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1719]
Mypy's stub cleanliness checking/enforcement has never been helpful for me.  Every time I interact with it, it just forces me to run the same command again with `-f`.

I propose we rip it out.  I don't think it makes sense to have user-facing flags for a development feature (especially not a flag as common as `-f`), and I don't think it makes sense for mypy to know about git submodules.

**Comment by gvanrossum** [comment]
+1

--Guido (mobile)

**Comment by phouse512** [comment]
is this something still being decided? if not, I'll take a stab at it.

**Comment by ddfisher** [comment]
We definitely want to do this.  Still want to take a stab at it? :)

**Comment by phouse512** [comment]
didn't see this till now - yeah I'll work on getting something up for this!

**Comment by JukkaL** [comment]
What about adding a shell script (or .bat) for doing the submodule update to the root of the repo? The most useful thing about the stub cleanliness check for me is that it prints out the exact command needed for updating typeshed. I can never remember the exact form. I usually use my own shell script for that, but when working in a new clone of the repo I don't have the shell script always around.

**Comment by ddfisher** [comment]
Having a script that just contains `git submodule update` seems a bit like overkill to me.  I've found adding `post-checkout` and `post-merge` hooks that update the submodule to be very convenient -- @JukkaL maybe you could just add those instead?

**Comment by JukkaL** [comment]
I'm not worried about myself in particular -- I'm more worried about new contributors that haven't encountered git submodules before. They were the original motivation for adding these checks -- to make submodule updates more discoverable. If typeshed is out of date and a user doesn't know anything about submodules, they'll likely have to read the readme to look up the right command. I still don't always remember the exact command to run after having used it for several months now, and I've found the prompts somewhat helpful (though a little noisy and inconvenient as well). 

About the hooks -- I don't like magic things happening automatically behind my back, since I'm worried about them breaking in various edge cases and causing more trouble than they are worth. Also, configuring the hooks for every clone of repo feels like unnecessary effort. As for new contributors, we can't expect them to read the docs in enough detail to set up the hooks if they are only getting familiar with the project.

Having a script (called, perhaps, `update-typeshed.sh`) seem like a reasonable compromise to me:

1. It's perhaps easier to remember `./update.sh` or `./update-typeshed.sh` than `git submodule update`.
2. It's faster to type the script name than `git submodule update` (important as we need to do this a lot, as I'd rather not rely on the hooks), since I can use shell autocompletion, unlike with git subcommands.
3. Even if I can't remember the exact name of the script, I can remember that it's a shell script so I can just run `ls *.sh` and it'll be there. Not quite so with looking up things from the readme, though I can grep the right command quickly if I'm lucky.
4. The update script can also automatically clone the submodule if I forgot to use `--recurse-submodules` when cloning (again, who reads documentation).
5. If you don't care about it, the cost of having the script is minimal and you can just ignore it.

To improve discoverability, when mypy or the test runner can't find typeshed, we could print out a message like this:
   ```
Git submodule 'typeshed' not initialized'.

Run ./update-typeshed.sh to initialize.

IMPORTANT: Run ./update-typeshed.sh also after to each pull, branch switch, rebase and merge
           if typeshed is out of date.    <--- use bold for this
```

Another option is to leave the checks as they are now, but provide an environment variable for suppressing all the checks.

**Comment by gnprice** [comment]
For me, a script like `./update-typeshed.sh` would actually make things less discoverable and more cumbersome than using the standard command `git submodule update`. The latter is at least a common tool shared across many projects I've worked in before; the script would be a new thing to look up every time until it becomes another fact I remember.

Even if the script happens to consist of just a line `git submodule update`, that wouldn't make the experience any simpler -- that would itself be a fact to look up, half-remember, look up again, etc., before I could rely on it.

If post-checkout and post-merge hooks are an effective individual solution, then perhaps a good solution for new contributors would be a script meant to be run in a new clone to set up a development environment, which would create those hooks. (And perhaps other steps, like install dependencies and self into a virtualenv, though more discussion would be needed on the details.)

> I can use shell autocompletion, unlike with git subcommands.

Whatever we do with this, though, I highly recommend getting shell autocompletion for git! It provides not only subcommands but also their options, and arguments like branch names. The `git` packages in Debian and Ubuntu set it up automatically, but if your environment isn't as helpful as that, the underlying code is [in upstream Git's `contrib/` tree](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) and you can add it to your config directly. Or if you're relying on homebrew, [this SO answer](http://stackoverflow.com/questions/14970728/homebrew-s-git-not-using-completion) might be useful.

**Comment by ddfisher** [comment]
+1 to what Greg said.

With regards to new contributors: there are always some things to learn when beginning to work on a new project.  I think learning to manage your typeshed version is a pretty small thing in the process of contributing to mypy.  (And, for what it's worth, I've been running with `git submodule update` as a git hook for the past month or so, and I haven't had a single problem with it so far.  I think it's a viable option.)

Also, the dirty stub check comes with costs:
- Code complexity: Without this, there's no reason for mypy to know or care about what sort of repository it or typeshed is in.  Mypy is quite a complex piece of software already, and I think it's decently important for the long-term (and our own development velocity) that we strongly pursue simplification where possible.
- Usage complexity: the `-f`/`--dirty-stubs` portion of the help message is completely irrelevant to the majority of mypy users.
