### ISSUE TITLE
Hashable doesn't work

### ISSUE THREAD

**Issue by miedzinski** [python/mypy#1746]
Typechecking `Hashable` seems broken.

```
from typing import Hashable


def f(x: Hashable):
    pass


f(0)
f('x')
```

```
$ mypy mypy.py
mypy.py:8: error: Argument 1 to "f" has incompatible type "int"; expected "Hashable"
mypy.py:9: error: Argument 1 to "f" has incompatible type "str"; expected "Hashable"
$ mypy -V
mypy 0.4.3-dev
```

**Comment by gvanrossum** [comment]
There are two solutions here; mypy could learn that Hashable is related to
__hash__, or we could inherit int, str etc. from it explicitly in typeshed.

--Guido (mobile)

**Comment by miedzinski** [comment]
Second option doesn't fix an issue with classes that have `__hash__` defined.

Is there any chance this will be put somewhere in roadmap?

**Comment by gvanrossum** [comment]
I agree (1) isn't very attractive. In terms of roadmap it would be part of "structural type checking". https://github.com/python/typing/issues/11

Maybe we should just close it here? There's already lots of discussion at that issue.

**Comment by JukkaL** [comment]
`object` is hashable, so just inheriting `Hashable` or is not a good approach, as then every type would be hashable. I think that mypy would have to know about the `__hash__ = None` idiom for marking a type as not hashable. This clearly breaks Liskov substitutability but mypy could still catch some clear violations such as using a list as a dictionary key even if it wouldn't be sound.

**Comment by pkch** [comment]
In addition, currently deriving from `Hashable` would break the normal hashability (because `typing.Hashable` is non-virtual subclass of `collections.abc.Hashable`, and the latter disable hashability by overriding `object.__hash__` with a virtual method `__hash__`). This is clearly not something a user of mypy intends when they derive from `typing.Hashable`, so it's good to fix it in the process of upgrading `Hashable` overall.

**Comment by ilevkivskyi** [comment]
Superseded by https://github.com/python/typeshed/issues/2148
