### ISSUE TITLE
Import clearml in project causes Segmentation fault  on mypy run

### ISSUE THREAD

**Issue by amishurov** [python/mypy#17616]
**Bug Report**
We have mypy typing tests included into unit tests
After importing clearml into work project, get constantly segfault error when run mypy tests
https://github.com/allegroai/clearml

**To Reproduce**
   1.  clone repo https://github.com/amishurov/clearml_seg_fault (prepared it to easy peproduce bug)
   2. poetry install
   3. poetry run pytest

**Expected Behavior**
Tests should executed successfully
**Actual Behavior**

**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags:  `--config-file pyproject.toml`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9

I've create issue in clearml project also https://github.com/allegroai/clearml/issues/1218

**Comment by hauntsaninja** [comment]
mypy is compiled with mypyc, which is a subset of Python that is strongly typed. If clearml is monkeypatching argparse, the segfault is expected. Your options are a) to ask clearml to remove or make the monkeypatch optional, b) run mypy in a subprocess that doesn't import clearml, instead of using mypy.api.run
