### ISSUE TITLE
[1.11 Regression] `partial` plugin doesn't respect TypeVar bounds when deciding if something can be passed to `partial`

### ISSUE THREAD

**Issue by AlexWaygood** [python/mypy#17646]
**Bug Report**

```py
from typing import Callable, TypeVar
import functools

T = TypeVar("T", bound=Callable[[str, int], str])
S = TypeVar("S", bound=type[str])

def foo(f: T) -> T:
    g = functools.partial(f, "foo")  # error: "T" not callable  [misc]
    return f

def bar(f: S) -> S:
    g = functools.partial(f, "foo")  # error: "S" not callable  [misc]
    return f
```

https://mypy-play.net/?mypy=master&python=3.12&gist=93876fe629e5320a88349da7a9f65188

Mypy should understand both `T` and `S` to be callable due to the fact that the TypeVars have `Callable` and `type` as their respective upper bounds. We're hitting this in our attempt to upgrade mypy to 1.11.1 for Argument Clinic over at CPython in https://github.com/python/cpython/pull/122550.

Cc. @hauntsaninja 

**Your Environment**

- Mypy version used: 1.12.0+dev.9d56820a63d5b47b53ff0ab6e96ce0951c774ae5 (compiled: no)

**Comment by AlexWaygood** [comment]
#17659 notes that this also causes issues for `Self` (which is internally just a special kind of TypeVar)

**Comment by hauntsaninja** [comment]
I'm going to very disappointingly fix this in https://github.com/python/mypy/pull/17660

This will fix your first example.
It would also fix the `type[str]` example, except it doesn't yet because str has overloaded constructor and overloads don't really work (mostly due to preexisting missing logic), see https://github.com/python/mypy/issues/17585
It will also not fix https://github.com/python/mypy/issues/17659 so I've reopened that. If I make mypy eagerly resolve the Self to its upper bound there, then it would introduce a complaint on the next line. So something cleverer needs to happen.

**Comment by AlexWaygood** [comment]
That all makes sense; thanks for the explanation!
