### ISSUE TITLE
Mypy doesn't recognize metaclass implementing __getitem__

### ISSUE THREAD

**Issue by sangsta** [python/mypy#1771]
Suppose we have an `Enum` called `MyEnum`, and we try something like `MyEnum["foo"]`, mypy will give us an error `Value of type "MyEnum" is not indexable`. We believe this is because mypy has trouble recognizing when a metaclass implements `__getitem__`.

A workaround is to do `getattr(MyEnum, "foo")`, but it'd be nice to have an actual fix.

**Comment by gvanrossum** [comment]
Oh, it looks like this already exists in the tracker: #741. I'll have to close this as a duplicate.

**Comment by gvanrossum** [comment]
Reopening this, since there's an extra wrinkle specifically for `__getitem__` -- because `X[Y]` is used as generic type parameterization, even with @elazarg's fix (#2475) the metaclass's `__getitem__` is not honored.

**Comment by raphCode** [comment]
Sorry to dig this up after years, but it seems the issue was never really resolved besides printing the correct type in `reveal_type()`.
I opened a new issue with details: #15107

I spent quite some time struggling to get custom generics to work in mypy, because this issue and the associated PR made me believe the feature is implemented.
To anyone in the same situation:
**Using custom generics via metaclass `__getitem__` is not supported in mypy at the time being.**
