### ISSUE TITLE
Upper bound is missing from generic function signature in error report

### ISSUE THREAD

**Issue by jolaf** [python/mypy#17792]
**Bug Report**

The provided test defines the generic function `f()` in two ways which are incompatible with each other – one has an upper bound, and the other has not.

However, when reporting this incompatibility, `mypy` prints two signatures that look equivalent because the upper bound is not mentioned in one of them.

This makes it very difficult to understand why `mypy` reports an error and how to fix it. Moreover, the error report looks like a bug in `mypy`.

**To Reproduce**

https://mypy-play.net/?mypy=1.11.2&python=3.12&enable-incomplete-feature=NewGenericSyntax&gist=06224b5d473a6be86cae73f00e4643f1

**Comment by brianschubert** [comment]
For reference,  the reproducer from my mypy playground link above is:
```python
from collections.abc import Callable
from random import choice
from typing import Any, TypeVar

if choice((True, False)):
    F = TypeVar('F')

    def f(a: F) -> F:
        return a
else:
    def f[F_: Callable[..., Any]](a: F_) -> F_:
        return a
```
which currently outputs
```none
main.py:11: error: All conditional function variants must have identical signatures  [misc]
main.py:11: note: Original:
main.py:11: note:     def [F] f(a: F) -> F
main.py:11: note: Redefinition:
main.py:11: note:     def [F_] f(a: F_) -> F_
Found 1 error in 1 file (checked 1 source file)
```
The issue is that the bound for `F_` isn't being displayed. 

---

The root cause seems to be this part of `pretty_callable`:

https://github.com/python/mypy/blob/a646f330641422d5bc9bf71d1f7751ab2d8a8d5d/mypy/messages.py#L2943-L2949

The relevant bit is the `isinstance(upper_bound, Instance)` check. This means that the bound for type var is only displayed if it's a subtype of `Instance`, which [`CallableType`](https://github.com/python/mypy/blob/a646f330641422d5bc9bf71d1f7751ab2d8a8d5d/mypy/types.py#L1798) is not. 

A quick fix would be to simply add a check for `CallableType`, as in:
```diff
          if isinstance(tvar, TypeVarType):
              upper_bound = get_proper_type(tvar.upper_bound)
              if (
                  isinstance(upper_bound, Instance)
                  and upper_bound.type.fullname != "builtins.object"
-               ):
+               ) or isinstance(upper_bound, CallableType):
                  tvars.append(f"{tvar.name}: {format_type_bare(upper_bound, options)}")
```
which would change the output to
```none
main.py:11: error: All conditional function variants must have identical signatures  [misc]
main.py:11: note: Original:
main.py:11: note:     def [F] f(a: F) -> F
main.py:11: note: Redefinition:
main.py:11: note:     def [F: Callable[..., Any]] f(a: F) -> F
Found 1 error in 1 file (checked 1 source file)
```
However, this wouldn't be a complete fix, since there are other `ProperType` (but not `Instance`) subtypes that should probably also be displayed as bounds, like `UnionType`, `LiteralType`, `TupleType`, and `NoneType` .
