### ISSUE TITLE
mypy stubgen is creating bad stubs when arguments have double underscores

### ISSUE THREAD

**Issue by daltairwalter** [python/mypy#17838]
`def badUnderscores(__unused_x:int) -> None:`  
`    print("Not using x")`

running `stubgen --include-docstrings` produces:
`def badUnderscores(__unused_x: int, /) -> None: ...`

Note the `, /` "argument" that is created here

**Comment by brianschubert** [comment]
Thanks for the issue!

This is intentional behavior. The `/` denotes [positional-only parameters](https://docs.python.org/3/tutorial/controlflow.html#special-parameters). Mypy treats parameter with two leading underscores as being positional-only. This is actually a requirement from the [typing spec](https://typing.readthedocs.io/en/latest/spec/historical.html#positional-only-parameters):
> To support positional-only parameters in code that must remain compatible with older versions of Python, type checkers should support the following special case: all parameters with names that begin but don’t end with __ are assumed to be positional-only

If you want to hint that the parameter is unused, consider using a single underscore.

See also
* https://peps.python.org/pep-0570/
* https://discuss.python.org/t/ambiguities-about-positional-only-parameters/42328

**Comment by daltairwalter** [comment]
Thank you for the detailed response.  Required or not, it definitely seems to be best practice for the stubgen to add the `/`.  This caused problems for a couple of my python tools, but the single underscore worked to fix the problems.
