### ISSUE TITLE
Clarify Usage of typing.NoReturn as a Generic Type Parameter in Stubs

### ISSUE THREAD

**Issue by ViktorSky** [python/mypy#17851]
**Documentation**

The documentation for `typing.NoReturn` does not clearly explain its behavior and limitations when used as a generic type parameter in Python stubs. Specifically, it is unclear whether it is appropriate to use `NoReturn` as a type argument, such as `Foo[NoReturn]`, and what the implications are when doing so.

In certain scenarios, it may be useful to use `NoReturn` in type stubs to indicate that a specific implementation or subclass should never return a value of type `T`. However, the current documentation lacks examples or guidance on whether this is a valid approach, and whether it may lead to future issues.

This ambiguity can cause confusion for developers who rely on stubs to document and enforce behavior in their code. An update to the documentation with clear guidelines and examples would be very helpful.

```python
from typing import Generic, NoReturn, TypeVar
from numpy import int8, float16

_T = TypeVar('_T')

class DType(Generic[_T]):
    def max(self) -> _T: ...

Int8: DType[int8]
Float16: DType[float16]
# The following usage is ambiguous based on the current documentation:
Bool: DType[NoReturn]
String: DType[NoReturn]
Complex64: DType[NoReturn]
```

**Proposed Changes:**
1. Update the documentation for `NoReturn` to explain its use as a generic type parameter, including when it is appropriate or not.
2. Provide examples of using `NoReturn` in type stubs, including valid and invalid scenarios.
3. Clarify any implications for static type checking when `NoReturn` is used in this way.

**Comment by erictraut** [comment]
You may find the Python typing spec to be a useful resource for questions like this. `NoReturn` (and the equivalent type `Never`) are documented in the spec [here](https://typing.readthedocs.io/en/latest/spec/special-types.html#noreturn). Mypy passes all of the [compliance tests](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html) related to `NoReturn` and `Never`.

`NoReturn` can be used in the explicit specialization of a generic type (like `DType[NoReturn]`). I recommend using `Never` rather than `NoReturn` to improve readability. From a type checker's perspective, they refer to the same type. The `NoReturn` symbol makes more sense when used in a return type annotation.

`NoReturn` and `Never` represent the "bottom type" of the Python type system, and they are assignable to all other types.

In your example above, the class `DType` is parameterized by an invariant type variable, so `DType[Never]` is assignable only to `DType[Never]` and is not assignable to `DType[float16]`. If `DType` were parameterized by a covariant type variable, then `DType[Never]` would be assignable to `DType[float16]`.

**Comment by ViktorSky** [comment]
Thank you very much for the explanation
