### ISSUE TITLE
When subclassing an imported TypedDict mypy will raise an error on NotRequired

### ISSUE THREAD

**Issue by svleeuwen** [python/mypy#18012]
**Bug Report**

When subclassing an imported TypedDict mypy will raise: `error: NotRequired[] can be only used in a TypedDict definition  [valid-type]`

**To Reproduce**

```python
# foo.py
from typing import TypedDict

class Foo(TypedDict):
    id: str

# bar.py
from typing import NotRequired

from foo import Foo

class Bar(Foo):
    name: NotRequired[str]
```

This will raise: `error: NotRequired[] can be only used in a TypedDict definition  [valid-type]`

However, without importing, this will pass as expected.
```python
from typing import NotRequired, TypedDict

class Foo(TypedDict):
    id: str
    
class Bar(Foo):
    name: NotRequired[str]
```

So somehow importing it makes a difference.

**Your Environment**

- Mypy version used: 1.12.1
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files):
```
python_version = 3.12
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
```
- Python version used: 3.12.7

**Comment by brianschubert** [comment]
Hmm, I can't reproduce this issue using the two-file setup on master. 

I see you have `ignore_missing_imports = true` set in your config file---if you set that to `false`, do you get an error along the lines of  `error: Cannot find implementation or library stub for module named "foo"`? If so, then you're getting this error because mypy wasn't able to follow the import of `foo`, which caused `Foo` to be assumed to have type  `Any` (i.e. not a `TypedDict`). You can verify this by adding `reveal_type(Foo)` in the file that imports `Foo` and checking whether mypy outputs `Revealed type is "Any"` or something like `Revealed type is  "def (...) -> TypedDict('foo.Foo', ...)"`.  Try double checking that `foo` is somewhere that mypy can find it. These sections from the mypy docs may be of help: [Mapping file paths to modules](https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules) and [Missing imports](https://mypy.readthedocs.io/en/stable/running_mypy.html#fix-missing-imports).
