### ISSUE TITLE
Mypy exclude doesn't work as expected

### ISSUE THREAD

**Issue by artsiomkaltovich** [python/mypy#18284]
**Bug Report**

I want to exclude a folder from mypy checks, but it still inspect it.

mypy -v output:
```
LOG:  Mypy Version:           1.13.0
LOG:  Config File:            /Users/a_kaltovich/projects/mypy_doesnot_work/pyproject.toml
LOG:  Configured Executable:  /Users/a_kaltovich/projects/mypy_doesnot_work/.venv/bin/python
LOG:  Current Executable:     /Users/a_kaltovich/projects/mypy_doesnot_work/.venv/bin/python
LOG:  Cache Dir:              .mypy_cache
LOG:  Compiled:               True
LOG:  Exclude:                ['libs']
```

**To Reproduce**

 * please refer to this project https://github.com/artsiomkaltovich/mypy_exclude
 * `git clone git@github.com:artsiomkaltovich/mypy_exclude.git`
 * execute `mypy .`

**Expected Behavior**

libs folder is excluded

**Actual Behavior**

`libs/lib1/lib1.py:2: error: Incompatible return value type (got "int", expected "str")  [return-value]`

**Your Environment**

Refer to pyproject.toml file.

**Comment by brianschubert** [comment]
Hi! This is expected behavior. The `exclude` option controls how mypy discovers files to type check (you can think of it as refining the "entry points" for type checking). However it doesn't affect the way that the discovered files are type checked. In particular, it doesn't affect the way mypy follow imports. If any of the files being analyzed import a module from `libs`, then by default that module will be analyzed as well (along with any modules that it imports). You can refer to [Following Imports](https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports) from the mypy docs for more details on how this works and what configuration options are available.

If you want to suppress errors for modules from `libs`, you can try setting [`follow_imports`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-follow_imports) to `silent` for those modules:

```toml
[[tool.mypy.overrides]]
module = "libs.*"
follow_imports = "silent"
```
