### ISSUE TITLE
Importing a new file within a module using "from x import y" fails in incremental mode

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#1848]
Consider the following test case:

```python
[case testIncrementalFoo]
from parent import a

[file parent/__init__.py]

[file parent/a.py]

[file parent/a.py.next]
from parent import b

[file parent/b.py.next]

[stale parent.a, parent.b]
[out]
```

 It initially starts with two files (`parent/__init__.py` and `parent/a.py`) that are both empty, then runs `mypy -i -c "from parent import a"` to warm up the cache.

We then add a new empty file, `parent/b.py`, and change `parent/a.py` to contain the single line `from parent import b` and re-run `mypy -i -c "from parent import a"`.

The expected behavior is that mypy should typecheck the modified files without complaining, but will instead report the following error:

```
<string>:1: note: In module imported here:
parent/a.py:1: error: Module has no attribute 'b'
```

This error disappears when we change `parent/a.py` to contain either the line `import parent.b` or `import parent.b as b`, or if the file `parent/b.py` existed before mypy was first run.

**Comment by gvanrossum** [comment]
Good find! I suspect the key to this issue is the ambiguity inherent in
`from parent import b`. This can either import an attribute defined in
`parent/__init__.py` or a submodule `parent/b.py`. I expect that if you
make some dummy change to `__init__.py` to force it to change that will
also make the problem go away -- if that's so, the solution probably
involves throwing away the cache data for `parent/__init__.py` when a
module is added (or removed).

**Comment by Michael0x2a** [comment]
It seems like making the dummy change _does_ make the problem go away, as you predicted :)

I'll look into the caching logic next then.
