### ISSUE TITLE
Unfortunate clash of union, generic and multiple inheritance

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1873]
Behold:

``` python
from typing import Generic, TypeVar, Union

T = TypeVar('T')
S = TypeVar('S')

class A(Generic[T]): pass

class I(Generic[T]): pass

class F(A[str], I[str]): pass

class Loop:
    def run(self, future: Union[A[S], I[S]]) -> S: pass

loop = Loop()
f = F()
loop.run(f)  # Error (see below)
```

This gives the following error:

```
__tmp__.py:17: error: Argument 1 to "run" of "Loop" has incompatible type "F"; expected "Union[A[None], I[None]]"
```

I spent way too much time boiling it down to this. It must involve multiple inheritance from two generic classes and an instance whose type matches either variant of the union; if I reduce the example further (e.g. make A or I non-generic) the error goes away.

I don't understand why this is (and it's probably a duplicate) but it's holding up creating proper stubs for asyncio that incorporate Awaitable. (In the original, A is Awaitable, I is Iterable, F is Future, Loop is AbstractEventLoop.)

**Comment by JelleZijlstra** [comment]
I ran into this too, because `typing.AwaitableGenerator` is apparently affected by the bug. I commented on https://github.com/python/typeshed/pull/903 with some close-to-real affected code.

Here's what I reduced my example to (slightly smaller than Guido's; T is Generator, U is Awaitable, and V is AwaitableGenerator):
```
from typing import TypeVar, Union, Generic

_T = TypeVar('_T')

class T(Generic[_T]): pass
class U(Generic[_T]): pass
class V(T[_T], U[_T]): pass

def wait_for(fut: Union[T[_T], U[_T]]) -> None: ...

wait_for(V[bool]())
```

**Comment by JukkaL** [comment]
This is probably due to how constraints are inferred for unions. Here there are two ways we can infer constraints between `V[bool]` and `Union[T[_T], U[_T]]`, since `V` multiply inherits from `T` and `U`. In this case the constraints would be the same either way, so mypy should be able to infer them without problems. There actually is a TODO comment in `mypy.constraints.any_constraints` that discusses this problem, so I suspect that this is a known issue. I'll have a look at it.
