### ISSUE TITLE
Confusing error message when class definition duplicated across if-else

### ISSUE THREAD

**Issue by sangsta** [python/mypy#1874]
I have a block of code that looks like this:

```
if foo:
    class A(object):
        ...
else:
    class A(object):
        ...
```

mypy complains for the second class definition:

```
error: Name 'A' already defined
```

However, this is technically not true.

**Comment by gvanrossum** [comment]
Yeah, this is a common issue. There are plans to fix this but they haven't landed yet. For now, just put `# type: ignore` on the second class statement.

**Comment by gnprice** [comment]
It seems like there are (at least) two or three things that could be done here:
* We don't allow these, and in many cases it'd be helpful if we did. This is complicated to get right, though. This is covered in existing issues.
* The error message is confusingly worded, because at runtime the class is never "already" defined.
* The error message isn't specific about where the other definition is -- which, when the code isn't a tiny example program, leaves the user to wonder if the puzzling message is really referring to that other definition up in the `if` or to some other place where it really was "already" defined, if they've even spotted the previous definition yet.

I think fixing the last point would in itself mitigate the confusing wording a lot, because it'd be totally explicit what other definition the checker has in mind and the user can figure out that that might be a problem even when they're never duplicated at runtime. So if nothing else, we should add a `previously defined here` note on that error.

**Comment by JukkaL** [comment]
The message is now `Name 'A' already defined on line 2`, which partially addresses the issue. If this is still too confusing, we can reopen the issue.
