### ISSUE TITLE
[BLOCKER] Effect of '# type: ignore' became much more severe after '--warn-unused-ignores'

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1911]
It seems the introduction of `--warn-unused-ignores` in 4889c0c caused even valid imports to acquire the type `Any`.

**Comment by Michael0x2a** [comment]
It seems like there's some disagreement over the expected behavior of the first test case (testIgnoreImportBadModule) introduced by https://github.com/python/mypy/commit/d379a93c5d84e378f89165765480b4f55088633b -- if a module is marked as `# type: ignore`, it should only ignore errors if that module does not exist, and not if there's any error of any kind from within that module.
