### ISSUE TITLE
Some special attributes of functions are not supported

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#1923]
According to the section on Callables in https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy, user-defined functions have these attributes:
`__doc__`, `__name__`, `__qualname__`, `__module__`, `__defaults__`, `__code__`, `__globals__`, `__dict__`, `__closure__`, `__annotations__`, `__kwdefaults__`. Out of these, `__qualname__`, `__annotations__` and `__kwdefaults__` are not present in python 2.

Builtin functions have `__doc__`, `__name__` and `__module__`. In python 3, `__qualname__` is not documented to be supported but I checked `len` and it supports it.

mypy doesn't support `__defaults__`, `__globals__` and `__closure__` in both python 2 and 3. In python 2, it doesn't support `__code__` and `__dict__` and in python 3 it doesn't support `__annotations__` and `__kwdefaults__`.

**Comment by gvanrossum** [comment]
Since mypy doesn't distinguish between user-defined and built-in functions, I'm not sure supporting `__defaults__`, `__globals__` and `__closure__` is right -- these are useful for pretty extreme introspection only. Have you run into code that doesn't type-check because of this, and if so, can you point me to some real-world examples?

FWIW casting to types.FunctionType should do it, that seems to have all of these.

**Comment by sharmaeklavya2** [comment]
Here is one real-world example which uses `__code__`: https://github.com/zulip/zulip/blob/master/zerver/lib/cache.py#L251

**Comment by sharmaeklavya2** [comment]
I think we can use `func.__module__` instead of `func.__code__.co_filename` in the real-world example above.

**Comment by gvanrossum** [comment]
Right. Please close this issue if you are satisfied.

--Guido (mobile)

**Comment by leycec** [comment]
**Necrobump.** We just drunkenly stumbled into this with [beartype](https://github.com/beartype/beartype).

Superficially, casting to `types.FunctionType` *does* solve this specific issue – while introducing even more issues, because `types.FunctionType` isn't subscriptable:

```
>>> from types import FunctionType
>>> FunctionType[['Ugh!',], '*sigh*']
Traceback (most recent call last):
  File "<ipython-input-2-3e54a5e6057d>", line 1, in <module>
    FunctionType[[int,], int]
TypeError: 'type' object is not subscriptable
```

So you can either have dunder attributes guaranteed to be defined on pure-Python callables *or* you can have typing metadata, which is basically the whole point of typing. Clearly, no one sane is going to discard typing metadata, which means everyone sane is just going to tell mypy to `# type: ignore[attr-defined]`, which defeats the whole point of typing.

There's no win-win here. Honestly, the least awful solution would be for mypy to just permissively accept attempts to access pure-Python callable dunder attributes. In short, I wish mypy also accepted a `--lax` option doing the exact opposite of `--strict`: relaxing assumptions that mostly don't matter anyway to just get mypy to accept code that almost certainly works anyway. `</shrug>`

**Comment by gvanrossum** [comment]
Bear type is unbearably annoying. Go away.
