### ISSUE TITLE
Unable to check method of same name of return type

### ISSUE THREAD

**Issue by tharvik** [python/mypy#2010]
```python
def str() -> str: ...
```
gives
```
/tmp/asd.py: note: In function "str":
/tmp/asd.py:1: error: Invalid type "asd2.str"
```

IMO, function definition shouldn't become types at all.

It was found when typing [`locale.str`](https://docs.python.org/3/library/locale.html#locale.str).

**Comment by gvanrossum** [comment]
Well, this is tricky. In general when you say `def foo(arg: X)` then X is looked up in the current scope. So if the current scope defines X to be something else, mypy would have to understand that there are two definitions of X, or it would have to split the scope in two based on where the override definition of X occurs. Note that in your PR for locale, there were some references to `str` as a type *after* the definition of `str` as a function. At the very least those references would have to be understood to reference the function.

**Comment by tharvik** [comment]
Isn't it easier to just not caring about function defining new types? Here, clearly, `def str` should do nothing to the stubs, it is just a name definition and not a type definition.

Having
```python
def a() -> None: ...
def b() -> a: ...
```
wouldn't make any sense, right?

**Comment by rwbarton** [comment]
mypy currently has just one namespace shared by values and types. This makes a certain amount of sense for Python since `class C: ...` actually creates a value named `C` in Python's runtime semantics. So, in mypy's view, if you assign anything to the name `str` (including via a function definition), `str` henceforth refers to that new thing, and no longer refers to the type `builtins.str`.

It may actually be sensible to introduce separate value and type namespaces, but it would need to be done carefully because of things like `isinstance`, `cast` and type synonym definitions. There also may be advantages to keeping the single namespace (e.g. if mypy grows new type system features in which types can refer to values).

**Comment by gvanrossum** [comment]
It might seem easier to you, but it's not easier for mypy's implementation. We don't really want to have to maintain two namespaces, one for types and one for (e.g.) functions.

**Comment by tharvik** [comment]
Hum, I see, I tought I wouldn't require much work.

As having a workaround working such as the one in [typeshed#462](https://github.com/python/typeshed/pull/462), it guess is pretty low priority.

**Comment by gnprice** [comment]
Agreed with the conclusions of the discussion -- I think we won't want to do this unless a different kind of use case arises. Thanks for raising this!
