### ISSUE TITLE
Error when referencing a class within its __init__ method

### ISSUE THREAD

**Issue by shreydesai** [python/mypy#2020]
I have a class called `Node` which represents a general node for a linked list. As defined, a node has two attributes: the node's data and a memory reference to the following node.

```python
from typing import TypeVar, Generic

T = TypeVar('T')

class Node(Generic[T]):
  def __init__(self, data: T, next: Node[T]) -> None:
    self.data = data
    self.next = next
```

When I run this module with the mypy checker (`mypy node.py`), it has no issue with this. However, `python3 node.py` yields the following error: `NameError: name 'Node' is not defined`.

I tried changing `next: Node[T]` to `next: object`, but that generated a mypy error (`error: Incompatible types in assignment (expression has type "object", variable has type Node[Any])`). 

How do I reconcile the differences in behavior when running this module with `python3` and `mypy` while also maintaining the structure of this class?

**Comment by Michael0x2a** [comment]
What's happening here is that when the Python interpreter hits the `__init__` method, the `Node` class is still in the process of being defined, and so `Node` hasn't been bound to the environment yet. This explains why Python claims `Node[T]`  isn't defined.

The workaround is to use [forward references](http://mypy.readthedocs.io/en/latest/common_issues.html?highlight=forward#import-cycles) and write `Node[T]` as a string, which mypy will also understand:

```python
from typing import TypeVar, Generic

T = TypeVar('T')

class Node(Generic[T]):
  def __init__(self, data: T, next: 'Node[T]') -> None:
    self.data = data
    self.next = next
```

This will make your code work nicely with both mypy and Python.

That said, it would probably be a good idea for mypy to at least warn about this in some way, since it seems to be a common tripup. I found a pre-existing issue for it [here](https://github.com/python/mypy/issues/1025), but it doesn't seem like anybody has started working on this yet.

**Comment by gvanrossum** [comment]
(Since this question was answered and there's no bug here, shouldn't we just close it?)
