### ISSUE TITLE
Simplest list assignment fails

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2023]
Adding the following test crashes:

    [case testListSimplest]
    a = [1]

Results

      ...
      File ".../mypy/mypy/checker.py", line 2238, in lookup_qualified
        return n.names[parts[-1]]
    KeyError: 'list'

**Comment by Michael0x2a** [comment]
This is due to a quirk of mypy's test framework. To speed up the tests and make debugging easier, what mypy's test framework will do is load up a very limited subset of Python's builtins, which, incidentally, doesn't lists.

To fix this, you can include one of the "builtins extension" files in `test-data/unit/fixtures` to augment the builtins by doing:

    [case testListSimplest]
    a = [1]
    [builtins fixtures/list.py]

You can see examples of test cases doing this inside the `check-list.text` file. But yeah, it's not a perfect system and can be pretty confusing to debug the first time around -- for more context about this system/suggestions people have made, see https://github.com/python/mypy/issues/890 and https://github.com/python/mypy/issues/1675.
