### ISSUE TITLE
default argument for generic function

### ISSUE THREAD

**Issue by naphatkrit** [python/mypy#2078]
I'm trying to do something like this:

```
T = TypeVar('T')

def identity(string):
  # type: (str) -> str
  return string

def f(normalize=identity):
  # type: (Callable[[str], T] -> str)
```

But mypy says this does not type-check. After adding a cast (`normalize=cast(Any, identity)`, or even `normalize=cast(Callable[[str], T], identity)`, this works fine.

**Comment by rwbarton** [comment]
This is intentional, as the caller of `f` gets to choose `T` and `identity` does not have type `Callable[[str], T]` for most types `T`. Also see the discussion at #1721.

Have you simplified the type of your real function `f`? It's hard to see how you could use `normalize` with this signature for `f` anyways.
