### ISSUE TITLE
Spurious "Directory not empty" error

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2080]
Running `./runtests.py` from bash on ubuntu on windows, I get a spurious `OSError: [Errno 39] Directory not empty` error. It happens even when I remove existing directories before running the test. The error does not happen in the Travis CI build.

Full traceback:
```
FAILURE  #1 run cmdline-test

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/.../mypy/mypy/myunit/__main__.py", line 18, in <module>
    main()
  File "/mnt/c/.../linux/mypy/mypy/myunit/__init__.py", line 230, in main
    num_total, num_fail, num_skip = run_test_recursive(t, 0, 0, 0, '', 0)
  File "/mnt/c/.../linux/mypy/mypy/myunit/__init__.py", line 279, in run_test_recursive
    stest, num_total, num_fail, num_skip, new_prefix, depth + 1)
  File "/mnt/c/.../linux/mypy/mypy/myunit/__init__.py", line 279, in run_test_recursive
    stest, num_total, num_fail, num_skip, new_prefix, depth + 1)
  File "/mnt/c/.../linux/mypy/mypy/myunit/__init__.py", line 260, in run_test_recursive
    is_fail, is_skip = run_single_test(name, test)
  File "/mnt/c/.../linux/mypy/mypy/myunit/__init__.py", line 297, in run_single_test
    test.tear_down()  # FIX: check exceptions
  File "/mnt/c/.../linux/mypy/mypy/test/data.py", line 218, in tear_down
    super().tear_down()
  File "/mnt/c/.../linux/mypy/mypy/myunit/__init__.py", line 133, in tear_down
    self.tmpdir.cleanup()
  File "/usr/lib/python3.4/tempfile.py", line 828, in cleanup
    _rmtree(self.name)
  File "/usr/lib/python3.4/shutil.py", line 468, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.4/shutil.py", line 466, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/mnt/c/.../workspace/linux/mypy/tmp-test-dirs/mypy-test-n58pqsd_'
```

**Comment by Michael0x2a** [comment]
I remember running into this issue before -- as far as I can tell, what's probably happening is that there's some sort of process that's attempting to index your repo files, which will momentarily cause directories to not be empty/to be prevented from being deleted. 

So, this might be some sort of antivirus software or your repo might be running in something like a Dropbox folder (which is somewhat ironic) or you might have Windows explorer open to the directories the test suite is trying to delete.

I don't think this has anything to do with Ubuntu on Windows in particular, since I remember seeing this just on regular Windows using Powershell.

The (partial?) fix that I found was to tweak the tests slightly so they retry deleting a directory after a short delay if it fails the first time on Windows. I vaguely remember running into other issues that distracted me from forming together a pull request with this fix, but maybe you can give it a try and see if it helps?

**Comment by elazarg** [comment]
Once it happens it reproduces until I `rm -r` everything there. Until next time.

**Comment by gvanrossum** [comment]
A virus checker could cause this.

**Comment by elazarg** [comment]
I don't have anything that doesn't come with Windows 10.

**Comment by elazarg** [comment]
Is there a chance that it's related to the explicit `.close()` [here](https://github.com/python/mypy/blob/master/mypy/test/data.py#L61-L68), [here](https://github.com/python/mypy/blob/master/mypy/test/data.py#L159-L161) or [here](https://github.com/python/mypy/blob/master/mypy/test/data.py#L332-L334)? It doesn't occur only when there are exceptions, but perhaps it was caused by previous ctrl+break. What is the reason not to use `with` statements?

(I can't directly test it since the error is not deterministic).

**Comment by gvanrossum** [comment]
Feel free to submit PRs that replace those open/close pairs with `with
open(...) as f` blocks.

**Comment by elazarg** [comment]
I am not sure this was really solved by #2140, but it didn't happen since then.

**Comment by gvanrossum** [comment]
"didn't" -> "hasn't".

**Comment by elazarg** [comment]
<*blushing*>
