### ISSUE TITLE
Not installable with Python3.5?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [python/mypy#2085]
Is there no Python 3.5 version of mypy?!

https://gist.github.com/anonymous/60653e377ef8ca0bbe129c8d7cf41c41

**Comment by jdelic** [comment]
@Unrepentant-Atheist From your Gist:

```
ImportError: Python 3.5 is not supported by DBUtils.
                                               ^^ see this?
```

The line 

```
Collecting dbutils (from sqlbean>=0.490->mypy)
```

must be a bug in pip reporting. `mypy` does not even have a `requirements=` line in `setup.py`, it certainly does not depend on `dbutils`.

**Comment by Unrepentant-Atheist** [comment]
So...what am I supposed to do now?

**Comment by jdelic** [comment]
@Unrepentant-Atheist 

Quick googling shows that DBUtils 1.1 was released in 2006 and the website (company?) that created it (webwareforpython) is defunct. Looking at it's `setup.py`:

```
cd /tmp
pip download DBUtils==1.1
tar xfz DBUtils-1.1.tar.gz
cat DBUtils-1.1/setup.py
```

shows

```python
py_version = version_info[:2]
if not (2, 3) <= py_version < (3, 0):
    raise ImportError('Python %d.%d is not supported by DBUtils.' % py_version)
```

So the error message is kind of wrong, because DBUtils only supports Python 2.x. By extension `sqlbean` (which also seems to be fairly unsupported) also only supports Python 2.x since it depends on DBUtils.

> So...what am I supposed to do now?

Use Python 2.7 and move on to different software in the future when you can is your best bet, I guess.

I'm also an idiot, because I didn't realize that the original dependency lists `mypy`. This repository is distributed on pypi as `mypy-lang` because of a naming conflict with the package you're looking for which is the [mypy wsgi framework](https://pypi.python.org/pypi/mypy/0.236).

**Comment by Unrepentant-Atheist** [comment]
Oh well, no mypy for me I guess. =( Too bad, I like static typing and wanted to integrate it into my Atom and SublimeText IDEs.

**Comment by jdelic** [comment]
> Oh well, no mypy for me I guess. =( Too bad, I like static typing and wanted to integrate it into my Atom and SublimeText IDEs.

Oh, now I get it. Sorry, I thought you wanted `sqlbean` and landed **here by accident**. Instead you want mypy. I can solve this problem quickly:

`pip install mypy-lang`.

:laughing:

**Comment by ddfisher** [comment]
Yet another `mypy-lang` casualty. :(
