### ISSUE TITLE
If expression doesn't have the same type as an equivalent if/else block

### ISSUE THREAD

**Issue by berdario** [python/mypy#2104]
``` python
def f() -> Union[str, bytes]:
    if randint(0,1):
        return b'bytes'
    else:
        return 'string'
```

This type checks

``` python
def f() -> Union[str, bytes]:
    return b'bytes' if randint(0,1) else 'string'
```

This doesn't

**Comment by JukkaL** [comment]
Yeah, this is unfortunate. The reason is that mypy doesn't infer union types very aggressively. A potential fix is to infer a union type for an if expression if the context is a union type, but this is pretty ad hoc.

**Comment by elazarg** [comment]
@JukkaL Why doesn't join always yield a `Union`? It's always sound, more precise, and there's a finite number of types involved in any expression. Alternatively, it can widen if it has, say, 10 items.

It will also give useful information to the programmer. Instead of figuring out why `x` is of type `object`, she can see that it's `Union[str, int]` so there's an `int` involved somewhere.

**Comment by berdario** [comment]
It seems that this has been fixed in the past
