### ISSUE TITLE
Misleading error message for multiple defined function

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#214]
Consider this code:

    def f() -> int: return 1
    def f() -> int: return 2

The type checker gives this type error:

    t.py, line 2: Name 'f' already defined (overload variants 
    must be next to each other)

This is misleading, since the functions are next to each other and this is not a case of overloading but redefinition.

**Comment by thomasballinger** [comment]
This is what Elm does:
Detected errors in 1 module.
~~~
-- DUPLICATE DEFINITION --------------------------------------------------------

Naming multiple top-level values `foo` makes things ambiguous. When you say
`foo` which one do you want?

10| foo =
    ^^^
Find all the top-level values named `foo` and do some renaming. Make sure the
names are distinct!
~~~

**Comment by gvanrossum** [comment]
The desired message is `Name 'f' already defined` or possibly something including the line number of the previous definition.

**Comment by thomasballinger** [comment]
It looks to me like this error message is never actually used for multiply defined functions (because those don't exist in user code) or for overloads being out of order (I get different bad errors when I try that), so all there is to this issue is changing the message. I'm not familiar with the project at all though, can anyone confirm?

**Comment by gvanrossum** [comment]
My theory is now that the part about overload in the error message is a relic from long ago when the `@overload` decorator did not exist.
