### ISSUE TITLE
Nested functions don't take type restrictions into account

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2145]
Example:
```python
from typing import *

def f(a: Union[int, str]) -> int:
    if isinstance(a, str):
        return -1
    def inner() -> int:
        return a+1  # E: Unsupported operand types for + ("Union[int, str]" and "int"
    return inner()
```
Note that when inner() is defined, and also when it's called, a can only be an int. But we still get an error.

I ran into this when checking some real-world code against strict optional -- there the union was Optional[int] and the type restriction was `if a is not None`, but it's the same problem.

**Comment by ddfisher** [comment]
I think this is quite difficult to do correctly.  This is correct because `f` exits before `inner` is defined, but wouldn't be correct for other local information about types.  For example:
```py
from typing import *

def f(a: Union[int, str]) -> int:
    if isinstance(a, str):
        return -1
    else:
        def inner() -> int:
            return a+1  # E: Unsupported operand types for + ("Union[int, str]" and "int"
    a = "foo"
    return inner()
```
The binder doesn't keep track of this information at the moment -- I'm not sure how hard it would be to add, but probably not super easy.

**Comment by gvanrossum** [comment]
I see. I'm fine with closing this then.
