### ISSUE TITLE
Selected Typeshed stubs for the wrong version

### ISSUE THREAD

**Issue by berdario** [python/mypy#2153]
From my understanding, 2and3 stubs should be ovverriden by 3, which should be overriden by 3.5 (assuming 3.5)

After updating to Mypy 0.4.4 (from 0.4.1) though I get a new spurious error:

    No overload variant of "itemgetter" matches argument types [builtins.str]

The code for itemgetter here seems correct:

https://github.com/python/typeshed/blob/master/stdlib/3/_operator.pyi

But here instead it's picking up

     def itemgetter(item: int)

https://github.com/python/typeshed/blob/master/stdlib/2and3/operator.pyi

Why is the code from 2and3 used, instead of the more specific one?

**Comment by gvanrossum** [comment]
Presumably because these are two different modules -- `_operator` is the builtin one, and `operator` is the public one. So neither is overriding the other. OTOH I suspect `_operator` should be deleted since everybody should be using the public one.

I haven't found time to look more into which definition of `itemgetter` is more correct. Can you cook up a little example demonstrating the error you are getting?

**Comment by gvanrossum** [comment]
Oh, also, this is in any case an issue for https://github.com/python/typeshed/issues, not for mypy.

**Comment by berdario** [comment]
Oh, I assumed that since a module like `operator` usually imports `_operator`, that mypy would've had some machinery to include that...

Thank you, unfortunately I was a bit in a hurry (otherwise I'd have changed the `pyi` on my own), but I reopened this in the typeshed project
