### ISSUE TITLE
runtests.py -jN doesn't control pytest parallelism

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#2226]
When I run `runtests.py -j2` the pytest tests still use all my processors, which defeats my purpose of using `-j2` (to keep my browser responsive). The pytest parallelism should be limited also. (But it looks like the entire pytest run counts as only one job in the test runner? so it's not so clear exactly what the limit should be.)

**Comment by rwbarton** [comment]
`PYTEST_ADDOPTS='-n 2'` serves as a workaround.

**Comment by gnprice** [comment]
Thanks for surfacing this!

I think a simple workaround like having `runtests.py` unconditionally pass `-n2` would be good.

The root issue is that we have this hybrid of `runtests.py` and `pytest` -- which is because we haven't finished the migration to `pytest` that we started. I do think that each test file converted to `pytest` is an improvement in itself, even before the migration is complete; it'd be good to take it further forward.

**Comment by elazarg** [comment]
I think this has been fixed - `-j` passes `-n` parameter to pytest, and all the data-driven tests have been migrated to pytest.

**Comment by gvanrossum** [comment]
Yeah I think this requires no further action.
