### ISSUE TITLE
Assigning theoretically conflicting functions confuses mypy

### ISSUE THREAD

**Issue by viraptor** [python/mypy#2248]
The following code triggers mypy errors:
```
_ord = ord if str is bytes else lambda x: x

def f(s):
    # type: (bytes) -> List[int]
    return [_ord(c) for c in s]
```
One is about `_ord`: `"function" not callable`

Another is about _ord itself: `Incompatible return value type (got "Union[str, bytes, bytearray]", expected "int")`

These may be 2 different issues actually, but I expected the following to happen. a) Based on the `--py2` flag, only one of the branches is considered and the type is obvious. b) Mypy should then know `_ord` is a callable function.

It seems like it already happens if `_ord` is written like this:
```
def _ord(x):
    if str is bytes:
        return ord(x)
    else:
        return x
```
Specifically there's no error about unknown `ord` in this case in py3 mode and no error about `return x` in py2 mode.

**Comment by viraptor** [comment]
There's also no error in:
```
if str is bytes:
    def _ord(x):
        return ord(x)
else:
    def _ord(x):
        return x
```
so it looks like the ternary expression is introducing the problem.

**Comment by kirbyfan64** [comment]
@viraptor You've got it a bit backwards. Mypy never evaluates any expressions like `str is bytes`. The latter isn't any different:

```python
if str is bytes:
    x = 1  # type: int
else:
    x = 1  # type: int
```

gives:

```
x.py:4: error: Name 'x' already defined
```

The `str is bytes` check has nothing to do with the original issue; this:

```python
_ord = ord if False else lambda x: x

def f(s):
    # type: (bytes) -> List[int]
    return [_ord(c) for c in s]
```

still errors. In fact, Python 2 mode doesn't even have anything to do with it. Here's a smaller test case:

```python
from typing import *

_ord = ord if False else lambda x: x

def f() -> Any:
    return _ord(0)
```

**Comment by rwbarton** [comment]
Functions without type annotations are given types like `Callable[[Any], Any]`. So in your examples with `def _ord(x):`, there is no problem (and also no type checking).

**Comment by kirbyfan64** [comment]
Here's the smallest I can reduce it thus far:

```python
class A: pass
def a(s: A) -> int: pass
b = a if False else lambda x: x
b()
```

**Comment by rwbarton** [comment]
But the definition of `b` is wrong. What type is it supposed to have?

**Comment by kirbyfan64** [comment]
So, I think this is two separate issues. One is that items of type `builtins.function` aren't seen as callable by mypy:

```python
a = None  # type: function
a()  # error: "function" not callable
```

This should probably be like calling a function `Callable[[...], Any]`.

The other still escapes me:

```python
class A: pass
def a(s: A) -> int: pass
b = a or lambda x: x  # error: Incompatible return value type (got "A", expected "int")
```

Since when is `A` a return type? :O

@rwbarton `reveal_type` says that `b` is of type `builtins.function`.

**Comment by kirbyfan64** [comment]
Oh, I just figured out the second one.

```python
class A: pass
def a(s: A) -> int: pass
b = a or lambda x: x
```

Since `a` is of the type `Callable[[A], int]`, mypy uses that as the type for the lambda. Except the lambda is returning the argument which mypy now thinks is of type `A`!

This one arguable isn't a bug, though it is rather surprising. Maybe a note about how the lambda's type was inferred would help out...

**Comment by rwbarton** [comment]
Right (and `error: "function" not callable` is my favorite nonsense mypy error) but what type do you, the programmer, intend for `b` to have? How do you intend to use `b` in a real program? (Your example 'b()` is surely wrong, whichever value `b` has.)

The original `_ord` has the same problem. It seems to me that mypy is doing the correct thing here.

**Comment by kirbyfan64** [comment]
@rwbarton Well, I would argue that, if this *is* intentional, then mypy shouldn't set the fallback type on function inference to `builtins.function`. And maybe the error message could stand to be improved a bit...

**Comment by rwbarton** [comment]
Well `a` and `lambda x: x` are both functions, so you can use methods of the class `function` on `b` (if indeed there are any...) So `function` is a correct type to give `b`.

The wording of the error message `"function" not callable` is certainly unfortunate. Maybe we should have a special case for this situation like `cannot call function of unknown type`.

**Comment by kirbyfan64** [comment]
@rwbarton Why not just assume it's like `Callable[[Any, ...], Any]`?

**Comment by viraptor** [comment]
I agree with @kirbyfan64 that the error message should be improved at least. Essentially it neither explains what the issue is, nor helps me come up with a solution. (apart from "error occured, fuzz the source and retry") Adding the name/expression that was called would be helpful too. (what if there are multiple calls on one line?)

I assumed that the lambda would be typed `Any -> Any` since you can't do generics (`T->T`) with this typing. So _ord would be something like `Union[Any,int] -> Union[Any,int]`. Is that unreasonable?

**Comment by rwbarton** [comment]
mypy tries not to introduce `Any` on its own (except in the type of unannotated functions; and this already causes plenty of confusion). Here mypy will try to make the lambda have the same type as the other argument to the conditional expression. If that argument had a type like `A -> A` for some `A`, this would succeed. If there wasn't any context from which to guess the type of the lambda, mypy would ask for a type annotation.

Introducing `Any` is bad because it silently disables type checking, which means we fail to reject bad programs. The definition of `_ord` could be an error, and the uses of `_ord` could be erroneous; we'll miss those errors if we silently give `_ord` type `Any -> Any`.

If you *want* to give `_ord` type `Any -> Any`, then just use a type annotation on `_ord`.

**Comment by JukkaL** [comment]
At least improving the error message would be a no-brainer. Perhaps mypy could even have a heuristic for detecting such tricky conditional function definitions and give a message such as `Need type annotation for "b" -- callable type is ambiguous`.

**Comment by gvanrossum** [comment]
Let's say we should improve the error message. Anyone up for doing that?

**Comment by rwbarton** [comment]
Suggested improvement in #2296.

**Comment by gvanrossum** [comment]
OK, merged that.
