### ISSUE TITLE
Error when checking exception classes

### ISSUE THREAD

**Issue by squiddy** [python/mypy#2256]
mypy 0.4.5, CPython 3.4.4

**Works fine**

``` python
classes = (RuntimeError, )
reveal_type(classes) # Revealed type is 'Tuple[def (*args: Any) -> builtins.RuntimeError]'

try:
    pass
except classes as e:
    pass
```

**Doesn't work**

``` python
classes = tuple([RuntimeError])
reveal_type(classes) # Revealed type is 'builtins.tuple[def (*args: Any) -> builtins.RuntimeError]'

try:
    pass
except classes as e: # error: Exception type must be derived from BaseException
    pass
```

Note how the revealed types are similar (`Tuple` vs. `builtins.tuple`) and the elements are the same.

**Comment by gvanrossum** [comment]
Hm... Looks like a pretty simple fix in visit_except_handler_test() in mypy/checker.py. Maybe you'd like to try to contribute a PR?

**Comment by squiddy** [comment]
I'll give it a try. :)

**Comment by rwbarton** [comment]
I'm guessing this is a reduced test case from a program in which you didn't really write `tuple([RuntimeError])`, so it might be worth giving some thought first to whether your potential fix will fix the issue with your actual program.

**Comment by squiddy** [comment]
@rwbarton Good point. The code in question is not mine, but I asked and essentially that's really it. They define a global list of various exceptions that need to be handled differently, and pass them to the except handler.

**Comment by rwbarton** [comment]
So the real program probably looks like this:
```
class A(Exception): pass
class B(Exception): pass

exc_types = [A, B]
reveal_type(exc_types) # E: Revealed type is 'builtins.list[builtins.type*]'
exc_tuple = tuple(exc_types)
reveal_type(exc_tuple) # E: Revealed type is 'builtins.tuple[builtins.type*]'

try:
    pass
except exc_tuple as e: # E: Exception type must be derived from BaseException
    reveal_type(e) # E: Revealed type is 'Any'
```

But `tuple[type]` is not really specific enough, since the tuple could contain any types, not just those which derive from BaseException. Seems like you ought to write something like
```
exc_types = [A, B] # type: List[Type[Exception]]
```

**Comment by squiddy** [comment]
You've lost me there, sorry. I understand how your example is likely a more accurate representation of the program, and what is going on there, but what am I to do with that?

Are you suggesting to add that type hint to the original program? `(RuntimeError, )` works fine, shouldn't `tuple([RuntimeError])` or `tuple(a_list_of_exception_classes)` work as well?

I have a local fix that seems to be working, however the test is still giving me headaches. :)

**Comment by rwbarton** [comment]
What's the type of `a_list_of_exception_classes`?

**Comment by rwbarton** [comment]
Concretely, I'm guessing that your change either fails to accept the `try/except` in my example program, or it fails to reject the `try/except` if you add `int` to the list `exc_types`.

`tuple[T]` is a homogenous collection, like `List[T]`. The fact that you got `tuple[T]` instead of `Tuple[T]` in your original program is a result of the special situation of having just one element of the tuple. Once you pass through a list, you lose specific information about the types of individual elements of the list. For example `tuple([1, 'a'])` doesn't have type `Tuple[int, str]`, but just `tuple[object]`.

`Type[BaseException]` is the type for class objects that are subtypes of `BaseException`, so that seems like the appropriate thing to check for in an `except` clause.

**Comment by squiddy** [comment]
Thank you for taking the time to explain it, I really appreciate that. Still trying to get my head around this project. I now see what you mean:

```python
x = [KeyError]
reveal_type(x) # Revealed type is 'builtins.list[def (*args: Any) -> builtins.KeyError]'
y = [KeyError, ValueError]
reveal_type(y) # Revealed type is 'builtins.list[builtins.type*]'

z = (KeyError, ValueError)
reveal_type(z) # Revealed type is 'Tuple[def (*args: Any) -> builtins.KeyError, def (*args: Any) -> builtins.ValueError]'
```

If I understand `visit_except_handler_test` correctly, it goes through all the types in the expression of the except handler, and checks if they are subtypes `self.named_type('builtins.BaseException')` (which I suppose is `Type[BaseException]`).

That leaves me wondering, if I'm losing type information in the expression `[KeyError, ValueError]` already,  there is not much I can do later on, or can I?

Instead, inferring the type of `[KeyError, ValueError]` should be improved if possible. In that case, that could be `List[BaseException]`, right?

**Comment by gvanrossum** [comment]
@rwbarton, would it be sound if `[C1, C2]` (where the elements are all classes) were to look for a common base class and use that as the item type? This is already happening for `[C1(), C2()]`, but I guess that code was never updated for `Type[]`, so it falls back to `type` instead.

**Comment by rwbarton** [comment]
@squiddy You've almost got it, except `[KeyError, ValueError]` is not a `List[BaseException]`. `List[BaseException]` is the type of a list of *instances* of `BaseException`. But `KeyError` is the class itself, not an instance. That's what `Type[C]` is for: see https://mypy.readthedocs.io/en/latest/kinds_of_types.html#the-type-of-class-objects

@gvanrossum Yes, we should just infer `List[Type[Base]]` automatically in this case. In fact, it already happens for `Type[C]` things:
```
from typing import Type

class A: pass
class B(A): pass
class C(A): pass

b = B # type: Type[B]
c = C # type: Type[C]
reveal_type([b, c])  # Revealed type is 'builtins.list[Type[typec.A]]'
```
But without the type annotations on `b` and `c` mypy doesn't figure out to do this, because the type of `B` itself is actually a Callable `def () -> typec.B`, not `Type[B]`. So it'd definitely be an improvement to have mypy do it automatically.

**Comment by gvanrossum** [comment]
Agreed. I removed the difficulty/easy label because nothing around this stuff ever ends up being easy (not for me anyways -- maybe for you or Jukka :-).

**Comment by ethanhs** [comment]
The "Doesn't work" currently works as expected on 0.521, so I am closing this, as I believe the issue has been resolved.
