### ISSUE TITLE
None passed to Generic gets turned into void

### ISSUE THREAD

**Issue by refi64** [python/mypy#2312]
``` python
from typing import *

T = TypeVar('T')

class G(Generic[T]):
    thing: T

x: G[None] = G()
reveal_type(x.thing) # Revealed type is 'void'; should probably be 'None'
```

**Comment by kirbyfan64** [comment]
@ddfisher This actually only happens when `strict-optional` is *not* enabled.

**Comment by gvanrossum** [comment]
The label David just added means that this problem is either fixed by turning on `--strict-optional` or should be fixed (by a separate patch) once `--strict-optional` becomes the default (or the One True Way). In this case it's the former, so we consider it a legacy bug that we don't really care about.

**Comment by gvanrossum** [comment]
What does this say with '--strict-optional'?

--Guido (mobile)

**Comment by kirbyfan64** [comment]
@gvanrossum It correctly says `None`.

**Comment by gvanrossum** [comment]
OK, then I don't think we need to fix this.

**Comment by ilevkivskyi** [comment]
There is no such thing as `void` anymore, so this is no more relevant.
