### ISSUE TITLE
Bug when running mypy on a sigle file (with per-file settings in the config)

### ISSUE THREAD

**Issue by megapctr** [python/mypy#2345]
The use case: I don't want to type-check tests and other misc files. I'm using vim with the syntastic plugin, which runs mypy on a file affter saving it.

This is my mypy config
```
$ cat mypy.ini 
[mypy]
silent_imports = True

[mypy-module/*]
silent_imports = False
```

This is my code
```
$ cat module/base.py 
class Config:
    pass
```
```
$ cat module/feature.py 
from module.base import Config


def do_things() -> None:
    use_config(False)  # error


def use_config(config: Config) -> None:
    return
```

Running mypy on the module directory works as expected
```
$ mypy module
module/feature.py: note: In function "do_things":
module/feature.py:5: error: Argument 1 to "use_config" has incompatible type "bool"; expected "Config"
```

Running mypy on a single file (that's how syntastic uses mypy) reports no errors
```
$ mypy module/feature.py
(no errors)
```
```

**Comment by gvanrossum** [comment]
Yes, I can repro this. Note that the example also needs an emty `module/__init__.py`. I'll look into it.

**Comment by gvanrossum** [comment]
Wow, you've uncovered a serious flaw in the design of pattern matching in mypy.ini files. The match is on the filename, but this is problematic for several reasons: in some cases the filename is turned into its full path (e.g. /home/guido/src/mypy/mypy/main.py instead of mypy/main.py) and in your case no path at all is present at the point in the code where mypy matches patterns against the path.

What I'll do is change the meaning of patterns to refer to module ids (e.g. `module.base`) rather than filenames. That's better all around (the path matching also doesn't work well on Windows...).
