### ISSUE TITLE
Branch not checked with `--strict-optional`

### ISSUE THREAD

**Issue by valtron** [python/mypy#2447]
```python
def f(x) -> None:
	if x is None: 1+''
```

`mypy --strict-optional` gives no errors. Seems to assume `x is not None` and doesn't bother checking the body of the `if`.

Without `--strict-optional` it works as expected and checks the entire function.

**Comment by gvanrossum** [comment]
Can even be simplified to:
```python
def f(y: Any) -> None:
	if y is None:
             1 + ''
```

**Comment by rwbarton** [comment]
The problem is here: https://github.com/python/mypy/blob/master/mypy/meet.py#L108. `is_overlapping_types` thinks `NoneTyp` does not overlap with `Any` which is why the branch is not checked.

The comment says "NoneTyp does not overlap with other non-Union types under strict Optional checking". But it should overlap at least with `Any`, and presumably `object` too:
```py
def h(x: object) -> None:
    if x is None:
        reveal_type(x)
```
is also considered an unreachable branch. (With a more specific type like `x: int`, it's correct that the branch be considered unreachable.)

It looks like this logic was added to handle overloading. Maybe @ddfisher remembers the situation here? I think `NoneTyp` just needs to be considered overlapping `Any` and `object`, but not 100% sure.

**Comment by ilevkivskyi** [comment]
All the examples in this issue work correctly on master.
