### ISSUE TITLE
frozenset is not compatible with FrozenSet

### ISSUE THREAD

**Issue by jboning** [python/mypy#2514]
```
from typing import FrozenSet

def f(fs):
    # type: (FrozenSet[str]) -> None
    fs = frozenset(['a'])
```
results in
```
frozenset.py: note: In function "f":
frozenset.py:5: error: Incompatible types in assignment (expression has type frozenset[str], variable has type FrozenSet[str])
```

**Comment by jboning** [comment]
I wasn't sure whether this should be here or on the typing repo; let me know if I should refile over there.

**Comment by gvanrossum** [comment]
Good catch! Seems to be a typeshed issue; basically changing the
definitions of class frozenset there to inherit from FrozenSet instead of
from AbstractSet might do it. If you feel like trying your hand at your
first typeshed PR, you can just submit that without first creating a new
issue there; if not, please at least file a typeshed issue.

**Comment by jboning** [comment]
Closing this out in favor of the typeshed PR. Thanks for the pointer!
