### ISSUE TITLE
Non-existing file of form a.b.py triggers assert '.' not in mod

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2558]
Repro:
```
mypy a.b.py
```
Regardless of whether `a.b.py` exists or not this gives
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/guido/src/mypy/mypy/__main__.py", line 5, in <module>
    main(None)
  File "/Users/guido/src/mypy/mypy/main.py", line 38, in main
    sources, options = process_options(sys.argv[1:])
  File "/Users/guido/src/mypy/mypy/main.py", line 364, in process_options
    targets.append(BuildSource(f, crawl_up(f)[1], None))
  File "/Users/guido/src/mypy/mypy/main.py", line 429, in crawl_up
    assert '.' not in mod
AssertionError
```

**Comment by Gazzini** [comment]
Run `mypy a/b.py` instead.

When specifying a file path from the command line, you should use the actual path of the file. This seems like reasonable, not-buggy behavior. I don't think that directory names usually allow for `.`s, and that is sort-of what the error is saying (although it _could_ be a little more clear).

For the record, I arrived here because I was doing the same thing :smile:

**Comment by vors** [comment]
@Gazzini I believe Guido is talking about a file with a name `a.b.py`, not file `b.py` in folder `a` which would correspond to `import a.b` in python.

**Comment by Gazzini** [comment]
Ah, makes sense. IMO, a good solution would be to rename the file without a "." Character. Maybe use an underscore or something.

**Comment by gvanrossum** [comment]
The point is that mypy should report this as an error (non-existing file) or process the file as a script (if it exists), not crash in an `assert`.
