### ISSUE TITLE
Move mypy caching files to __pycache__

### ISSUE THREAD

**Issue by lweberk** [python/mypy#2576]
Would that be possible?
Would that make sense? 
What synergies can be used if done so?

Best regards,
~lwk

**Comment by gvanrossum** [comment]
I don't think this makes sense -- `__pycache__` is managed by Python and `.mypy_cache` is managed by mypy, and these are tools with entirely different workflows. I regularly delete the `.mypy_cache` but I basically never do anything to `__pycache__`. Also, when a package is installed by root, its `__pycache__` may be writable only by root.

If you had your own set of answers in mind, please realize that I can't read your mind -- if you have a suggestion, make it, so we can discuss it, rather than asking "leading questions". (It's possible that in your culture direct suggestions are frowned upon and asking questions is how people avoid issues around inappropriate suggestions. In that case please accept my apologies for my directness.)

**Comment by lweberk** [comment]
Unfortunately no, I do not have my own set of answers readily available. Assuming a certain lack of knowledge on my part, which others might otherwise have regarding both __pycache__ and .mypy_cache other than the obvious you can see from looking at their contents, I preferred to open the question to more experienced people that might have been behind the original decision. Either they have a reason for separating which they could share to put my mind to rest about it or there is the slightest chance they may not have seen the possibility. Was it to arrogant to make such assumption and ask questions that might shed some light on that quandary?

On a more apologetic note, it was not my intention to offend with a weak case or to waste time by bringing it up in that way. I will take note on that. My apologies.

On the technical note, there is nothing more to say other than thank you for the insights.

On a purely personal note, let me say that I am a big fan of type annotations and mypy. They are both already a first class citizen in our company. Thank you all for your excellent work and for making it freely available.

~lwk

**Comment by gvanrossum** [comment]
No worries! I would have understood better where you're coming from if you had simply asked "what is the difference between `.mypy_cache` and `__pycache__`?"
