### ISSUE TITLE
Nested dictionary comprehensions not being inferred correctly

### ISSUE THREAD

**Issue by euresti** [python/mypy#2592]
Here's an example:

```
BB = {key: value for keys, value in [
    [['key', 'key2'], "value"],
] for key in keys}

print BB   # `{'key2': 'value', 'key': 'value'}`
reveal_type(BB)  # Revealed type is 'builtins.dict[builtins.str*, typing.Sequence*[builtins.str]]'
```

And so if you change the "value" to something that's not a sequence you get this:
```
BB = {key: value for keys, value in [
    [['key', 'key2'], 7],
] for key in keys}

print BB
reveal_type(BB)
```

```
t6.py:3: error: Iterable expected
t6.py:3: error: "object" has no attribute "__iter__"; maybe "__str__"?
```

**Comment by JukkaL** [comment]
Mypy doesn't understand heterogeneous arrays used like tuples. The example works if we use tuples:

```py
BB = {key: value for keys, value in [
    (['key', 'key2'], "value"),    # note (...) not [...]
] for key in keys}

print BB   # `{'key2': 'value', 'key': 'value'}`
reveal_type(BB)  # Revealed type is 'builtins.dict[builtins.str*, builtins.str*]'
```

There's no technical reason why mypy couldn't support such types, but that would probably require a PEP 484 change unless this would be an internal, non-user-accessible type system feature. Usually it's cleaner to just switch to tuples, so this is not very likely to be changed. 

However, perhaps mypy could give a more useful error message in some cases and suggest using a tuple. Here's a simple idea for a heuristic (which could easily misfire, though):

* Record each line that contains a heterogeneous list literal, but don't generate a message by default.
* If we generate a type error for the surrounding function, also write a note about the heterogeneous list literal and suggest using a tuple. Here the assumption is that the error is perhaps caused by the list literal, even though in general we can't easily verify whether that is the case.

**Comment by euresti** [comment]
Oh Tuple vs List, that totally works in my real code.  I should've know because when I ended up writing a method to do what I wanted I ended up writing:

```
def make_dict(*args):
    # type: (*Tuple[Iterable[_KT], _VT]) -> Dict[_KT, _VT]
    ret = {}
    for keys, value in args:
        for key in keys:
            ret[key] = value
    return ret
```
And turning things to tuples anyway.

**Comment by gvanrossum** [comment]
I think this can be closed.
