### ISSUE TITLE
How to make packages compatible with mypy

### ISSUE THREAD

**Issue by afrieder** [python/mypy#2625]
I'm getting my feet wet with PyPI with a tiny little package (https://github.com/afrieder/matcher). I want to include types so mypy can type check it. I've included both annotated .py files and a .pyi stub. However, installing this through pip (currently using `pip install -e .`, the newest version on PyPI doesn't have the stubs yet) results in `Cannot find module named 'matcher'`. First I'd like to request help and I'd also request that this be documented somewhere. mypy is an amazingly cool tool, and I'd love for more package developers to use it, but there's no documentation for making type hints more usable. Thanks.

**Comment by gvanrossum** [comment]
Thanks for asking! You're right this is a bit of a pain right now. Most "big name" packages solve this by adding stubs to typeshed, but we can't keep that up to date for every package, and when the package owner maintains the stubs it's better to have a different place to look for stubs.

One thing you could do would be to arrange to install your stubs in a separate directory rather than in site-packages, and then direct users to add that separate directory to their MYPYPATH environment variable. You'd need to add an `__init__.pyi` as well.

There's a proposal for where those stubs should live in [PEP 484](https://www.python.org/dev/peps/pep-0484/#storing-and-distributing-stub-files) (search for "shared/typehints/python3.5") but mypy doesn't implement it yet -- hence the suggestion to add it to MYPYPATH.

IIRC there's also some confusion about the exact name of that directory (but I can't find the issue ATM). There's definitely some discussion at https://github.com/python/mypy/issues/1190. Even more at https://github.com/python/typing/issues/184 and https://github.com/python/typing/issues/84.

@ambv Are you interested in this issue at all? I believe we could use some help cutting through all the various proposals and just implement something (especially if it matches PEP 484).

**Comment by ambv** [comment]
@gvanrossum Yes, I'll work on it this week.

**Comment by ethanhs** [comment]
I will add some simple documentation and add a link to PEP 561 in implementing https://github.com/python/mypy/pull/4278

**Comment by MartinThoma** [comment]
Here is a direct link to [PEP 561 -- Distributing and Packaging Type Information](https://www.python.org/dev/peps/pep-0561/).

It would be nice to have a tool which checks packages for compatibility ([question here](https://www.reddit.com/r/Python/comments/9vswdd/does_a_mypycompatibility_check_exist/)). [`check_typedpkg`](https://github.com/ethanhs/check_typedpkg) could be what I am looking for, but it is not on PyPI so far.
