### ISSUE TITLE
A generated tuple inferred as Tuple[T, ...] even though it has obviously constant length

### ISSUE THREAD

**Issue by ze-phyr-us** [python/mypy#2628]
```python
from typing import Tuple

def f() -> Tuple[int, int]:
	return tuple(i * 2 for i in (1, 2))
```

mypy-lang==0.4.6

```
test.py: note: In function "f":
test.py:4: error: Incompatible return value type (got Tuple[int, ...], expected "Tuple[int, int]")
```

Not sure how hard it would be to fix this, but I have a legit, non-contrived use case along the lines of 

```python
yield tuple(
	yaml.load(f.open())
	for f in (x_file, y_file, z_file)
)
```

**Comment by ambv** [comment]
Either cast the result or change the type to `Tuple[int, ...]`. Also, note that your example `f.open()` in a generator expression will raise ResourceWarnings.

**Comment by gvanrossum** [comment]
I presume the key reason to want `Tuple[int, int]` instead of `Tuple[int, ...]` is that the length of the tuple is relevant to the caller. I think it would be interesting to support this but it feels a bit tricky and not very common, so I think for now you'll have to use a work-around.

This is also an example of why Python's type system is hard to capture in a set of simple rules.

**Comment by ze-phyr-us** [comment]
Yes, in this case the length of the tuple was crucial.

No worries, I kind of expected this would be a hard case. Just wanted to put it out there.

**Comment by tnguyen14** [comment]
@ambv how would you cast the type?

**Comment by JelleZijlstra** [comment]
You'd do something like `cast(tuple[int, int], tuple(...))`.
