### ISSUE TITLE
mypy.bat is missing from the wheel file

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2688]
See https://github.com/python/mypy/issues/1495#issuecomment-272568520

The strange thing is that MANIFEST.in has this line
```
recursive-include scripts *
```
but apparently that doesn't include mypy.bat?

**Comment by ambv** [comment]
This is true for source releases but for wheels, `setup(scripts=)` is used and here we only include `mypy.bat` on "nt" platforms. The solution is to add a source distribution, too.

**Comment by gvanrossum** [comment]
I'm not so sure -- the source distribution doesn't have the dependencies on typing and typed_ast, and those (esp. the latter) are essential for Windows.

**Comment by ambv** [comment]
How so? It does depend on both per `install_requires=`.

But actually, a source distribution won't work because the *wheel* will be preferred by `pip` anytime and the current wheel claims compatibility with all platforms. So, we should get a *Windows-specific* wheel to fix this. But I don't know how to force `pip wheel` to admit the wheel is for a specific platform only. Probably needs to be done from a Windows box.

**Comment by gvanrossum** [comment]
But this feels silly -- apart from mypy.bat there is nothing that's platform specific.

Also, I'm trying to add this to MANIFEST.in but it doesn't work -- the scripts/mypy.bat file is not added to the wheel:
```
include scripts/mypy.bat
```
What I have to do instead is remove the "if nt" check from setup.py.

So it seems bdist_wheel takes the list of scripts purely from the setup() call (even though for other things IIRC it uses MANIFEST.in).

**Comment by ambv** [comment]
Wheels are pre-built which means they no longer run `setup()` on the user's environment (they don't even ship `setup.py`. So arbitrary files listed in MANIFEST.in can't be used by wheels because it's not clear where they should *go* in the end user's environment. If it doesn't end up installed, it's not included.

> But this feels silly -- apart from mypy.bat there is nothing that's platform specific.
I disagree it's silly. Different platform-specific wheels contain different platform-specific content. Even if the only difference is the entry point script file (mypy.bat for Windows), that should be enough to warrant a separate wheel. This *is* platform-specific. Maybe `console_scripts` (#1875) works around this somehow, I can't tell, on OS X it still builds a py3-none wheel. Maybe `pip` is somehow smart about this during install time. I don't know.

An open question is what do we do with 0.470? Releasing a Windows-specific wheel is the only way now to avoid having to release 0.471.

**Comment by ddfisher** [comment]
I built a wheel on Windows, but it doesn't appear to be platform specific.  I'll look into forcing that (and making sure that mypy.bat is present).  Can someone give me perms for the mypy package so I can upload it once I've done so?

**Comment by gvanrossum** [comment]
Maybe `setup.py bdist_wheel -p <something>` will work?

What's your pypi username? I can add you.

**Comment by ddfisher** [comment]
I'll try that!  I wonder if I'll need to make 32 and 64 bit wheels -- I'm not sure how to spell "all Windows platforms".

My PyPI username is "ddfisher".

**Comment by ddfisher** [comment]
Build 32 and 64 bit Windows wheels.  Verified the output mentioned `mypy.bat`.  Installed the 64 bit one locally and confirmed it works.  I'm going to upload them to PyPI.

**Comment by ddfisher** [comment]
Uploaded.  Confirmed Windows wheel installed when on Windows and that the resulting mypy works.  This is now fixed for 0.470.

**Comment by gvanrossum** [comment]
Thanks! Is there anything else we can do, or do we just have to remember to make Windows wheels for each future release?

**Comment by ethanhs** [comment]
I am not sure what change made this work, but I believe this is fixed, as I just made a generic wheel on Windows and it included mypy.bat.

**Comment by gvanrossum** [comment]
Great. IIRC this was due to an outdated version of wheel.

**Comment by ethanhs** [comment]
@gvanrossum note that building a generic wheel on Linux will _not_ include the file. Jukka and I were discussing possibly using an Appveyor artifact as the the final wheel, but that brings the possible issue of depending on Appveyor. FYI

**Comment by gvanrossum** [comment]
Still better than depending on @ddfisher doing it manually. :-)
