### ISSUE TITLE
Cannot determine type error with TypeVar with value constraint

### ISSUE THREAD

**Issue by mohabusama** [python/mypy#2697]
Assuming the following code snippet:

```python
from typing import Callable, TypeVar, Generic

T = TypeVar('T', str, int)
Printer = Callable[[T], None]

class Klass(Generic[T]):
    def __init__(self, msg: str, p: Printer[T]) -> None:
        self.msg = msg
        self.p = p

    def echo(self) -> None:
        print(self.msg)
```
`mypy` returns error for `print(self.msg)`: `error: Cannot determine type of 'msg'`

`reveal_type` fails to determine type of `self.msg`:
`reveal_type(self.msg)` results in 
```
error: Cannot determine type of 'msg'
Revealed type is 'Any'
```

If we changed type variable to unconstrained, `T = TypeVar('T')`, everything works as expected.

**Comment by gvanrossum** [comment]
I can repro this but don't understand it yet. The Printer alias and p
argument are not even needed.

--Guido (mobile)

On Jan 16, 2017 8:21 AM, "Mohab Usama" <notifications@github.com> wrote:

Assuming the following code snippet:

from typing import Callable, TypeVar, Generic
T = TypeVar('T', str, int)
Printer = Callable[[T], None]
class Klass(Generic[T]):
    def __init__(self, msg: str, p: Printer[T]) -> None:
        self.msg = msg
        self.p = p

    def echo(self) -> None:
        print(self.msg)

mypy returns error for print(self.msg): error: Cannot determine type of
'msg'

reveal_type fails to determine type of self.msg:
reveal_type(self.msg) results in

error: Cannot determine type of 'msg'
Revealed type is 'Any'

If we changed type variable to unconstrained, T = TypeVar('T'), everything
works as expected.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/python/mypy/issues/2697>, or mute the thread

**Comment by mohabusama** [comment]
@gvanrossum True indeed. Here is a simpler version:

```python
from typing import TypeVar, Generic

T = TypeVar('T', str, int)

class Klass(Generic[T]):
    def __init__(self, msg: str) -> None:
        self.msg = msg

    def echo(self) -> None:
        print(self.msg)
```

**Comment by gvanrossum** [comment]
Even simpler:
```python
from typing import TypeVar, Generic
T = TypeVar('T', int, str)
class C(Generic[T]):
    def __init__(self) -> None:
        self.msg = ''
        reveal_type(self.msg)
```
gives
```
__tmp__.py:6: error: Cannot determine type of 'msg'
__tmp__.py:6: error: Revealed type is 'Any'
```

**Comment by gvanrossum** [comment]
Oh wait, @JukkaL mentioned this on [gitter](https://gitter.im/python/mypy?at=587cf052074f7be763da0db3): "my reading is that defining an attribute in a generic method that uses a constrained type variable is broken."

**Comment by ilevkivskyi** [comment]
Raising priority since this appeared again and it looks "fundamental".
