### ISSUE TITLE
Tarball format of PyPI package

### ISSUE THREAD

**Issue by stargrave** [python/mypy#2698]
There are neither tarballs nor eggs in PyPI since 0.470 version, but only wheels. pip install --no-binary option (PIP 9.0.1) causes to skip all wheels and does not install that version of mypy at all. Exactly I have never met packages that could not be installed with no-binary.

Are there any serious reasons on using only wheel packages for mypy now? How can I deal with that package (except manual intevention) with no-binary option? This option is a precaution that no blobs or pre-built compiled code won't be installed, only source code at least is allowed.

**Comment by ambv** [comment]
There's no binary component in mypy wheels, hence they are compatible with any platform. The separate Windows wheel is there simply because the entry point script is called mypy.bat and not simply mypy.

What's your use case for using --no-binary? It was not designed with security in mind but for working around builds that *cannot* be used due to incompatible system libraries. If you don't trust binary blobs in packages, you shouldn't trust source packages either unless you audit them before running `pip install`.

**Comment by stargrave** [comment]
I assumed that if there is somepackage.tgz and somepackage-linux-amd64.whl, then no-binary option just sets preference to use .tgz version. You are right that I should check all downloaded PyPI packages to see if they contain any blobs, but at least I can trust and check not so paranoidly each time tarball/egg package is downloaded with no-binary option. Without that options I know that I will get blobs all the time it is possible. All about the tradeoffs: no-binary is relatively good tradeoff at least to forbid explicitly told binary packages. Currently mypy in my development system is the only that has no tarball/egg.

**Comment by gvanrossum** [comment]
I don't think there's a compelling reason to support this.
