### ISSUE TITLE
api.run() does not support arguments containing whitespace

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2728]
The api.run() API takes a single string representing the command line. This is then split on whitespace. There is no mechanism for quoting spaces, so e.g. a file or directory with a space in its name cannot be passed. Maybe the `params` argument should be changed to type `List[str]` which could be stored directly in `sys.argv`.

**Comment by gvanrossum** [comment]
@JdeH thoughts?

**Comment by geatec** [comment]
The alternative would be adding a mechanism for quoting spaces, keeping closer to the exact command line syntax. However I think that would be articificial, there's no need to be dogmatic about mimicking the commandline exactly. Passing a list rather than a string that has to be splitted is the right, simple, clean thing to do. I propose I'll make this change.

**Comment by JdeH** [comment]
Sorry, was logged in under my company account, but its just me...
