### ISSUE TITLE
sys.version_info is assumed to be (3, 5), even on Python 3.6

### ISSUE THREAD

**Issue by 5j9** [python/mypy#2836]
Running Python 3.6, I noticed that any type hints that I add to the stub files with a `if sys.version_info >= (3, 6):` condition, don't have any effect.

After investigating this a little, it seems that [semanal.py](https://github.com/python/mypy/blob/ae47a3edc5ff69845398cbefa7652b51362f5c1c/mypy/semanal.py#L3030) uses the `PYTHON3_VERSION` value inside [default.py](https://github.com/python/mypy/blob/452a64fd1a361204a3123abca57a312e15baa9a3/mypy/defaults.py#L2) module as sys.version_info and it is currently hardcoded as `3.5`.

Using `mypy.ini` config file with the following content fixes the issue:

```
[mypy]
    python_version = 3.6
```

But still the default behaviour is confusing and probably should be changed.

**Comment by gvanrossum** [comment]
Hm, I suppose we should make the default dynamic. I can't think of a good reason why the default should be hard-coded.

(Didn't you mean 3.6 in your example though?)

**Comment by 5j9** [comment]
Yes, sorry, 3.6 is correct. Fixed.

**Comment by JukkaL** [comment]
I'd prefer to make the default Python version to always be the latest supported official Python release available at the time of mypy release -- currently that would be 3.6. Here's my reasoning:

* It would be consistent with how mypy behaved until recently (hard coding 3.5 as the default).
* New users may mistakenly think that mypy doesn't support 3.6 features at all if they happen to first try running mypy using Python 3.5, since they may not be aware of `--python-version`. This could be fixed by making the error messages more informative, though.
* Users may run mypy and the program they are developing using different versions of Python, perhaps not even realizing this. If this happens, it may be unclear why mypy doesn't support 3.6 features.
* If the default is dynamic, it may result in confusion, as it looks like mypy works differently in different environments with different Python versions installed.
* If there are multiple developers, different developers might use a different Python version to run mypy. Again, this may be a little confusing if the users haven't yet figured out how to configure the Python version explicitly.
* Mypy generally is permissive by default. Here it seems consistent to allow all Python features by default.

**Comment by gvanrossum** [comment]
While there are other concerns (for smaller installations there's likely
only one relevant Python 3 version) I am convinced by Jukka and I think we
should just bump the default version to 3.6.

**Comment by Dedoig** [comment]
Just ran into this as well, confused about what command-line switches needed to use with 3.6.

Is HEAD supposed to work with 3.6 without needing command-line switches?

**Comment by gvanrossum** [comment]
Use `mypy --python-version 3.6`.

**Comment by Dedoig** [comment]
I did (using HEAD). I got error below, should I post as bug with traceback? (cannot include driver.py):
mypy --python-version 3.6 driver.py 
driver.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
driver.py: note: please use --show-traceback to print a traceback when reporting a bug

**Comment by gvanrossum** [comment]
Oh, I think that's due to the typed-ast update. Try this remedy: https://github.com/python/mypy/issues/2862

**Comment by Dedoig** [comment]
Tried that, same result.

**Comment by gvanrossum** [comment]
OK, open a different issue please.
