### ISSUE TITLE
Piping the results of mypy to head can result in a broken pipe error

### ISSUE THREAD

**Issue by w0rp** [python/mypy#2893]
I have been working on getting mypy to return some meaningful results with a large codebase, and this requires writing a very large number of stubs. As a result, I see hundreds of lines of errors for very small files. To wade through all of this, I have been piping the results to `head` and gradually fixing various issues.

Every now and then, I have noticed that piping the results of the `mypy` output to `head` results in a broken pipe error.

Sometimes I see this error:

```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

At other times, I see this:

```
Traceback (most recent call last):
  File "/home/.../bin/mypy", line 6, in <module>
    main(__file__)
  File "/home/.../lib/python3.5/site-packages/mypy/main.py", line 53, in main
    f.write(m + '\n')
BrokenPipeError: [Errno 32] Broken pipe
```

Sometimes, I don't see any errors.

I can't provide a link to the project, due to copyright reasons, but you should be able to repeat this bug with any file which produces sufficiently long output if the results are fed to `head`, say with `mypy some/file.py | head -n 10`, etc.

**Comment by kirbyfan64** [comment]
I have a fix, but my mypy git repo is on an external hard disk that just accidentally got wiped...

FWIW putting this in `mypy/main.py` should fix it:

```
import signal

...

    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
```

**Comment by JukkaL** [comment]
I was able to reproduce this on macOS. Thanks for reporting this! A PR to fix this would be most welcome as well :-)

**Comment by pkch** [comment]
When `head` gets its 10 lines, it know it's done, so it closes the pipe. As a result, the OS (Linux/OSX but not Windows) sends `SIGPIPE` signal to the previous process in the shell pipe. The default (and usually correct) handling of `SIGPIPE` is to terminate. This mechanism is designed to make shell pipes like `cat hugefile | head` work efficiently - without having to read the entire file when you only need the first few lines.

Python interpreter (for reasons that I don't understand) overrides the default handling of `SIGPIPE`; specifically, it ignores this signal. As a result, any time the pipe is closed on the other end, instead of terminating, a python program would (by default) keep trying to write to the non-existent pipe, thus eventually causing a write error (how soon this happens depends on buffer sizes and policy).

You can verify this behavior by simply running `python -c "print('\n'.join('a'*1000000))" | head`.

To fix this, one would need to override python's handler with the default handler of `SIGPIPE` (which terminates the process). As @kirbyfan64 suggested, it can be done with `signal.signal(signal.SIGPIPE, signal.SIG_DFL)`.

Windows does not have a `SIGPIPE` signal at all, and so this solution wouldn't work. Instead, I suppose one could simply catch `BrokenPipeError` and terminate with exit code 0. But this is only a partial solution because some IO functions in python standard libraries catch and ignore this exception (instead of terminating). This is why sometimes the user sees a message like `Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>` -- and after that, some effort is wasted by the program that keeps producing output that won't be needed any more. I don't know of any feasible comprehensive solution to this problem under Windows.

I wouldn't consider this a major bug, since the error message only happens after the desired number of lines are displayed by `head`, so it's just a minor annoyance (unless someone uses the output in some kind of an automated system).

**Comment by w0rp** [comment]
The problem is that `mypy` doesn't handle the well defined behaviour in a pleasing manner, and it's not hard to solve. The program ought to be able to safely handle the pipe being closed early.

**Comment by gvanrossum** [comment]
The reason Python changes the default signal handler is so that programs
that care about this error can catch the I/O error as an exception and do
the usual cleanup using try/finally -- correctly handling exceptions is
much easier than correctly handling signals. (There may also have been
something where the signal would also be sent when writing to a closed pipe
that's not stdout/stderr, which is even less defensible.)

In mypy's case I am fine with restoring the signal to its default, as long
as it's a no-op on systems where there is no such signal or the call won't
work.

While you're at it you might want to do the same for SIGINT (mypy users
don't care about mypy's traceback when they hit ^C).

**Comment by gvanrossum** [comment]
Good, I think a narrow try/except just in that one spot in main() should be
sufficient for almost all cases.
