### ISSUE TITLE
Type in f-string results in too few arguments for __str__

### ISSUE THREAD

**Issue by iksteen** [python/mypy#2947]
Here's a simple example:

    print(f'Type of 1: {type(1)}')

When run with Python 3 this prints:

    Type of 1: <class 'int'>

However when type-checked with mypy we get an error regarding a missing argument for \_\_str\_\_:

    demo.py:1: error: Too few arguments for "__str__" of "int"

**Comment by gvanrossum** [comment]
Oooh, that's tricky. I think it understands that `type(1)` is just `int` and then it substitutes `str(int)` which it tries to map to `int.__str__()` but that fails because `int.__str__()` is an instance method with a mandatory `self` argument. The root cause is that mypy isn't yet very good at distiguishing class operations from instance operations (it should use the metaclass's `__str__` here).

There are many work-arounds, e.g. use `str(type(1))`.

**Comment by skftn** [comment]
Wouldn't a more appropriate (yet still suboptimal) approach be to assume any result from an f-string expression can eventually be coerced into a `str`?

**Comment by gvanrossum** [comment]
Hm, that's actually a fine idea.
