### ISSUE TITLE
Explicit type arguments to override type inference

### ISSUE THREAD

**Issue by graingert** [python/mypy#3096]
In Python 3.5/3.6 I propose:

```python
from mypy_extensions import type_args

class A: pass
class B(A): pass

type_args(bisect_left, (A))([B()], A())
```

But that's rather ugly, a Scala like syntax `type_args[A]([B()], A())` would be nice but a pain to do.

**Comment by JelleZijlstra** [comment]
For people like me who have trouble understanding what's going on here (correct me if I'm wrong): this would be a way to explicitly specify the type argument to a generic function. Normally, if you write `def f(x: T) -> T:`, then call `f(1)`, mypy would infer the type argument to `f` as `int`, but if you do `type_args(f, (float))(1)` instead, it would infer it as `float`.

**Comment by graingert** [comment]
of course type_args would be:

```
def type_args(f, types):
    return f
```

**Comment by JukkaL** [comment]
This is something that used to be supported until mypy switched to Python syntax. I don't like the proposed syntax, though.

**Comment by graingert** [comment]
@JukkaL how was it supported before?

**Comment by kirbyfan64** [comment]
Maybe splitting things up would be nicer:

```python
typed_args(func)[A, B](x, y)
```

or abusing slice syntax (my personal favorite):

```python
typed_args[myfunc: A, B, C](a, b, c)
```

**Comment by graingert** [comment]
@kirbyfan64 I really like `typed_args(func)[A, B](x, y)`

**Comment by gvanrossum** [comment]
Can't you use a cast()? Seems a pretty unusual use case.

**Comment by graingert** [comment]
@gvanrossum providing the type args to a generic function is type safe, cast is not.

**Comment by gvanrossum** [comment]
> I really like typed_args(func)[A, B](x, y)

Maybe you can find a way to use braces too? :-)

**Comment by graingert** [comment]
@gvanrossum sure, you can use `typed_args(func)[{A, B}](x, y)`

**Comment by JukkaL** [comment]
@graingert The earliest versions of mypy translated to Python and it used `myfunc<A>(args)`, IIRC.

**Comment by sixolet** [comment]
@graingert I think the reason you're running into trouble here is that the explicit type arguments you're trying to provide here are subtly not safe. In your original example, `[B()]` is inferred as `List[B]`, and `List[B]` is not a valid `List[A]`, due to the type argument of `List` being (correctly) invariant.  There's no type at all you can fill in for the `_T` of `bisect_left` that will satisfy.  It's ok at runtime here only because you're only reading from the list, not changing it.  It sounds like @gvanrossum is right that `cast` is the feature you're looking for.

**Comment by graingert** [comment]
@sixolet ah in that case the example is wrong.

**Comment by sixolet** [comment]
... Ah.  Actually it's probably the `_T` of `bisect_left` that is invariant, blocking this, since `bisect_left` takes a `Sequence`

**Comment by sixolet** [comment]
... but playing with it, making it covariant doesn't help.  Sorry, I thought I knew more than I do.  I'm back to thinking it's just a bug in type inference having to do with type variable variance, because `List[int]` should be a valid `Sequence[int]` and `Sequence[int]` should be a valid `Sequence[float]`

**Comment by JukkaL** [comment]
Maybe we should move the type inference discussion to #2035 and leave this for the explicit type arguments discussion.

**Comment by JukkaL** [comment]
This should be proposed as a PEP 484 extension in the typing issue tracker of typing-sig@ if somebody wants to move ahead with this.
