### ISSUE TITLE
Use of covariant type arguments in methods needs to be reported as error

### ISSUE THREAD

**Issue by pkch** [python/mypy#3139]
Contravariant type args in method return is correctly identified as type errors; but covariant type args in method arguments does not create an error:

```
T_co = TypeVar('T_co', covariant=True)

class Covariant(Generic[T_co]):
    def f(x: T_co) -> T_co:  # Need an error here
        return x

T_contra = TypeVar('T_contra', contravariant=True)

class Contravariant(Generic[T_contra]):
    def f(x: T_contra) -> T_contra:  # E: Cannot use a contravariant type variable as return type
        return x
```

It works correctly for normal functions though (not methods).

**Comment by ilevkivskyi** [comment]
This is because ``x`` in your example is interpreted as ``self``. The ``self`` in methods is indeed special (it actually varies covariantly in some sense). If I change your example as following:
```python
class Covariant(Generic[T_co]):
    def f(self, x: T_co) -> T_co:  # Note 'self' added
        return x
```
Then mypy correctly gives an error:
```
error: Cannot use a covariant type variable as a parameter
```

For variance of self-types we have issue https://github.com/python/mypy/issues/2352

**Comment by pkch** [comment]
Ah I didn't mean self-types, I just wrote the signature incorrectly 😛
