### ISSUE TITLE
I'm wondering if it would make sense to have a stdlib cli generator using mypy typing?

### ISSUE THREAD

**Issue by kootenpv** [python/mypy#3170]
Or perhaps this would be too difficult to get right with everyone liking their own way to do it.

**Comment by JelleZijlstra** [comment]
I'm not sure what you're proposing exactly, could you clarify?

**Comment by kootenpv** [comment]
Ok sorry with the assumptions. A CLI generator would be like click/argparse and others that can help people create a CLI for a python package.

I would say that you do not need a lot of fancy stuff, just that typing would really help creating a good CLI.

    @mycli
    def add(a: int, b: int):
        return a + b

Then from commandline:

    $ mypackage add 1 1
    2

while using a string would give:

    $ mypackage add a b
    ValueError: invalid literal for int() with base 10: 'a'

as a CLI solution might use the mypy typings to enforce types (thus trying to create an `int` out of `"a"`).

**Comment by JelleZijlstra** [comment]
Oh, I see. That sounds like something that could be useful, but that's probably best developed as a separate project, since it's pretty different from what mypy is for and the bar for inclusion in the standard library is high. Maybe an existing package like click or docopt would be interested in including this functionality.

**Comment by kirbyfan64** [comment]
Plac is pretty similar in concept:

http://micheles.github.io/plac/

**Comment by ambv** [comment]
Plac and [Larry's DryParse](https://bitbucket.org/larry/dryparse) are both doomed because they reuse function annotation for an unrelated and incompatible use case.

@kootenpv, instead of starting yet another command-line parser, could you look into making Click work with annotations? Soon enough you'll want some of the complex command-line handling that Click provides so you'll end up with some syntax for it anyway.

**Comment by gvanrossum** [comment]
Please discuss this idea elsewhere.
