### ISSUE TITLE
More regular releases or typeshed as a separate package

### ISSUE THREAD

**Issue by samuelcolvin** [python/mypy#3174]
On the release of mypy 5.0.1 there was an [error](https://github.com/python/typeshed/pull/966) in typeshed which caused mypy to incorrectly fail on my code. I fixed that error 6 weeks ago but there's been no subsequent release of mypy so I still can't merge an update of mypy.

Two possible solutions:
1. release patch updates to mypy more often
2. release typeshed as a separate package which mypy requires, then release updates to typeshed more often thus allowing problems in typeshed to be remedied with a new release without needing to release mypy

Sorry to sound grumpy, thank you again for mypy: I think typing is one of the most exciting things happening in python ATM.

**Comment by JelleZijlstra** [comment]
I've encountered similar problems. Unfortunately I don't think your solution 2 is realistic, because it's still common for changes in typeshed to require concurrent changes in mypy. For example, due to python/typeshed#1156, the current version of typeshed will probably crash the most recent release of mypy. Maybe we could maintain multiple branches of typeshed and release only changes that don't interact with mypy.
