### ISSUE TITLE
is_subtype vs is_proper_subtype

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3297]
Currently, we have two functions ``is_subtype`` and ``is_proper_subtype``. There are two corresponding visitors: ``SubtypeVisitor`` and ``ProperSubtypeVisitor``, both of them implement some complex logic.
I think that _ideally_ there should be only one visitor, ``ProperSubtypeVisitor``, and ``is_subtype`` should be simply:
```python
def is_subtype(left, right):
    if isinstance(left, AnyType) or isinstance(right, AnyType):
        return True
    return is_proper_subtype(left, right)
```
Are there any reasons why it is not possible now? Maybe this question already exists in a roadmap mentioned in https://github.com/python/mypy/issues/3194 (btw @JukkaL @ddfisher is it possible to make it public?)

(I have found this issue https://github.com/python/mypy/issues/2038, but I am not sure it is up to date.)

**Comment by JukkaL** [comment]
It's more complex than that, since `List[str]` is considered a subtype of `List[Any]`, etc. Maybe we could have a flag for `SubtypeVisitor` that indicates whether we should be taking a proper or normal subtype. I thought about merging the two when writing the proper subtype visitor, but it didn't seem obvious at that time that combining would make the code easier to read or maintain. However, it might well be worth it, since they duplicate a lot of logic.
