### ISSUE TITLE
Support structural subtyping for named tuples

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3521]
This appeared in https://github.com/python/typing/issues/427

We can consider allowing code like this:
```python
class Point(NamedTuple):
    x: int
    y: int
class LabeledPoint(NamedTuple):
    x: int
    y: int
    label: str

def fun(p: Point): ...
fun(LabeledPoint(1, 2, 'test'))  # OK
```
This seems to be type safe and will be relatively easy to implement after protocols land.

**Comment by gvanrossum** [comment]
If you really want this, can you make it an option in PEP 544? Personally I think it would require an extra marker class, since otherwise if fun() contained `assert isinstance(p, Point)` it would be problematic.

**Comment by ilevkivskyi** [comment]
> If you really want this, can you make it an option in PEP 544?

Not that I _really_ want this, but I have seen this "feature request" at least twice, so that we can at least consider this.

Concerning the PEP, I would rather add a common section about ``NamedTuple`` and ``TypedDict``, they are quite similar and the latter already behaves structurally. What do you think?

> I think it would require an extra marker class, since otherwise if fun() contained ``assert isinstance(p, Point)`` it would be problematic.

Again, maybe we can just have a class keyword?
```python
class Point(NamedTuple, structural=True):
    x: int
    y: int
```

**Comment by gvanrossum** [comment]
I suppose I caused one of those feature requests myself. :-)

As we have now clearly demonstrated, this is one of those features that a requester can easily think is simple to implement, but there are actually many traps in any possible solution.

I'm not so sure that NamedTuple and TypedDict are really all that similar (except they are both attempts to handle outdated patterns in a statically-typed world). Now that we have a design for dataclasses, even the current limited OO version of NamedTuple seems already a dead end and I sort of wish we hadn't gone there (extra sad because I originally wanted it). In any case I expect NamedTuple and TypedDict to take different development paths (though we may want to curb our enthusiasm for OO TypedDict definitions given what we're going through for NamedTuple).

I propose to stop proposing any new additions to NamedTuple (but TypedDict is something we want to develop at least to the point where it's actually useful for Dropbox).

**Comment by ilevkivskyi** [comment]
> Now that we have a design for dataclasses, even the current limited OO version of NamedTuple seems already a dead end and I sort of wish we hadn't gone there (extra sad because I originally wanted it) [...] I propose to stop proposing any new additions to NamedTuple

``NamedTuple`` class syntax was anyway an interesting experience that was not in vain I believe. Now we have much more input for the dataclasses.

> (but TypedDict is something we want to develop at least to the point where it's actually useful for Dropbox).

Maybe then it makes sense to add a section about ``TypedDict`` to PEP 544, since ``TypedDict`` behaves _structurally_?

**Comment by gvanrossum** [comment]
Actually I think TypedDict needs its own PEP if we want it to be more than a mypy-specific extension.

**Comment by ilevkivskyi** [comment]
> Actually I think TypedDict needs its own PEP if we want it to be more than a mypy-specific extension.

OK, less work for me :-) Then this issue can be closed I think. I others don't agree, then they can re-open.
