### ISSUE TITLE
List[str] incompatible with Optional[List[Union[str, MyClass]]]

### ISSUE THREAD

**Issue by jpowie01** [python/mypy#3537]
Hi all,
I'm using mypy 0.511 with Python 3.5.2 and I've found an issue which gave me this error:
```
Incompatible return value type (got List[str], expected "Optional[List[Union[str, MyClass]]]")
```

Here is an example code that reproduces this bug:
```python
from typing import Optional, List, Union


class MyClass:
    pass


def my_function() -> Optional[List[Union[str, MyClass]]]:
    list_of_strings = ['a', 'b', 'c']
    return list_of_strings
```

As far as I understand it should be fine. Please correct me if I'm wrong.

**Comment by ilevkivskyi** [comment]
This is not a bug but expected behavior due to invariance of ``List``, see [these docs](http://mypy.readthedocs.io/en/latest/generics.html#variance-of-generics) for why this is not type safe, and [these docs](http://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance) for possible workarounds.

In your case, I would probably just add an explicit annotation to ``list_of_strings`` (if other code supports this).
