### ISSUE TITLE
Use plugin to support Django models

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3539]
We'd also need stubs for Django. Django is very popular so having the plugin live in the mypy repo would be reasonable.

**Comment by JukkaL** [comment]
This was originally discussed at #1240.

**Comment by ilevkivskyi** [comment]
@dmoisset You might be interested in this.

**Comment by lwm** [comment]
Thanks @ethanhs, happy to go with your recommended approach. I'm asking a heck of a lot of questions but I'll keep going - what is meant by 'a plugin for django'? I'm not quite sure what is the purpose of the plugin and why we need it.

**Comment by ethanhs** [comment]
@lwm the idea is that Django models do some rather dynamic things that mypy does not, nor will not in the near future, support. Therefore, if there is a plugin for mypy which knows about how these models work, people can still get some type safety when using mypy in conjunction with Django. There is a plugin for attrs which lives in the mypy sources which you may be interested in.

**Comment by lwm** [comment]
Thanks @ethanhs, I'll give that existing plugin a look over and see how I go :+1:

**Comment by ethanhs** [comment]
Great, let me know (here or on Gitter) if you have questions. There is usually someone around who can answer your questions on the [typing Gitter](https://gitter.im/python/typing).

**Comment by willmcgugan** [comment]
Hi,

I've been looking in to typing Django models myself, which would be a massive benefit for my client's project. The plugin approach seems the clear winner, and I would love to see that in mypy. But I understand its quite challenging and might take some time.

In the meantime, I've been trying to put together another solution that might work for us (and other projects). It's just a days work, but I've fudged together a script which can import Django models, inspect them and output .pyi files. It's not quite finished, but in theory it should cover all the field attributes and the dynamic attributes Django adds.

I was wondering if anyone has tried such an approach and if its worth persevering? 

Somewhat related is an issue I had with the inspect lib, which I use to extract method signatures from the models. The `Signature` object turns forward references in to something like the following:

```
-> Union[_ForwardRef('DeviceMemory'), NoneType]
```

Which mypy rejects, because of the use of parenthesis in `_ForwardRef`. Is that a bug in the inspect module?  Replacing that with a regex, feels like a hack--I'm hoping there is a workaround.

**Comment by ilevkivskyi** [comment]
@willmcgugan This is an interesting approach, somewhere in between `stubgen` (a basic static stub generator, comes with mypy) and `PyAnnotate` (collecting types from function calls at runtime). I am not aware of anyone else doing this, but  there is a project https://github.com/TypedDjango/django-stubs, so you might want to coordinate your efforts with them.

Regarding your question, this is caused by the fact that all string literals that appear as type parameters are internally wrapped in a special class `typing._ForwardRef`. What you see is its standard `repr()`. There are several possible solutions, the best one is probably to use `typing.get_type_hints()` instead (it requires a namespace argument where to evaluate the forward references).

**Comment by ilevkivskyi** [comment]
I think this can be closed, there is a Django plugin actively developed in a separate repo: https://github.com/mkurnikov/django-stubs. All further discussion about supporting various Django features could continue there.
