### ISSUE TITLE
Don't enforce strict mode on typeshed

### ISSUE THREAD

**Issue by smessmer** [python/mypy#3617]
When running mypy with `--strict` on a project that uses some standard libraries which are missing types in current typeshed, it will complain and point to the typeshed. See https://github.com/python/typeshed/pull/1438

It should not apply `--strict` to typeshed. Ideally, `--strict` mode should also not apply for other dependencies, but only to your own source code, as you can't influence third party code anyhow.

**Comment by ilinum** [comment]
For reference, `--strict` option enables the following flags:
```
--disallow-untyped-calls, --disallow-untyped-defs,
--check-untyped-defs, --disallow-subclassing-any,
--warn-redundant-casts, --warn-return-any, 
--warn-unused-ignores, --no-implicit-optional, --strict-optional
```

Out of all of these, there are a few that can possibly affect typeshed: 
`--disallow-untyped-defs` which disallows functions without type annotations. This flag needs to be addressed.
`--disallow-subclassing-any` could in theory affect typeshed but (as far as I understand) this shouldn't happen.
`--warn-unused-ignores` could affect typeshed but in practice it shouldn't bother users very much.
`--no-implicit-optional` should not affect typeshed (I could be wrong).
`--strict-optional` should not affect typeshed.

Overall, I think the only option from the `--strict` group worth addressing is `--disallow-untyped-defs`.
Perhaps, we could just check if it's a typeshed file before reporting the error (should be pretty easy to do). 

That being said, I think that no errors from typeshed should be reported at all because (as you pointed out, the user can't influence typeshed code). We should, however, provide a flag to enable those errors (for purposes of debugging typeshed). 
We should also test typeshed with as many flags enabled as we can.

**Comment by ilinum** [comment]
@JelleZijlstra @gvanrossum what do you think?

**Comment by JelleZijlstra** [comment]
I generally agree that mypy shouldn't give errors about incompletely typed typeshed code, but getting the details right is tricky. I don't have time to think about all cases right now, but here are a few thoughts:

`--warn-unused-ignores` should be suppressed in typeshed, because the `# type: ignore` may only apply to a different type checker or Python version than the one the user is running. Mypy already has special casing (in errors.py if I recall correctly).

For `--disallow-untyped-calls`, I think the errors actually appear in user code, but they appear because typeshed stubs don't have types. This might need a more complicated heuristic than "suppress errors in typeshed".

**Comment by ethanhs** [comment]
A couple more thoughts on other flags

For `--disallow-subclassing-any` we can ignore [this class](https://github.com/python/typeshed/blob/master/stdlib/3/unittest/mock.pyi#L34) and safely use it, I think. 

For `--no-implicit-optional` we should wait for a conclusion of [this typing issue](https://github.com/python/typing/issues/275), then we should be able to allow it. 

For `--disallow-untyped-defs` we are almost certainly going to have to disable this for typeshed as there are over 1000 issues in just Python 3 stubs (3-3.6). I think it should be fine to allow `--check-untyped-defs`.

For `--warn-return-any` Im pretty sure it is unrealistic for us to allow this for typeshed, as there are a lot of complex functions that return Any, many correctly.

**Comment by hauntsaninja** [comment]
mypy ignores a number of errors in stubs. If someone has a repro (that isn't four years old ;-) ), we can take a look
