### ISSUE TITLE
Incorrect `error: 'builtins.object' object is not iterable` in nested list comprehension

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#3627]
```python
from typing import *
def foo(f: Callable[[int], Tuple[str, List[int]]]) -> None:
    def g(i: int) -> List[Tuple[str, int]]:
        return [(s, j) for s, js in f(i) for j in js]
```

> testmy.py:4: error: 'builtins.object' object is not iterable

```
[mypy]
python_version = 3.6

check_untyped_defs = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_subclassing_any = True
follow_imports = normal
incremental = True
strict_optional = True
warn_no_return = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_ignores = True
```

Using `mypy 0.520-dev-35fbfb6b91c9aef37453ff86b532823127f4072e`

**Comment by gvanrossum** [comment]
Does it still give that error if you write am equivalent for-loop?

**Comment by ethanhs** [comment]
With:
```
from typing import *
def foo(f: Callable[[int], Tuple[str, List[int]]]) -> None:
    
    def g(i: int) -> List[Tuple[str, int]]:
        reveal_type(f(i))
        out = [] # type: List[Tuple[str, int]]
        for s, js in f(i):
            for j in js:
                out.append((s, j))
        return out
```
and all settings default the output is:
```
main.py:5: error: Revealed type is 'Tuple[builtins.str, builtins.list[builtins.int]]'
main.py:7: error: 'builtins.object' object is not iterable
```

So this is an issue when iterating over it.

**Comment by gvanrossum** [comment]
That helps, since the inner loop is irrelevant in the second example. A reduced version is then:
```py
def f(a: Tuple[str, List[int]]):
  for i, j in a:  # E: 'builtins.object' object is not iterable
    pass
```
We can deconstruct this further and find:
```py
def f(a: Tuple[str, List[int]]):
  for x in a:
    reveal_type(x)  # Revealed type is 'builtins.object'
    i, j = x  # error: 'builtins.object' object is not iterable
```
So we see that when iterating over `Tuple[str, List[int]]` the join of the item types is used as the type of the iteration variable, and that is apparently `object`. The error then is coming from the unpack operation.

Maybe mypy actually found a bug in the original program? Because it would only work at runtime if the string in the tuple had exactly two characters and the list had exactly two values. Maybe the OP intended for `f` to return a *list* of tuples?

**Comment by ethanhs** [comment]
This is why complex generator statements aren't ideal :)

Yes, I believe mypy is correct here. The error isn't the most clear however due to the join. Im not sure there is a simple way to make the error clearer.

**Comment by Daenyth** [comment]
Yup, good catch.
