### ISSUE TITLE
Error iterating over bulitin functions

### ISSUE THREAD

**Issue by AdamNiederer** [python/mypy#3728]
Hello,

When running this snippet through mypy 0.520, I recieved an error.

```python
# error: "object" has no attribute "__name__"; maybe "__ne__" or "__new__"?
for fn in str, filter:
    print(fn.__name__)

# no error
for fn in str, int:
    print(fn.__name__)

# no error
for fn in any, filter:
    print(fn.__name__)
```

`str` and `filter` both have a `__name__` attribute, but it looks like mypy is up-casting something when builtins associated with types are mixed with non-type-associated builtins.

**Comment by JelleZijlstra** [comment]
You can investigate better with `reveal_type`, but I suspect what's going on is that str and int are types in typeshed and any and filter are functions. Therefore, `(str, filter)` contains two different types and iterating over it yields their common base class, `object`, which doesn't have `__name__`. But iterating over str and int gives you `type`, because both are of the same type.

I'm not sure there's anything actionable to do here.

**Comment by gvanrossum** [comment]
Good call Jelle! When mypy sees a sequence with different item types it takes the join of those types. In this example the join of `str` and `int` is `type` which has `__name__`; the join of `any` and `filter` is `function` which also has `__name__`; but the join of `str` and `filter` is `object`, which doesn't define `__name__`. This is how it should be.
