### ISSUE TITLE
multiprocessing.Queue doesn't match Queue[all] for logging.handlers.QueueHandler

### ISSUE THREAD

**Issue by bcl** [python/mypy#3804]
import logging.handlers
    import multiprocessing as mp

    def foo(queue: mp.Queue):
        handler = logging.handlers.QueueHandler(queue)

Returns the error:
tt.py:6: error: Argument 1 to "QueueHandler" has incompatible type "Queue"; expected Queue[Any]

**Comment by gvanrossum** [comment]
This is a [typeshed](https://github.com/python/typeshed/) issue.

The `Queue` expected by `logging.handlers.QueueHandler()` is a `queue.Queue`. It seems the `multiprocessing.Queue` class emulates that (i.e. duck typing). We might fix this by adding `queue.Queue` as the base class of `multiprocessing.Queue` in the stubs for multiprocessing. It should probably become a generic class then (since `queue.Queue` is generic). Do you want to attempt that as a PR for typeshed?

**Comment by bcl** [comment]
Sure - https://github.com/python/typeshed/pull/1525

**Comment by JelleZijlstra** [comment]
Closing this since we can discuss on the typeshed issue.
