### ISSUE TITLE
ignore type comment should support environment markers 

### ISSUE THREAD

**Issue by gaborbernat** [python/mypy#3812]
some errors pop up only under Python 2 or 3; it would be nice to silence them for only a given environment (as a general ignore will trigger a note report if it's not used under a given environment while running under ``--strict`` mode) :+1:

**Comment by gvanrossum** [comment]
I am not keen on this, designing the syntax will be complicated.

**Comment by gaborbernat** [comment]
any suggestions to tackle the underlying issue then? :+1: (e.g. while type hinting code that should support both Python 2/3 or different platforms, some linters may throw false positives)

**Comment by JukkaL** [comment]
There are a few things that might work right now:
* Refactor your code so that the original issue no longer needs to be ignored. For example, use a cast or `Any` type.
* Disable the option which causes mypy to warn about unused ignores. Periodically look for unused ignored manually, and do nothing about cases which only happen in some environments.
* Run mypy for each environment and process the output from mypy so that only errors about unused ignores that happen on all environments are reported.

None of the above are perfect. I'm not sure what a good solution would look like. Maybe warning about unused ignores should not be enabled by `--strict`.

**Comment by gaborbernat** [comment]
@JukkaL  the only reliable workaround for now is option 1 (well pointed out). Option 2 and 3 I found kinda hard to maintain, especially for people just joining the project.

@gvanrossum can't we just use the environment marker syntax for packages (e.g. setuptools way of specifying dependencies)? at the moment the ignore takes no argument we would need to just add one argument that's the environment marker, not? Or am I missing something bigger here?

**Comment by gvanrossum** [comment]
Part of the problem with adding arguments to `ignore` is that we can't do this in a mypy-specific fashion -- it's a standard that's also supported (AFAIK) by PyCharm and Google's pytype project. Plus if you look up mypy's implementation you'll find that it may not be so easy to change (it gets parsed in a different stage than the rest of type annotations).

**Comment by gaborbernat** [comment]
I see so any kind of extension would probably involve at least a PEP; and would be kinda hard to do in a backwards compatible way (given that at least one of the main three parse it exactly). Quite the pain indeed.

**Comment by ethanhs** [comment]
Closing this, as we seem to agree that this is hard to do, not standards compliant, and good alternatives exist. (Also discussion of this type of subject should probably happen on python-ideas, or maybe the typing tracker).

**Comment by gaborbernat** [comment]
I don't think there are good alternatives (those were workarounds, requiring to change how you write code to work around limitations in type system).

**Comment by ethanhs** [comment]
Perhaps they aren't good, but regardless, the solution as stated is not going to happen without a PEP. If you would like to change the subject of the issue or open a new issue, discussion of removing `--warn-unused-ignores` from `--strict` seems to be useful.
