### ISSUE TITLE
MyPy Logo

### ISSUE THREAD

**Issue by mvcisback** [python/mypy#383]
Playing around with logos for another project.....this popped into my head

![mypy](https://cloud.githubusercontent.com/assets/388723/3936084/1df44cae-249d-11e4-8ece-1afc148c0125.png)

Its the normal Python Logo transformed to make an M for mypy

**Comment by ilevkivskyi** [comment]
Here is another idea for the logo:

![mypy](https://user-images.githubusercontent.com/12005495/29493671-1c07a672-859b-11e7-89d1-eef0cf7c922b.png)

@JukkaL I think it is OK to use the Python logo if we have a permission. The "logic" behind this idea is quite simple, it looks like ``x: list[int]``, where ``x == Python`` in our case :-) Also I like simple logos that contain the actual title.

I took the colours (``#1f5082`` and ``#dfdfdf``) from CSS on [mypy-lang.org](http://mypy-lang.org), we could play with other colours, but I think this pair looks quite "solid". I also tried to play with font, it seems to me that monospace looks quite bad (especially letter ``m``), therefore I tried something wider, I think this looks better.

(I have an original SVG, but GitHub doesn't support embedding it in a post.)

**Comment by gvanrossum** [comment]
I like this idea. Something seems wrong with the colors though -- when I click on the image I only see the blue parts. In general the gray part is way too light for my taste, it looks like a "grayed out" menu item.

**Comment by ilevkivskyi** [comment]
Here is a version with a bit darker gray ``#b7b7b7`` (I also put it on a non-transparent white background):

![mypyb](https://user-images.githubusercontent.com/12005495/29498784-43ef5a3c-8603-11e7-97b4-2c29eb9bb01e.png)

**Comment by gvanrossum** [comment]
It's a bit better, but the gray still makes me think "grayed out". Maybe we
need to ask a designer friend... (I could ask my designer brother to have a
look if you want to.)

**Comment by ilevkivskyi** [comment]
> Maybe we need to ask a designer friend... (I could ask my designer brother to have a look if you want to.)

Yes, this is definitely a good idea.

**Comment by ilevkivskyi** [comment]
Here is a balanced version (both colours now have the same lightness):

![mypyc](https://user-images.githubusercontent.com/12005495/29498974-10a607f8-8607-11e7-8bf5-3f7ae38e65bb.png)

**Comment by gvanrossum** [comment]
@justvanrossum What do you think of this logo design? How would you improve it?

For more info about mypy, see e.g. http://mypy-lang.org/examples.html. The form of the logo, interpreted as `snakes: my[py]`, is derived from the syntax which declares an argument or variable named. For example we write `arg: List[int]` to declare an argument `arg` that is a list of integers, so the logo declares a variable `snakes` that is a `my` of `py`s. (Also, we like to write "mypy", the name of the tool, without initial cap.)

**Comment by ethanhs** [comment]
I like the design of the `snakes: my[py]`, but it felt a little too monochromatic. I thought I'd try using the Python colors and gradient (or approximately thereof):

![mypy_color](https://user-images.githubusercontent.com/9504279/40606243-9cb2447a-6219-11e8-8480-361e002107a1.png)

**Comment by ilevkivskyi** [comment]
Btw I ended up using a bit lighter (closer to original Python) blue. This is what @msullivan shown on his PyCon lighting talk:
![mypy_light](https://user-images.githubusercontent.com/12005495/40612652-69edbdda-6273-11e8-9724-27b0659804e2.png)

**Comment by ethanhs** [comment]
@ilevkivskyi yeah, I see what you mean about the disctinctiveness of the brand. I'm happy with the lighter blue version :)

**Comment by JukkaL** [comment]
I can't help thinking that the concept of the colon and the square brackets is a bit too clever. It wasn't obvious to me when I first saw the logo, and it may be confusing for other people as well. My preference would be for something simpler. What about only having the colon part and leaving out the square brackets, for example?

**Comment by ilevkivskyi** [comment]
FWIW it would look like this:
![mypy_light](https://user-images.githubusercontent.com/12005495/40742754-624d0b64-6447-11e8-9259-928b76177818.png)

TBH, I like the variant with square brackets more. Here are same thoughts:
* > I can't help thinking

  This is good! :-) It means that the logo catches attention. It's not too trivial, while not too complex exactly enough to start thinking about "why that brackets?" :-)
* Generics is an important part of the type system, and something mypy does IMO better than any other existing type checkers
* I would like people to use more of `List[int]`, or even `List[Any]`, rather than just `list`, if the logo will push them at least a little, I will be already happy.
* In this plain form it is too close to just standard Python logo (snakes), but this may be subjective.
* On the other hand, with brackets "my" and "py" are a bit too far from each other.

**Comment by ilevkivskyi** [comment]
(Btw @JukkaL I think you should make the final decision, finally you are the "father".)

**Comment by msullivan** [comment]
I think both look good, but I prefer the one with generics

**Comment by ilevkivskyi** [comment]
Another idea that came to my mind is that we can provide a "plate" for projects that use mypy. So that people can add it to their READMEs and it will look like this (currently click directs to mypy-lang.org)

------

[![Build Status](https://api.travis-ci.org/python/mypy.svg?branch=master)](https://travis-ci.org/python/mypy) [![Chat at https://gitter.im/python/typing](https://badges.gitter.im/python/typing.svg)](https://gitter.im/python/typing?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [![Checked with mypy](https://rawgit.com/ilevkivskyi/mypy/master/test.svg)](http://mypy-lang.org/)

**Comment by msullivan** [comment]
I love the badge idea
