### ISSUE TITLE
mypy throws error: "Name 'asyncio.base_events.Server' is not defined" when imported with "import asyncio"

### ISSUE THREAD

**Issue by OndrejZapletal** [python/mypy#3851]
Simple code:

```
import asyncio
item: asyncio.base_events.Server = None
```
results in following error when checked by mypy:
`main.py:2: error: Name 'asyncio.base_events.Server' is not defined`

On the other hand code:
```
from asyncio.base_events import Server
item: Server = None
```
doesn't result in any error.

**Comment by ilevkivskyi** [comment]
Thanks for reporting!
What are your settings? It looks like you are using ``--follow-imports=silent`` or something similar. The problem is that ``base_events`` is not defined in ``typeshed``. If you are indeed using something like ``--follow-imports=silent``, then I would recommend to close this issue, and open one at [typeshed tracker](https://github.com/python/typeshed/issues).

**Comment by OndrejZapletal** [comment]
You are correct I'm actually using `--follow-imports=silent`. I will close this issue and open one in `typshed`. Thank you for the response.
