### ISSUE TITLE
type of kwargs confused 

### ISSUE THREAD

**Issue by levsa** [python/mypy#3897]
mypy gets confused about types in the following example:

```python
class Region:
    def __init__(self, name: str, area: float = 0, radius: int = 0) -> None:
        pass


def given_region(self, name: str, area: float = None, radius: int = None):
    region_args = {}
    if area is not None:
        region_args['area'] = area

    if radius is not None:
        region_args['radius'] = radius

    region = Region("Region name", **region_args)
    return region
```
which gives:
```
mypy_region.py:15: error: Argument 2 to "Region" has incompatible type **Dict[str, float]; expected "int"
```
The problem is solved if region_args is type-declared with `Dict[str, Any]`.

**Comment by levsa** [comment]
I realized the problem, Dict[] gets a derived type based on "area", the first assignment (I'm guessing). I guess the solution is declaring region_args type explicitly.

**Comment by ilevkivskyi** [comment]
This is normal behaviour. First, it is always recommended to annotate empty containers, second, I would rather recommend using ``TypeDict`` instead of ``Dict`` in this case see [docs](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict) (note, the ``TypedDict`` is not yet in ``typing``, so that you should import it from ``mypy_extensions``).
