### ISSUE TITLE
Equivalent type specifications producing different results

### ISSUE THREAD

**Issue by teepark** [python/mypy#3921]
mypy will pass a type declaration using a type variable, while failing one that uses exactly the same definition inline.

```python
from typing import Callable, Dict, TypeVar

class Parent(object):
    pass

class Child(Parent):
    pass

def takes_child(c:Child) -> Child:
    return c

_P = TypeVar('_P', bound=Parent)
_F = Callable[[_P], _P]

passes = takes_child  # type: _F
fails = takes_child  # type: Callable[[_P], _P]
```

In this case I'm not sure if it should actually be failing both. If I see a type declaration of `Callable[[_P], _P]` then I should be able to call that function on an instance of any `Parent` subclass (say a `Child2` instance), when the actual function is more restrictive. But in any case the two declarations seem to be equivalent, and so should probably be producing the same result.

**Comment by ilevkivskyi** [comment]
When you write ``_F = Callable[[_P], _P]`` this creates a generic alias. So that when you use it plain (i.e. not as ``_F[int]``), all type variables are substituted with ``Any``, this is well described in [the docs](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#type-aliases). So that plain ``_F`` is equivalent to ``Callable[[Any], Any]`` and your assignment passes.

If you don't like this and want to be warned about implicit ``Any`` substitutions in generic types and aliases, then you should use ``--disallow-any=generic``, again, [docs](http://mypy.readthedocs.io/en/latest/command_line.html?highlight=disallow-any#additional-command-line-flags).

In general, the second assignment should fail, it is not type safe.

**Comment by teepark** [comment]
Thanks @ilevkivskyi! I suspected there was something I was missing, and that explains it.
