### ISSUE TITLE
NamedTuple doesn't accept field called `count`

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#3950]
```
from typing import *
class Foo(NamedTuple):
    count: int
```

```
foo.py:3: error: Incompatible types in assignment (expression has type "int", base class "tuple" defined the type as Callable[[Tuple[Any, ...], Any], int])
```

**Comment by ilevkivskyi** [comment]
This is not a bug, ``tuple`` has a method named ``count`` and here you are trying to override it in an incompatible way, so this is a Liskov violation.

**Comment by PeterJCLaw** [comment]
Just hit this and couldn't work out what the underlying issue was. I looked in the docs for both `typing.NamedTuple` and `collections.namedtuple` and neither mentions that having a field called `count` isn't supported.

There are a some other things which conspire to make this harder to understand:
Firstly the older spelling is accepted by mypy:
``` python
from typing import NamedTuple
Foo = NamedTuple('Foo', (
    ('count', int),
))
```

Secondly, in either spelling the type according to `reveal_type(Foo(9).count)` is `builtins.int`.

Finally the code does work and seems to behave as expected.

I appreciate that this may not be something which mypy can allow, however if that is the case please could it:
- be consistent about the error between spellings
- have a clearer error message

Regarding the clarity of this: while I can now (that I understand the issue) see what mypy was saying, I didn't initially understand that the assignment issue was to do with the assignment of the member `count` into the class. It felt like I was _declaring_ a class member, which is conceptually different (even if it's actually an assignment).

Would an error message like the following be possible here (emphasis to show changes):
> Incompatible types in _class member declaration_ (expression has type "int", base class "tuple" defined the _member_ type as "Callable[[Tuple[int, ...], Any], int]") [assignment]

Maybe even add something like:
> Hint: are you overriding a method with an attribute?

If there's scope to change the error code from `assignment` to perhaps `member-declaration` (or something) that might also help? Not sure if that would be too breaking though.

For comparison, the method override error message is (to me) much clearer:
> Signature of "count" incompatible with supertype "tuple"  [override]

**Comment by PeterJCLaw** [comment]
Ah, I see there's an open issue for the message: https://github.com/python/mypy/issues/4507
