### ISSUE TITLE
Failing to use variables for types

### ISSUE THREAD

**Issue by mitar** [python/mypy#3962]
If I have file `foo.py`:

```python
from typing import *

A = TypeVar('A')

class Foo(Generic[A]):
    def foo(self) -> A:
        pass

    def bar(self) -> A:
        pass
```

The following file `bar.py` raises strange errors:

```python
from foo import Foo

import numpy as np  # type: ignore

A = np.ndarray

class Bar(Foo[A]):
    def foo(self) -> A:
        pass

    def bar(self) -> A:
        pass
```

Errors:

```
bar.py:7: error: Invalid type "bar.A"
bar.py:8: error: Invalid type "bar.A"
bar.py:11: error: Invalid type "bar.A"
```

If I inline `A` then it works:

```python
from foo import Foo

import numpy as np  # type: ignore

class Bar(Foo[np.ndarray]):
    def foo(self) -> np.ndarray:
        pass

    def bar(self) -> np.ndarray:
        pass
```

Python 3.5.2
mypy 0.521

**Comment by gvanrossum** [comment]
This comes from this line: https://github.com/python/mypy/blob/3db14517724fa1e49479ef8a22f8e1dbf33bba6e/mypy/typeanal.py#L262
A simple one-file repro:
```py
from typing import *
T = TypeVar('T')
class Foo(Generic[T]): pass
import blah  # type: ignore
B = blah
class Bar(Foo[B]): pass
```
I think there's something wrong with the block before (the comment `# Something with an Any type` sounds like someone was a bit worried when writing this code).

**Comment by mitar** [comment]
This also does not work with the same error:

```
from typing import *
T = TypeVar('T')
class Foo(Generic[T]): pass
B = None
class Bar(Foo[B]): pass
```

**Comment by ilevkivskyi** [comment]
@mitar Concerning aliases to ``None``: the PEP 484 rule that ``None`` is equivalent to ``type(None)`` only applies to type context, not to runtime context, to create an alias one can write ``Void = type(None)``, see https://github.com/python/mypy/pull/3754

Concerning the original error, we can in principle allow creating aliases to unimported types (since we now have ``TypeOfAny.unimported``). Anyway, the error message is clearly too terse.

**Comment by mitar** [comment]
The following does not work either:

```python
from typing import *
T = TypeVar('T')
class Foo(Generic[T]): pass
B = type(None)
class Bar(Foo[B]): pass
```

**Comment by ilevkivskyi** [comment]
@mitar 
> The following does not work either:

Yes, since PR referenced by me is not yet merged, next time please read references before replying.

**Comment by mitar** [comment]
I missed the fact that is is not yet merged. Sorry.

**Comment by AlexWaygood** [comment]
> A simple one-file repro:
> ```python
> from typing import *
> T = TypeVar('T')
> class Foo(Generic[T]): pass
> import blah  # type: ignore
> B = blah
> class Bar(Foo[B]): pass
> ```

On mypy 0.942, you can now get mypy to understand this code [by using `typing.TypeAlias`](https://mypy-play.net/?mypy=latest&python=3.10&gist=7770ffce14303a074504d69597a67836) (or `typing_extensions.TypeAlias` on Python <3.10) to explicitly declare `B` as a type alias:

```python
from typing import *
T = TypeVar('T')
class Foo(Generic[T]): pass
import blah  # type: ignore
B: TypeAlias = blah
class Bar(Foo[B]): pass
```

Since there's now an easy workaround, I'm closing this issue.
