### ISSUE TITLE
None inferred as variable type from UninhabitedType

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4104]
The inferred type for `x` is unexpected (especially when using `--strict-optional`):

```py
from typing import TypeVar

T = TypeVar('T')

def f() -> T: pass

x = f()
reveal_type(x)  # None
```

It would be better to require an annotation for `x`.

**Comment by gvanrossum** [comment]
Why is the definition of f() not considered an error?

**Comment by ilevkivskyi** [comment]
@gvanrossum 
> Why is the definition of f() not considered an error?

Because it is not unsafe. As discussed in https://github.com/python/mypy/issues/2885 we can't prohibit _all_ possible useless annotations. Moreover now we have https://github.com/python/mypy/issues/4066, so that I think the way forward is to prohibit empty bodies (so that one can't make a body for such annotations).

**Comment by gvanrossum** [comment]
It may not be unsafe, but I'm pretty sure that whenever you see that, the user misunderstands what type variables are on a fundamental level (e.g. they confuse them with type aliases).
