### ISSUE TITLE
Display daemon stdout and stderr in client (including stack traceback)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4187]
Currently if the daemon crashes, the dmypy client doesn't display the traceback:

```
Response: {'error': 'No data received', 'roundtrip_time': 12.825819969177246}
```

Instead, display a traceback and whatever other output is produced by the daemon.

Also, if I add debug prints to mypy, I'd like to see their output when using `dmypy`. It's okay not to stream them, but I'd like the daemon to capture whatever I write to stdout/stderr and pass it to the client, which would then show it.

This is currently possible through `dmypy daemon` but it's not very user-friendly. I need to have a separate terminal if I want to see the output in real time, and if I forget to use it I won't see the output.

**Comment by gvanrossum** [comment]
Perhaps not quite what you want yet, but there's now another option: `dmypy [re]start --log-file <file>` will stream stdout and stderr to `<file>` rather than throwing it away. When I want it streamed I start a process `tail -f <file> &`.

I'll keep this open because capturing output (at least stdout) and reporting it back to the client also makes sense.

**Comment by gvanrossum** [comment]
Do you still want this or does `--log-file` satisfy your needs?

**Comment by msullivan** [comment]
This is partially fixed, and I think we only really want to collect crash tracebacks. Closing in favor of a bug tracking the crash tracebacks we still miss (#4804)
