### ISSUE TITLE
Make the 2 last parameters for typing.Generator optional

### ISSUE THREAD

**Issue by sametmax** [python/mypy#4221]
If I use:

    Generator[int]

mypy complains:

    error: "Generator" expects 3 type arguments, but 1 given

I can silence mypy by doing:

    Generator[int, None, None]

But given that the majority of generators just yield, rarely return or send, I think it would make sense to allow the last 2 parameters to have a default value of None.

**Comment by ethanhs** [comment]
This issue is probably better suited to be discussed in the typing repo https://github.com/python/typing

**Comment by JukkaL** [comment]
Is there a reason you can't use `Iterator[int]` as the return type?

**Comment by zeth** [comment]
> Is there a reason you can't use `Iterator[int]` as the return type?

Because the type is a Generator. Are we annotating the types or not?

**Comment by hauntsaninja** [comment]
We are annotating the types, all three of them, yield send and return ;-) For everything else, there's Iterator.

While I don't think this is a compelling case since there's a solution that works perfectly well, I'm sympathetic to the idea of defaults for generic types in general. The forum to take that issue up is the typing-sig mailing list or https://github.com/python/typing
