### ISSUE TITLE
Unsupported type Type[...] error when instantiating NamedTuple from class variable

### ISSUE THREAD

**Issue by joshstaiger** [python/mypy#4300]
Run mypy 0.550 on the following code

```python
from typing import NamedTuple, Type, cast

class A(NamedTuple): ...

A1: Type[A] = A  # no error
A2: Type[A] = A  # error: Unsupported type Type["A"]
A2()

def j(cls: Type[A]) -> None:  # error: Unsupported type Type["A"]
    cls()

class B(): ... # no error

B1: Type[B] = B
B1()
```

I see `error: Unsupported type Type["A"]` on the lines for `A2` and `def j`, but not in other places, as indicated.  

I'm probably hitting an edge case for `NamedTuple` here.

**Comment by gvanrossum** [comment]
The really odd thing is that removing the `A2()` call makes the error go away. I have a feeling that the error is really for that call but is given the line number for the *definition* of `A2` instead of the call line.

**Comment by ilevkivskyi** [comment]
FWIW I have seen a very similar problem when working on self types in generic classes. Hopefully, my fix will also fix this one.

**Comment by mitar** [comment]
One more example:

```python
import typing

T = typing.TypeVar('T')
L = typing.TypeVar('L', bound='List')

class List(typing.List[T]):
    def __init__(self, iterable: typing.Iterable = ()) -> None:
        super().__init__(iterable)

    def copy(self: L) -> L:
        return type(self)(self)
```

**Comment by mitar** [comment]
But this works:

```python
import typing

T = typing.TypeVar('T')
L = typing.TypeVar('L', bound='List')

class List(typing.List):
    def __init__(self, iterable: typing.Iterable = ()) -> None:
        super().__init__(iterable)

    def copy(self: L) -> L:
        return type(self)(self)
```

So if I do not use `T` in `class List(typing.List[T]):`.

**Comment by ilevkivskyi** [comment]
It looks like instantiating (calling) ``Type[X]`` sometimes has problems if ``X`` is:
* a tuple type
* a generic type
* type variable with a bound to the above

Maybe there are some more details.

**Comment by mitar** [comment]
And `Type[X]` is called somewhere internally?

**Comment by mitar** [comment]
Is there any way to silence this error?

**Comment by ilevkivskyi** [comment]
> Is there any way to silence this error?

Hm... this is the problematic part. It looks like it is impossible to silence the error if the ``Type[...]`` comes from ``type(self)`` or similar. I am therefore setting priority to high (anyway I wanted to work on this around New Year).

**Comment by mitar** [comment]
The issue is also that this is not available: https://github.com/python/mypy/issues/626

**Comment by elliott-beach** [comment]
There's a test  (by @gvanrossum) describing that you can't take the type of a Tuple from when `Type[C]` was implemented: https://github.com/python/mypy/blob/d8892c453ef8becd888b12b5812f0c0abbfc4c98/test-data/unit/check-classes.test#L2432-L2437
 


Since the above is basically taking `Type`[tuple], it seems like that is behavior is intended, or at least already known. `testTypeUsingTypeCErrorUnsupportedType` covers the same thing.

The behavior is basically caused by there being no case for `TupleType` in `analyze_type_callee_callee`, which builds the new type object: https://github.com/python/mypy/blob/d8892c453ef8becd888b12b5812f0c0abbfc4c98/mypy/checkexpr.py#L649. 

The error with generics is related to the same function and also seems like a deliberate choice by @gvanrossum (https://github.com/python/mypy/blob/master/mypy/checkexpr.p#L672-L673).

Since I've looked in to this, I would like to fix it, but that would hasty without more info.

**Comment by gvanrossum** [comment]
Note the difference between `tuple` and `Tuple`. PEP 484 forbids `Type[Tuple[...]]` but allows (implicitly) `Type[tuple]`. Since `NamedTuple` is closest to `Tuple[...]` (it has a fixed set of fields) it stands to reason that it's disallowed as well.

IMO the only real issue is that
```
A1: Type[A]
```
doesn't give an error unless you try to call `A1()`, and that it then puts the error on the definition of `A1` rather than at the call site. Something's definitely fishy there.

**Comment by JukkaL** [comment]
`Type[A]` if `A` is a named tuple seems well-defined, unlike `Type[Tuple[...]]`, since there is a specific type object `A` (and similarly for subclasses of `A`). There is no type object that is specific to `Tuple[int, str]`, for example (it's just `tuple` which is shared between all tuple types).

**Comment by gvanrossum** [comment]
That's a good point. Maybe PEP 484 should be clearer on this (especially if
we actually get a PR that fixes this for NamedTuple).

**Comment by elliott-beach** [comment]
Because `namedtuple` is a normal subclass of `tuple`, I think you could say the behavior should be that `Type[A]` where `A` is a subclass of `tuple` should work. 

Oddly (to me), this behavior does work when simply subclassing `tuple`, e.g.,
```
class MyTuple(tuple):
    pass
A: Type[MyTuple] = MyTuple
A((1,2))  # no error
```
This happens because `MyTuple` is an `Instance` whereas a namedtuple type is a  `TupleType`.
So the special type of NamedTuple is the only case that is handled incorrectly.

**Comment by gvanrossum** [comment]
There's nothing "normal" about NamedTuple. :-(

Note that when you subclass tuple, it ends up being a variable-length tuple that's homogeneously typed (all items have the same type). Both NamedTuple and Tuple are fixed-length tuples with heterogeneous types (each item has its own type). That's the reason they are special.

**Comment by elliott-beach** [comment]
Sorry, thanks for explaining that.

**Comment by ilevkivskyi** [comment]
One minor comment to future self: the formatting for this error is also wrong it looks like
```
__main__.py: error: Unsupported type Type["L"]
```
instead of
```
__main__.py: error: Unsupported type "Type[L]"
```

**Comment by gvanrossum** [comment]
We should at the very least add the line number to the error. This is already a high priority issue.

**Comment by ilevkivskyi** [comment]
All the original examples now pass correctly, the only remaining problem is that now reasonably invalid (from mypy's point of view) things like `type((1, 2))()` cause an error that has wrong formatting and don't have a line number:
```
test.py: error: Unsupported type Type["Tuple[int, int]"]
```

**Comment by ilevkivskyi** [comment]
A similar example just came in https://github.com/python/mypy/issues/7086.

**Comment by lovasoa** [comment]
Hello ! Any news on this ?
This seems to be a blocker for https://github.com/lovasoa/marshmallow_dataclass/pull/77

**Comment by JukkaL** [comment]
This seems to work now using the latest git master.
