### ISSUE TITLE
"Dict entry 0 has incompatible type "str": "int"; expected "bytes": "Any""

### ISSUE THREAD

**Issue by Zheaoli** [python/mypy#4304]
~~~Python
from typing import Dict, List, Any, AnyStr, TypeVar
def abc(xyz: str) -> Dict[AnyStr, Any]:
    return {"abc": 1}
~~~

And I use mypy to check this file. It's giving an Error.

Below is the Error message

> "Dict entry 0 has incompatible type "str": "int"; expected "bytes": "Any""

But I don't know why

**Comment by ilevkivskyi** [comment]
This is because ``AnyStr`` is a type variable that ranges over ``str`` and ``bytes``. What you probably wanted is ``Union[str, bytes]``.

After seeing several questions like this, I think maybe we need to rename ``AnyStr`` to something that sounds more like type variable? For example ``StrVar`` or similar. Or just add some big red warning to the docs?

**Comment by JukkaL** [comment]
`AnyStr` is often confusing, but just renaming it perhaps wouldn't help much, since I expect people to have trouble understanding the concept behind it. Here better error messages would likely help. Here's an idea:

```
t.t2.py:3: note: If the value of type variable "AnyStr" is "bytes":
t/t2.py:3: error: Dict entry 0 has incompatible type "str": "int"; expected "bytes": "Any"
t.t2.py:3: note: ("AnyStr" ranges over "str" and "bytes"; see also <relevant doc url>)
```

The link could point to an entry that discuss common issues with `AnyStr` and possible solutions.

**Comment by JukkaL** [comment]
Tagged as feature (better error message).

**Comment by JelleZijlstra** [comment]
Maybe we should reject the function signature in the original report. Could a function with the signature `def abc(xyz: str) -> Dict[AnyStr, Any]:` have any valid return statement other than `return {}` or similar?

**Comment by JukkaL** [comment]
Yeah that's a good point, though similar things can happen when `AnyStr` is used in an argument type. The return statement could also be something like `return SubClassOfDict()`, which might actually be reasonable in some cases.

More generally, if a type variable is only used in a return type, and there is any other error within the body of the function, we could perhaps generate a hint that warns about using a type variable only in the return type. This way `return {}` would still be accepted, assuming there are no other errors within the function -- but if there are other errors, the extra note would be benign since the build will be failing anyway.

**Comment by hauntsaninja** [comment]
We've implemented more diagnostics to catch incorrect use of type vars
