### ISSUE TITLE
Proper way to type circular dependency

### ISSUE THREAD

**Issue by gpkc** [python/mypy#4440]
The following code generates `F821 - undefined name 'B'` on the `A.__init__` method:

```
class A:
    def __init__(self, B_obj: B) -> None:
        pass


class B:
    def __init__(self, A_obj: A) -> None:
        pass
```

What would be the best way to declare those typings?

**Comment by ilevkivskyi** [comment]
Please see http://mypy.readthedocs.io/en/latest/kinds_of_types.html?highlight=forward#class-name-forward-references and also PEP 563

**Comment by Menda** [comment]
I came across this issue when those classes are set in different files (`a.py` and `b.py`) and they are dependent on each other, so declaring the import statements at the beginning would cause a circular import when executing the program.

To avoid it:

```
# a.py
from typing import List, TYPE_CHECKING

if TYPE_CHECKING:
    from .b import B

class A:
    def __init__(self, B_obj: B) -> None:
        pass
```

More info: https://mypy.readthedocs.io/en/latest/common_issues.html?highlight=TYPE_CHECKING#import-cycles

**Comment by codewithpatch** [comment]
> The following code generates `F821 - undefined name 'B'` on the `A.__init__` method:
> 
> ```
> class A:
>     def __init__(self, B_obj: B) -> None:
>         pass
> 
> 
> class B:
>     def __init__(self, A_obj: A) -> None:
>         pass
> ```
> 
> What would be the best way to declare those typings?

I'd like to ask - is this a good design to do?
I'm having lots of circular dependency in my project using this design due to type annotations. I was solving it using forward reference `from future import annotations` 

But I was advised by my our techlead that it is better to make a flat hierarchy. The problem is, by doing his advise - there is going to be a huge refactor that will happen with the code.

Something like this is what he advised
```
module_a/
 __init__.py
 A.py

module_b/
 __init__.py
 B.py

root or a module_c/
 main.py -> imports both A and B and translates between them
```

I like my current implementation since it saves me from creating a 3rd class in module C. Yet I was advised that it is not a good thing to do.

Anyone can share their thoughts about this?

**Comment by KuSi833** [comment]
I have a similar issue in the relationship between a Chart, and the Elements being drawn on it. 
The charter contains a List[Element] of all the elements it contains,
and each element needs a reference to the Charter to be able to reference certain variables defined on the Charter level.

Tkinter works in a similar fashion where each object that is created has reference to the root, and the root has reference to all elements on it. I very much prefer this design choice over having a 3rd class.

**Comment by JukkaL** [comment]
You can sometimes avoid circular dependencies by using Abstract Base Classes or protocols, but introducing them can be non-trivial.

**Comment by KuSi833** [comment]
The class Element is an Abstract base Class, but since every Element needs to be assigned to a Chart the Circular dependency issue already arises there. Could this be solved using protocols?

So far importing annotations from __future, and then importing the types at the end seems to be a good solution,
I wouldn't want to introduce too much complexity with protocols.
