### ISSUE TITLE
Python 2: Says isinstance(string_obj, six.text_types) is unicode

### ISSUE THREAD

**Issue by JohnVillalovos** [python/mypy#4516]
mypy is claiming that the variable should be of type 'unicode' when it should allow type 'str'

Sample code:

```
#!/usr/bin/python -ttu

import sys
from typing import Any

import six

def main():
    foo("hello")


def foo(a):
    # type: (Any) -> None
    reveal_type(a)
    b = "hello"
    reveal_type(b)
    if isinstance(a, six.string_types):
        reveal_type(a)
        b = a
        print "Type of 'a' is {}".format(type(a))

if '__main__' == __name__:
    sys.exit(main())
```

Output is:

```
$ mypy --py2 tt.py
tt.py:14: error: Revealed type is 'Any'
tt.py:16: error: Revealed type is 'builtins.str'
tt.py:18: error: Revealed type is 'builtins.unicode'
tt.py:19: error: Incompatible types in assignment (expression has type "unicode", variable has type "str")
```

If I run the program (commenting out the 'reveal_type()' lines) I see:

```
$ ./tt.py
Type of 'a' is <type 'str'>
```

**Comment by gvanrossum** [comment]
What's the definition of six.string_types *in typeshed*?

**Comment by JohnVillalovos** [comment]
I see this:

```
$ cat .tox/pep8/lib/mypy/typeshed/third_party/2/six/__init__.pyi | grep string_types
string_types = (str, unicode)
```

**Comment by gvanrossum** [comment]
I don't think there is a bug here. Mypy (obviously) doesn't take into
account the call to foo("hello") from main() -- all it uses when
type-checking foo() is that the argument a is declared as Any, and then
inside the isinstance() check it is refined to the union of str and
unicode. That union happens to be equivalent to just unicode, since mypy
treats str as a subtype of unicode. So at that point a is assumed to have
type unicode (as revealed). But the variable b is initialized from a plain
string (b = "hello") so its type is inferred as str. While mypy considers
it safe to assign str to unicode (since it treats str as a subclass of
unicode), the same rule makes it disallow assigning unicode to str.

You can fix your code by adding `# type: unicode` to the initialization of
b.

**Comment by JohnVillalovos** [comment]
Well this is just a sample script to narrow down the issue. The problem I have is a bigger code base where it is not 'unicode' but 'str'. we Have a dict where various types are stored as the values, so I used 'Any'.

The code is here:
https://github.com/openstack/ironic-lib/blob/8f4e89facd86c65d760b47d5b82df5856f375a34/ironic_lib/utils.py#L289-L297

Line 297 is where I am seeing the error as I add the type hints.

On line 262 I am doing:
```
 def parse_root_device_hints(root_device):
     # type: (Dict[str, Any]) -> Dict[str, Any]
```

And get the same type of error.

**Comment by gvanrossum** [comment]
I'm sorry, I can't help you debug this if you don't show me the exact code you're checking. I don't see the annotation you claim to have on line 262 so I presume there are also other annotations you aren't showing. In any case I really don't think there's a mypy or typeshed bug, you just need to get your head around how mypy infers types (and probably read up on invariant types). Remember, `reveal_type()` is your friend!
