### ISSUE TITLE
Docs: should generators return `Iterator`, not `Iterable`?

### ISSUE THREAD

**Issue by neilconway** [python/mypy#4707]
The cheat sheet says:

```python
# A generator function that yields ints is secretly just a function that
# returns an iterable (see below) of ints, so that's how we annotate it.
def f(n: int) -> Iterable[int]:
    i = 0
    while i < n:
        yield i
        i += 1
```

This is not wrong, but it results in a valid program like this failing to type-check:

```python
print(next(f()))
```

If `f()` was declared to return `Iterator` instead, this program would typecheck. Calling `next` on a generator is a reasonably common thing to do, so I'd argue this is a surprising result.

**Comment by gvanrossum** [comment]
That's true, but to counter this, the cheat sheet isn't supposed to be a complete reference. I'd claim that calling `next()` directly is somewhat esoteric, and trying to explain the difference between `Iterator` and `Iterable` in a cheat sheet does not serve the purpose of keeping it short and sweet. I hope you'll agree with me that in general `Iterable` is more useful than `Iterator`.

**Comment by neilconway** [comment]
Fair point. My perspective is that `Iterator` is the more specific type; when annotating a return type, this gives the user access to more functionality than `Iterable` and avoids surprising situations like the one pointed out above. If the user wants to declare they are returning a more abstract type, then fair enough, but that's a design decision they should make intentionally.

**Comment by pawel-slowik** [comment]
Annotating a generator as an Iterable can lead to user confusion in case the caller tries to loop over the result more than once. This silently fails, because the iterator is exhausted. The caller reasonably expects to be able to loop over the result multiple times, because there's nothing in the Iterable protocol that forbids this.

I understand the "typehint as something you can loop about" sentiment (as opposed to "typehint as something that reveals implementation details"). But using the Iterable interface to mask an Iterator creates a sneaky problem of distinguishing between "something you can loop about" and "something you can loop about _once_".

**Comment by gvanrossum** [comment]
There is no type that indicates "can be iterated multiple times" since `Iterator` is a subtype of `Iterable`. In fact, a common error is defining a function that takes an `Iterable` and tries to iterate over it multiple times, and then passing it an `Iterator`. This type-checks (since `Iterator` has an `__iter__` method) but fails at runtime.

In newer Python 3 versions we have `Collection` for this purpose, but it's basically a union of `Set` and `Sequence`.

**Comment by pawel-slowik** [comment]
> There is no type that indicates "can be iterated multiple times"

I thought that that's what Iterables are for, but now I can see that this is not true.

Thanks for clearing that up.

**Comment by gward** [comment]
This appears to have been resolved in https://github.com/python/mypy/pull/6896. Close this issue?
