### ISSUE TITLE
Inner class not recognised

### ISSUE THREAD

**Issue by spkersten** [python/mypy#474]
Consider this snippet:

``` python
from typing import *

class A:
    class B:
        pass

    def f() -> None:
        x = []  # type: List[B]
```

mypy outputs:

```
In function "f":
line 8: Name 'B' is not defined
```

**Comment by elazarg** [comment]
I don't understand this issue, The inner class is recognized when accessed using `A.B` as it should be. If the discussion is about `self.B` (which to me sounds like requiring Scala-style path-dependent type system) then the title of the issue and the example are unrelated.

**Comment by gvanrossum** [comment]
Looking at the original example, I think PEP 484 is not completely clear about the scope in which type comments like `# type: List[B]` are looked up; for type annotations in argument declarations the scope might be different than for variable declarations in the body.

However PEP 526 provides an alternate syntax that requires the type to be evaluatable:
```python
class A:
    class B:
        pass

    def f() -> None:
        x: List[B] = []
```
Here B is clearly inaccessible (because of Python's inscrutable scope rules for method bodies, which intentionally skip the containing class's scope) so I think we should use the same rule for type comments.

Closing; agreed that the discussion about subclasses of A overriding B belongs somewhere else.
