### ISSUE TITLE
Error while multiplying a `SupportsInt` and an int

### ISSUE THREAD

**Issue by akaptur** [python/mypy#4758]
I've got the following code:
``` python
from decimal import Decimal
d = Decimal('10')
x = max(d, 0) * 3
```
Mypy types `max(d, 0)` as a SupportsInt, which seems correct, but then complains:
```
test.py:3: error: Unsupported operand types for * ("SupportsInt" and "int")
```
I expect to be able to perform any operation between X and SupportsX if that operation is supported between X and another X.

This is mypy 0.570 and the underlying code is Python 3.6.1. I can reproduce this issue with no flags passed.

**Comment by gvanrossum** [comment]
Hi Allison, `SupportsInt` basically means that an object can be passed to `int()`. This class does not itself have operator overload behavior like `__add__`.

It is derived as the return type for `max()` in your example because it's the common superclass for `Decimal` and `int` (the types of the arguments you pass it).

Your best option is probably to use `max(d, Decimal(0))` instead.

**Comment by msullivan** [comment]
Is there a documentation bug here that we should fix, or should we just close this?

**Comment by JukkaL** [comment]
I'll add a note about this to the documentation of `SupportsInt`.
