### ISSUE TITLE
Cannot specify return type with Union[..., NotImplemented] (and others, e.g. Ellipsis)

### ISSUE THREAD

**Issue by kamahen** [python/mypy#4791]
**[UPDATE:** The reported behavior happens only with `--warn-return-any` or `--strict`.]

Mypy gives `warning: Returning Any from function declared to return "bool"` for
```python
class C:
    def m(self) -> bool:
        return NotImplemented
```

So, try this:
```python
from typing import Union
class C:
    def m(self) -> Union[bool, type(NotImplemented)]:
        return NotImplemented
```
which gives error
```
q.py:3: error: invalid type comment or annotation
q.py:3: note: Suggestion: use type[...] instead of type(...)
```

Following mypy's suggestion results in:
```
q.py:3: error: Return type becomes "Union[bool, Type[Any]]" due to an unfollowed import
q.py:4: warning: Returning Any from function declared to return "Union[bool, Type[Any]]"
```

which also gives a runtime error: `TypeError: Parameters to generic types must be types. Got NotImplemented.` or (when attempting `type[...]`) `TypeError: 'type' object is not subscriptable`.

(See also pull #4770, which attempts to fix some magic methods)

There seem to be two issues:

1.  Only magic methods can return `NotImplemented` without a complaint from mypy
2.  If the programmer tries to get rid of the mypy complaint by specifying `-> Union[bool, type(NotImplemented)]`, mypy doesn't like that and suggests changing it to `-> Union[bool, type[NotImplemented]]`, which gets a runtime error (`Type[NotImplemented]` doesn't work either).

**Comment by Strilanc** [comment]
A similar issue occurs with `Ellipsis`. For example, if you try to specify the type of a method which operates on slices possibly involving ellipses, there's no way to say "I return a tuple containing items that are an integer, a slice instance, or Ellipsis".

I suggest that these, and other, builtin singleton values be handle the same way that `None` is handled. If you say `Union[int, None]`, that's the same as saying `Optional[int]` even though *technically* you should say `type(None)` or `NoneType` instead of `None` because `None` is a value not a type.

**Comment by Strilanc** [comment]
Using the string `'NotImplemented'` appears to work when invoking mypy and at runtime.

**Comment by ilevkivskyi** [comment]
Yes, I think we can allow `NotImplemented` as a singleton (you can open an issue on `typing` tracker for the runtime part). But `Ellipsis` will be harder, since it already has special meaning, for example `Tuple[int, ...]` is a variable length tuple. How would we distinguish it from a tuple of two elements? (A similar problem appears for `Callable`).

**Comment by whatisaphone** [comment]
I suggest mypy continues to treat `...` as it does today, but treats the long spelled-out form `Ellipsis` as the type of the singleton. In other words:

```py 
foo: Tuple[int, ...] = (2, 3, 4)
foo: Tuple[int, Ellipsis] = (2, ...)
```

Switching them around would cause errors in both cases:

```py 
foo: Tuple[int, Ellipsis] = (2, 3, 4)  # error: 3 elements found, but only 2 expected
foo: Tuple[int, ...] = (2, ...)  # error: type(Ellipsis) is not assignable to int
```

**Comment by 625781186** [comment]
![image](https://user-images.githubusercontent.com/30521429/78107417-fe774f80-7427-11ea-959a-bf0466661d55.png)

You can't express the meaning that `return a list just only have 2 element` ,

**Comment by jack1142** [comment]
Could also just support usage of `type(Ellipsis)`/`type(...)` as a type alias (maybe explicit type alias, i.e. PEP 613), so that one could do:
```py
EllipsisType = type(Ellipsis)

foo: Tuple[int, EllipsisType] = (2, ...)
```
How does that look?

> I suggest mypy continues to treat ... as it does today, but treats the long spelled-out form Ellipsis as the type of the singleton.

As far as I know, this would not be really possible as `Tuple[int, ...]` and `Tuple[int, Ellipsis]` mean the same at runtime.

**Comment by hauntsaninja** [comment]
Some more discussion at https://mail.python.org/archives/list/typing-sig@python.org/thread/277RFXNQYLT6D3R4EYZZOPPGX56SNIK6/

**Comment by julian-klode** [comment]
So, `NotImplemented` worked fine as a return type in e.g. `Union[int, NotImplemented]` in mypy 0.782, but now in mypy 0.790 it says

```
apt/package.py:473: error: Variable "builtins.NotImplemented" is not valid as a type
apt/package.py:473: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
```

Making it a `Literal[NotImplemented]` does not help:

```
apt/package.py:473: error: Parameter 1 of Literal[...] is invalid
```

I'm a bit unhappy.

**Comment by hauntsaninja** [comment]
mypy_primer bisects this to https://github.com/python/typeshed/pull/4222 to fix https://github.com/python/typeshed/issues/3315
Previously NotImplemented was just Any, which is why you got the complaint with `--warn-return-any`.

Seems like we should sprinkle some more special casing on this. Not the greatest workaround, but you could use `NotImplementedT = Any`. You could also dangerously rely on typeshed implementation details here and do some `if TYPE_CHECKING` stuff.
In most cases, I think the best thing to do is to not put NotImplemented in the return type and just type ignore if using with `--warn-return-any`. (You should only want to be able to put NotImplemented in your return type if you want all callers to be aware of that and have to check that the returned value is NotImplemented)

**Comment by julian-klode** [comment]
Yeah, um, in my case I'm not sure what the code is doing, as it wraps a cmp-style function, and the callers then do > 0, for `__gt__` for example, which produces a `TypeError` with `TypeError: '>' not supported between instances of 'NotImplementedType' and 'int'`. I think that code is buggy, as the `__gt__` functions and friends should forward `NotImplemented` return, but then mypy never gave me a bug about that :/

**Comment by EPronovost** [comment]
@julian-klode Not sure about your situation but I just encountered issues related to `NotImplemented` after upgrading to `mypy 0.790`.  Here is the commit that fixed things for me.  https://github.com/numba/numba/pull/6222/commits/55b6edaa0e5395476809b14af94c67ad1c5cefa0

**Comment by ItsDrike** [comment]
> @julian-klode Not sure about your situation but I just encountered issues related to `NotImplemented` after upgrading to `mypy 0.790`. Here is the commit that fixed things for me. [numba/numba@55b6eda](https://github.com/numba/numba/commit/55b6edaa0e5395476809b14af94c67ad1c5cefa0)

This is interesting, yet really weird. It means that mypy will handle something like this:
```py
def foo() -> bool:
    return NotImplemented
```
as valid type-wise, even though this function never actually returned what was expected of it (being a bool). This probably shouldn't be the case. Even though it may be helpful since it allows for marking the return type of `__gt__` or other comparison methods as simple `bool` even though it may also return `NotImplemented`, but I'm a lot more inclined to just use a union with NotImplemented and a bool which is more explicit and doesn't allow weird behavior like this.

Also, since I didn't see any quick fix for this, if someone needs it, this is how I was able to get a mypy compliant annotation that works without issues:
```py
NotImplementedType = type(NotImplemented)

def foo() -> NotImplementedType:
    ...
```
I'm relying on `type(NotImplemented)` to get the internal builtin `NotImplementedType` because for some reason, it isn't included in the `types` stdlib module which is the place I'd expect it to be defined.

**Comment by flisboac** [comment]
@ItsDrike In mypy 0.930, `def foo() -> bool` works (but should it? I think not).

But `NotImplementedType = type(NotImplemented)` fails with the message:

> Variable "__main__.NotImplementedType" is not valid as a type
> See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases

**Comment by hauntsaninja** [comment]
mypy is basically working as expected here. `NotImplemented` is allowed to duck type to better integrate with Python's data model. Any follow-ups are perhaps better discussed over at typeshed.

**Comment by alexshpilkin** [comment]
@hauntsaninja

> `NotImplemented` is allowed to duck type to better integrate with Python's data model. Any follow-ups are perhaps better discussed over at typeshed.

This does not make any sense whatsoever to me, sorry. Can you elaborate?

Is every type in Mypy implicitly a union with `NotImplementedType` (and if so, where is that documented, if anywhere)? Are the double-dispatch arithmetic and comparison dunders special-cased (and if so, how do I get that treatment for my own methods or functions, given Mypy doesn’t seem to recognize `NotImplementedType`)? Is there a sense of “duck typing” in which `NotImplemented` does legitimately act like a bool, an int, a `fractions.Fraction`, and every other arithmetic-like (not a technical term) type now known or heretofore invented?

I don’t mean to be confrontational, I really don’t, but these are the best of my guesses at what you could mean and they all sound kind of stupid to me now that I’ve written them out. What am I missing?

**Comment by erictraut** [comment]
`types.EllipsisType` was [added in Python 3.10](https://bugs.python.org/issue41810).

**Comment by alexshpilkin** [comment]
@erictraut So `typeshed` just needs to be changed to stop faking it (in https://github.com/python/typeshed/blob/2cd8f26e6671724351dd8d2b92f22738d8e85df8/stdlib/builtins.pyi#L1908)? OK, I see.
