### ISSUE TITLE
Is there a way to define a name as "something that can be json serializable"?

### ISSUE THREAD

**Issue by leandropls** [python/mypy#4972]
I was thinking something down the lines:

```
JsonDataTypes = Union[
    JsonDataTypes,
    Dict[JsonDataTypes, JsonDataTypes],
    List[JsonDataTypes],
    Tuple[JsonDataTypes]
]
```

But it obviously doesn't work.

**Comment by JelleZijlstra** [comment]
Not currently. See python/typing#182 for some prior discussion.

**Comment by ltalirz** [comment]
Looks like the consensus was that this is not going to be added to CPython's `typing.py` https://github.com/python/typing/issues/182#issuecomment-1320974824 (but type checkers like mypy could choose to implement aliases)

**Comment by ssbarnea** [comment]
To be honest I think that the issue was closed as fixed without even have a proof that it was. I spend a lot of trying trying to get a JSON-type to work and just to get to the conclusion that it is still not possible. I hope someone can prove me wrong here.

The tricky bit is that, in order to be of practical use, we would need one that works with:
- mypy
- pylance
- py38+ or newer (some projects may find py39+ acceptable too)
