### ISSUE TITLE
Calling __new__ via super

### ISSUE THREAD

**Issue by ltworf** [python/mypy#4991]
I just encountered this bug again: https://github.com/python/mypy/issues/1053

I checked this code, to make a subclass of tuple:

```
class A(tuple):
    def __new__(cls, fields):
        return super(A, cls).__new__(cls, tuple(fields))
```

With those settings:

```
python_version=3.5
warn_unused_ignores=True
warn_redundant_casts=True
strict_optional=True
scripts_are_modules=True
check_untyped_defs=True
```

Using mypy 0.590

And it results in

```
/tmp/test.py:3: error: Too many arguments for "__new__" of "object"
```

**Comment by ilevkivskyi** [comment]
I think this is actually a typeshed problem. I just looked through some stubs and noticed that there are some places where `__new__` is missing. Namely, `tuple` defines `__init__` instead on both Python 2 and 3 which doesn't really makes sense, since it is immutable, `tuple` should actually define `__new__` with the same signature. I don't know if other projects depend on this "fake" `tuple.__init__`, but I propose to close this issue and move to typeshed tracker. @JelleZijlstra what do you think?

**Comment by ltworf** [comment]
Sorry if it's misplaced. I opened it here because I thought it might be a regression from the old bug.

**Comment by ltworf** [comment]
https://github.com/python/typeshed/issues/2091
