### ISSUE TITLE
False exception error in raise statement with a ternary conditional operator

### ISSUE THREAD

**Issue by bonotake** [python/mypy#5128]
I faced with a strange mypy error, with such a code below:
```Python
def foo() -> None:
    message = 'test'
    raise Exception(message) if message else Exception  # -> mypy error


def bar() -> None:
    raise Exception  # ok


def baz() -> None:
    message = 'test'
    raise Exception(message)  # ok


def qux() -> None:
    message = 'test'
    raise Exception if not message else Exception(message)  # -> mypy error


if __name__ == '__main__':
    foo()
```

It seems legal code, but mypy produces two error messages there. 
```
$ mypy test.py
test.py:3: error: Exception must be derived from BaseException
test.py:17: error: Exception must be derived from BaseException
```
Actually, this error seems to happen not only with `Exception` but with any other built-in exceptions.
The version of mypy is 0.600, and that of Python is 3.6.3.

Thanks in advance.

**Comment by gvanrossum** [comment]
If you change it to
```py
    raise Exception() if not message else Exception(message)
```
then it will pass.

The reason is that mypy tries to do a join on the two branches of the conditional expression and it doesn't find a common base between `Exception` (a type) and `Exception(message)` (an Exception instance), so it infers the combined type as `object`, which is illegal for `raise`.

I think we can fix this easily by evaluating the expression for `raise` in the context `Union[Type[BaseException], BaseException]`.

**Comment by JelleZijlstra** [comment]
This is probably related to #5095, which partially reverted #5041.

**Comment by gvanrossum** [comment]
Well my guess is that `raise` doesn't provide the right context to the
expression. A function with the Union type I suggested worked.

**Comment by hauntsaninja** [comment]
Fixed in https://github.com/python/mypy/pull/17427
