### ISSUE TITLE
type refinement in function call

### ISSUE THREAD

**Issue by dfroger** [python/mypy#5206]
This is ok for mypy:

```
from typing import Union

def foo(x: Union[int, str]):
    if isinstance(x, int):
        return x + 10
```

but how can I make it work if the `isinstance` test is in a function call?

```
from typing import Union

def check(x: Union[int, str]) -> bool:
    return isinstance(x, int)

def foo(x: Union[int, str]):
    if check(x):
        return x + 10
```

I get:

```
foo.py:8: error: Unsupported operand types for + ("Union[int, str]" and "int")
```

**Comment by JelleZijlstra** [comment]
This could perhaps be done with literal types in the future, something like this:
```
@overload
def check(x: int) -> Literal[True]: ...
@overload
def check(x: str) -> Literal[False]: ...
```

**Comment by gvanrossum** [comment]
That's pretty verbose though..

**Comment by gwerbin** [comment]
I've had this issue recently too. I definitely think Mypy would benefit from some way to refine types by following conditional paths. Unfortunately implementing that kind of logic is well beyond my expertise.

**Comment by elazarg** [comment]
Related: #1203, #2357 #4063, #3062

**Comment by ilevkivskyi** [comment]
Here I copy the relevant link from one of the above issues I just closed https://github.com/Microsoft/TypeScript/issues/1007

**Comment by dbrgn** [comment]
I've found the TypeScript [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types) to be a very useful concept, especially when dealing with structured data coming in over the network (e.g. a JSON API).

This is the TS syntax:

```typescript
function isNumber(x: any): x is number {
    return typeof x === "number";
}
function isFish(pet: Fish | Bird): pet is Fish {
    return (pet as Fish).swim !== undefined;
}
```

That syntax is probably not feasible in Python (I don't think `pet is Fish` can be used as return type annotation, but can't find the definition for `TYPE_COMMENT` in [the grammar](https://docs.python.org/3/reference/grammar.html)).

Maybe a placeholder type (`def is_fish(pet: Union[Fish, Bird]): TypeAssertion`) could be used, which would tell the type checker to "inline" the type hint function when determining the type refinement in an if statement (or another similar control structure)?

Maybe `TypeAssertion[pet=Fish]` could work as well? Depends on the grammar of course.

**Comment by JelleZijlstra** [comment]
Grammatically type annotations are just expressions, so something like this:
```
def is_number(x: object) -> x is int:
    pass
```
is grammatically valid. However, it has some possible problems:
- The name `x` is obviously not necessarily defined at this point, so if you try this right now you'll likely get `NameError: x is not defined`. This is not a problem if `from __future__ import annotations` is on, because then Python will not attempt to evaluate the annotation.
- The `is` operator cannot be overloaded at runtime, so it's going to be hard to provide runtime introspection of this sort of annotation, although again this is mitigated by `from __future__ import annotations`.

In contrast, your `TypeAssertion[x=int]` syntax is invalid at runtime, so it would be much harder to add than `-> x is int`.

In any case, the bigger difficulty for getting something like this into mypy is going to be first convincing people that it's a good idea and second getting an implementation written and merged into mypy. Syntax is easy. :)

**Comment by dbrgn** [comment]
> first convincing people that it's a good idea

What would be a reason against this (besides implementation complexity)? It considerably helps when dealing with external data, because it combines runtime validation and static type checks.

**Comment by DustinWehr** [comment]
@JelleZijlstra would implementation be easy too? Could you not typecheck a call `is_number(t)` to
```
def is_number(x: object) -> x is int:  # or whatever syntax works
    pass
```
by just virtually (or literally) replacing it with `(is_number(t) and isinstance(t,int))`?

**Comment by DustinWehr** [comment]
How about a bundled do-nothing decorator?
```
@mypypred(t=int)
def is_number(x) -> bool:
    pass
```

**Comment by lubieowoce** [comment]
> by just virtually (or literally) replacing it with `(is_number(e) and isinstance(e,int))`

@DustinWehr a literal `isinstance()` wouldn't work bc it can't be used with e.g. generic types (as they're erased at runtime). but i guess the machinery used for `cast()` could be reused here

**Comment by DustinWehr** [comment]
@lubieowoce I would've guessed the static analyzer's use of `isinstance` isn't encumbered by that runtime constraint. I haven't looked at the code to see the approach taken though. It seems to understand at least simple boolean combinations of `isinstance` expressions (e.g. `isinstance(x,T) and not isinstance(x,T2)`). Maybe they're doing a brute force enumeration of the possible type narrowings along each path (approach I would implement first), or something more complex like symbolic execution.

**Comment by DustinWehr** [comment]
I see that this was already suggested in #7870 by @gantsevdenis.
> How about a bundled do-nothing decorator for the syntax?
> 
> ```
> @mypypred(t=int)
> def is_number(x) -> bool:
>     pass
> ```

**Comment by lubieowoce** [comment]
@DustinWehr i guess i was being a bit pedantic :)  btw if you want to take a look, the logic for isinstance checks seems to start in `mypy.checker.find_isinstance_check`: https://github.com/python/mypy/blob/9101707bd0c96624d09cb31fe573d7e25c89a35c/mypy/checker.py#L3798-L3814

> Maybe they're doing a brute force enumeration of the possible type narrowings along each path

i think that's indeed the case if i'm understanding you correctly. in general 

```
if isinstance (x, A):
  # yes
  ...
else:
  # no
  ...
```
seems to be handled with two different typings of variables, one for the `yes` branch and one for the `no` branch. if the condition is `isinstance(x, A) or isinstance(x, B)`, the two "type narrowings" given by the isinstance checks are combined, giving (more or less) `x: Union[A, B]` etc. see: https://github.com/python/mypy/blob/9101707bd0c96624d09cb31fe573d7e25c89a35c/mypy/checker.py#L3953-L3971

**Comment by vbraun** [comment]
Repeating the name `x` of the argument of the type guard isn't really necessary, the syntax could just be
~~~
def is_integer(x: Any) -> IsInstance[int]   # or TypeAssertion[int] or TypeGuard[int]
    pass
~~~
On a related note, a still-open typescript feature request for is to extend type guards to multiple arguments. It would be nice to cover that use case as well, e.g.
~~~
def is_integer_and_string(x: Any, y: Any) -> IsInstance[int, str]
    pass
~~~

**Comment by wyfo** [comment]
Why do we need a boolean return?

A direct solution to this issue would be to implement type-guard functions to return the checked argument, like a checked cast in fact:
```python
def as_integer(x) -> int:
    if not isinstance(x, int):
        raise ValueError("not an int")
    return x
```
If-else logic can simply be achieved using try-catch-else blocks.
```python
try:
    checked_x = as_integer(x)
except ValueError:
    ...
else:
    ...  # use checked_x as an integer in this block
```
This checked-cast functions can also be used as expression, which is convenient for case like `expect_an_int(as_integer(x))` (but with risks of exception mix up between expect_an_int and as_integer).

Checked-cast functions could also return an `Optional` in order to avoid exception (but that's maybe not suited for some cases)
```python
def as_integer(x) -> Optional[int]:
    return x if isinstance(x, int) else None

if (checked_x := as_integer(x)) is not None :
    ...
else:
    ...
```

Moreover, if several parameters needs to be type-checked, a tuple returns can do the job:
```python
def check_int_and_str(x, y) -> tuple[int, str]:
    if not isinstance(x, int) or not isinstance(y, str):
        raise ValueError("bad types")
    return x, y

checked_x, checked_y = check_int_and_str(x, y)
```

But yes, this solution imply to assign an additional variable (with an additional name), so it's heavier, but **it already works** out of the box and do the job, no PEP required.

**Comment by wyfo** [comment]
That's being said, if boolean type-guard functions have to be implemented in the language (and I would be happy to use them to replace my heavier checked-cast), why not using [PEP 593](https://www.python.org/dev/peps/pep-0593/) `Annotated`?
By adding a standard type annotation (for `Annotated`), one could write something like
```python
from typing import Annotated, TypeGuard

def is_integer(x) -> Annotated[bool, TypeGuard(int, "x")]:  # map the type-guard to the corresponding parameter
    return isinstance(x, int)
```
That could allow type-guarding of several parameters:
```python
def check_int_and_str(x, y) -> Annotated[bool, TypeGuard(int, "x"), TypeGuard(str, "y")]:
    return isinstance(x, int) and isinstance(y, str)
```
Using a PEP 593 type annotation instead of a whole new type has the advantage of **not impacting every tools using type annotation** (as metadata can just be ignored). 
This is also exactly the purpose of PEP 593 as it states:
> a type T can be annotated with metadata x via the typehint Annotated[T, x]. **This metadata can be used for either static analysis** or at runtime. 

The type-guard is indeed a metadata of the function result, but the function still returns a `bool`.

But yes, this solution seems to be a little bit heavier than @vbraun proposal or [PEP 647](https://www.python.org/dev/peps/pep-0647/), but nothing prevent the specification and implementation of my proposal to provide the following shortcuts:
- when no parameter name is passed to `TypeGuard`, i.e. `TypeGuard(int)`, it applies to the first parameter (or the second in case of a method)
- `TypeGuard` has a `__getitem__` method which gives the following result: `TypeGuard[T] == Annotated[bool, TypeGuard(T)]`

A simple implementation would be:
```python
class TypeGuard:
    def __init__(self, tp, param=None):
        self.tp = tp
        if param is not None and not isinstance(param, str):
            raise TypeError("Type guard parameter mapping must be a string")
        self.param = param

    def __getitem__(self, item):
        return Annotated[bool, TypeGuard(item)]
```

It would then possible to write
```python
def is_integer(x) -> TypeGuard[int]: ...
# which would give in fact `def is_integer(x) -> Annotated[bool, TypeGuard(int)]`
# which would thus be equivalent to `def is_integer(x) -> Annotated[bool, TypeGuard(int, "x")]`
```
As easy, but more powerful (support arbitrary parameters), and again, less complexity (no additional `SpecialForm`),  less impact on existant tools. 

@gvanrossum I've discovered PEP 647 while writing this comment; is it too late to add this proposal using PEP 593 to it ? (or to debate if the checked casts of my previous comment are enough or not)

**Comment by gvanrossum** [comment]
Let’s keep the discussion in one place, typing-sig.

**Comment by JelleZijlstra** [comment]
Mypy now supports `TypeGuard` from PEP 647. Closing.

**Comment by espetro** [comment]
Hi everyone! I've created a pretty simple library for refinement types, by making use of PEP 647 (Type guards) and PEP 593 (Annotated types).

Currently, it only works for functions with a @refined decorator, but I'd love to get it to support mypy and other type checkers. Contributions are more than welcome! 😊 🍻

**Comment by antonagestam** [comment]
@espetro You might be interested in [phantom-types](https://github.com/antonagestam/phantom-types), which works with pre-`TypeGuard` type guards, e.g. `isinstance()`. It's also heavily inspired by fthomas/refined. Feel free to reach out in the project's [Discussions](https://github.com/antonagestam/phantom-types/discussions) if you're interested in collaborating! You can see a quick example of how it works in the [Getting Started section](https://phantom-types.readthedocs.io/en/stable/pages/getting-started.html).

\* end of shameless self-plug, sorry for off topic *
