### ISSUE TITLE
NamedTuple should not satisfy Protocol with mutable fields

### ISSUE THREAD

**Issue by pnachum** [python/mypy#5293]
The following code doesn't produce a type error, but will crash at runtime, because the named tuple's fields cannot be set

```python
from typing import NamedTuple
from typing_extensions import Protocol

class HasX(Protocol): 
    x: str
    
class A(NamedTuple):
    x: str

a: HasX = A("foo")
a.x = "bar"
```
Since `HasX` requires `x` to be settable, `A` should not be a structural subtype of `HasA`.

**Comment by ilevkivskyi** [comment]
OK, the solution is super-simple here. Since named tuple variables are "artificial" (auto-generated), and therefore are always created directly as a `Var` with `is_property` set to `True`, they are not identified as immutable by protocol check (it looks for a `property` decorator).

So it would be just one line fix in `subtypes.get_member_flags`, we need to add a check for `v.is_property` in this code:
```pthon
    # just a variable
    if isinstance(v, Var):
        flags = {IS_SETTABLE}
```

Would you like to make a PR?

**Comment by pnachum** [comment]
I'll leave that to people smarter than me 😄.
