### ISSUE TITLE
Overload supertype methods

### ISSUE THREAD

**Issue by marcosschroh** [python/mypy#5633]
I am trying to fix some annotations on magic and normal methods. For example, I have some cases like:

```
class Headers(typing.Mapping[str, str]):
    ...

    def __contains__(self, key: str) -> bool:
        ...
        return False

    def keys(self) -> typing.List[str]:
        ...
        return ['a', 'b']
```

and when I run `mypy somefile.py --disallow-untyped-defs` I have the following errors:

```
error: Argument 1 of "__contains__" incompatible with supertype "Mapping"
error: Argument 1 of "__contains__" incompatible with supertype "Container"
error: Return type of "keys" incompatible with supertype "Mapping"
```

I can fix the error doing `key: typing.Any` and ignoring the second error with `# type: ignore` respectively, but I would like to really specify which type should be in each case.

What I understand is that I need to override the methods using the @override decorator and I need to respect the order of inheritance. Is it correct?

If my assumption is correct, Is there any place in which I can find the exact signatures of the parent classes? Is there anyway to disabled "incompatible with supertype" errors?

Thanks in advance,

Marcos.

**Comment by ilevkivskyi** [comment]
> Is there anyway to disabled "incompatible with supertype" errors?

There is no global flag for this, because Liskov principle is like one of cornerstones of the type system.
You can silence the error by `# type: ignore` of course.

Original definitions can be found in the typeshed repository.

**Comment by ilevkivskyi** [comment]
(Also we prefer Gitter for questions, tracker is mostly for bugs and feature requests.)

**Comment by marcosschroh** [comment]
Thanks for the reply @ilevkivskyi !! 

tracker is mostly for bugs and feature requests: Thanks, good to know for the future!!

**Comment by tomchristie** [comment]
Let me re-phrase this issue, since there are two aspects that don't seem obviously correct to me:

* Subclassing `typing.Mapping[str, str]`, I'd assume that the function signature for the argument `key` in `__contains__` ought to match the generic type?
* Subclassing `def __contains__(self, key)` to `def __contains__(self, key: str)` is in any case more specific. A more specific subtype doesn't violate Liskov, no?

**Comment by Michael0x2a** [comment]
> Subclassing typing.Mapping[str, str], I'd assume that the function signature for the argument key in __contains__ ought to match the generic type?

`__contains__` isn't a generic method -- it's defined to have the type signature `__contains__(self, key: object) -> bool`. You can [check this on typeshed](https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L335). The reason why `__contains__` is defined this way is because doing things like `1 in {"foo": "bar"}` is technically legal.

> Subclassing def __contains__(self, key) to def __contains__(self, key: str) is in any case more specific.

When you're overriding a function, it's ok to make the argument types *more general* and the return types *more specific*. That is, the argument types should be contravariant and the return types covariant.

If we did not follow the rule, we could end up introducing bugs in our code. For example:

    class Parent:
        def foo(self, x: object) -> None: ...

    class Child(Parent):
        def foo(self, x: str) -> None: ...

    def test(x: Parent) -> None:
        x.foo(300)  # Safe if 'x' is actually a Parent, not safe if `x` is actually a Child.

    test(Child())

Because we broke liskov, passing in an instance of `Child` into `test` ended up introducing a bug.

**Comment by tomchristie** [comment]
> __contains__ isn't a generic method -- it's defined to have the type signature __contains__(self, key: object) -> bool

Okay, yes. I think it'd be a perfectly reasonable (but different) behavior if it *was* expected to be generic. (ie. raise TypeErrors for `in` on type-strict containers for invalid comparison types), but either way around seems reasonable ways to have defined the behavior, so.

> When you're overriding a function, it's ok to make the argument types more general and the return types more specific. That is, the argument types should be contravariant and the return types covariant.

Gotcha 👍

Thanks for your time.
