### ISSUE TITLE
Type aliases at function scope does not work as expected

### ISSUE THREAD

**Issue by martin-ejdestig** [python/mypy#5769]
The following code:

```py
from typing import Dict

def foo(text: str) -> str:
    Bar = str
    Baz = Dict[Bar, int]
    return ''
```

Results in mypy0.630 reporting 'error: Invalid type "Bar"'.

If Bar is moved to file scope, there are no warnings.

**Comment by ilevkivskyi** [comment]
This is actually by design. At nested scopes, such as class or function, assignments with a class object in the r.h.s. create a variable with type `Type[...]` instead of an alias. The reason is that this is much more typical use case. Note that a subscripted assignment like `Baz = Dict[str, int]` still creates an alias.

There is a long overdue documentation issue about this https://github.com/python/mypy/issues/3494, and also about the extra-terse error message https://github.com/python/mypy/issues/4030. I will raise priorities of both to high.

**Comment by martin-ejdestig** [comment]
OK. It is very confusing though. :(

**Comment by martin-ejdestig** [comment]
It is very confusing though.

I am also wondering, is there a way to create an alias for str at local scope like in this example? Do not want to pollute the outer namespace.

**Comment by ilevkivskyi** [comment]
Why do you need create an alias to `str`? Maybe what you want is a `NewType` actually?

**Comment by martin-ejdestig** [comment]
For readability. Did not know about NewType, will try to use that instead.

**Comment by martin-ejdestig** [comment]
NewType worked. Had to convert str to Baz in a couple places but I guess I gained a bit of type safety.

Would like to reiterate that it is still very confusing though. Especially since just moving Bar to file scope works. Documentation and better error message will help, but it is still not intuitive.

**Comment by ilevkivskyi** [comment]
> Would like to reiterate that it is still very confusing though.

Just stating this is not very helpful, what is the solution that you propose?

**Comment by martin-ejdestig** [comment]
I know too little about how mypy relates to Python and the language specification. I assume it is too late to change so that "Bar = str" means the same thing at file and function scope? Or is that something that can be done?
