### ISSUE TITLE
Bug: Overloads detecting overlaps in non-overlapping types?

### ISSUE THREAD

**Issue by astronouth7303** [python/mypy#5821]
Sorry if I'm just missing something.

This passes type check:

```python
import typing
from numbers import Real

Realish = typing.Union[Real, float, int]

VectorOrSub = typing.TypeVar('VectorOrSub', bound='Vector2')

VectorLike = typing.Union[
    VectorOrSub,
    typing.List[Realish],  # TODO: Length 2
    typing.Tuple[Realish, Realish],
    typing.Dict[str, Realish],  # TODO: Length 2, keys 'x', 'y'
]

class Vector2:
    def __mul__(self: VectorOrSub, other: typing.Union[VectorLike, Realish]) -> typing.Union[VectorOrSub, Realish]:
        return 42  # Dummy implementation
```

However, changing the annotations of `.__mul__()` to a more correct overload-based one:

```python
class Vector2:
    @typing.overload
    def __mul__(self: VectorOrSub, other: VectorLike) -> Realish: pass

    @typing.overload
    def __mul__(self: VectorOrSub, other: Realish) -> VectorOrSub: pass

    def __mul__(self, other):
        return 42  # Dummy implementation
```

Causes the error:

> /tmp/test.py:17: error: Overloaded function signatures 1 and 2 overlap with incompatible return types

As far as I can tell, `Realish` and `VectorLike` don't overlap, so I'm not sure what this error is saying.

(Context: I'm working on https://github.com/ppb/ppb-vector/ )

**Comment by astronouth7303** [comment]
(Apologies if this already exists or is a known bug.)

**Comment by astronouth7303** [comment]
Further testing: mypy considers `Realish` and `VectorOrSub` to be overlapping types. Which I guess makes sense if someone makes a type that inherits from both?

How can I annotate that that's not a thing that happens? Assuming that's what's happening.

**Comment by astronouth7303** [comment]
Alternatively: As soon as you have a `TypeVar` with `bound` set, can it be said to overlap with literally anything? that seems less than useful.

**Comment by Michael0x2a** [comment]
Try doing this:

```python
class Vector2:
    @typing.overload
    def __mul__(self: VectorOrSub, other: VectorLike[VectorOrSub]) -> Realish: pass

    @typing.overload
    def __mul__(self: VectorOrSub, other: Realish) -> VectorOrSub: pass

    def __mul__(self, other):
        return 42  # Dummy implementation
```

iirc, since `VectorLike` uses a typevar, [it's implicitly a generic type][0]. So when using it, you need to substitute in the typevar you want to use, just like any other generic type. (E.g. you need to do `List[str]`, not just `List` -- likewise we need to do `VectorLike[Something]`, not just `VectorLike`.)

And since you didn't substitute in some value into the `VectorLike` generic type, mypy ends up deciding that the `VectorOrSub` typevar must be of type `Any`. (And `Any` will overlap with anything, including `Realish`, hence the warning).

I believe you can have mypy warn you about similar mistakes elsewhere in your code by passing in the `--disallow-any-generic` flag, which reports an error whenever you instantiate a generic type with an implicit Any argument.

In your original example, that flag would have reported an error with the first overload in your second example.

  [0]: https://mypy.readthedocs.io/en/stable/generics.html#generic-type-aliases

**Comment by astronouth7303** [comment]
Ah!

I also just found that this version clears the error:

```python
VectorLike = typing.Union[
    'Vector2',
    typing.List[Realish],  # TODO: Length 2
    typing.Tuple[Realish, Realish],
    typing.Dict[str, Realish],  # TODO: Length 2, keys 'x', 'y'
]
```

I think this is more correct, as well? In the cases of `VectorLike`, I just mean "A Vector2, a subclass of it, or any data that's convertable to a Vector2", which means I was incorrect to use the `TypeVar` in its definition.

Thank you for that explanation!

**Comment by astronouth7303** [comment]
That is exactly why it was used in the first place.
