### ISSUE TITLE
if type(var) is class: ... doesn't constrain type as expected

### ISSUE THREAD

**Issue by AndrewUshakov** [python/mypy#5847]
Consider simplified code (mypy 0.641 messages are in comments):
```Python
# coding=utf-8

from typing import TYPE_CHECKING


class A:
    def __init__(self, name: str) -> None:
        self.name = name


class B(A):
    def __init__(self, name: str, value: float) -> None:
        super().__init__(name)
        self.value = value


if __name__ == '__main__':

    lst = tuple([A('abc'), B('cde', 2.718), 'abc'])
    if TYPE_CHECKING:
        reveal_type(lst)            # main.py:21: error: Revealed type is 'builtins.tuple[builtins.object*]'

    for x in lst:
        if TYPE_CHECKING:
            reveal_type(x)          # main.py:25: error: Revealed type is 'builtins.object*'
        if type(x) is B:
            if TYPE_CHECKING:
                reveal_type(x)      # main.py:28: error: Revealed type is 'builtins.object*' ??????????
            print(x.name, x.value)  # main.py:29: error: "object" has no attribute "name"    ??????????
                                    # main.py:29: error: "object" has no attribute "value"   ??????????
    print()

    for y in lst:
        if TYPE_CHECKING:
            reveal_type(y)          # main.py:35: error: Revealed type is 'builtins.object*'
        if isinstance(y, B):
            if TYPE_CHECKING:
                reveal_type(y)      # main.py:38: error: Revealed type is 'main.B'
            print(y.name, y.value)
```
Both loops are equivalent, but mypy complains about line 29 because the "isinstance(x, B)" works but "type(x) is B" doesn't. Situation is slightly similar to the issue  #4864.

P.S. In real situation I have more complicated hierarchy of classes (including classes C(B) etc.) and need to constraint processing to objects of type B only.

**Comment by gvanrossum** [comment]
Note that mypy doesn't have a way (internally, nor in the type system) to express "B but not a subclass of B". The best we could probably do is make `type(x) is B` equivalent to `isinstance(x, B)`, but that would be cheating (a little but).

Until this is fixed, as a workaround, you could write `type(x) is B and isinstance(x, B)`.

**Comment by AndrewUshakov** [comment]
Thank you. Other variant, use ```cast(B, x)```. This trick also works and doesn't require explanations.

Or, may be, it will be better to implement some special type of comment like ```# type: assume x: B```
to help mypy in difficult situations? Such comments will be less general than ```# type: ignore```, which hide all errors in the line.

**Comment by gvanrossum** [comment]
The cast works, but I don't like it, because it silences possible errors too. Adding type comments is not recommended. We should probably just add support for `type(x) is B`. But it'll be low priority given that it's very uncommon and there's a reasonable workaround.

**Comment by Tinche** [comment]
I've been adding mypy to my work code base and this is one of the problems I've encountered. (The other one is unions being used in a runtime context error that should be reverted in my opinion.)

This is the pattern I see most often: 

* a microservice servicing different requests
* I have an attrs class for each request
* the natural way to model this is having a union of all requests
* I can create an object from json satisfying this union using cattrs
* now I need to actually dispatch based on the real class of the request
* singledispatch works for this, but sometimes I can't use it
* I would like a single type() call and a chain of its, because chaining isinstance is expensive for a large number of union members

I agree it's not high priority, but I do see it in use. Thanks for the workaround :)

**Comment by erictraut** [comment]
This appears to work fine in the latest version of mypy, so I think it can be closed.

**Comment by gvanrossum** [comment]
Agreed.
