### ISSUE TITLE
please write .mypy_cache/.gitignore by default

### ISSUE THREAD

**Issue by douglasbagnall** [python/mypy#5863]
If when mypy writes a cache, it also did something like:
``` 
   with open(os.path.join(cache_dir, '.gitignore', 'w')) as f:
         f.write('*')
```
i.e. `echo '*' > .mypy_cache/.gitignore`

then nobody would ever be annoyed by the sudden appearance of thousands of untracked files.

Note this differs from issue  #3336 which added the ignore files to particular projects. This would work for every project, and not interfere with anybody's existing top-level .gitignores.

I have not found the right place in the code to make the patch.

**Comment by ethanhs** [comment]
On top of the principle of least surprise, I'd rather not do this for each vcs that exists, and doing this just for git seems... weird.

**Comment by takeda** [comment]
@refi64 @ethanhs  looks like it was added anyway, sigh: https://github.com/python/mypy/pull/8193

This is an issue, if there is a tooling that parses .gitignore but doesn't traverse subdirectories. In those cases the .mypy_cache might still end up being processed, because of this change I forgot to add it to root folder's `.gitignore`.

It won't kill me, but this was totally unnecessary, and it is a gotcha if one is not aware of it.

**Comment by ethanhs** [comment]
> This is an issue, if there is a tooling that parses .gitignore but doesn't traverse subdirectories.

That sounds like a bug in the tool you are using, not mypy. Furthermore, I do think *most* people probably are using mypy in a git vcs system where they don't want to check the cache into version control...
