### ISSUE TITLE
Function is missing type annotation for __init__(self)

### ISSUE THREAD

**Issue by alex65536** [python/mypy#5943]
The minimal code is:
~~~~
class MyClass:
    def __init__(self):
        pass
~~~~

When running `mypy code.cpp` with the following `mypy.ini`

~~~~
[mypy]
ignore_missing_imports = True
disallow_untyped_defs = True
~~~~

it says:

~~~~~
code.py:2: error: Function is missing a type annotation
~~~~~

The expected result is not errors

**Comment by JelleZijlstra** [comment]
That's because you have the `disallow_untyped_defs` flag on, which produces an error for function definitions without a type annotation. You should add `-> None` to the annotation for your method, or not use `disallow_untyped_defs`.

(Also, I'm happy to see that we're using mypy to check C++ code now. :) )

**Comment by andreymal** [comment]
@JelleZijlstra but `-> None` is implied (https://github.com/python/mypy/issues/604), so `def __init__(self)` actually has a type annotation, so this is a mypy bug?

**Comment by JelleZijlstra** [comment]
We decided at the time to still require`-> None` for initializers with no arguments, so that the default would still be to leave these functions unchecked.
