### ISSUE TITLE
Incompatibility in intraction with functools.  

### ISSUE THREAD

**Issue by h8hawk** [python/mypy#5953]
>>>from typing import List, Tuple
>>>from functools import singledispatch
>>>@singledispatch
>>> ...def foo(a):
>>> ...    pass 

When I using generic class I encounter with error:

>>> @foo.register
... def _(a : List[int]):
...     pass 
... 
Traceback (most recent call last):
  File "<input>", line 2, in <module>
    def _(a : List[int]):
  File "/lib/python3.7/functools.py", line 811, in register
    f"Invalid annotation for {argname!r}. {cls!r} is not a class."
AssertionError: Invalid annotation for 'a'. typing.List[int] is not a class.
`

**Comment by ilevkivskyi** [comment]
This is not a mypy bug, but a (very reasonable) runtime limitation of `singledispatch()`.

You can't register `sigledispatch` implementation oh types like `List[int]`, only on `list` etc., because it can't always guarantee the generic argument. If you think the error message is not clear, please open an issue on bugs.python.org instead.
