### ISSUE TITLE
Remove @builtinclass

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#599]
The PEP 484 draft doesn't have `@builtinclass`, so remove it. Alternatively, figure out an alternative way of encoding this information.

**Comment by elazarg** [comment]
If I am not mistaken, it can be removed right now. No test demonstrate a need for it.

The only use of this information inside mypy (through `ClassDef.is_builtinclass`) is in [`nearest_builtin_ancestor()`]((https://github.com/python/mypy/blob/master/mypy/meet.py#L119)), called from [`check_multiple_inheritance()`](https://github.com/python/mypy/blob/master/mypy/checker.py#L947) in `checker.py`[1]. Replacing 
```Python
-        if base.defn.is_builtinclass:
+        if base.defn.fullname == 'builtins.object':
```
passes all the tests[2], except the whitebox-test [testBuiltinclassDecorator](https://github.com/python/mypy/blob/master/test-data/unit/semanal-classes.test#L521) in `semanal-classes.test`, but this test only verifies that the implementation tracks this information.

[1] It resides on `meet.py`, for some reason, adding an unnecessary dependency
[2] Otherwise it could be replaced with looking up the decorator. Or keeping a list of builtin classes

**Comment by gnprice** [comment]
Thanks for investigating! Sounds like a small patch with that cleanup would be great.

**Comment by gvanrossum** [comment]
Let's leave this open until it's also removed from typeshed (two lines).
