### ISSUE TITLE
disallow_any_generics = False in mypy.ini doesn't get precedence over --strict mode

### ISSUE THREAD

**Issue by awaizman1** [python/mypy#6062]
Hi,

Running mypy 0.650 in strict mode and a configuration file where 'disallow_any_generics = False' is set, does't seems to work - I still get 'error: Missing type parameters for generic type'

Reproducing the problem:
test.py:
```
from typing import Tuple

def foo() -> Tuple:
    return 1, 2
```

mypy.ini:
```
[mypy]

disallow_any_generics = False
```

now run:
`mypy --strict --config-file mypy.ini test.py`

Thanks

**Comment by Michael0x2a** [comment]
I think this is expected behavior -- the `--strict` flag sets `disallow_any_generics` to true, and command line flags always take precedence over whatever's inside the config file.

I believe the recommendation is to instead explicitly enable the flags `--strict` uses inside your config file -- run `mypy --help` to see the latest list. This also helps keeps your configs stable over time as new options are added to/bundled with `--strict`.

**Comment by ilevkivskyi** [comment]
Yes, `--strict` is intended to be... strict :-) You can just enable/disable individual flags if you want to have slightly lower level of strictness than `--strict`.
