### ISSUE TITLE
Question: Partial callable signature

### ISSUE THREAD

**Issue by mehdigmira** [python/mypy#6077]
Hello,

When using decorators, we often know that the function that will be decorated should take param x and y, but we don't care about the rest of the parameters. Is there currently a way to do this ?
Something like `Callable[[str,...], Any]` would be perfect. It would work for `f(x: str)` but also for `f(x: str, y: int)` and `f(x: str, *args, **kwargs)`

**Comment by JelleZijlstra** [comment]
You can do this with callable protocols (https://mypy.readthedocs.io/en/latest/protocols.html#callback-protocols).

**Comment by mehdigmira** [comment]
I was not able to make it work with callable protocols either

```python
from typing import Any

from typing_extensions import Protocol


class DecoratedF(Protocol):
    def __call__(self, a: str, *args: Any) -> None: ...


def g(f: DecoratedF): ...


@g
def f(a: str, b: str) -> None: ...
```

Am I doing smth wrong ?

**Comment by ilevkivskyi** [comment]
This is actually very similar to https://github.com/python/mypy/issues/5876 (see also a decorator example there). Which is _opposite_ to the idea of callback protocols in some sense. Callback protocols allow to express signatures that are impossible to express using `Callable` syntax. However, there is something that can be expressed using `Callable` that can't be expressed as a signature, for example `Callable[..., int]` (with literal `...`).

Potentially we can just also allow special meaning for `*args: Any, **kwds: Any` _at the end_ of a signature to mean "I don't care" instead of "Should allow all possible calls".

**Comment by JukkaL** [comment]
We don't want to support a non-standard extension to the callable syntax, so proposed changes should go through the typing issue tracker or typing-sig@.
