### ISSUE TITLE
mypy requires an annotation for empty `frozenset`

### ISSUE THREAD

**Issue by asottile** [python/mypy#6265]
Related to #1164:

```python
x = frozenset()
```

```console
t.py:1: error: Need type annotation for 'x'
```

I'll note that a similar case for empty tuple does not require an annotation.  I *think* this is different from `x = set()` because `frozenset` is immutable.

**Comment by ilevkivskyi** [comment]
But what should we infer for `x = frozenset()`? `FrozenSet[<nothing>]`? But then this code will fail:
```python
x = frozenset()
set(x).add(42)
```
We can of course special-case this, but is it really worth it? I would propose to just close this.

**Comment by JukkaL** [comment]
Inferring `FronzenSet[<nothing>]` sounds kind of reasonable, especially as there is no obvious to explicitly annotate that type. 

The example where this would cause an error does not feel convincing, since the same issue already happens with tuples. I don't think that anybody has complained about it, and empty tuples are much more common than empty frozen sets:

```py
x = tuple()
list(x).append(1)  # Error
```

However, this sounds like a low-priority thing since the issue seems rare and there is a simple workaround.
