### ISSUE TITLE
Mypy infers Optional types for values assigned in if statements only when None is assigned first

### ISSUE THREAD

**Issue by huzecong** [python/mypy#6351]
**Are you reporting a bug, or opening a feature request?**
Bug.

When typing checking something similar to this:
```python
import random

if random.randint(0, 1):
    a = 1
else:
    a = None
reveal_type(a)
```
Mypy (with default settings) gives the following error:
```
1.py:6: error: Incompatible types in assignment (expression has type "None", variable has type "int")
1.py:7: error: Revealed type is 'builtins.int'
```
However, when reversing the two branches:
```python
import random

if random.randint(0, 1):
    a = None
else:
    a = 1
reveal_type(a)
```
Mypy is able to infer the correct type `Union[builtins.int, None]`. Is this the intended behavior?

**Comment by gvanrossum** [comment]
This is by design. The type inferred in the first assignment rules (regardless of whether it's inside an `if`), *except* if it's `None` or an empty container (dict, list etc.). In the latter case, mypy tries to infer the type from a later mutation or assignment of the same variable, assuming it's simple enough to infer -- if not, you'll get an error "Need type annotation".

**Comment by huzecong** [comment]
I see. Thanks for the detailed explanation!
