### ISSUE TITLE
--module flag does not work with installed packages

### ISSUE THREAD

**Issue by antonagestam** [python/mypy#6394]
I'm running into a weird bug that first showed up as all modules passing on my local machine but then spitting hundreds of errors when running on Circle CI. I then continued to experiment with the different flags and it turns out to only affect the `--module` or `-m` flags. When running with the `--package` flag instead it works:

```bash
$ mypy --module probe.models
$ mypy --package probe.models
probe/models.py:31: error: Argument 1 to "int" has incompatible type "Optional[str]"; expected "Union[str, bytes, SupportsInt]"
probe/models.py:148: error: Argument 1 to "id_from_optional" of "DrillPlan" has incompatible type "Union[int, str, None]"; expected "Optional[str]"
```

Any ideas about what might be going wrong here?

```bash
$ python --version
Python 3.7.2
$ mypy --version
mypy 0.670
$ cat mypy.ini
[mypy]
ignore_missing_imports = True
```

**Comment by gvanrossum** [comment]
The `-m` flag only load the `__init__.py` file of the package, and whatever that explicitly imports. So if you have an empty `__init__.py` file, that would explain this. Try `-v` to see what files it parses.

**Comment by antonagestam** [comment]
Hmm okay, but that doesn't explain why the behavior differs between Linux and Macos. I assumed that the `-m` flag would behave similarly to `python -m module`. In my case `probe.models` is a module (`probe/models.py`) and not a package. The `probe/__init__.py` file is indeed empty, but that shouldn't really be the issue here right? Adding an import of the models module didn't change anything.

Looking at the log it looks pretty much the same up until the call with `--package` spits a type check error.

I now realized it might have to do with how the `probe` package is installed. I made a tiny example here: https://github.com/antonagestam/mypy-issue-6394

It looks like the behavior differs if the module is from an installed package.

**Comment by antonagestam** [comment]
Update: I added a dockerized example with two works.sh and doesntwork.sh to illustrate the two usages I assumed would yield the same results.

**Comment by gvanrossum** [comment]
OK, I will have to look into this later.

**Comment by antonagestam** [comment]
Cool, I'll be fine using the `--package` in the meantime. Perhaps the title of this issue should be changed to "--module flag does not work with installed pacakages"

**Comment by gvanrossum** [comment]
I finally dug into this.

The reason is that it's intentional -- errors in *installed* packages are suppressed, unless you pass `--no-silence-site-packages`.

This is (briefly) documented [here](https://mypy.readthedocs.io/en/latest/command_line.html#import-discovery). The reason for this behavior is that *in general* errors in installed third-party packages are non-actionable -- they are issues for the third-party package developer.

The behavior is implemented by [this code](https://github.com/python/mypy/blob/1b9b2b36a03d364f1bd4fdd6233c9f794dd3f985/mypy/build.py#L2256-L2260). The reason is that the site-packages part of `sys.path` contains the parent directory of the package, which in the case of a package installed with `pip install -e` is the source tree containing that package.

I don't think there's anything for us to do here, so I'm closing this issue. Thank you for your patience!

**Comment by antonagestam** [comment]
@gvanrossum Oh, that makes sense! Thank you for taking the time and explaining!
