### ISSUE TITLE
Inconsistency in metaclass/Type interaction

### ISSUE THREAD

**Issue by msullivan** [python/mypy#6416]
Since #6370, we reject the following code:
```
from typing import Type
class Meta(type):
    pass
class Thing(metaclass=Meta):
    pass

def foo(x: Type[Thing]) -> Type[Thing]:
    assert isinstance(x, Meta)
    return x
```
with the error `Incompatible return value type (got "Meta", expected "Type[Thing]")`.

Previously this worked because we thought that `Meta` and `Type[Thing]` had no overlap and so the rest of the function after the assert wasn't checked.

This caused one error in S.

The answer might be that we need to consider `Type[Thing]` to be a subtype of `Meta`?

**Comment by ilevkivskyi** [comment]
> The answer might be that we need to consider `Type[Thing]` to be a subtype of `Meta`?

IIRC this is already true, we need to fix _proper_ subtype (which is still a separate visitor, see also https://github.com/python/mypy/issues/3297)

Also even with proper subtype fixed, this may not help since `isinstance()` can widen type, see
https://github.com/python/mypy/issues/6386. Or maybe better proper subtype check will fix both issues.
