### ISSUE TITLE
New semantic analyzer: should we collect functions from AST instead of symbol tables?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#6454]
Currently, functions are collected for processing from symbol tables, not form ASTs. This causes some issues, for example, if there is method name clash in class-based named tuple, then the user provided method will be not analyzed, which will cause a crash later, see `testNewNamedTupleIllegalNames`.

This is a follow-up for https://github.com/python/mypy/pull/6452

**Comment by JukkaL** [comment]
This is something I started to wonder about as well. This may also affect fine-grained incremental mode, and it would be nice if the solution we come up would support that as well. I see three plausible alternatives for how to deal with this:

* Rename definitions with name clashes. For example, we can use dummy suffixes, as we currently do for certain things. We'd need to extend this to deal with methods at least, and to make sure the renamed functions work consistently in every context.
* Traverse the module top level to find all functions, as suggested above. This may not work well in the context of mypy daemon, however.
* Treat functions with name conflicts as part of the module top level instead of as independent functions.

**Comment by JelleZijlstra** [comment]
#6783 has a concrete example of a crash with dataclasses that's caused by this.
