### ISSUE TITLE
issues with sys.metapath

### ISSUE THREAD

**Issue by rbtcollins** [python/mypy#646]
I'm trying out mypy on pip.

For instance:
PYTHONPATH=. mypy --use-python-path --verbose ./pip/index.py
pip/index.py, line 15: No module named 'pip._vendor.six.moves.urllib'
pip/index.py, line 16: No module named 'pip._vendor.six.moves.urllib'
In module imported in /usr/lib/python3.3/distutils/util.py, line 507,
                   in /usr/lib/python3.3/distutils/dist.py, line 16,
                   in pip/locations.py, line 170,
                   in pip/cmdoptions.py, line 17,
                   in pip/__init__.py, line 29,
                   in pip/index.py, line 18:
/usr/lib/python3.3/lib2to3/refactor.py, line 126: Invalid assignment target
/usr/lib/python3.3/lib2to3/refactor.py, line 127: Invalid assignment target

If you look at https://github.com/pypa/pip/blob/develop/pip/_vendor/__init__.py you can see that metapath is used to enable the vendoring functionality; I suspect thats the cause of the first two issues above. I'm not sure what the rest is about.

**Comment by JukkaL** [comment]
The message `pip/index.py, line 15: No module named 'pip.vendor.six.moves.urllib'` is due to mypy not finding the given module (neither the implementation nor a stub). The reason seems to be that `six.moves` is not a regular module -- the contents are created dynamically. Not sure what's the best way to deal with this. Using stubs should work, but this will be tedious.

The message `/usr/lib/python3.3/lib2to3/refactor.py, line 126: Invalid assignment target` is due to assigning to a function. Mypy conservatively complains about such assignments, but this is an implementation limitation and the restriction will be lifted once I figure out how these should be checked.

I don't know what you mean by metapath. Could you elaborate?

Note that you can use a `# type: ignore` comment to ignore individual errors if you can't easily figure out why mypy is complaining.

**Comment by rbtcollins** [comment]
sys.metapath is a way of intercepting the module loading process, and is used by pip as part of the vendoring process. There's a PEP describing it - I haven't looked into mypy's implementation enough to see whether its relevant to this or not.

**Comment by JukkaL** [comment]
Do you mean `sys.meta_path` (with an underscore)? Can you be more specific about what you are having issues with? Mypy currently has `sys.meta_path` in stubs, but that's the extent of the support it currently has.

**Comment by gvanrossum** [comment]
Closing as too vague to be actionable.
