### ISSUE TITLE
VarArg not working with builtin functions like max() or sum()

### ISSUE THREAD

**Issue by GoldsteinE** [python/mypy#6498]
Simple example:
```python
from typing import Callable
from mypy_extensions import VarArg


f: Callable[[VarArg(float)], float] = max
```
I can use `max()` as a function of floats with variadic args, but mypy gives me an error:
```
main.py:5: error: Incompatible types in assignment (expression has type overloaded function, variable has type "Callable[[VarArg(float)], float]")
```

I have mypy v0.670, Python 3.7.2. It's reproducible on mypy-play: https://mypy-play.net/?gist=df78cea368c8240fa82c63d5546f8aae

**Comment by ilevkivskyi** [comment]
Mypy has troubles figuring subtyping between callables and overloads, see e.g. https://github.com/python/mypy/issues/495, but in this case mypy is right. A function annotated as in your code supports calls like `f()` and `f(42)`, but `max` fails, since there are at least two required arguments. So you should write:
```python
f: Callable[[float, float, VarArg(float)], float] = max
```
This passes mypy.
