### ISSUE TITLE
show_none_errors causes invalid behavior for descriptors

### ISSUE THREAD

**Issue by Elscouta** [python/mypy#6514]
Setting show_none_errors in the config file causes descriptor-based attributes to no longer be detected. Instead, even when called on an instance, they return the type of the property itself.

Minimal code for reproduction:

test.py
```
from typing import Generic, TypeVar, overload, Any, Union
import datetime as dt

T = TypeVar('T')

class Column(Generic[T]):
    @overload
    def __get__(self, instance: None, owner: Any) -> "Column[T]": ...
    @overload
    def __get__(self, instance: object, owner: Any) -> T: ...

    def __get__(self, instance: Union[None, object], owner: Any) -> "Union[Column[T], T]": ...

class MyClass:
    prop: Column[dt.date] = Column()

reveal_type(MyClass.prop)
reveal_type(MyClass().prop)
```

mypy.ini:
```
[mypy]
python_version = 3.6
#show_none_errors = False
```

This yields the following (expected) result:

```
test.py:17: error: Revealed type is 'test3.Column[datetime.date*]'
test.py:18: error: Revealed type is 'datetime.date*'
```

However, uncommenting the show_none_errors line modifies the output into:

```
test.py:17: error: Revealed type is 'test3.Column[datetime.date*]'
test.py:18: error: Revealed type is 'test3.Column[datetime.date*]'
```

**Comment by gvanrossum** [comment]
That's definitely a bug; when `show_none_errors` is set, apparently some part of the type analysis is wrongly skipped.

But why are you using that flag? Shouldn't you use `strict_optional`? IIRC `show_none_errors` is part of a very old and buggy way to work around the errors caused by introducing strict `Optional` checking in a code base that was annotated before mypy supported that.

**Comment by Elscouta** [comment]
Thanks for the quick reply.

We tested with strict_optional instead and the error reporting is indeed much more accurate.
