### ISSUE TITLE
Generic type not deduced in a list

### ISSUE THREAD

**Issue by jrapin** [python/mypy#6538]
When building a list of instances of a generic class with different type parameters(eg. `mylist = [MyClass[float](), MyClass[bool]()]`), `mypy` seems unable to deduce that it can be typed as `List[MyClass[Any]]`.
Is this expected? I understand that `List` is invariant, but since all the instances come from the same generic class, `List[MyClass[Any]]` seemed pretty safe to me. Is there something wrong with this assumption?

Example: run `mypy myscript.py` on the following script (see comments):

```python
from typing import Generic, TypeVar, List, Any

X = TypeVar("X")


class MyClass(Generic[X]):
    pass


# List[MyClass[Any]] is not deduced
mylist = [MyClass[float](), MyClass[bool]()]
reveal_type(mylist)  # Revealed type is 'builtins.list[builtins.object*]'

# But the following works just fine
mylist2: List[MyClass[Any]] = [MyClass[float](), MyClass[bool]()]
reveal_type(mylist2)  # Revealed type is 'builtins.list[MyClass[Any]]'
```

Tested with Python 3.7.2, mypy 0.670 and master (0.680+dev.b31698fd79fcc0b478fb02692f4217deeae42edb).

**Comment by ilevkivskyi** [comment]
> Is this expected? I understand that `List` is invariant [...]

Your understanding is correct and this is by design: mypy only infers `Any` in three cases:
* There is an existing `Any` type in the type context, i.e. user "requested" `Any` type.
* There was a type error found by mypy (bad types in user code)
* There is a bug in mypy.

Using an explicit annotation is the right choice in your case.
