### ISSUE TITLE
Stop supporting Python 3.4 to run mypy

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#6564]
Python 3.4 has reached its end of life: https://mail.python.org/pipermail/python-dev/2019-March/156705.html

We can still support targeting it with `--python-version 3.4`, but we should no longer feel bound to support *running* mypy with 3.4.

**Comment by ilevkivskyi** [comment]
+1 from me. Some PRs fail on 3.4 because it has some syntax limitations, I think the latest example is Michael's union PR.

**Comment by JukkaL** [comment]
Let's do this. 

I think that mypyc doesn't support 3.4. This means that once we ship a mypyc-compiled mypy by default, we should either drop 3.4 support or add Python 3.4 support to mypyc. The latter seems pointless because of the EoL, so dropping 3.4 support seems to make the most sense from this point of view as well.

**Comment by ethanhs** [comment]
Apologies, fat fingered. I am about ready with a PR.
