### ISSUE TITLE
Support __main__

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#658]
Right now, it says the module can't be found.

**Comment by JukkaL** [comment]
Ah yes, I stumbled into this a while ago myself. Thanks for reporting this!

**Comment by ddfisher** [comment]
@kirbyfan64 I know it's been a while, but can you be more specific about the issue you ran into here?

**Comment by kirbyfan64** [comment]
I *think* it was `import __main__`.

**Comment by gvanrossum** [comment]
If you're talking about code that imports `__main__`, I can't repro. E.g.
```
mypy -c 'import __main__'
```
passes without errors.

**Comment by ErikBjare** [comment]
@gvanrossum Put the `import __main__` in a file then run `mypy test_main.py` and the following will happen:

```
test_main.py:1: error: Cannot find module named '__main__'
test_main.py:1: note: (Perhaps setting MYPYPATH would help)
```

Interesting that `mypy -c 'import __main__'` works.

**Comment by gvanrossum** [comment]
FWIW this is because when you pass module filenames (i.e. *.py) on the command line the module name is derived from the filename. So `mypy test_main.py` sets the module name to `test_main`. With `-c` the module name is always set to `__main__`. The module name is also set to `__main__` if you pass a file whose extension isn't `.py` (or `.pyi`).

So I'm not even sure this counts as a bug. Certainly the legit use cases for importing `__main__` are pretty limited, and mypy probably shouldn't assume it has any particular attributes.

**Comment by JukkaL** [comment]
What about `__main__` in a package, to run a package as a program?

**Comment by gvanrossum** [comment]
That's different, there will always be a `__main__.py` in that case and
it's not toplevel.

**Comment by gvanrossum** [comment]
Is there a compelling use case?

**Comment by JukkaL** [comment]
Closing as there don't seem to be compelling use cases.
