### ISSUE TITLE
TypeVar argument of Tuple alias becomes Any

### ISSUE THREAD

**Issue by pdeblanc** [python/mypy#6704]
In the file `foo.py`:

```
from typing import Tuple, TypeVar

T = TypeVar('T')
TT = Tuple[T, T]


def car(items: TT) -> T:
    reveal_type(items)
    return items[0]
```

The revealed type is `Tuple[Any, Any]`:

```
➜  ~ git:(master) ✗ mypy --version
mypy 0.701
➜  ~ git:(master) ✗ mypy foo.py
foo.py:8: error: Revealed type is 'Tuple[Any, Any]'
```

I believe the correct type should have been the same as in this file `bar.py`:

```
from typing import Tuple, TypeVar

T = TypeVar('T')


def car(items: Tuple[T, T]) -> T:
    reveal_type(items)
    return items[0]
```

Which produces the output:

```
➜  ~ git:(master) ✗ mypy --version
mypy 0.701
➜  ~ git:(master) ✗ mypy bar.py
bar.py:7: error: Revealed type is 'Tuple[T`-1, T`-1]'
```

**Comment by ilevkivskyi** [comment]
This is by design, please read the docs before opening issues, https://mypy.readthedocs.io/en/latest/generics.html#generic-type-aliases

If you want to be warned about this behavior, use `--disalllow-any-generics`, again, this is all in the docs https://mypy.readthedocs.io/en/latest/command_line.html#disallow-dynamic-typing
