### ISSUE TITLE
Add option to stop output after encountering first error

### ISSUE THREAD

**Issue by vaibhavkarve** [python/mypy#6820]
It would be nice to have a command line flag "-x" which would stop the mypy check the moment the first error is encountered.

This would allow users to focus on the mypy errors one at a time instead of having to look at the full list every time.

**Comment by ilevkivskyi** [comment]
This may be actually non-trivial. If mypy stops during type-checking its cache will be in an inconsistent state.

Even if we would allow this only in non-incremental mode, it is only possible to do type-checking per SCC. Finally you can just write `mypy <args> | head -n1` if you want to just keep the output short.

**Comment by gvanrossum** [comment]
Maybe an approximation would be a flag that treats all errors as blockers?

**Comment by ilevkivskyi** [comment]
> Maybe an approximation would be a flag that treats all errors as blockers?

Interesting idea. This however will still require a bit or work, because we would need to pass `is_blocker` through a bunch of methods, and update some logic in `mypy.errors`.

**Comment by JukkaL** [comment]
One alternative would be to only add a filtering step to error reporting. We'd only display the first error reported within mypy. All errors would be generated internally but only the first one would be shown. 

Not sure if this is worth adding though, since we have so many command line options already and it would be easy to do the filtering in a runner script as Ivan suggested. We could perhaps have a "mypy recipes" section in the docs where we'd discuss various things that can be built on top of mypy such as various runner scripts, and this could be discussed there.

**Comment by msullivan** [comment]
I don't think we're going to do this
