### ISSUE TITLE
Allow use of type variables at runtime

### ISSUE THREAD

**Issue by saulshanabrook** [python/mypy#6964]
Currently MyPy gives an error of `xxx is a type variable and only valid in type context` when you try to pass a `TypeVar` into a function. Would it be possible to remove this error? Or allow disabling it behind a flag?

I assume it is there to help prevent users from misusing the `TypeVar`s, but there some uses for them at runtime, like for functions have arguments of `typing.Type`. I [am using it](https://github.com/Quansight-Labs/metadsl/issues/69#issuecomment-500575590) to define pattern matching on these types of functions.

If you have some `TypeVar`, `T` and you pass it into a function, then at runtime the inferred type should be `typing.Type[T]`.

**Comment by saulshanabrook** [comment]
To amend my suggestion, I see that just disabling this error is not enough. Ideally, `MyPy` would understand it as a runtime type of this type. For example this should work:

```python
T = TypeVar("T")

def fn(t: Type[T], v: T) -> T:
   ...

U = TypeVar("U")


def other_fn(v: U) -> U:
     # here passing in U means we have a Type[U], and a U type being passed in, so it should return a U
    return fn(U, v)
```

**Comment by Michael0x2a** [comment]
I'm a little confused -- it seems like your example contains a legitimate type error, even if we do remove the existing restrictions around Typevars?

If we were to call `other_fn(3)` for example, we'd end up internally calling `fn(U, 3)` which is basically equivalent to `fn(TypeVar(...), 3)` -- the first param is whatever it is `TypeVar(...)` evaluates to at runtime.

This violates the type signature of `fn`: 3 will never be an instance of whatever-it-is `TypeVar(...)` returns.

In order for your example to type check, the *Python runtime* would need to understand how TypeVars work and locally reassign `U` to be equal to int inside of `other_fn` -- and do this for every single distinct call to `other_fn`. (And obviously, that would cause a pretty noticeable performance hit due to the increased overhead/require a large change in Python semantics).

Or perhaps you meant to define `fn` as `fn(t: Type[T], v: Any) -> T:`? But I don't think calling `fn(U, v)` would be very helpful in that case either: since the value of `U` doesn't change at runtime, you'd be passing in the exact same object no matter what `v` is. So you don't really gain anything by passing in `U` as a parameter.

**Comment by saulshanabrook** [comment]
Thanks for taking a look at this.

> In order for your example to type check, the Python runtime would need to understand how TypeVars work and locally reassign U to be equal to int inside of other_fn -- and do this for every single distinct call to other_fn. (And obviously, that would cause a pretty noticeable performance hit due to the increased overhead/require a large change in Python semantics).

Well, yeah I am not suggesting we do that. I would want the call to be `fn(U, 3)`, as written. This example is not useful, but I was just trying to make something minimal here. I just added a more fleshed out example [here](https://github.com/Quansight-Labs/metadsl/issues/69#issuecomment-500898932). Currently MyPy complains at `convert_optional` function in the "Functional" approach because of this issue.

We end up trying out the expressions created with the `TypeVar`s in them against different parts of the expression tree, using the `TypeVar`s as wildcards for types. Once we can match, we now know what actual type should be used for the `TypeVar` in that replacement, and can replace all instances of it in the resulting expression.

Any thoughts you have on these two approaches would be appreciated, since it is a big design decision on my end and I want whichever one I choose to hopefully be compatible with the direction of MyPy long term.

The `classmethod` based approach I articulate there has some runtime issues, but at least those [I can work around](https://github.com/python/typing/issues/629#issuecomment-493683034).

**Comment by saulshanabrook** [comment]
I am closing this because I have decided to with the approach of only passing type parameters as generic arguments to classes, instead of passing them into functions like this.
