### ISSUE TITLE
mypy does not validate type when wrapped in generic type alias of Union[T]

### ISSUE THREAD

**Issue by untitaker** [python/mypy#7002]
```python
from typing import Union, TypeVar

_T = TypeVar("_T")
Bar = Union[_T]

def foo(a: Bar[int]) -> None:
    return None

foo("abc")
```

I would expect this piece of code to not validate, because `foo()` (indirectly) takes only integers.

The above example validates when run with `mypy --strict` on commit 44172caa.

Whether `--strict` is passed or not does not seem to matter.

**Comment by untitaker** [comment]
The example above was constructed based on https://mypy.readthedocs.io/en/latest/generics.html#generic-type-aliases, specifically because of the following example:

```python
Vec = Iterable[Tuple[T, T]]

[...]

v1: Vec[int] = []      # Same as Iterable[Tuple[int, int]]
```

**Comment by untitaker** [comment]
Root cause seems to be that `Union[int]` is `Any`:

```python
from typing import Union

reveal_type(Union[int])  # revealed type is Any
```

**Comment by untitaker** [comment]
Curiously `reveal_type(Union[int])` always returns `Any`, but when using that `Union` in a function declaration it clearly does not behave that way.

**Comment by ilevkivskyi** [comment]
`reveal_type(Union[int])` always shows `Any` because `Union[int]` is not something meaningful as an expression. It looks like the type of `f` is `'def (a: _T?)'`, which means the bug is missing (edge) case in `replace_alias_tvars()` and `get_typ_args()`. These only take care of cases where type variables are nested somewhere, while a union of a single element is immediately simplified to that element.

This should be easy to fix, maybe we should switch these to use a proper visitor similar to `expand_type()` to make this part of code less error-prone.

**Comment by AlexWaygood** [comment]
Mypy [emits the correct error message](https://mypy-play.net/?mypy=0.750&python=3.10&gist=ac32ab85df1e4bd6ddfe6a35af2a843d) for this in version 0.750+; this is now fixed.
