### ISSUE TITLE
Concrete types implementing nested protocols

### ISSUE THREAD

**Issue by dmontagu** [python/mypy#7041]
Thanks for the awesome tool! I'd like to be able to validate against nested protocols as described below.

------
* Are you reporting a bug, or opening a feature request?

Bug (I think)

* Please insert below the code you are checking with mypy

```python
from typing_extensions import Protocol

class InnerProtocol(Protocol):
    number: int

class OuterProtocol(Protocol):
    inner: InnerProtocol

def f(x: OuterProtocol) -> None:
    pass

class Inner:
    def __init__(self, number: int) -> None:
        self.number = number

class Outer:
    def __init__(self, inner: Inner) -> None:
        self.inner = inner

inner = Inner(number=0)
outer = Outer(inner=inner)
f(outer)
```

* What is the actual behavior/output?

```
test.py:28: error: Argument 1 to "f" has incompatible type "Outer"; expected "OuterProtocol"
test.py:28: note: Following member(s) of "Outer" have conflicts:
test.py:28: note:     inner: expected "InnerProtocol", got "Inner"
```

* What is the behavior/output you expect?

No errors

* What are the versions of mypy and Python you are using?
python 3.7.3
mypy 0.710
mypy-0.720+dev.48916e63403645730a584d6898fbe925d513a841

* What are the mypy flags you are using? (For example --strict-optional)

I get the same result regardless of flags.

-----

Maybe I'm misunderstanding how this is supposed to be done, but PyCharm seems to handle this use case pretty robustly (the above code raises no warnings, but, e.g., changing the name of `Inner.inner` to `Inner.inne` causes a warning). (But I'd rather use mypy for scriptability etc.)

**Comment by ilevkivskyi** [comment]
Although PyCharm is fine with it, this code is actually unsafe, you can read an example here https://mypy.readthedocs.io/en/latest/common_issues.html#covariant-subtyping-of-mutable-protocol-members-is-rejected

So in your case `inner` must be read-only:
```python
class OuterProtocol(Protocol):
    @property
    def inner(self) -> InnerProtocol: ...
```
(it still can be writeable on the implementation, if needed).

**Comment by dmontagu** [comment]
This makes sense, thank you for the fast response!

**Comment by Murtagy** [comment]
Would be super to have a help from type checker on this error

**Comment by mgilson** [comment]
This rabbit hole gets a little deeper.

```py
from typing import Protocol
from dataclasses import dataclass, field

@dataclass
class Foo:
    a_mutable_collection: list[int] = field(default_factory=list)


class FooProto(Protocol):
    @property
    def a_mutable_collection(self) -> list[int]:
        ...

@dataclass
class FooContainer:
    foo: Foo

class FooContainerProto(Protocol):
    foo: FooProto


def f(x: FooContainerProto) -> None:
    ...

f(FooContainer(Foo()))
```

This code also fails in mypy even though we're taking advantage of the "read-only" property trick:

```
.../mypytest.py:25: error: Argument 1 to "f" has incompatible type "FooContainer"; expected "FooContainerProto"  [arg-type]
    f(FooContainer(Foo()))
      ^~~~~~~~~~~~~~~~~~~
.../mypytest.py:25: note: Following member(s) of "FooContainer" have conflicts:
.../mypytest.py:25: note:     foo: expected "FooProto", got "Foo"
```

We can resolve this by updating the return type of `FooProto.a_mutable_collection` to be an immutable collection interface type -- e.g. `typing.Sequence`:

```py
from typing import Protocol, Sequence
...

class FooProto(Protocol):
    @property
    def a_mutable_collection(self) -> Sequence[int]:
        ...

...
```

I'm trying to decide whether I think `mypy` is correct or incorrect here.  If I understand the type system correctly here, `mypy` is _assuming_ that a mutation to the returned collection will also be visible on the instance that is holding the `@property`.  This assumption is frequently true, but not necessarily (the property _could_ make a copy before returning the object)

I suppose you probably run into this with returning other non-collection types that are mutable (e.g. mutable class instances).

Mostly I wanted to mention this here because this is the ticket where a colleague of mine landed when we hit this issue and I'd like to add more documentation around the work-arounds.

I'm also open to making a PR at some point to try to make the documentation in the link from @ilevkivskyi slightly more robust (if that would be a welcome contribution).

**Comment by erictraut** [comment]
@mgilson, I don't think your proposed workaround addresses the problem. Mypy still generates an error if you change `list` to `Sequence` in your code sample above. 

For this code to type check without error, you need to make `FooContainerProto.foo` read-only. This is required for the same reason that `FooProto.a_mutable_collection` must be read-only, as @ilevkivskyi explains above.

```python
class FooContainerProto(Protocol):
    @property
    def foo(self) -> FooProto:
        ...
```

FWIW, pyright agrees with mypy and produces the same errors here. I recently added the note "x is invariant because it is mutable" to pyright's error to help clarify why this error occurs. 

![image](https://github.com/python/mypy/assets/7040122/c4224360-37b3-4c4d-8111-f47eaa67eb0d)

It might be worth adding a similar note to mypy's error message. Additional documentation is also a good idea.

**Comment by mgilson** [comment]
@erictraut -- sorry ... my example was broken.  Let me cook up another that actually mirrors the code I'm working with (I promise I've tested it better this time)

```py
from typing import Protocol, Sequence
from dataclasses import dataclass, field

@dataclass
class Item:
    x: int


class ItemProto(Protocol):

    @property
    def x(self) -> int:
        ...


@dataclass
class Foo:
    a_mutable_collection: list[Item] = field(default_factory=list)


class FooProto(Protocol):
    @property
    def a_mutable_collection(self) -> Sequence[ItemProto]:  # Fails if return type is `list[ItemProto]`
        ...

@dataclass
class FooContainer:
    foo: Foo

class FooContainerProto(Protocol):

    @property
    def foo(self) -> FooProto:
        ...


def f(x: FooContainerProto) -> None:
    ...

f(FooContainer(Foo()))
```

The crux of the matter is that with the protocols, I could add something to the `list` that conforms to the `ItemProto` Protocol within the function, but that thing could actually _not_ be an `Item` and therefore errors could happen because the assumptions about the types contained in the list would be violated in the caller.
