### ISSUE TITLE
Using variables as key of TypedDict 

### ISSUE THREAD

**Issue by ronneke1996** [python/mypy#7178]
With the following example I get an error.

```python
from mypy_extensions import TypedDict

class Test(TypedDict):
    a: str
    b: str

def read(test: Test) -> str:
    key = 'a'
    return test[key]
```

```
error: TypedDict key must be a string literal; expected one of ('a', 'b')
```

Can mypy not figure out that `key` is set to a literal?

In my own code im building up `key` dynamically to get a key from a TypedDict.

mypy version: 0.711

**Comment by msullivan** [comment]
We don't support that, no. I think it does work if `key` is given a `Literal` type, but that doesn't seem super useful.

The dynamic version we definitely won't be able to do useful typechecking of, I think. Best move is probably a `# type: ignore`

**Comment by ilevkivskyi** [comment]
I think `key: Final = 'a'` should also work, if this helps.

**Comment by b0g3r** [comment]
Should, but doesn't :(

In my case, I restrict possible keys for external API, e.g.:
```python
class DataType(TypedDict, total=False):
    FIELD1: str
    FIELD2: str

def send_to_external_api(data: DataType):
   ...
```

And then use these keys in generic way:

```python
class MyGenericWay:
    external_api_key: Final = 'FIELD1'

    def send(self):
        send_to_external_api({self.external_api_key: 'value'})

class AnotherClass:
    external_api_key: Final = 'FIELD2'
    ...
```

But mypy allows only in-place literal as keys and also restrict `Final`:

```python
from mypy_extensions import TypedDict
from typing_extensions import Literal, Final


class MyDict(TypedDict):
    field_name: int

d: MyDict
d = {'field_name': 1}

name_in_var = 'field_name'
d = {name_in_var: 1}

name_in_literal2: Literal['field_name'] = 'field_name'
d = {name_in_literal2: 1}

name_in_final: Final = 'field_name'
d = {name_in_final: 1}
```

```
test.py:13: error: Expected TypedDict key to be string literal
test.py:16: error: Expected TypedDict key to be string literal
test.py:19: error: Expected TypedDict key to be string literal
test.py:22: error: Expected TypedDict key to be string literal
```

Should I create a new issue, or @msullivan will reopen this?

**Comment by b0g3r** [comment]
Looks like it needs to change a few lines in [checkexpr::check_typeddict_call_with_dict](https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L489-L503):

https://github.com/python/mypy/blob/bd00106aee988dc24b0f39ff89f1b77e4edbb57d/mypy/checkexpr.py#L495-L500

Add check for literal like this: 
```python
if not isinstance(item_name_expr, StrExpr) or not (isinstance(item_name_expr, LiteralType) and isinstance(item_name_expr.value, str)):
```

@ilevkivskyi What do you think?

**Comment by ilevkivskyi** [comment]
@b0g3r Your use case is a different issue, it will be fixed by https://github.com/python/mypy/pull/7645

**Comment by svet-b** [comment]
This is problematic for us, since we use "constants" [0] like `SOME_KEY = 'some_key'` to do dictionary lookups in a predictable way across our codebase. Doing this generally reduces the chance of runtime failure due to typos in key names, and even has benefits like enabling auto-completion (since key names are pre-defined). But it doesn't play nice with mypy, as others have described above, which is a shame.

That said, I did find that setting `SOME_KEY: Final = 'some_key'` seems to allow the use of variables as keys. This is on mypy version 0.971.

What still doesn't work is something like the following:
```
from typing import Final, TypedDict

class A(TypedDict):
    key1: str
    key2: str

KEY1: Final = 'key1'
KEY2: Final = 'key2'

a = A({KEY1: 'abc', KEY2: 'def'})

ALLOWED_KEYS: Final = (KEY1, KEY2)
for k in ALLOWED_KEYS:
    print(a[k])
```
```
mypy_test.py:14: error: TypedDict key must be a string literal; expected one of ("key1", "key2")
```

[0] These are of course not real constants since that's not a thing, but they're variables that never change.

**Comment by AlexWaygood** [comment]
> from typing import Final, TypedDict
> 
> class A(TypedDict):
>     key1: str
>     key2: str
> 
> KEY1: Final = 'key1'
> KEY2: Final = 'key2'
> 
> a = A({KEY1: 'abc', KEY2: 'def'})
> 
> ALLOWED_KEYS: Final = (KEY1, KEY2)
> for k in ALLOWED_KEYS:
>     print(a[k])

Here's a workaround for you:

```python
from typing import Final, TypedDict, Sequence, Literal

class A(TypedDict):
    key1: str
    key2: str

KEY1: Final = 'key1'
KEY2: Final = 'key2'

a = A({KEY1: 'abc', KEY2: 'def'})

ALLOWED_KEYS: Sequence[Literal['key1', 'key2']] = (KEY1, KEY2)
for k in ALLOWED_KEYS:
    print(a[k])
```

https://mypy-play.net/?mypy=latest&python=3.10&gist=5d6a143eb9827c44bf1eff9bbb01c1d2

**Comment by svet-b** [comment]
Thanks @AlexWaygood , appreciate the tip! Thought I can't shake the feeling that this level of verbosity is not justified here. Specifically, I can't execute
```
ALLOWED_KEYS: Sequence[Literal['key1', 'key2']] = (KEY1, KEY2)
```
without first defining `KEY1` and `KEY2` and giving them values. So in this line I'm providing those values again, purely for type-checking purposes. Which also introduces the risk that the key values used for type-checking are actually different from the real variable values. Though maybe I'm missing something.

Either way, I think the above is maybe a bit of an edge case to the core issue outlined by OP. Though it would be nice if cases like these - which are quite unambiguously correct from a developer perspective - are handled properly by mypy. Otherwise it's easy to feel that we have to jump through hoops and make the code less readable just in order to satisfy mypy.

**Comment by qeternity** [comment]
Why is this closed? It's not resolved and it's very awkward when using TypedDicts.

**Comment by ketozhang** [comment]
Furthermore, a common use case is converting dict -> tuple of a specific order (e.g., passing kwargs to position-only function):

```python
class D(TypeDict):
  a: int
  b: str

d: D =  {"a": 0, "b": "foo"}

key_order = ("b", "a")
t = (d[k] for k in key_order) 
```

```
error: TypedDict key must be a string literal; expected one of ("a", "b")
```

**Comment by gandhis1** [comment]
Here's another example that I don't think should error:

```
from typing import TypedDict

DataDict = TypedDict(
    "DataDict",
    {
        "A": float,
        "B": float,
    },
)

test: DataDict = {"A": 1.0, "B": 2.0}
for field in ["A", "B"]:
    test[field] *= 2.0  # TypedDict key must be a string literal; expected one of ("A", "B")mypy(error)
```

I echo previous thoughts about this issue needing remain open as the problem is not resolved.

**Comment by aarondr77** [comment]
Echoing the sentiment that this would be a helpful improvement. We use constants exactly as @svet-b described above.

**Comment by rd-andreas-lay** [comment]
Same here. It's confusing and would be highly appreciated if fixed.

**Comment by JanEricNitschke** [comment]
I would also really like this to be adressed. I have two related problems:

```
from typing import TypedDict

class GameRound(TypedDict):

    roundNum: int
    tRoundSpendMoney: int
    tBuyType: str

cols = [
    "roundNum",
    "tRoundSpendMoney",
    "tBuyType",
]
r: GameRound = {"roundNum": 5, "tRoundSpendMoney": 1000, "tBuyType":"Eco"}

for k in cols:
     print(r[k])  # TypedDict key must be a string literal; expected one of ("roundNum", "tRoundSpendMoney", "tBuyType")  [literal-required]

for k in r.keys():
    print(r[k])  # TypedDict key must be a string literal; expected one of ("roundNum", "tRoundSpendMoney", "tBuyType")  [literal-required]
    
for k in r:
    print(r[k])  # TypedDict key must be a string literal; expected one of ("roundNum", "tRoundSpendMoney", "tBuyType")  [literal-required]
```

**Comment by stefanmatar** [comment]
Doesn't seem to have been fully fixed by #14621, (should be included in the latest mypy version 1.4.1) given this definiton:


```
TYPE_A = "TYPE_A"
TYPE_B = "TYPE_B"
TYPE_C = "TYPE_C"

Types = Literal['TYPE_A', 'TYPE_B', 'TYPE_C']


class BaseMongoDto(TypedDict):
    type: Types


class SomeMongoDto(BaseMongoDto):
    id: UUID


instance = SomeMongoDto(
    type=TYPE_A,
    ...
)
```

I am getting `mongodb/mappers.py:92: error: Incompatible types (expression has type "str", TypedDict item "type" has type "Literal['TYPE_A', 'TYPE_B', 'TYPE_C']")  [typeddict-item]`


And I need to add `# type: ignore[typeddict-item]` to ignore the error.

**Comment by tibbe** [comment]
Can confirm it's not fixed in 1.4.1, even if the key is a known `Literal`.

**Comment by dedekind** [comment]
TypedDict looked useful at the first glance, but lack of easy ways to handle this situations make it much less useful.

**Comment by ubmarco** [comment]
This works for me:
```Python
def some_func() -> None:
    from typing import TypedDict

    class Foo(TypedDict):
        a: str
        b: str

    foo = Foo(a="some", b="value")

    keys: list[Literal["a", "b"]] = [
        "a",
        "b",
    ]

    for key1 in keys:
        print(foo[key1])  # works

    for key2 in ["a", "b"]:
        print(foo[key2])  # does not work
```
