### ISSUE TITLE
What current options for Python 2.7?

### ISSUE THREAD

**Issue by Dedoig** [python/mypy#719]
One of my projects uses Python 2.7. I would like to:

1. Use type annotations (including the parameterized types in typing.py)
2. If possible, run some mypy-like static checker 

What options should I look at for doing one or both of these?

Thanks!

**Comment by JukkaL** [comment]
Currently the 2.7 story is still lacking. You can use type annotations in your Python 2.7 code using type comments, but the support is experimental. Here is an example:

```python
def f(x): # type: (int) -> int
    return x + 1
```

Python 2.7 stubs are not as complete as the 3.x ones, so if you want to this route you'll probably have to port some 3.x stubs to 2.7. Also, some Python 2 specific syntax is not supported. You can file issues on any unsupported syntax and it should be easy to fix that.

Another option is to use the mypy codec that's included in mypy (but undocumented). It lets you use Python 3 annotation syntax with Python 2 -- the codec will strip away annotations. It looks something like this:

```python
# coding: mypy
def f(x: int) -> int:
    return x + 1
```

See `mypy/mypy/codec/README` for more information. Again, this is experimental and it doesn't work in the main file that you run, as you'll have to register the codec before you can use it. However, I think there is a way to install the codec system-wide so that you can use it everywhere, but I can't remember the details.

Feel free to ask more questions if you want to try this -- Python 2 support is definitely something that mypy should have :-) Also, ideas for improvements are welcome. Some people have suggested using docstrings or function decorators for annotations in Python 2.

**Comment by ianozsvald** [comment]
Out of curiosity @JukkaL  - "Python 2 support is definitely something that mypy should have" - why? There's approximately 4 years left for Py2.7 before deprecation. One of my public arguments for getting folk to shift to Py3.4+ is to remind them that if devs have to split their time supporting Py2+3, they have less time to focus on new features and moving their tools forwards.
At my next PyDataLondon meetup I'll give a lightning talk (to 200+ folk) on Python 3.5 and I'll be urging my members to upgrade (I do this most months), hence my curiosity about you stating that you're keen to support Python 2.7.

**Comment by kirbyfan64** [comment]
Because hundreds of places still use 2.7 and probably will use it even after the EOL, I'm guessing. Just look at Windows XP. It reached it's EOL, yet many places still use it.

EOL != no one using it anymore

**Comment by JukkaL** [comment]
There are multiple large Python codebases that I'm aware of that are still Python 2 only, and unlikely to change in the near future (these are proprietary; popular open source projects are mostly Python 3 compatible already). Even many Python 3 compatible projects also need to remain Python 2 compatible because many users are still stuck with Python 2. 

Also, if mypy had Python 2 support it might actually make it easier for some projects to migrate to Python 3, as type checking could find many Python 2/3 compatibility issues.

**Comment by ianozsvald** [comment]
Hi @JukkaL. Cool, I like the approach of helping Python 2 users develop forward-compatible code for their transition to Python 3. 
I'll be mentioning MyPy in my lightning talk, hopefully it'll send over some new users. Many thanks for the reply.

**Comment by gvanrossum** [comment]
Let's close this. We now have mature Python 2 support.
