### ISSUE TITLE
Type hinting has different effects in function signature, and in function body

### ISSUE THREAD

**Issue by bamaxw** [python/mypy#7346]
There seems to be an inconsistency between how mypy reacts to a callable that is typed in function signature, and anywhere else.

I can reproduce this issue with this two examples:

Example 1: This code works ok, mypy is very happy with how everything is typed
```python
import typing as t

T = t.TypeVar('T')

def func_no_err() -> None:
    get_elem: t.Callable[[t.List[T]], T] = lambda lst: lst[0]
    lst: t.List[str] = ['test']
    a: str = get_elem(lst)
```

Example 2: mypy doesn't want to accept `lst` as an argument to the `get_elem` function, because it has a `t.List[str]` type and not `t.List[T]`
```python
import typing as t

T = t.TypeVar('T')

def func_yes_err(get_elem: t.Callable[[t.List[T]], T] = lambda lst: lst[0]) -> None:
    lst: t.List[str] = ['test']
    a: str = get_elem(lst)
    # Argument 1 has incompatible type "List[str]"; expected "List[T]" mypy(error)
```

It works the same with a function defined with `def` and not with `lambda`.

Is this an expected behaviour? I am not sure why this would work differently in these two scenarios.

**Comment by ilevkivskyi** [comment]
Python syntax doesn't support _explicit_ declaration of generic functions, for example:
```
def foo[T](x: List[T]) -> T: ...
```
Therefore mypy has some heuristic (implicit) rules for how to bind type variables. In particular, in the second function mypy thinks that `func_yes_err()` is itself generic in `T`. (You can check this using `reveal_type()`.)

To override the default type variable binding you can use callback protocols. For example, the desired type for `get_elem` is:
```python
from typing import Protocol

class Getter(Protocol):
    def __call__(self, items: List[T]) -> T: ...
```
In these terms the type mypy infers in the second case is like this:
```python
class OtherGetter(Protocol[T]):
    def __call__(self, items: List[T]) -> T: ...

def func_yes_err(get_elem: OtherGetter[T] = lambda lst: lst[0]) -> None:
    ...
```

As I said the implicit rules are a bit ad-hoc, but we can't change them since this will break a lot of existing code.
