### ISSUE TITLE
Drop support for Python 3.5.1?

### ISSUE THREAD

**Issue by msullivan** [python/mypy#7420]
Dropping support for 3.5.1 would save us some occasional hassle:
 * Its typing module has bugs that we have to work around
 * And typing is missing a bunch of stuff that we have to get from typing_extensions instead. (Dropping 3.5.1 support will save me from having to send a PR to pyflakes to have it understand `typing_extensions.overload` as a synonym for `typing.overload`).

We already don't support 3.5.0 so there is no new burden of explaining the lack of support for 3.5 early point releases.

mypyc only supported 3.5.2 before the merge into mypy, and fixing it was annoying if not actually hard. 

There's a bunch of discussion at https://github.com/python-trio/trio/issues/880

Thoughts?

**Comment by ilevkivskyi** [comment]
Personally, I would love to drop 3.5.1. I thought however we still need it somewhere internally, but if it is not the case anymore, I am all in favour.

**Comment by Michael0x2a** [comment]
I think the last time we brought this up internally, the blocker was that 3.5.1 was apparently the default Python 3 on Ubuntu 16.04.

Though FWIW, I'm also favor in dropping support. The people who need to support Python 3.5.1 are also the ones who probably care about legacy support + supporting things like Python 2.7. And in that case, they're probably already used to running mypy using an entirely separate Python. So probably dropping support for Python 3.5.1 wouldn't be too huge a burden? Maybe this is too optimistic, not sure.

(Actually, we could take this line of reasoning one step further and also maybe justify dropping support for Python 3.5 entirely? But this is probably too aggressive, realistically speaking.)

**Comment by ethanhs** [comment]
I personally would be really happy to see this change. I don't think Ubuntu 16.04 should hold us back. If people really want to use a new mypy release on a 3 year old OS, I think asking them to use a separate Python is acceptable, especially since it is easy to install newer Python packages on older Ubuntu https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa. Also there is now a newer LTS...

**Comment by JukkaL** [comment]
Looks like Ubuntu 16.04.5 has Python 3.5.2, but earlier Ubuntu 16.04 releases have 3.5.1. I wonder if we can assume that most 16.04 users have upgraded to Ubuntu 16.04.5 or later by now (it was released Aug 2018). Looking at Ubuntu's release list, it seems that older 16.04 releases are supported until 2021. If this is the case, it would be a bit odd to only support some Ubuntu 16.04 minor releases. Other than that, I don't see major reasons not to drop support for 3.5.1, but I also don't see it as urgent since the extra maintenance burden seems pretty low?

**Comment by hauntsaninja** [comment]
We should just drop 3.5 entirely
