### ISSUE TITLE
Impossible to use class based syntax for TypedDict in Python 2, can't mix required and non-required fields

### ISSUE THREAD

**Issue by TimSimpsonR** [python/mypy#7507]
This means it's impossible to mix required and non-required fields in a typed dict.

Here's an example:

```py2
import mypy_extensions as mt

Base = mt.TypedDict(
    "Base",
    {
        "required": str,
    },
    total=True
)

class Sub(Base):
    nonrequired  # type: int

```

```
error: Invalid statement in TypedDict definition; expected "field_name: field_type"
```

The error message is suggesting Python 3 syntax, which MyPy itself flags as an error:

```py2
class Sub(Base):
    nonrequired: int
```
```
error: invalid syntax
```

The other problem is that "total=False" cannot be specified as an argument in Python 2 as it's a Python 3 language feature:

```py2
class Sub(Base, total=False):
    nonrequired: int
```

```
error: invalid syntax
```

There are two solutions I can think of. The first would be to keep MyPy from flagging the Python 3 syntax as an error when dealing with TypedDict subclasses. In the project I'm working on, I have a lot of MyPy type annotations in a file which is "imported" only by MyPy (using the "if False: import" trick), so this alone would work around the issue.

Another idea is to allow users to pass in base types to the call to `TypedDict` like so:

```py2
Sub = mt.TypedDict(
    "Sub",
    {
        "nonrequired": int,
    },
    total=False,
    bases=[Base]
)
```

This would also allow for the use of dictionary keys which aren't valid Python attributes.

**Comment by JelleZijlstra** [comment]
I think this is a known limitation. Another workaround could be to define the TypedDict in a stub file, and in the corresponding implementation file just define the TypedDict as Any or something.

**Comment by JukkaL** [comment]
If I remember correctly, some users have successfully used inheritance in Python 2 by having three TypedDicts instead of two:
* The first one only has required items.
* The second one only has non-required items (no inheritance relationship with the first one).
* The third one that inherits the first and second ones, but doesn't define any additional items.

I think that this and Jelle's suggestion are the only things that may work. Closing, as we are not planning to improve Python 2 support for TypedDicts. Python 2 End of Life is happening soon.

**Comment by JukkaL** [comment]
(We aren't going to stop supporting Python 2 any time soon, but we are not prioritizing any new Python 2 specific feature development.)

**Comment by TimSimpsonR** [comment]
@JukkaL Awesome! Using multiple inheritance was much cleaner and helped me do exactly what I needed. Thank you.
