### ISSUE TITLE
Type inference of list is too generic and inconsistent between assigning a list and calling with a list parameter

### ISSUE THREAD

**Issue by ltworf** [python/mypy#7618]
```python3
l = [1,'1']
```

That line will be seen as `List[object]`, when in fact `List[Union[int, str]]` would be more precise.

This is annoying because if I do this:

```python3
def f(p: List[Union[int, str]]):
    ...

l = [1,'1']
f(l)
```

mypy will fail, saying that the type of the list is wrong.

However if I directly call `f([1, '1'])` then it will work correctly.

I have encountered this issue when working with subprocess. It works if I pass a list of Path and strings but if I'm building the list separately, adding switches and so on, then it fails. So in that case, if I annotate the list I end up with a code that is longer than all the castings to str() to make mypy happy.

**Comment by msullivan** [comment]
Yeah, this is a frustrating one. The issue is that mypy does a pretty local form of type inference, so it will decide on `l`s type before it is used. We could decide on `Union[int, str]`, but that is also wrong in a bunch of places and switching will break a lot of people's type checking.

The inconsistency with calling with a list parameter is intentional, though. mypy takes into account the context an expression appears.

There are improvements that could be made to the type inference but I'm not sure if any of them are likely to be on the roadmap soon, unfortunately.

@ilevkivskyi Do you know if there is an existing bug open about this sort of thing?

**Comment by ltworf** [comment]
I'm curious, how would it break people's type checking to infer it like that? After all when updating mypy it is often the case that it fails.

The only problem I see would be doing an append to a list with a type not in the union later on.

**Comment by ilevkivskyi** [comment]
@msullivan The idea of using type ranges was discussed in https://github.com/python/mypy/issues/3178 (although it is a big change and therefore low priority). Also https://github.com/python/mypy/issues/5219 is relevant.

@ltworf FYI `List[Union[Dog, Cat]]` is not a subtype of `List[Animal]`.
