### ISSUE TITLE
Bug: list('abc') not inferred to be of type List[str]

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [python/mypy#7766]
`list('abc')` should be inferred to be of type List[str]. However, we still get errors if used as the argument to a function.

### MRE
```python
import collections
named_tuple = collections.namedtuple('Test', list('abc'))
```

### Command used
`mypy code.py`

### Version
mypy 0.720
Python 3.7.4

### Actual output
 `error: List or tuple literal expected as the second argument to namedtuple()`. 

### Expected behaviour
I would expect it to succeed without error.

Reference: https://github.com/pandas-dev/pandas/pull/29114#discussion_r337152697

**Comment by msullivan** [comment]
`list('abc')` *does* get inferred as being of type `List[str]`. The issue here is that it is not a list "literal" -- that is, something like `["a", "b", "c"]`. mypy needs it to be a literal so that it can easily read off and determine the names of the fields.

It would probably be *possible* to handle this particular case, but it doesn't seem common enough to be worth doing.

**Comment by ilevkivskyi** [comment]
FYI, there is an idiomatic way of doing this, that is also supported by mypy:
```python
from collections import namedtuple

C = namedtuple('C', 'a b c')
c = C(1, 2, 3)
c.a  # OK
c.x  # Error
```

**Comment by AbhijeetKrishnan** [comment]
Thank you! mypy's behaviour is confusing me though. The error when the second argument is `list('abc')` is `error: List or tuple literal expected as the second argument to namedtuple()`. '`a b c`' is neither a list nor a tuple (I believe it is a `str`). Why does mypy not complain in the latter case?
