### ISSUE TITLE
stubgen style issues

### ISSUE THREAD

**Issue by srittau** [python/mypy#7899]
Currently stubgen adds an 'Any' annotation to arguments where it cannot determine the type. While having that option for projects that use --disallow-incomplete-defs makes sense, for typeshed contributions I'd prefer that those arguments remain unannotated by default. This way it is very easy to discern that a particular argument still needs an annotation, while `Any` can also mean that someone already checked manually, but a more strict annotation was either not possible or too complicated. Of course, this distinction is not perfect, but it's a good indication of areas that need work. (For an example, have a look at the werkzeug stubs in typeshed, where it's very easy to determine, which classes have been worked on manually.)

Also, stubgen adds unnecessary `= ...` values to instance attributes, but not to top-level ones.

**Comment by ilevkivskyi** [comment]
I don't have a strong opinion on this, but @JukkaL may have.

**Comment by JukkaL** [comment]
The `Any` annotations for arguments was added to support using `--strict` with generated stubs (#4766). I'm okay with removing them by default, but we may need to add a backward compatibility option to enable the existing behavior to avoid a feature regression.

I believe that class attributes get a `= ...` initializer because there was an idea to disinguish between attributes accessible through both the type object and instances, and attributes accessible only through instances. A dummy initializer would indicate that that the attribute can also be accessed through a type object. If unclear, we'd default to adding the initializer. However, this proposal didn't go anywhere. 

I'm fine with removing the initializers. It's probably too late to change the semantics of the initializer, and if we want to introduce a way of declaring instance-only attributes, we may have to come up with an alternative way to specify them.

**Comment by ilevkivskyi** [comment]
One place where `...` is used by mypy is for protocols (maybe also normal ABCs, I don't remember), if there is no `...` the attribute is considered abstract and a class explicitly subclassing a protocol can't be instantiated without defining it. I think however this a exceedingly rare scenario, just wanted to add my 2 cents.

**Comment by hauntsaninja** [comment]
I think this has since been changed
