### ISSUE TITLE
Forward reference to namespaced type with same name breaks with TypedDict

### ISSUE THREAD

**Issue by Phlogistique** [python/mypy#8097]
* Are you reporting a bug, or opening a feature request?

I am reporting a bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from __future__ import annotations
from typing import Union, Any
from typing_extensions import TypedDict


class T(TypedDict):
    b: b.T


class b:
    T = Union[Any]
```

* What is the actual behavior/output?

```
failure2.py:7: error: Name 'b.T' is not defined
Found 1 error in 1 file (checked 1 source file)
```
* What is the behavior/output you expect? 

No type error

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Python 3.7.3, mypy 0.750. I get the same results after installing mypy from Git master.

* What are the mypy flags you are using? (For example --strict-optional)

No particular flag.

* If mypy crashed with a traceback, please paste
  the full traceback below.

No crash

Additional notes:
The following examples *do* typecheck properly:
* Name the type differently:
```
from __future__ import annotations
from typing import Union, Any
from typing_extensions import TypedDict


class T(TypedDict):
    b: b.U


class b:
    U = Union[Any]
```
* Without TypedDict:
```
from __future__ import annotations
from typing import Union, Any


class T:
    b: b.T


class b:
    T = Union[Any]
```
* Without forward reference:
```
from __future__ import annotations
from typing import Union, Any
from typing_extensions import TypedDict


class b:
    T = Union[Any]


class T(TypedDict):
    b: b.T
```

**Comment by JukkaL** [comment]
Thanks for the detailed bug report! Something is clearly wrong here.

**Comment by TH3CHARLie** [comment]
Well, I encounter a similar situation with class T inherited from `NamedTuple`. It seems like this kind of inheritance cause TypeInfo of class `b` has no node of attribute `T`, but I'm still trying to figure out the deeper reason.

**Comment by PattenR** [comment]
When the first class is analysed we add it to missing_names. This is because the first analysis of the TypeDict will be incomplete so we don't want to add its type information anywhere. 

But then when analysing the second class we then don't add the member T's symbol to the symbol table because we see it under the missing_names variable.

This behaviour was added in https://github.com/python/mypy/pull/6257 and is expected to apply to anything that defines a name in the current scope. But in the example given shows that in the case of TypedDicts we are ignoring not just at this top scope. 

My initial thought was to update add_symbol_table_node() in seminal.py to add to the symbol table when the symbol has kind MDEF (when it's a member variable). This solved this example, but any feedback/other edge cases would be great! I've opened a PR so you can see how this would work. 

This works because we want the class T to be ignored (because it's a subclass of TypedDict), but we still want the symbol for member T to be added to the symbol table. Once added to the symbol table it can then be found.

**Comment by Phlogistique** [comment]
Thanks a lot!
