### ISSUE TITLE
Annotating that a function always returns the same value

### ISSUE THREAD

**Issue by zhangwen0411** [python/mypy#819]
```
if is_new_version():
    from sqlalchemy.dialects.mysql.base import MSBinary
else:
    from sqlalchemy.databases.mysql import MSBinary
```

It would be great to be able to annotate that is_new_version() always returns True, so that mypy doesn't check the second module.

**Comment by o11c** [comment]
Note that mypy currently type-checks even inside literal `if False:` blocks, and this is needed to break import cycles (though @JukkaL suggested an `if typing.MYPY` for that case), so (currently) both branches would be typed anyway.

I do strongly believe that in a decent type system, all constant values should be treated equally to types.

This would be particularly useful for modules and classes, which can have attributes that objects of their type generally don't.

Bikeshedding: `typing.Value[False]`, `typing.Constant[False]`. I prefer the former because of things like `[0, x]` (consider separately the cases where x is a local variable, a global constant, a generic parameter, or a function argument whose type is `typing.Value[...]`).

Note that `typing.Value[Foo]` is different than my other suggestion of `typing.Class[Foo]`, which means "any subclass of Foo (TBD: include ducks? Probably not, because superclasses) with the same constructor".

We don't need a `typing.Conditional[cond, type_if_true, type_if_false]` because ternary expressions in `typing.Value[expr]` suffice.

There probably needs to be a way to indicate which global (and class-scope) variables are intended to be mutable and which are intended to be immutable. Currently function and class definitions are assumed to be immutable and all other variables are assumed to be mutable.

Note that passing a `typing.Value[[1, 2, 3]]` object to a function expecting a less specific mutable type (such as `List[int]`, `MutableSequence[int]`, or `Any`) could change the values, and thus the types. But `Sequence[int]` is safe. It would be possible to go the C++ way and provide `const` for argument types, but that would be significantly more complicated than just providing constness at the type level (note that with classes and modules being `typing.Value[...]`, constants in their scope *is* at the type level).

**Comment by JukkaL** [comment]
This will potentially be fixed by implementing literal types -- you'd be able to declare that a function always returns `True`. We are not going to add a feature that only addresses the original use case, so closing this issue.
