### ISSUE TITLE
Catching index out of range on empty strings and lists at compile time.

### ISSUE THREAD

**Issue by TZubiri** [python/mypy#8274]
Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request
I'm reporting an error in user code that mypy did not catch at compile time.

* Please insert below the code you are checking with mypy,
def first_letter(x:str)->str:
    return x[0]

from typing import List
def first_item(x:List)-> int:
    return x[0]

def first_integer(x:List[int])->int:
    return x[0]

print(first_letter('Hello World'))
print(first_item([1,2,3]))
print(first_integer([1,2,3]))

#This raises a runtime error, but mypy doesn't catch them.
print(first_letter(''))

print(first_item([]))

print(first_integer([]))
* What is the actual behavior/output?
Success: no issues found in 1 source file
* What is the behavior/output you expect?
I yield on this one. There's different possible solutions and I understand why they wouldn't be compatible with python, provided that static typing is an afterthought in python.

**Comment by ethanhs** [comment]
This would require mypy tracking the length of every container object *in the easy case* (things read from a file or similar would be impossible to check because we wouldn't know their length). But tracking that state even for string constants is almost certainly infeasible. We could special case empty strings, but I doubt that would have much benefit.

Is there another programming language that has a type system that handles this?

**Comment by JukkaL** [comment]
Something like this is not a good fit for how mypy works, but I could imagine someone building a separate tool that does deeper static analysis on top of a type-annotated mypy AST.
