### ISSUE TITLE
Feature request: disallow untyped/Any parameters to typed function

### ISSUE THREAD

**Issue by Ploppz** [python/mypy#8281]
I haven't found a way to configure mypy to do this:

If I have a function `def foo(a: MyType)`, and in some other function, I call `foo(something)` then I would like an error from mypy if `something` has not been given an explicit type (or if it is Any).
The calling function would then have to convince mypy that `something` is of a certain type (we don't have to care about any other typing in that function), for example declaring it as `something: MyType = typedload.load(some_other_untyped_function(), MyType)` - here assuming that `some_other_untyped_function` returns a dict that `typedload` can convert to `MyType`.

If mypy could assure me that any caller of `foo` sends in the right types then I would have some peace of mind.

**Comment by JukkaL** [comment]
Something like this has been requested before, and intuitively it sounds like a potentially useful feature, as it would allow library writers to require some basic level of type checking in code that uses the library. If I understood the proposal correctly, mypy would only complain about specific functions if they are called with an `Any` argument, but other functions not opted in could be called with `Any` arguments as before.

This has a bunch of challenges, however:
* If the typed function is a method, mypy won't be able to catch calls to it via an `Any` value, for example. This would be a pretty major hole. (Say, argument `x: Any` followed by `x.foo(x)`. Mypy doesn't know which `foo` method this would call.)
* You could take an alias of `foo` and call through it, and mypy couldn't generally know that it's `foo`. (For example, something like `alias = [foo]` followed by `alias[0](dangerous_value)` elsewhere.)
* Mypy doesn't perform checking in unannotated functions by default, by design, and this would be another hole, unless we make an exception for this feature.

**Comment by Ploppz** [comment]
Ok understood, thanks for the reply. Feel free to close this issue then.

**Comment by ltworf** [comment]
Oh, I just found this now.

typedload is annotated, except that to my knowledge there is no generic way in python to annotate "it will return an instance of the type passed in the parameter"

**Comment by ltworf** [comment]
Maybe i should just do a mypy plugin…
