### ISSUE TITLE
MyPy does not infer non-None value despite previous assert

### ISSUE THREAD

**Issue by julaudo** [python/mypy#8299]
Consider the following function:
```
def test(value: str = None, value2: str = None):
    assert(value or value2)
    print(value or value2.capitalize())
```

Mypy gives this error:

> error: Item "None" of "Optional[str]" has no attribute "capitalize"

The following function is simpler, and also generates the error:
```
def test(value: str = None, value2: str = None):
    assert(value)
    print(value or value2.capitalize())
```

**Comment by JukkaL** [comment]
One reason why these are tricky that it's not sufficient for mypy to infer a non-`None` type, but also it should figure out that the `str` value can't be empty, as an empty string is considered false. In the second example mypy actually infers `str` as the type of `value` after the assert.

I'm closing this since this is probably too difficult for mypy to handle, and this seems to happen quite rarely. If this starts to look like a relatively common issue, we may consider reopening this.
