### ISSUE TITLE
Too many arguments for IntEnum reported

### ISSUE THREAD

**Issue by Spenhouet** [python/mypy#8344]
If I define the following `IntEnum`:

    Numbers = IntEnum('Numbers', ['ZERO', 'ONE', 'TWO'], start=0)

mypy throws the following lint error: `Too many arguments for IntEnum()`.

The `start` parameter is an official methods:

> use the start parameter to specify a different starting value

https://docs.python.org/3/library/enum.html

**Comment by Michael0x2a** [comment]
Yeah, it looks like the checks in https://github.com/python/mypy/blob/master/mypy/semanal_enum.py#L99 are too strict.

If you're feeling up for submitting a PR, I think it would probably be good enough relax the checks so they make sure there are only two *positional* arguments, not just two arguments in total, and that the keyword arguments all have the right names -- see `call.arg_kinds`, `call.arg_names`, and https://github.com/python/mypy/blob/master/mypy/nodes.py#L1501.

And if you also feel like checking the types of the keyword arguments, we can probably get away with insisting the user always uses int and str literals for start/qualname/module. (Supporting arbitrary variables is tricky, since we special-case handling enums before the type checking phase).

**Comment by rahulrj** [comment]
@JukkaL is this a feature or a mypy bug? Can i submit a PR for this?

**Comment by mridullpandey** [comment]
hi bro @rahulrj  are you working on it...

**Comment by swetavooda** [comment]
If nobody is assigned for this issue, I would like to work on it.

**Comment by rahulrj** [comment]
I am not working on this @mridullpandey

**Comment by mridullpandey** [comment]
hi @swetavooda i have did some sort of modifications on it,will you please take another one ..pls let me know asap thanks :-)

**Comment by mridullpandey** [comment]
@Michael0x2a  will you please elaborate it  what to actually do

**Comment by swetavooda** [comment]
@mridullpandey If you are really willing to work on this, you may continue. I'll find another issue to work on.

**Comment by Arshaan-256** [comment]
#8436

**Comment by Arshaan-256** [comment]
Merge pull request #8436. Hopefully that would fix the issue.

**Comment by mridullpandey** [comment]
then why this is still alive
@Arshaan-256

**Comment by Arshaan-256** [comment]
@mridullpandey Because it has been reviewed yet. Once the PR is reviewed by the collaborator, only then can the issue be closed. The PR has passed the tests as well.

**Comment by momohatt** [comment]
This seems to have been already fixed in #9123

**Comment by JelleZijlstra** [comment]
Indeed, closing this issue
