### ISSUE TITLE
Class inheritance asterisk leads to "Parse error before *"

### ISSUE THREAD

**Issue by jimbo1qaz** [python/mypy#852]
Python 3.4.3 x64, mypy master, Windows 7 x64.

A class inheriting from a list of classes via asterisk leads to a parse error.

Also happens with lone classes before the list.

Example:

```
classes = []    # type: List[type]

class TestClass(*classes): pass
```

**Comment by o11c** [comment]
The parser fix likely will be included with my `syntax` branch, but I'm not sure how to lower it for analysis.

**Comment by gvanrossum** [comment]
This now leads to a different error, "Invalid base class". I think that's reasonable (how is mypy going to figure out the specific base classes you wanted). So...

I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.
