### ISSUE TITLE
"Type of TypedDict is ambiguous" despite tag fields being distinct Literal types

### ISSUE THREAD

**Issue by florimondmanca** [python/mypy#8533]
Hi there,

Thanks for all the awesome work on mypy! It's brought incredible improvements to my workflow. :-)

I'm reporting what could be a bug with [tagged unions](https://mypy.readthedocs.io/en/stable/literal_types.html#tagged-unions), which were released in 0.770. As of today this is also reproducible against `master`.

Unfortunately this bug makes usage of tagged unions impractical. Last time I beta-tested it (a few days before the 0.770 release — perhaps around March 1st), it worked though.

Let me know if there's anything I can do to help resolve!

## Reproduction case

```python
# example.py
from typing import TypedDict, Literal, Union

# TypedDict interfaces with distinct tag fields.
A = TypedDict('A', {'@type': Literal['type-a'], 'value': str})
B = TypedDict('B', {'@type': Literal['type-b'], 'value': str})

# Tagged union of A and B.
C = Union[A, B]

c: C = {
    '@type': 'type-a',
    'value': 'test',
}
```

## Expected behavior

```console
$ mypy example.py
# OK - no errors
```

## Actual behavior

```console
$ mypy example.py
example.py:7:8: error: Type of TypedDict is ambiguous, could be any of ("A", "B")
example.py:7:8: error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Union[A, B]")
Found 2 errors in 1 file (checked 1 source file)
```

## Version info

- Python 3.8.1
- Mypy 0.770
- Mypy flags: none (and no `mypy.ini` in the current workdir).

## Additional context

I notice an ambiguous case is tested here:

https://github.com/python/mypy/blob/1180a9dfbdf6aef9a9df3a6f7639b3cd42f0be47/test-data/unit/check-typeddict.test#L837-L846

But the snippet above is _unambiguous_: `Literal['type-a']` and `Literal['type-b']` don't overlap at all. Is the test above passing in `master`?

**Comment by florimondmanca** [comment]
Ah, so I realize this might actually be a feature request… It seems we can't use a tagged union to declare variable, but only a function parameter, and then pattern-match inside the function based on whichever exact type is passed as a parameter, eg:

```python
from typing import TypedDict, Literal, Union

# TypedDict interfaces with distinct tag fields.
A = TypedDict('A', {'@type': Literal['type-a'], 'value': str})
B = TypedDict('B', {'@type': Literal['type-b'], 'value': str})

# Tagged union of A and B.
C = Union[A, B]

def process(c: C): pass

a: A = {'@type': 'type-a', 'value': 'test'}
process(a)  # OK
```

I'm not sure if it even makes sense to allow using `C` to declare a variable here — but I _think_ (?) it does? Eg even though mypy loses info about the exact type passed to a function, it's still true that either one of `A` or `B` will be passed to the function, right? I might use some more context on the design decisions behind tagged unions… Maybe I'm missing something?

**Comment by msullivan** [comment]
I think that I agree that this is a bug.

There is a pretty easy workaround, though:
```
a: A = ...
c: C = a
```
works

**Comment by florimondmanca** [comment]
Hi @msullivan, thanks :)

FWIW, my precise use case was yielding dicts that match a tagged union inside a generator function:

```python
from typing import TypedDict, Literal, Union, Iterator

A = TypedDict('A', {'@type': Literal['type-a'], 'value': str})
B = TypedDict('B', {'@type': Literal['type-b'], 'value': str})
C = Union[A, B]

def stream() -> Iterator[C]:
    yield {'@type': 'type-a', 'value': 'test'}
```

```console
$ mypy example.py    
example.py:9: error: Incompatible types in "yield" (actual type "Dict[str, str]", expected type "Union[A, B]")
example.py:9: error: Type of TypedDict is ambiguous, could be any of ("A", "B")
Found 2 errors in 1 file (checked 1 source file)
```

In that case your workaround works too, although pretty clunky:

```python
def stream() -> Iterator[C]:
    a: A = {'@type': 'type-a', 'value': 'test'}
    yield a
```

I'm new to the mypy codebase, but if you've got any pointers on where this might come from I can try and investigate a bit more.

**Comment by Michael0x2a** [comment]
The strategy I personally use is to grep for part of the error message. That usually points you to some location in messages.py, which is responsible for constructing and reporting error messages. Then, you can work backwards to figure out how exactly we ended up reaching that particular point in the code.

For example, grepping for "Type of TypedDict is ambiguous" should point you to [typed_dict_ambiguous in messages.py](https://github.com/python/mypy/blob/master/mypy/messages.py#L1153). And from there, we can see this is only called by [find_typeddict_context in checkexpr.py](https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L3322).

And finally, if we step through what this function is doing, we discover that mypy is comparing the TypedDicts against the dict expression only by their keys and bails out early if there are multiple potentially valid TypedDict contexts. (And the caller of find_typeddict_context is what's actually responsible for checking the values).

This is where the bug is coming from: this filtering strategy is probably too aggressive/the whole flow of logic here could probably do with a second look.
