### ISSUE TITLE
Invalid assignment target when setting function to compatible function type

### ISSUE THREAD

**Issue by ecprice** [python/mypy#862]
Code like the following gives an error:

```
def bar() -> None: pass

if 1:
    def foo() -> None: pass
else:
    foo = bar
```

```
foo.py:6: error: Invalid assignment target
```

even though replacing `foo = bar` with another `def foo()` would work fine.  This seems related to #708 but distinct.

**Comment by o11c** [comment]
Eh, it's all part of the same fundamental design flaw, I'd call it a dupe.

Remember that mypy follows *both* branches of the if statement, in the order they occur.

Though even with all my consideration, I am not entirely sure what ought to be done for descriptors in general.

**Comment by ecprice** [comment]
Well, in this case the error happens in semanal, and blocks any other type checking for the file.  So it's clearly distinct, and more annoying when it happens.

I don't see the issue with mypy following both branches, in order.  The assignments are compatible.  Why shouldn't mypy treat this the same way it treats the following?

```
if 1:
    def foo() -> None: pass
else:
    def foo() -> None: pass
```

**Comment by JukkaL** [comment]
Yeah, the code above should be valid. The underlying issue is that mypy treats functions and variables as different kinds of definitions (due to an old design decision that can be traced back to Alore). We should probably relax this and always allow assignments to functions. 

This wouldn't resolve all issues with existing code as people are often sloppy and use mock functions that aren't fully compatible with the original function, such as by having different argument names. And in general argument names will be difficult to enforce until all the stubs have correct argument names for all functions, including underscore prefixes for arguments that are positional-only. This will be a lot of work, but with suitable tooling it should be doable. Or maybe don't care too much about argument names except for the most common functions and commonly mocked functions. The same issue also applies to overriding methods -- currently mypy just doesn't care about argument name compatibility (at least much) because a lot of code doesn't even try to be consistent.

**Comment by o11c** [comment]
An interesting case from the standard library is `encodings.utf_8.IncrementalDecoder._buffer_decode`.

In this case, a base class's abstract method is overwritten by a non-descriptor callable (we really need a way to be able to specify those).

**Comment by ethanhs** [comment]
Closing as this works under 0.510 and master.
