### ISSUE TITLE
Defining type equivalencies

### ISSUE THREAD

**Issue by adithyabsk** [python/mypy#8632]
## Situation
This is probably a silly question but here goes...

```python
# test.py
from marshmallow import Schema, fields
import pytz

class ExampleSchema(Schema):
   schema_date = fields.AwareDateTime(default_timezone=pytz.UTC)
```

```console
$ mypy test.py
```

## Error raised
Argument "default_timezone" to "[AwareDateTime](https://marshmallow.readthedocs.io/en/stable/_modules/marshmallow/fields.html#AwareDateTime)" has incompatible type "[_UTCclass](https://github.com/stub42/pytz/blob/7b1a844c8ecf2996142ac0eb32201b676e9dcb9a/src/pytz/__init__.py#L259)"; expected "Optional[timezone]"

## Question / Help
It doesn't make sense to reach out to `marshmallow` to accept `pytz` timezones, since it doesn't need to have any concept of pytz timezones as long as they are compatible. Is there any configuration that I can pass the type checker to let it know that those types are equivalent.

(Besides `# type: ignore`)

**Comment by JukkaL** [comment]
So the issue seems to be that the types in `marshmallow` are too narrow.

A cast or a `# type: ignore` are the ways to go, or you can implement a helper
function that does the (no-op) type conversion. There is no supported way to 
say that two types should be treated as equivalent.

More generally, maybe `marshmallow` should use protocol types to define
timezone types?

**Comment by adithyabsk** [comment]
@JukkaL If I were to open up an issue in `marshmallow` for this, what direction would I suggest the project take to solve this issue. Do they have to define a protocol type that checks for all the attributes that they need in a `datetime` so that it could be compatible with `pytz`?
