### ISSUE TITLE
Auto-discovery of .test files

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#8650]
Currently all the `.test` files (used for mypy self tests) are enumerated in the test case runners, such as in `mypy/test/testcheck.py`. This is error-prone and can be confusing.

It would be better to do auto-discovery of test files using file name prefixes. For example, all the files with names like `check-*.test` would be executed by `mypy.test.testcheck`.

(Additionally, if there is an unrecognized `.test` file, it would be nice to generate an error and give hints about how to fix the issue. Addressing this is optional for now, however, and may be a bit tricky.)

**Comment by davidzwa** [comment]
I am interested in looking into this, as it was a bit unexpected that the `testpep561.py` file parsed the `pep561.test` file by direct reference (as do other tests I presume?). As I've read they do this by specifying the `files` property in a DataSuite-inheriting class. I've worked with code running in this extract (testpep561.py):
```
class PEP561Suite(DataSuite):
    files = ['pep561.test']

    def run_case(self, test_case: DataDrivenTestCase) -> None:
        test_pep561(test_case)
```

One would expect one (or a couple extended) classes(s) to parse all the tests and generate a recognizable pytest output.

It's going to require a bit more understanding on my side, although I gained some experience through #8524 and @ethanhs his work in #8571. So just for clarity's sake:
- We are interested in regex'ing `foo-bar.test` files by combining unit tests starting with **foo**.
- We are interested in intercepting pytest autodiscovery (any class extending TestCase/Suite/DataSuite/etc.) . Any pointers to which class to start studying if so? (Files: `data.py` or `helper.py` possibly).
- We need some global awareness of which tests are picked up only once by a module (f.e. `mypy.test.testcheck` as your example goes). I'd expect this to be more strict: we can **only** allow one `.test` file to map to one `test*.py` file?
- We'd like some way of generating a mapping the data tests in a custom discovery class, with 'missed_cases' as optional output, but it is expected to by tricky because it can generate wrong information/advice or has some edge cases.

**Comment by davidzwa** [comment]
@JukkaL it'd be awesome to hear your thoughts so I can get to work.

Just a 'go-ahead' is fine for now.

**Comment by davidzwa** [comment]
I will work on this, although any comment would be great. @ethanhs do you have any thoughts? It isn't a small endeavor this time, but pretty similar to data-driven tests like we worked on earlier

**Comment by ethanhs** [comment]
I'm afraid I'm not sure the particulars of what @JukkaL has in mind, so it'd be best to ask him.

**Comment by davidzwa** [comment]
@JukkaL I'd gladly hear about whether this issue can be acted upon

**Comment by iamsdas** [comment]
I'd like to work on this issue.
From what I understand, we need the list of `.test` files to be auto generated. I am thinking of using something like `pathlib.Path().rglob("prefix*.test")` to do so. What do you think?

**Comment by davidzwa** [comment]
Up for grabs, @ethanhs @JukkaL could you help this fella out?

**Comment by MiHarsh** [comment]
Hello Sir ,

I was trying to fix auto-discovery of .test files #8650

Here is the script

```
# List of files that contain test case descriptions.

typecheck_files = [f for f in os.listdir("../../test-data/unit") if re.match(r'check-\w+-?\w+?.test',f)]

# Tests that use Python 3.8-only AST features (like expression-scoped ignores):
if sys.version_info < (3, 8):
    typecheck_files.remove('check-python38.test')
if sys.version_info < (3, 9):
    typecheck_files.remove('check-python39.test')

# Special tests for platforms with case-insensitive filesystems.
if sys.platform not in ('darwin', 'win32'):
    typecheck_files.remove('check-modules-case.test')  
```

But there was path not found error. Can you exactly tell me from where would it be called ?
As seen in [ReadMe](https://github.com/python/mypy/blob/master/test-data/unit/README.md) , you have called many functions as 

```
$ pytest -n0 mypy/test/testcheck.py
```

So is that the default location from where we can call it ? If yes ,then maybe this would work :

```
# List of files that contain test case descriptions.

typecheck_files = [f for f in os.listdir("test-data/unit") if re.match(r'check-\w+-?\w+?.test', f)]


# Tests that use Python 3.8-only AST features (like expression-scoped ignores):
if sys.version_info < (3, 8):
    typecheck_files.remove('check-python38.test')
if sys.version_info < (3, 9):
    typecheck_files.remove('check-python39.test')

# Special tests for platforms with case-insensitive filesystems.
if sys.platform not in ('darwin', 'win32'):
    typecheck_files.remove('check-modules-case.test')
    
```
Please Help !!

**Comment by SwagatSBhuyan** [comment]
Hello, I'd like to solve this issue, although many have already solved this prior to me.
@JukkaL @davidzwa Can anyone reach out, I have a few pointers. Also, it'd be great to start my contribution journey from this issue of mypy.

Thanks!
