### ISSUE TITLE
Mypy thinks that my alias is a type variable

### ISSUE THREAD

**Issue by nazariyv** [python/mypy#8674]
* Are you reporting a bug, or opening a feature request?
bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
import pandas as pd  # type: ignore

# alias, not a type variable
Dataframe = pd.DataFrame

def load(data: Dataframe):
  ...
```

* What is the actual behaviour/output?
"Variable ...Dataframe" is not valid as a type. See the link with common issues (type variables versus aliases)

* What is the behaviour/output you expect?
This is an alias, so everything should work fine

* What are the versions of mypy and Python you are using?
Python=3.7.7
mypy==0.770
mypy-extensions==0.4.3

  Do you see the same issue after installing mypy from Git master?
Yes

* What are the mypy flags you are using? (For example --strict-optional)
Vscode mypy integration, single flag defined in `mypy.ini`:
```
[mypy]
follow_imports = "skip"
```

**Comment by nazariyv** [comment]
BTW, if I change the signature from

```
def load(data: pd.DataFrame):
  ...
```

the error goes away

**Comment by ravwojdyla** [comment]
+1 seeing the same issue with:

```python
python==3.8.6
mypy==0.812
mypy-extensions==0.4.3
```

👋 @nazariyv have you been able to workaround it in a sane way?

**Comment by JelleZijlstra** [comment]
The issue here is that because mypy doesn't know anything about pandas, it doesn't know that pandas.DataFrame is a type, and instead just treats it as a value of type Any. Then if you do `Dataframe = pd.DataFrame`, it just thinks that you're assigning a value of type Any to `Dataframe`, not creating a type variable. This has come up repeatedly; perhaps mypy should allow variables of type Any as annotations.

Possible workarounds:
- Write stubs for pandas, so that pd.DataFrame is no longer Any (but good luck with that)
- Use `if TYPE_CHECKING` to set `DataFrame = Any` for mypy (which *is* recognized as a type alias)
- Use `from pandas import DataFrame` instead (though I haven't tried this)

**Comment by AlexWaygood** [comment]
In 2022, [the solution](https://mypy-play.net/?gist=6c0720114c16c3a1e254cf5e573c3faf&mypy=latest&python=3.10&flags=strict) is to use `typing.TypeAlias` (or `typing_extensions.TypeAlias` on Python <3.10) to explicitly declare a type alias:

```python
from typing import TypeAlias
import pandas as pd  # type: ignore

# alias, not a type variable
Dataframe: TypeAlias = pd.DataFrame

def load(data: Dataframe):
  ...
```
