### ISSUE TITLE
Mypy thinks that abstractstaticmethod should have at least one argument

### ISSUE THREAD

**Issue by nazariyv** [python/mypy#8679]
```python
@abstractstaticmethod
def extract(): 
    raise NotImplementedError("should have a method to extract")
```

Mypy wants this method to have at least one argument.

**Comment by Michael0x2a** [comment]
Currently, mypy currently only supports using `@staticmethod` and `@abstractmethod` separately, like so:

```python
class Foo:
    @staticmethod
    @abstractmethod
    def extract():
        raise NotImplementedError("should have a method to extract")
```

Probably mypy should also support `@abstractstaticmethod` -- while that decorator has been [deprecated since Python 3.3](https://docs.python.org/3/library/abc.html#abc.abstractstaticmethod), it still does see use from time to time.

Anyways, closing this in favor of https://github.com/python/mypy/issues/6244, which discusses the same problem with `@abstractclassmethod`.
