### ISSUE TITLE
Can't deduce type in Union of TypedDicts

### ISSUE THREAD

**Issue by johng** [python/mypy#8710]
Given the following example

```python

class A(TypedDict):
    a : int

class B(TypedDict):
    b : str

def foo(f: Union[A,B]) -> Union[str, int]:
    if "a" in f:
        return f["a"]
    else:
        return f["b"]
```

I would expect the type of `f["a"]` to be `int` and `f["b"]` to be a `str`. Instead mypy complains that `f["a"]` is invalid because of the missing index `b` and vice versa.

```
error: TypedDict "B" has no key 'a'
error: TypedDict "A" has no key 'b'
```

**Comment by msullivan** [comment]
This sort of refinement rule for TypedDicts wouldn't be sound, since TypedDicts have structural subtyping. So for example, `{"a": "a string", "b": "another strong"}` is a valid value of type `B`, because it has a key `b` with type `str`. We don't mind that it also has an extra key "a". This is useful in a lot of ways, but it unfortunately means that deciding that the value is an `A` because it has a key `"a"` isn't valid; a value of `B` could have that key also.

Thanks!

**Comment by johng** [comment]
@msullivan I disagree, mypy will complain about extra keys.

Given the following example

```
class A(TypedDict):
    a: str

a: A = {"b":"123", "a": "awbdawd"}
c: A = {"a": "adwawd"}
``` 

Mypy will complain about the extra key for `a`.

**Comment by johng** [comment]
@msullivan could you take another look please
