### ISSUE TITLE
`sum(List[Decimal]) + sum(List[Decimal])` incompatible type error

### ISSUE THREAD

**Issue by myartsev** [python/mypy#8814]
Using mypy-0.770 with no additional flags

```
from decimal import Decimal

foo = [Decimal("1"), Decimal("2")]
sum(foo)

sum(foo) + sum(foo)
```

The first `sum` statement is okay, but the second is an `error: Argument 1 to "sum" has incompatible type "List[Decimal]"; expected "Iterable[int]"  [arg-type]`

**Comment by hauntsaninja** [comment]
Interesting.

For some context, `sum` is typed as the following in typeshed.
```
@overload
def sum(__iterable: Iterable[_T]) -> Union[_T, int]: ...
@overload
def sum(__iterable: Iterable[_T], start: _S) -> Union[_T, _S]: ...
```
This is how the `int` gets in there; i.e. how `reveal_type(sum(foo))` is `Union[decimal.Decimal*, builtins.int]`. This is correct, since you could run:
```
foo.clear()
assert isinstance(sum(foo), int)
```

It seems to me that mypy is using the context that the return value of the first sum could be an int to infer the argument type of the second sum.

If you convince it that it's dealing with a Decimal by the time it gets to the second foo you no longer see an error, e.g. by:
```
cast(Decimal, sum(foo)) + sum(foo)  # or
Decimal(0) + sum(foo) + sum(foo)  # or
sum(foo) + Decimal(0) + sum(foo)  # but not
sum(foo) + sum(foo) + Decimal(0)
```
My guess is that mypy is forgetting about `__radd__` somewhere.

**Comment by hynekcer** [comment]
This is currently fixed, probably between versions 0.950 and 0.960

**Comment by hauntsaninja** [comment]
Hmm, the lack of error here bisects to https://github.com/python/mypy/pull/12631
@huguesb / @JelleZijlstra  is it expected that that PR changes what errors get reported?

**Comment by JelleZijlstra** [comment]
No, that's not expected. Maybe something changed to overload resolution.

**Comment by hauntsaninja** [comment]
Are you looking into it?

**Comment by JelleZijlstra** [comment]
No

**Comment by hauntsaninja** [comment]
Okay, false alarm. I bisected this wrong. Looks like it's a typeshed change, which is believable https://github.com/python/typeshed/pull/8000/files
