### ISSUE TITLE
Name 'X' already defined on line Y when inside a if/else

### ISSUE THREAD

**Issue by WhyNotHugo** [python/mypy#8828]
When defining a class in an `if/else`, `mypy` seems to think I'm redefining a class, when it's really only being defined once:

```python
pillow_installed = True  # Adding this so the example is self-contained and valid.


if pillow_installed is None:
    ImageWriter = None
else:
    class ImageWriter(BaseWriter):  # error on this line
        pass
```

Outputs:
```
barcode/writer.py:330: error: Name 'ImageWriter' already defined on line 327
```

Using mypy 0.770.

**Comment by Alberth289346** [comment]
Not a project member, but I had a similar thing yesterday.

`mypy` assumes a variable name has one and only one type through the entire program.

The `ImageWriter = None` line defines the type of that variable as `None` (variable has the same type everywhere, so any line where you can derive the type is good, I guess).
The `else` clause attempts to make the variable a class, which is not `None`, so you get an error.

What you really want to express is that the variable has 2 possible values rather than one. That means it has a `typing.Union` type, or for `None` a `typing.Optional` type.

You seem to need to do the following:
``` python
# Move the class outside the if so the type of ImageWriter can always be resolved.
class MyImageWriter():  # Removed BaseWriter here for self-containment
     pass

# Declare the type of ImageWriter. Note you cannot refer to the class
# definition with the same name as that would refer back to the variable
# that you are declaring here.
ImageWriter: Optional[Type[MyImageWriter]]

if pillow_installed is None:
    ImageWriter = None
else:
    ImageWriter = MyImageWriter
```

Alternatively, you can declare the type as part of the `None` assignment: `ImageWriter: Optional[Type['MyImageWriter']] = None`

**Comment by WhyNotHugo** [comment]
Declaring `MyImageWriter` outside the if will fail, because it that code only works if an optional dependency is there.

This fails too:
```python
from typing import Optional, Type
pillow_installed = True

ImageWriter: Optional[Type]

if pillow_installed is None:
    ImageWriter = None
else:
    class ImageWriter():
        pass
```

Output is:

    test.py:9: error: Name 'ImageWriter' already defined on line 4

I think mypy needs to understand that there's branching going on, and it's `ImageWriter` is **not** already defined in this case.

**Comment by msullivan** [comment]
Yeah, mypy does not really understand conditional class definitions very well and probably won't. This is partially because mypy is opinionated that this sort of thing is usually an anti-pattern, but also because it's not super clear how to support it well and it usually isn't hard to work around. 

I'd put the class definition case first and put a type: ignore on the redefinition.

Thanks!

**Comment by jepperaskdk** [comment]
Please reopen this - basic scoping is not supported currently:
```
x: str = 'd'

if x == 'a':
    y: int = 123
elif x == 'b':
    y: int = 456    # error: Name 'y' already defined on line 4
elif x == 'c':
    y = 'abc'       # Incompatible types in assignment (expression has type "str", variable has type "int")
    y: str = 'def'  # error: Name 'y' already defined on line 4
```
I would only expect these errors if I had defined `y: int = 123` before the if statement.

**Comment by jepperaskdk** [comment]
@JukkaL Thank you for your reply.
I understand that the variable `y` may be set on the scope outside the if-block, but to me, the error here is not logical, since only 1 of those 3 branches will be hit.

This case below is different, since the first if-block may set the variable on the outer scope, and hence it may exist when reaching the second if-block:
```
if ...:
    y: int = 123
if ...:
    y: int = 123
```

**Comment by erictraut** [comment]
As Jukka mentioned, Python doesn't introduce different scopes for `if` blocks. All references to `y` in your code sample refer to the same symbol, and you are providing conflicting type declarations for that symbol. In one place, you're declaring that it is limited to an `int`. In another location, you're declaring that the same symbol is limited to a `str`. If your intent is that `y` is allowed to be assigned either an `int` or `str`, then you should declare its type as a union of those two types (`int | str`).

**Comment by jepperaskdk** [comment]
@erictraut Thanks, I think I get it now. `y: int` and `y: str` would effectively be wrong, since the combination of the two branches would yield that y is in fact `Union[int, str]` after the two blocks. Thank you for your replies 👍

**Comment by vishal-ramesh2** [comment]
I have a similar issue. I have a code block
```python
if ...:
    y: ClassA = func1(...)
else ...:
    y: ClassA = func2(...)
```

I have the same type declarations for the symbol, but I get the error inside the `else` that `y` is already defined on line `<inside if>`. What would be the best way to handle this?

**Comment by vishal-ramesh2** [comment]
Adding more info

I cannot do what @msullivan suggested by having `y: ClassA = func2(...)` outside the if/else block because the functions `func1` and `func2` do different operations on the database and return the results of the operation.

**Comment by hauntsaninja** [comment]
See the example here https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#variables with `child`

**Comment by vishal-ramesh2** [comment]
Thank you!
