### ISSUE TITLE
No `arg-type` error for incompatible Django model types

### ISSUE THREAD

**Issue by myartsev** [python/mypy#8852]
Using mypy-0.770 with no additional flags

```python3
from django.db import models

class Baz():
    pass

class Foo(models.Model):
    pass

class Bar(models.Model):
    pass

def f(param: Foo) -> None:
    pass

f(Foo())
f(Bar())
f(Baz())
```

mypy has one error: `error: Argument 1 to "f" has incompatible type "Baz"; expected "Foo"  [arg-type]`
`f(Bar())` is unexpectedly fine.

What is special about the django models here?
The two expected arg-type errors would be raised if a vanilla base class is used instead:
```python3
from django.db import models

class Baz():
    pass

class Foo(Baz):
    pass

class Bar(Baz):
    pass

def f(param: Foo) -> None:
    pass

f(Foo())
f(Bar())
f(Baz())
```

**Comment by msullivan** [comment]
Do you have the django stubs installed? Could it be that you don't and it isn't finding the class?

**Comment by myartsev** [comment]
That's right, I am not using django stubs (for other reasons) but I was surprised that it'd be needed here.

**Comment by russelldavis** [comment]
Yeah, it's surprising due to a hidden `Any`. When mypy can't find stubs, it substitutes `Any` ([details here](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library)).

And when you have `Any` as a base class, all other classes become compatible (because they could potentially be the base class).

**Comment by erictraut** [comment]
I think mypy is working correctly here. Without stubs installed, the imported symbols will have the type `Any`.
