### ISSUE TITLE
Tuple slicing is not supported

### ISSUE THREAD

**Issue by o11c** [python/mypy#886]
`mypy -c 'v = (1, 2, 3); major, minor = v[:2]'`

`<string>:1: error: Tuple index must an integer literal`

Oddly, this was not a failure *before* I rebased my branch.

**Comment by JukkaL** [comment]
Yeah, mypy should support this, obviously. Not sure why it got broken, though (or why it used to work).

I think that this needs to be fixed in ` visit_index_expr_helper` (`mypy/checkexpr.py`).

**Comment by JukkaL** [comment]
Basic support for this is now in (by @jhance). 

I'm leaving this open for now as a few additional things would be nice to have:

* Negative literal int in slice (e.g., t[:-1]).
* Non-literal in slice for uniform tuples. Basically a tuple like `Tuple[int, int, int]` would be treated similarly to `Tuple[int, ...]` for slicing. (See also #899.)

**Comment by jhance** [comment]
> Basically a tuple like Tuple[int, int, int] would be treated similarly to Tuple[int, ...] for slicing

I firmly believe this is evil. Having `n=0` and slicing on `n:` would give me a different type than slicing on `0:`.

**Comment by o11c** [comment]
There are plenty of ways to get the same object with a different type, there is nothing evil about that.

**Comment by jhance** [comment]
Its not about the fact that I get the same object with a different type, its the fact that I'm allowed to:
1) Do things engaging with variable-length tuples simply because it happens to be homogenous, despite non-variable-length homogenous tuples not being special in the type system.
2) Its too easy to accidently end up with a homogenous tuple when you don't intend to. If you want this why are you not using sequence?

**Comment by o11c** [comment]
But even if you *don't* intend to get a homogenous tuple, you'll just get an error a little bit later.
