### ISSUE TITLE
Allow non-literals when indexing uniform tuples

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#899]
Currently mypy doesn't allow indexing fixed-length tuples using a non-literal index. We should probably support this at least for tuples with homogeneous types. 

For example, code like this should probably be okay:

``` python
t = (1, 3, 7)
for i in range(len(t)):
    print(i, t[i])
```

The example below is actually already valid so rejecting the above code is inconsistent (this works due to how we set the `fallback` attribute for tuples to be `Tuple[t, ...]`):

``` python
t = (1, 2, 3)
for i, x in enumerate(t):
    print(i, x)
```

**Comment by JukkaL** [comment]
The relevant bit of code is `visit_index_expr_helper` in `mypy/checkexpr.py`.

**Comment by o11c** [comment]
I think there's a good argument for allowing it for all tuples, just with a return type of `Union[T, U, V...]`.

Rather than forcing the error immediately, let the error be deferred if necessary.

**Comment by momandine** [comment]
I had a generator expression that constructed a tuple, that I knew from context would be of length 3
```
self.tpl = tuple(int(x) for x in some_string.split('.'))  # type: Tuple[int, int, int]
```
And then later `__getitem__` that indexed into the tuple
```
def __getitem__(self, key):
    # type: (int) -> int
    return self.tpl[key]  
```
There were two mypy errors:
```
error: Incompatible types in assignment (expression has type Tuple[int, ...], variable has type "Tuple[int, int, int]")
error: Tuple index must be an integer literal
```
The first is easier to understand, the latter I found very confusing because it went away as soon as I typed the tuple-generator exception without a specific length, e.g. `Tuple[int, ...]`. Why would indexing into a less-specific tuple be ok but a fixed-length one bad?
