### ISSUE TITLE
Literal inference with a discriminated tuple type is either broken or very limiting

### ISSUE THREAD

**Issue by bsmedberg-xometry** [python/mypy#9080]
Please provide more information to help us understand the issue:

* *Are you reporting a bug, or opening a feature request?* I don't know whether this should be considered a bug or a missing feature; but it's definitely a lack of functionality relative to typescript or similar static checkers.

* *Please insert below the code you are checking with mypy:*

```python
from typing import Union, Tuple
from typing_extensions import Literal, Final

return_type = Union[
    Tuple[Literal[True], int],
    Tuple[Literal[False], str],
]


def get_int_or_string(a: str) -> return_type:
    if a.startswith("int"):
        return True, 17

    return False, "notfound"


is_int, result = get_int_or_string("intfoo")
if is_int:
    math_op: int = result + 5
    print(f"It was an int: {math_op}")
else:
    str_op = result + " more string"
    print(f"It was a string: {str_op}")
```

* *What is the actual behavior/output?*

```
/home/bsmedberg/mypy-test.py:12: error: Incompatible return value type (got "Tuple[bool, int]", expected "Union[Tuple[Literal[True], int], Tuple[Literal[False], str]]")
/home/bsmedberg/mypy-test.py:14: error: Incompatible return value type (got "Tuple[bool, str]", expected "Union[Tuple[Literal[True], int], Tuple[Literal[False], str]]")
/home/bsmedberg/mypy-test.py:19: error: Unsupported operand types for + ("str" and "int")
/home/bsmedberg/mypy-test.py:19: note: Left operand is of type "Union[int, str]"
/home/bsmedberg/mypy-test.py:22: error: Unsupported operand types for + ("int" and "str")
/home/bsmedberg/mypy-test.py:22: note: Left operand is of type "Union[int, str]"
Found 4 errors in 1 file (checked 1 source file)
```

* *What is the behavior/output you expect?*

I expect this file to pass type-checking as written. There are two pieces of the reported errors which are incorrect:

1. Within the `get_int_or_string` function, if I return a literal `True` value, the type inference system cannot match that up to a `Literal[True]` for type discrimination. I was able to work around this bug by doing an ugly two-part:
   ```python
   literal_true: Literal[True] = True
   return literal_true, 17
   ```
2. when consuming the resulting union type, the check against the literal type should discriminate the union so that I can then operate on the other variable `result`. I've tried various workarounds for this including `if is_int == True`, `if is_int is True`, and even `if is_int == literal_true`, all to no avail.

* *What are the versions of mypy and Python you are using?*

mypy == 0.782, python 3.6.8

  *Do you see the same issue after installing mypy from Git master?* I have not tried this yet.

* *What are the mypy flags you are using? (For example --strict-optional)* no flags

**Comment by JukkaL** [comment]
The return type case seems something that wouldn't too difficult to support, but it doesn't sound very useful without support for the narrowing use case. Keeping track of dependencies between the types of local variables would require some pretty heavy machinery, arguably for a fairly rare use case.

A reasonably way to do this is to rewrite the code to use a union of dataclasses or named tuples, and to not decompose the return value until after a type check (using `isinstance`). Literal types are mostly designed to support some legacy use cases, and we aren't planning to make them significantly more powerful.

I'm closing this since the required fix seems too complicated. If somebody can suggest a simple way to support this, I might reconsider.
