### ISSUE TITLE
Annotate as specific module?

### ISSUE THREAD

**Issue by goodwillcoding** [python/mypy#9082]
Hi folks,

I have two possible logging modules to use and I am trying to annotate `_logging` like so.

```
import logging

def logger(request, _logging:Union[logging, logging2]=logging) -> logging.Logger:
    return _logging.getLogger("test")
```
And running in 
```
error: Module "logging" is not valid as a type
error: Returning Any from function declared to return "Logger"
error: logging? has no attribute "getLogger"
```

Is there a way to annotate something as specific module? I've tried types.ModuleType but that was working either

**Comment by JelleZijlstra** [comment]
There is no real way for this right now. `ModuleType` "works" in the sense that will let you pass the argument, but because it only has attributes valid on any module, it's not very useful in practice.

You could define a Protocol containing methods like `getLogger(name: str) -> Logger`, but I haven't verified whether that works.

**Comment by JukkaL** [comment]
Using a protocol is probably the best way. You may need to use an explicit cast.
