### ISSUE TITLE
Question: Can't import Django app located in the same project

### ISSUE THREAD

**Issue by LanDinh** [python/mypy#9135]
Project structure:

```
- project
|- __init__.py
|- project
 |- __init__.py
 |- settings.py
|- app1
 |- __init__.py
 |- views
  |- example_view.py
|- app2
 |- __init__.py
 |- datatypes.py
```

`settings.py` is a Django configuration file that contains both `app1` and `app2` in its `INSTALLED_APPS`.
`example_view.py` contains `from app2 import datatypes`

This works well when running the server, no problems at all. But when throwing `mypy` at it, I get the error `project\app1\views\example_view.py:14: error: Cannot find implementation or library stub for module named 'app2'`. I should add that `mypy` is perfectly able to find typing issues within `datatypes.py` itself (I've introduced errors on mistake to check that), it just doesn't realize that the module that `example_view.py` is trying to import is just this `datatypes.py` it can type check perfectly fine.

I've tried to solve this by adding `mypy_path` to `[mypy]` in my `mypy.ini`, but to no avail (I might not have done that correctly; I used `\\127.0.0.1\X$\<path-to-project>`, following the instructions at https://mypy.readthedocs.io/en/stable/config_file.html).

I'm using `python 3.8.1` and `mypy 0.770` and use the command `mypy --strict --follow-imports=error project`.

I'm not really sure what else to do, I've tried a lot of other (less sensible things), trying to get mypy to be happy... Without that import from the sibling app, everything works fine. I don't want to restrict my project to only have 1 app, as this will totally get out of hand as I add more code to it. I could of course create a `superapp` and have both `app1` and `app2` be childen of that, but I don't think that it's good practice to completely change the structure of my working project just to satisfy `mypy`, when all information that it needs _sits there_ - the literally only problem is that `mypy` can't connect that import with that other file it successfully type checks.

**Comment by LanDinh** [comment]
I've made some progress... As it turns out, I understood UNC paths correctly, but had a typo in my path.

Now, the module is found, but `mypy` still is throwing errors:

```
error: Import of 'app2' ignored
(Using --follow-imports=error, module not passed on command line)
```

I can make this go away by prefixing the package with the project name like this: `from project.app2 import datatypes`, but then, `django` is having problems and I can't run the server anymore, as the module `project` can't be found.

**Comment by noahsark769** [comment]
@LanDinh could you share the mypy_path configuration you used in order to get rid of the `Cannot find implementation` errors? I'm trying to do the same thing (make mypy correctly fine the django app aliased imports) and I haven't been able to figure out the correct combination of paths (maybe you need PYTHONPATH too?) and `mypy` invocation (are you using `mypy ./project`?) to get the imports to resolve correctly so that code from these imports is typechecked

**Comment by noahsark769** [comment]
I believe that the reason you're seeing the `ignored` errors now instead of `Cannot find implementation` is that `follow-imports` is now set to `error` (see https://mypy.readthedocs.io/en/stable/running_mypy.html#follow-imports) - in the default `follow-imports` behavior (normal) I believe you get the `Cannot find implementation` error when running with `--strict`. It seems that the underlying issue is still that mypy is not correctly finding the module, though

**Comment by noahsark769** [comment]
Ah, I was finally able to get it to work by passing MYPYPATH and PYTHONPATH environment variables as the same value:

```
MYPYPATH=./project PYTHONPATH=./project mypy project
```

**Comment by LanDinh** [comment]
I've since completely changed the structure of my project, so this is no longer an issue for me (sorry for the delay in answering!).

So I'll go ahead and close this :)
