### ISSUE TITLE
`mypy.codec` and `typing` are not installable for python2

### ISSUE THREAD

**Issue by o11c** [python/mypy#917]
Working on #915, when mypy is installed rather than run from the current dirrectory, the `mypy.codec` tests only work in python3 mode because there is no `setup.py` for python2.

Some previous discussion on #732 and #724.

**Comment by o11c** [comment]
Current thought: move it to `mypy_codec` package instead of a subpackage.

In the mean time I am XFAILing it so I can work on the rest of the bug.

**Comment by o11c** [comment]
Alternatively: move current `setup.py` to `setup3.py`, add a `setup2.py`, and have `setup.py` dispatch automatically.

**Comment by o11c** [comment]
Also affects `typing`, had to do some nasty hacks to make `testpythoneval` work for now.

**Comment by JukkaL** [comment]
I'd rather keep the existing `setup.py` unmodified and add a separate package `mypy-encoding` (with a dash instead of an underscore) that supports both Python 2 and Python 3. The official term is Source File Encoding: https://www.python.org/dev/peps/pep-0263/

For typing we need a separate package as well. At some point the idea was to have `typing` in https://github.com/JukkaL/typing but I haven't that in a while. We'll have to figure this out.

**Comment by JukkaL** [comment]
Actually, this is multiple independent issues. I'm going to split this into two separate issues.

**Comment by JukkaL** [comment]
This is now an umbrella task for #919 and #920. I'm keeping this open for now, but further discussion should probably happen under the subtasks.

**Comment by gvanrossum** [comment]
No, we should deprecate the codec and delete the code. See my comment in #919.
