### ISSUE TITLE
stubtest with config file

### ISSUE THREAD

**Issue by pikachu** [python/mypy#9193]
I want to pass in some plugins to `stubtest.py`, but it [calls](https://github.com/python/mypy/blob/65186ae1e23fd44f1d7e6aa2c4458bdf55640742/mypy/stubtest.py#L956) `build` without passing in any `extra_plugins` (you can see `extra_plugins` is a [param for`build`](https://github.com/python/mypy/blob/65186ae1e23fd44f1d7e6aa2c4458bdf55640742/mypy/build.py#L143)). Is this an in-progress feature?

More generally, can we make stubtest take in a config file the same way static type checking does? Is it true that most users would like to run runtime and static type checking with the same configuration?

Thanks in advance!

**Comment by hauntsaninja** [comment]
My primary goal with stubtest was to improve tests for typeshed stubs, so I just took the path of least resistance with the build (stubgen, a much older script, also kind of does its own thing for its build).

> Is it true that most users would like to run runtime and static type checking with the same configuration?

Plugins aside, I'm not sure how many mypy config options would be relevant to what stubtest does (since they do pretty different things...), so I'd be a little wary of changes purporting to make their configuration the same. Anyway, at the very least supporting plugins in stubtest sounds like something that's useful and should be done.

Btw, I might have missed something, but I'm not sure that anything currently passes `extra_plugins` to `build` (I think existing use is all from options), although refactoring some logic from `load_plugins_from_config` plus passing `extra_plugins` is probably the way to go here if you're looking to implement this.

**Comment by pikachu** [comment]
Sweet - I ended up creating a [PR](https://github.com/python/mypy/pull/9203) for this. I didn't modify `load_plugins_from_config` at all - was able to isolate this all in `stubtest.py`. We can continue discussion there.
