### ISSUE TITLE
Tests depend on the format of error strings too much

### ISSUE THREAD

**Issue by jhance** [python/mypy#921]
I've been thinking about this a bit, and I think the fact that we rely on `[out]` and other particular formatting of output is probably bad.

It would be nicer to have an object that represents the errors, and check against that, but not the formatting of how that object represents its error message to the user. We can test that separately, but testing it along with a lot of check-\* tests will make it impossible to change how the output looks in the future.

**Comment by o11c** [comment]
My `syntax` branch has the start of this.

**Comment by jhance** [comment]
I think the major work here is actually figuring out how to automate conversions. I like the *.test files but instead of # E: <...> I'd rather have # E: CovariantInInvalidContextError(...)

**Comment by o11c** [comment]
Uh, automating conversions is some simple sed tasks.

That said, one thing I *haven't* figured out how to do is meaningfully parameterize the errors. Saying *what* the error is can follow the standard `-Wfoo` form, but there is no standard for e.g. the name of the variable and type the warning was emitted for. Also, I want to think about XML output (the tests would use the same data that generates that).

Possibly my plans for `gettext` will make that clearer.

**Comment by jhance** [comment]
No, its not.

**Comment by ecprice** [comment]
> I think the major work here is actually figuring out how to automate conversions. I like the *.test files but instead of # E: <...> I'd rather have # E: CovariantInInvalidContextError(...)

There actually already is some functionality for this.  If you run myunit with the `-i` option, it automatically updates # E <...> lines with the current output of mypy.  For example,

`python3 -m mypy.myunit -m mypy.test.testcheck -i '*testForced*' `

This was broken in the move to myunit, so it doesn't know the correct directory of the test file.  I made a quick, somewhat hackish patch here: [mypy-update-testcase.patch.txt](https://github.com/JukkaL/mypy/files/12757/mypy-update-testcase.patch.txt)

I dunno what's going on with the myunit/pytest, but at least for the moment this works.

[How am I supposed to attach patch files to github comment threads? Or am I supposed to create a branch for these things?]

**Comment by jhance** [comment]
Yeah, its more that we need to deal with tests that use `[out]` as opposed to `# E:` especially for when errors eventually may become more than one line...

**Comment by o11c** [comment]
> [How am I supposed to attach patch files to github comment threads? Or am I supposed to create a branch for these things?]

Use https://gist.github.com/

**Comment by o11c** [comment]
> somewhat hackish patch

If that code is what I think it is, the `testcase` object has a `old_cwd` attribute that you really want to use for the prefix.

**Comment by ecprice** [comment]
Ah, nice.  I made a pull request with `old_cwd`. (#927)

**Comment by JukkaL** [comment]
Having a symbolic representation for errors could be pretty useful, but we'd need to think pretty carefully what's the best way to do this. Maybe we should look at how other tools implement this, such as Python linters and clang?

There are at least three kinds of changes in errors that can currently break test cases:

1. Error message formatting changes
2. The set of errors being reported changes (e.g., additional errors get reported)
3. Attributes associated with existing errors change, such as a new attribute for some errors (this also implies a formatting change)

This proposal would fix (1) but (2) and (3) would still be issues.

If the main goal is to make it easier to iterate on error messages, we could also consider something like this instead:

* Generalize the `-i` option to work with tests other than type checker tests.
* Remove most notes from the output so that we won't need to use `[out]`, at least not often.
* Either generalize `-i` to work with `[out]` or move everything away from `[out]` and just use `# E: ...`. This may need some changes to test data format, such as supporting multiple message lines per source line. Shouldn't be too hard.
* Document `-i` and potentially make it more discoverable and easier to use (not sure how exactly, though).
* Add tests for `-i` to catch regressions.

This would help with (1), (2) and (3). It would probably be easier to implement than the alternative, and would help even if we had symbolic error representations (via (2) and (3) and by making the initial migration easier). What do you think?

**Comment by JukkaL** [comment]
This seems like a too disruptive change to make at this point.
