### ISSUE TITLE
Why do I need annotations for an empty list or dictionary

### ISSUE THREAD

**Issue by thomascellerier** [python/mypy#922]
Every time I do
```Python
var = []
```
or 
```Python
var = {}
```
mypy complains and I end up writing
```
var = []  # type: list
```
or
```
var = {} # type: dict
```

If I'm not specifying a more narrow type why does mypy require me to annotate the variables in a way that gives it no additional information. If I type `[]` then `# type: list` is just additional noise.

**Comment by kirbyfan64** [comment]
Because a lot of people will guess "Hey, mypy infers the types of my lists!", while it really doesn't.

Crystal does the exact same thing.

**Comment by thomascellerier** [comment]
From my point of view, if mypy is an optional type checker then it should stay out of the way unless you explicitly define types. I have no idea what the python3.5 spec says about this though.

**Comment by o11c** [comment]
IIRC mypy *does* stay out of your way until you *start* annotating a function, and then it complains for every single issue in the function.

The granularity is rather poor for global code however.

**Comment by JukkaL** [comment]
There are two related things:

1. Mypy complains about `x = []` on the module top level. Yes, this should be fixed, via something called 'weak mode' (I'll write about this later). Basically the type should default to `List[Any]` if there is no annotation. There should also be an opt-in 'strong' or 'strict' mode which would be similar to how mypy works currently.
2. Mypy complains about `x = []` in an annotated function. Mypy could do a better job here, but in general mypy *should* complain if it can't infer the item type, as otherwise you have code that can't be type checked even though everything looks as if it is fully annotated.

**Comment by gvanrossum** [comment]
See also #1055. For some simple cases involving local variables this has now been solved.

**Comment by thomascellerier** [comment]
Great :) thanks for the fix.

**Comment by JukkaL** [comment]
Closing this as this is resolved for most cases that we are planning to support. Feel free to file new issues for particular examples where type inference still fails.
