### ISSUE TITLE
Rethink detection of weakmode

### ISSUE THREAD

**Issue by jhance** [python/mypy#925]
Currently we "check the first 10 tokens". This is arbitrary and could lead to weirdness. Imagine a scenario where there are more options like this - there could even be more than 10 and then, well...

I feel like we should check tokens up until the first non-comment or non-docstring and search in any of those.

**Comment by JukkaL** [comment]
Yeah, that was just a quick hack to get a prototype working. We may also want to reconsider how weak mode works in general. My vision is to make it the default mode, so that you'd get some useful type checking even for programs without any type annotations. I'll file a separate issue about weak mode in general. It could be one of the killer features that will make mypy useful for large projects who can't easily annotate everything.

**Comment by gvanrossum** [comment]
Honestly I think we should rip out the current implementation of weak mode completely, and maybe start over later if we still want it. AFAIK it's not tested, not used, and not working. @ecprice Thoughts?

**Comment by JelleZijlstra** [comment]
I don't know what "weak mode" was, but it's apparently gone, so this can be closed.
