### ISSUE TITLE
Dict type checking fails for variable vs static code

### ISSUE THREAD

**Issue by tomzx** [python/mypy#9267]
Mypy 0.782

I have the following bit of (simplified) code which I would expect should pass typing in both the OK/Not OK cases, but fails in the Not OK case. It seems that the difference is that a variable is used in that case. Another interesting observation is that if I replace `Extended` with a version where each value in `Base` is used to create a `List`/`Dict`, then the error is gone (e.g., `Extended = Union[Base, List[str], List[int], ..., Dict[str, str], Dict[str, int], ...]`. The "fix" is however definitely not convenient since it also forces a single type for the whole `List`/`Dict`.

```python
from typing import Union, Dict, List


Base = Union[str, int, float, bool, None]
Extended = Union[Base, List[Base], Dict[str, Base]]
ExtendedDict = Dict[str, Extended]

# OK
x: ExtendedDict = {
    "test": [3]
}

# Not OK
# error: Dict entry 0 has incompatible type "str": "List[int]"; expected "str": "Union[str, float, None, List[Union[str, int, float, bool, None]], Dict[str, Union[str, int, float, bool, None]]]"
test = [3]
y: ExtendedDict = {
    "test": test
}
```

**Comment by gvanrossum** [comment]
Mypy is right.

The inferred type of the variable `test` in the second fragment is `List[int]`. An assignment like `y["test"].append(3.14)` would be considered valid by mypy. But it would mutate `test` by appending a float, which would violate the type of `test`.

In most cases the workaround is to use `Sequence` instead of `List`, though I haven't reasoned through whether that would work in this example.
