### ISSUE TITLE
Make Python 2 support official

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#931]
Mypy now has a mostly working Python 2 (2.7) support, but it's not properly documented and there are some obvious rough edges. This is an umbrella issue where we collect ideas for things that we'd like to have for proper Python 2 support. We can later create more specific issues.

Some things I have in mind (TODO add links to issues):

* Document comment-based function annotation syntax (`# type: (...) -> rt`).
* Document `--py2` command line option.
* Figure out a good workflow that avoids Python version conflicts, as mypy must be run using Python 3.
* Make it easy to install `typing` for Python 2 and document this.
* Make the mypy encoding official and easy to install.
* Review stubs (on typeshed) and make sure that there are no glaring omissions (compared to Python 3 stubs).
* Review Python 2 `typing` and add missing features.

**Comment by jhance** [comment]
What kind of python version conflicts could occur?

I use 2/3 on the same system all the time and it doesn't seem to really have issues.

**Comment by JukkaL** [comment]
Mostly Python 2 and 3 work just well side by side.

I think that this conflict could happen: User has a Python 3 virtualenv for running mypy. `python` points there to Python 3. They also have a Python 2 program that uses `/usr/bin/env python` or similar, or scripts that run `python` or `pip` and expect these to be Python 2 variants. These break when the mypy virtualenv is active.

**Comment by milliams** [comment]
It looks like the recent 0.3 release covered most of this. What is left on this to make it complete?

**Comment by gvanrossum** [comment]
I checked and most the bullets about docs that need to be added have been taken care of. I also think the Python 2 stubs in typeshed are reasonably complete.

The exception is the mypy codec, which we'll probably discontinue anyways (it's too brittle and we don't need it now we have `# type: (argtypes) -> rtype`).

The 2/3 version issue should be dealt with by installing and invoking mypy as a separate binary. Even if you have a Python 3 virtualenv dedicated to mypy, it needn't be *activated* in order to run mypy on your Python 2 program -- you can just say `/path/to/venv/bin/mypy --py2 program.py`.

(There may be some Windows problems related to that but there are already separate issues open for Windows.)
