### ISSUE TITLE
Allow to alias None

### ISSUE THREAD

**Issue by Hibou57** [python/mypy#9402]
## 🚀 Feature

Allow aliasing like `T = None`.

## Pitch

`None` as a type on its own, generally does not make sense except as a singleton type and it is used for optional types, which is just an union including `None`. But in some corner case, `None` is not a proper name (ex. cases where Void or Null or Unit matches better) and would need to be aliased and will still be used like `None` is.

I don’t know if there is anything against it in any PEP.

**Comment by JelleZijlstra** [comment]
Supporting `T = None` as a type alias is problematic because it's difficult to distinguish between a type alias and a normal assignment (assigning global variables to None is quite common).

[PEP 613](https://www.python.org/dev/peps/pep-0613/) would solve this (you'd write `T: TypeAlias = None`), but isn't supported by mypy yet.

**Comment by gvanrossum** [comment]
Maybe we should close this issue and open one instead for support of PEP
613...

**Comment by Hibou57** [comment]
Done ::-P (PEP 613 seen to be the answer, indeed)
