### ISSUE TITLE
Allow passing None to Mapping.get

### ISSUE THREAD

**Issue by aecay** [python/mypy#9430]
## 🚀 Feature

I often have occasion to write code like:
```python
from typing import Dict
a: Dict[str, str] = {"x": "y"}
b: Dict[str, str] = {"y": "z"}
def f(x: str) -> str:
    f_a = a.get(x)
    reveal_type(f_a)  # Optional[str]
    f_b = b.get(f_a, "default")  # error: Argument 1 to "get" of "Mapping" has incompatible type "Optional[str]"; expected "str"
```

mypy rejects this code with the above-mentioned error.  However, it seems natural to traverse the dictionaries in this way, providing a default value only at the end of the chain of lookups to preserve the contract of the function `f`.  My proposal is, for a dictionary with keys of type `K`, to allow `Optional[K]` as the first argument to `get()` (and not strictly `K`) as is the case now.

Python is dynamic enough that in principle the argument type of `get` could be `Any` -- it will never be a runtime error and the default will always be returned if the key is not found.  It doesn't seem right to relax the argument type that far, though: it would make mypy miss obvious errors (like using an `int` as a key passed to `get` on a dict of `str`s).  But, because of the use case sketched above, `None` feels different.  As hinted by the name `Optional[T]` (supplementing `Union[T, NoneType]`), it often represents a missing value of type T, not its own independent type.  That's why it feels correct, to me, to allow it as an argument to `get`.

(This is, in a way, a similar pattern to what's enabled in JS by the `.?` operator.  That operator is a bit different since it deals with missing values not missing keys, but the logical operation feels somehow comparable: performing a nested lookup while safely accounting for possibly missing elements at any level.)

**Comment by gvanrossum** [comment]
This sounds reasonable, and I think it could be implemented in typeshed, without any mypy changes, by adding the following overloads to `class Mapping` in `stdlib/3/typing.pyi`:
```
    @overload
    def get(self, key: None) -> Optional[_VT_co]: ...
    @overload
    def get(self, key: None, default: Union[_VT_co, _T]) -> Optional[Union[_VT_co, _T]]: ...
```
(Note that we cannot guarantee that `x.get(None)` returns `None` -- we can just make `None` always an acceptable key.)

**Comment by aecay** [comment]
@gvanrossum thanks for the pointer.  🙂  I've opened the above-linked PR on typeshed to bring those overloads in.

**Comment by hauntsaninja** [comment]
I think there are two issues here:
1) The extent to which making key Optional is principled, or more generally how to balance type safety vs what the runtime allows
2) The fact that changes to Mapping.get have the potential to break all users who currently implement Mapping via LSP violations.

Given that, I think I'm:
-1 on making key Optional. I don't find chained gets particularly compelling (just catch the KeyError). Especially when given 2, this could be confusingly neither here nor there for implementers of Mapping.
-0 on making key of type object. Typeshed typically prefers to avoid false positives, however, there's precedent for being stricter with datastructures (eg, `list.__add__` and iirc some set stuff). We do have some leeway since `__getitem__` is far more commonly used and will continue to be strongly typed. But 2 still applies, and I'm not convinced that type ignore or handling the KeyError isn't the better thing to do when this comes up.

**Comment by gvanrossum** [comment]
I'm not a big user of chained gets myself, but I have used them, and I
understand that in some domains they are people's bread and butter. So I
see the attractiveness -- adding a try/except for each get() makes your
code quite unwieldy and distracts from the task at hand. (It's also why we
might end up doing PEP 505, eventually.)

I do worry about breaking existing users with a change to such a popular
method (it could even be *the* most popular method :-).

**Comment by terencehonles** [comment]
I see the PR linked has stalled and then been closed. I was about to open an issue regarding this but found this before I did.

Is there are particular feeling about this now? I believe I have a mix of asserts/casts/type ignores and in this pass I just defined my `dict[K | None, V]` even though it will never be `None` I just didn't want to add a `# type: ignore[arg-type]` since that's problematic if the type _isn't_ `None` and I didn't feel like adding an extra line to assert or import `cast`.

I can look at updating the linked PR for the current typeshed structure, but I don't want to put work into it (can't do it now) if it's not going to be likely to be merged.

I personally feel it _could_ be widened to accept object, but that is much less compelling than just opening it up to `None`. The case that I can see for accepting object would be really that: I would expect that if `K` were a union that mypy would only complain if you passed something which is also a union and it had no union overlap. i.e:

```python
container: dict[str | bytes, int] = {
  b'zero': 0,
  'one': 1,
  ...,
}

# OK since int will never be in container, but there is some overlap of types
def get_value(key: int | str | bytes) -> int:
  return container.get(key, 0)

# errors (int is not in str | bytes)
container.get(0, 0)

# also errors (int and bool are neither in str | bytes)
def get_value(key: int | bool) -> int:
  return container.get(key, 0)
```

Arguably you could say that if there was no overlap then mypy would be able to determine it is using the default value since the container would never hold the key, but that would be expanding the scope of this specific issue and I'm not sure that level of checking is necessary.

For my use of `None`, I'm working with a model which defines:

```python
class Model:
  id: int | None
  ...
```

Most of the time this is defined since the model instance is coming from the database, but for correctness the type is defined as optional since when creating a new record the model instance has no ID. In this specific code I know the ID is non null, but if it were null I'd be OK with returning `None` from the `dict` since not every ID will even be in the container and I am already handling if the value returned is `None`.
