### ISSUE TITLE
To take `type()` into account as `isinstance()` already is

### ISSUE THREAD

**Issue by Hibou57** [python/mypy#9441]
**Feature**

To benefit from `type(v) is T` condition to infer `v` is of type `T`.

**Pitch**

Some classes may be explicitly declared `@final` (as an exemple, most of my classes hierarchy are just two levels, an abstract base class and a set of  derived classes, all `@final`). With such a case, to check a type with `type()` is enough.

The implementation of Mypy I use (mypy 0.782), does not benefit from it:

    class C:
        pass

    class D(C):
        pass

    def f1(c: C) -> None:
        v: D
        if isinstance(c, D):
            v = c
            # OK, no error.

    def f2(c: C) -> None:
        v: D
        if type(c) is D:
            v = c
            # Complains with this:
            # Incompatible types in assignment (expression
            # has type "C", variable has type "D")

Allowing `type(v) is T` when T is `@final`, to be handled as if it was `isinstance(v, T)`, may be an option; but I don’t know if it’s easily feasible.

This was just to share a thought, it’s not blocking.

**Comment by gvanrossum** [comment]
I believe this has been proposed before, but "type" and "isinstance" are very popular words in our issue tracker so I can't find the issue.

I think a problem with this is that people will also want this to have the semantics "and it is not an instance of a proper subtype", and that's harder to implement (because there is no other place in mypy where those semantics are used).

Finally, you can solve the problem by using isinstance(), so this would at best be a low-priority issue, and we already have too many of those.

Therefore let me close this. If you disagree, you may submit a PR.
