### ISSUE TITLE
Add test case for installing mypy using setup.py

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#954]
Add a test case that runs `setup.py install` (in a virtualenv) and type checks a dummy program using an installed mypy.

We shouldn't modify `.travis.yml`. This should run using `runtests.py`. Create a virtualenv within the test case and clean it up afterwards.

Installation got broken a while ago so this would have actually prevented a breakage.

**Comment by JukkaL** [comment]
We also shouldn't need to modify `setup.py` for this.

**Comment by ethanhs** [comment]
So I tested the nested virtualenvs, and at least in my experience, they don't really work that well. I am currently thinking uninstalling the installed version (after Travis executes setup.py) then installing from the wheel is the best test. If you want to test `setup.py` installs, I can set it up so that it runs the same check before uninstalling. That way we are testing: install via `setup.py`, install via `wheels` and uninstall.

**Comment by gvanrossum** [comment]
I'd love it of you came up with a specific PR for your version of the plan!

**Comment by hauntsaninja** [comment]
In https://github.com/mypyc/mypy_mypyc-wheels we now run some tests against built wheels
