### ISSUE TITLE
Specifying which Python interpreter stubgen should use

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#965]
Add a `-p <path-to-python>` option to stubgen that will replace the `--py2` option. Mypy would use this interpreter for these things:
- Determining Python version (2 or 3).
- Determining Python module search path.
- Runtime introspection (esp. for generating stubs for C modules).

As pointed out by @gnprice, the current behavior of using the current Python interpreter doesn't make sense when using a virtualenv, as the virtualenv would have mypy dependencies instead of the (third party) modules targeted by stubgen. This would also allow using an arbitrary Python 2 virtualenv.

We may also need a way of specifying PYTHONPATH for the target interpreter separately from the PYTHONPATH used to run mypy.

**Comment by gnprice** [comment]
This came to mind again today, in the context not of stubgen but of mypy itself. Someone on IRC had trouble getting mypy to find the code they were type-checking, because they were depending on a virtualenv and so `--use-python-path` didn't help them. If we had a `-p` option, they could use that in the same way for `mypy` as we were discussing for stubgen.

Would it make sense for the same `-p` option to apply to both? Perhaps we should retitle this bug to include both.

**Comment by JukkaL** [comment]
Good point -- retitled.

**Comment by ethanhs** [comment]
#4693 added this for mypy.

**Comment by hauntsaninja** [comment]
stubgen gained support for this at some point in the last four years
