### ISSUE TITLE
Should dictionary keys be assumed to be hashable?

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#9698]
```python
from typing import Any, Dict
x: Dict[Any, Any] = {}
reveal_type(list(x.keys()))
```
Gives:
```
a.py:3: note: Revealed type is 'builtins.list[Any]'
```
Ideally, mypy would intersect the key type with `Hashable`?

**Comment by JelleZijlstra** [comment]
That feels very ad hoc, and because of invariance it may well lead to more bugs than it fixes. Perhaps we could bound the typevar for the key type in typeshed, though.

**Comment by NeilGirdhar** [comment]
What does that entail?  What are the consequences of that?

**Comment by JukkaL** [comment]
We can't replace `Any` with `Hashable`, since `Any` allows arbitrary operations on values, whereas `Hashable` only allows a very limited set. This also explains why `Any` can be used as hashable -- you can do anything with an `Any` value, including hashing. 

For example, `list(x.keys())[0].startswith('x')` would be broken if we change the type to `Hashable`.

Adding a bound for the key type might be reasonable, but it won't address the original issue, and will need to be changed in typeshed.

**Comment by NeilGirdhar** [comment]
@JukkaL Ah, of course!  Thanks for taking the time to explain.

Is there anything that can be done for the original issue?

**Comment by JukkaL** [comment]
> Is there anything that can be done for the original issue? 

I don't think there's anything easy that can be done. My recommendation is to avoid `Any` types as much as possible -- they are primarily intended for migrating legacy code not written with type checking in mind.

> Why wouldn't adding a bound alter the type returned by keys?

Bounds don't affect `Any` types. `Any` is compatible with an arbitrary bound. The bound is only used to restrict the possible values for a type variable, but other than that it's ignored.
