### ISSUE TITLE
List item has incompatible type when passed to `pytest.mark.parametrize`

### ISSUE THREAD

**Issue by roniemartinez** [python/mypy#9787]
**Bug Report**

When a list of `NamedTuple` is passed to `pytest.mark.parametrize`, the following error are thrown:
```
tests/test_mypy.py:25: error: List item 0 has incompatible type "A"; expected "Tuple[Union[str, int], ...]"
tests/test_mypy.py:26: error: List item 1 has incompatible type "B"; expected "Tuple[Union[str, int], ...]"
Found 2 errors in 1 file (checked 1 source file)
```

`pytest.mark.parametrize` is using `Sequence` so a list should be valid.

**To Reproduce**

Use the following example code and run the latest mypy version (as of this writing, `0.790`)

```python
from typing import NamedTuple, Optional

import pytest


class A(NamedTuple):
    first: int
    second: Optional[str] = None
    third: Optional[int] = None


class B(NamedTuple):
    second: Optional[str] = None
    third: Optional[int] = None


@pytest.mark.parametrize(
    "param",
    [
        # bug
        [
            A(first=1),
            B(),
        ],
        # solution is to use tuple as param
        (
            A(first=1),
            B(),
        ),
    ],
)
def test_same_named_tuple(param):
    pass

```

**Expected Behavior**

No errors.

**Actual Behavior**

Throws:
```
tests/test_mypy.py:25: error: List item 0 has incompatible type "A"; expected "Tuple[Union[str, int], ...]"
tests/test_mypy.py:26: error: List item 1 has incompatible type "B"; expected "Tuple[Union[str, int], ...]"
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `mypy 0.790`
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: `Python 3.8.5`
- Operating system and version: `OSX 10.15.7 (Catalina)`

**Comment by nmay231** [comment]
I don't use pytest extensively, but looking through pytest's own [test suite](https://github.com/pytest-dev/pytest/search?q=pytest.mark.parametrize), I think you might be using parameterize incorrectly?

Try using two parameters to see if it at least fixes it.

```python
@pytest.mark.parametrize(
  ("param1", "param2"),
    [
        (A(first=1), B()),
        (A(first=2), B()),
    ],
)
```

Pytest seems to allow the weird option of supporting comma delimited strings to pass multiple parameters (for example, `"param1,param2"` instead of `("param1", "param2")`) and the error might be misleading because of that.

Otherwise, you might want to open an issue at PyTest to see if their types need to change to work with your use-case. :smile:

**Comment by hauntsaninja** [comment]
Yeah, pytest ships its own type stubs, so there's no action item for mypy.
