### ISSUE TITLE
"beep-boop is not a valid Python package name"

### ISSUE THREAD

**Issue by wwoods** [python/mypy#9814]
**Bug Report**

Paths with hyphens do not correctly work with mypy; trying to run mypy on such a path results in a "not a valid package name" error. This is not aligned with e.g. `importlib.import_module`, and so is probably a bug in mypy.

**To Reproduce**

```sh
$ mkdir beep-boop
$ touch beep-boop/__init__.py
$ mypy beep-boop
beep-boop is not a valid Python package name
$ python -c "import importlib; importlib.import_module('beep-boop')"
# Runs fine
```

**Expected Behavior**

Since `importlib` can correctly handle this path, it seems that mypy should as well. I would expect the above mypy command to correctly type check the specified package.

**Actual Behavior**

Bug as shown.

**Your Environment**

- Mypy version used: 0.770
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.2
- Operating system and version: Pop! OS 19.10

**Comment by hauntsaninja** [comment]
Almost all of the time this is not what the user intended / has implications for the fully qualified module names mypy infers.
mypy's standard here is the import statement, not supporting packages which force their users to use importlib to import them. (mypy wouldn't understand the type of `x` after `x = importlib.import_module("x")`, since it's dynamic anyway)

Fwiw, it looks like `mypy -p beep-boop` currently works, although I wouldn't necessarily rely on that working in the future.
