### ISSUE TITLE
Module has no attribute error

### ISSUE THREAD

**Issue by ghost** [python/mypy#9841]
**Bug Report**

Mypy throws the `Module has no attribute` error when trying to get a module attribute in a `for` loop by iterating the list of modules

**To Reproduce**

Try it yourself: https://repl.it/@vanburgerberg/Mypy-test

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: no
- Mypy configuration options from `mypy.ini` (and other config files): no config files
- Python version used: 3.8.2, 3.9.0
- Operating system and version: Linux

**Comment by gvanrossum** [comment]
FWIW, the example consists of two files:

* foo.py
```py
import bar

for element in [bar]:
  element.test()
```

* bar.py
```py
def test():
  print("Hello world")
```

The problem here is that the type of `[bar]` is not "a list containing the module `bar`" but just "a list containing modules".

I believe we have seen other reports of this, but I can't recall specific issues. I think you can fix it by defining a Protocol representing the module's interface, and using that to declare the type of the list.

**Comment by aryansingla** [comment]
I want to contribute in it.

**Comment by erictraut** [comment]
This bug appears to have been fixed. It no longer repros in mypy 1.5.
