### ISSUE TITLE
Running mypy against a directory produces different outcome from running against all files in that directory

### ISSUE THREAD

**Issue by obi1kenobi** [python/mypy#9954]
**Bug Report**
Unexpectedly to me, running `mypy` against an entire directory does not produce the same results as running it explicitly against all files in that directory.

Specifically, it is possible to construct a scenario where the following two invocations differ in outcomes — one will claim that there are no type errors, while the other will find valid type errors, even though both runs scanned the same files and used the same `mypy` configuration:
```
mypy src/
```
vs
```
mypy src/foo.py src/bar.py < ... all other Python files inside src/ ... >
```

**To Reproduce**

I encountered this bug while working with `pip` and its use of `mypy`, this issue has all the details including detailed repro steps: https://github.com/pypa/pip/issues/9502

The gist of the repro is the following:
* Clone the `pip` [repo](https://github.com/pypa/pip). The `master` branch as of this post was at commit `8d042c448718355447f133c440f7a931a5ae57c0`, and that is where I found the issue — though I don't expect the exact commit matters.
* Install `mypy==0.790`.
* Run `mypy src/` and note the 51 type errors. This is confusing, because `pip` runs `mypy` in its CI environment, via a `pre-commit` hook.
* Observe that `pre-commit` executes `mypy` with a different invocation, explicitly listing all the files in `src/` instead of simply supplying the directory (the full invocation is quite long, you can find it in the linked issue above). This invocation finds no type errors.

**Expected Behavior**
When scanning the same set of files with the same configuration, I expected `mypy` to behave identically. I expected that specifying a directory and specifying all Python files within that directory should find identical sets of type errors.

It seems that the maintainers of the `pre-commit` project and perhaps the `pip` maintainers as well may have had a similar expectation, as the 51 type errors reported in the `pip` project when running `mypy` with `pip`'s configuration appear to be real type errors and not erroneous in any way.

**Actual Behavior**
`mypy` finds 51 type errors when scanning the `pip` project as a directory, but finds no type errors when invoked with an explicit list of all the files within the `src/` directory.

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: None (`--pretty` is used by `pip`'s configuration, but the same issue exists without it as well)
- Mypy configuration options from `mypy.ini` (and other config files): The following config is in `setup.cfg`:
```
[mypy]
follow_imports = silent
ignore_missing_imports = True
disallow_untyped_defs = True
disallow_any_generics = True
warn_unused_ignores = True

[mypy-pip/_vendor/*]
follow_imports = skip
ignore_errors = True
```
- Python version used: 3.8.5
- Operating system and version: Ubuntu 20.04.1 LTS (focal) inside WSL2

The linked issue in the `pip` project has more detail if needed: https://github.com/pypa/pip/issues/9502

Thank you for all your hard work building and maintaining `mypy`! Please let me know if there's anything I can do to help.

**Comment by hauntsaninja** [comment]
Didn't check (afk), but I'm guessing this is because you're using the evil follow imports option https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports
It's basically never what you want

**Comment by hauntsaninja** [comment]
Yeah, if you remove those options I get the errors with pre-commit. The pre-commit interaction is because pre-commit doesn't list files in `_vendor` due to the global exclude (as evidenced by your full command), whereas with `mypy src` you run on everything top level. The evil follow import options should explain the rest.

(personal opinion: if I were using mypy with pre-commit I'd just have pre-commit run the exact mypy command I wanted. mypy shines at doing whole program analysis, so attempts to get diff-like type checking are either a futile lie or doomed to end in pain)

**Comment by obi1kenobi** [comment]
Wow, well done!

I changed the `follow_imports = skip` part to:
```
[mypy-pip/_vendor/*]
follow_imports = silent
```

This resulted in both invocations finding and reporting the 51 errors.

Since the `skip` option is so dangerous and yet so many projects likely (ab)use it (even `pip`!), would it be worth adding a warning or at least an info line that appears when `skip` is found in a config, to remind users that setting is almost never what one wants?

**Comment by hauntsaninja** [comment]
`follow_imports = silent` is dangerous as well. `follow_imports = error` is mostly benign but terribly annoying. I'd just remove any trace of `follow_imports`.

I think if we were to do that we should just remove it altogether. But there are legitimate uses and I imagine we wouldn't want to break them. I did just open a PR to change some words in the documentation since I've seen people get tripped up on this before, not sure what else should be done.

**Comment by obi1kenobi** [comment]
> But there are legitimate uses and I imagine we wouldn't want to break them. I did just open a PR to change some words in the documentation since I've seen people get tripped up on this before, not sure what else should be done.

Would it be feasible to add some of those legitimate use cases to the documentation? Right now, we have a combination of a dangerous feature that appears commonly misunderstood, and with no clear (to me) way to know what its intended use case is or how to determine which things one must "know what they are doing" in order to use it safely.

I think the emphasis added by your PR is definitely an improvement. I think a concrete example of the downsides of that option if misused (e.g. this one) together with an example of where it might be appropriately used would be even more likely to guide users in the right direction. Without that, I think it would be difficult for users to understand the risk they are facing.

**Comment by hauntsaninja** [comment]
I wouldn't add more words about the options to the documentation. However, I did take a slightly closer look at the pip errors out of curiosity and here's a motivating example: `src/pip/_internal/utils/misc.py:526: error: "None" has no attribute "require"`. Personally, I'd just type ignore that or use `if TYPE_CHECKING` into tricking mypy into looking at `pkg_resource` stubs instead of `vendor`, but if you care more about that false positive than some of the false negatives, it's a valid reason to use `follow_imports=skip`
